import type { CharacterInterpretation, CharacterName, ContentClaim } from '../../lib/content/types';
import { sourceRef } from './sources';

export const aztecNames: readonly CharacterName[] = [
  { id: 'name-aztec-quetzalcoatl-feathered-serpent', characterId: 'character-quetzalcoatl', name: '羽蛇', nameEn: 'Feathered Serpent', nameKind: 'title', isPrimaryForScope: true, sourceRefs: [sourceRef('florentineBook1', 'Book 1, Quetzalcoatl naming and attributes')], confidence: 'high' },
  { id: 'name-aztec-quetzalcoatl-ehecatl', characterId: 'character-quetzalcoatl', name: 'Ehecatl-Quetzalcoatl', nameEn: 'Ehecatl-Quetzalcoatl', nameKind: 'alias', isPrimaryForScope: false, sourceRefs: [sourceRef('florentineBook1', 'Book 1, wind and Quetzalcoatl identity')], confidence: 'medium' },
  { id: 'name-aztec-quetzalcoatl-topiltzin', characterId: 'character-quetzalcoatl', interpretationId: 'interpretation-aztec-topiltzin', name: 'Ce Acatl Topiltzin Quetzalcoatl', nameEn: 'Ce Acatl Topiltzin Quetzalcoatl', nameKind: 'literary-identity', isPrimaryForScope: true, sourceRefs: [sourceRef('annalsCuauhtitlan', 'Topiltzin Quetzalcoatl narrative')], confidence: 'contested' },
  { id: 'name-aztec-tonatiuh-nanahuatzin', characterId: 'character-tonatiuh', name: '第五太阳', nameEn: 'Fifth Sun', nameKind: 'title', isPrimaryForScope: true, sourceRefs: [sourceRef('leyendaSoles', 'Fifth Sun sequence')], confidence: 'medium' },
  { id: 'name-aztec-huitzilopochtli-mexica-patron', characterId: 'character-huitzilopochtli', name: '墨西加守护神', nameEn: 'Mexica Patron Deity', nameKind: 'title', isPrimaryForScope: true, sourceRefs: [sourceRef('codexBoturini', 'migration and patron deity sequence')], confidence: 'high' },
  { id: 'name-aztec-coyolxauhqui-lunar', characterId: 'character-coyolxauhqui', name: '铃饰面颊者', nameEn: 'She of the Bells on Her Cheeks', nameKind: 'title', isPrimaryForScope: true, sourceRefs: [sourceRef('florentineBook3', 'Book 3, Coyolxauhqui identity')], confidence: 'high' },
];

export const aztecInterpretations: readonly CharacterInterpretation[] = [
  { id: 'interpretation-aztec-quetzalcoatl-deity', characterId: 'character-quetzalcoatl', slug: 'deity-feathered-serpent', name: '羽蛇神祇身份层', role: '风、知识与羽蛇神祇的中央墨西哥身份', summary: '以神祇和羽蛇身份阅读魁札尔科亚特尔；不把后来的历史人物自动并入这一稳定神祇层。', traditionTags: ['central-mexican-nahua', 'colonial-nahua-witness'], sourcePeriods: ['Colonial Nahua witness'], sourceRefs: [sourceRef('florentineBook1', 'Book 1, Quetzalcoatl deity identity')], identityAnchors: ['羽蛇', '风', '贝壳'], symbols: ['羽蛇', '风', '贝壳'], canonicalDesignOverrides: { paletteCues: ['绿松石', '羽绿', '云白'] }, promptFragment: 'Keep the deity interpretation distinct from Topiltzin the historical-literary identity.', confidence: 'high' },
  { id: 'interpretation-aztec-topiltzin', characterId: 'character-quetzalcoatl', slug: 'ce-acatl-topiltzin', name: 'Ce Acatl Topiltzin 历史—文学身份层', role: 'Cuauhtitlan 传统中的人物与文化英雄身份', summary: '只在 Anales de Cuauhtitlan 等来源范围内呈现 Topiltzin；不把他写成羽蛇神祇的无争议传记。', traditionTags: ['nahua-cuauhtitlan', 'colonial-nahua-witness'], sourcePeriods: ['16th-century colonial record'], sourceRefs: [sourceRef('annalsCuauhtitlan', 'Topiltzin Quetzalcoatl narrative')], identityAnchors: ['Ce Acatl', 'Topiltzin', 'Cuauhtitlan source scope'], symbols: ['芦苇年名', '迁徙与文化英雄'], canonicalDesignOverrides: { silhouette: 'human cultural hero silhouette, not a literal feathered serpent body' }, promptFragment: 'Render a human historical-literary identity and never merge it into the deity body plan.', confidence: 'contested' },
  { id: 'interpretation-aztec-quetzalcoatl-ehecatl', characterId: 'character-quetzalcoatl', slug: 'ehecatl-wind-form', name: 'Ehecatl 风神关联层', role: '风与 Quetzalcoatl 身份关联的来源解释层', summary: 'Ehecatl-Quetzalcoatl 是来源限定的身份关联，不自动创建第二个 Quetzalcoatl Character，也不声称所有材料都同义。', traditionTags: ['central-mexican-nahua', 'ritual-codex'], sourcePeriods: ['Colonial Nahua witness', 'Central Mexican ritual codex tradition'], sourceRefs: [sourceRef('florentineBook1', 'wind and Quetzalcoatl identity'), sourceRef('codexBorgia', 'wind deity iconographic context')], identityAnchors: ['风', '面具形象', '羽蛇关联'], symbols: ['风', '羽蛇'], canonicalDesignOverrides: { costumeLanguage: ['风动羽饰与来源限定的仪式面具'] }, promptFragment: 'Preserve wind-form scope; do not copy a Maya or European dragon design.', confidence: 'medium' },
  { id: 'interpretation-aztec-nanahuatzin-solar', characterId: 'character-nanahuatzin', slug: 'solar-transformation', name: '纳纳瓦钦太阳转化层', role: '投入火堆后成为太阳的来源解释层', summary: '纳纳瓦钦与托纳提乌的关系是特定太阳诞生文本中的转化关系，不等于所有太阳神身份的同名合并。', traditionTags: ['central-mexican-nahua', 'cosmic-creation'], sourcePeriods: ['Colonial Nahua witness'], sourceRefs: [sourceRef('florentineBook3', 'Book 3, Nanahuatzin becomes the Sun')], identityAnchors: ['火堆', '谦卑', '转化'], symbols: ['火堆', '太阳'], canonicalDesignOverrides: { paletteCues: ['余烬红', '太阳金'] }, promptFragment: 'Show transformation as a source-scoped narrative event, not a generic fire god.', confidence: 'contested' },
  { id: 'interpretation-aztec-coyolxauhqui-lunar', characterId: 'character-coyolxauhqui', slug: 'lunar-reading', name: '科约尔沙乌基月亮解释层', role: 'Coatepec 叙事与月亮 / 星群的来源限定解释', summary: '月亮对应是可供用户选择的解释层；文本、纪念碑与现代学术解释不能被压缩成一个无争议事实。', traditionTags: ['mexica-tenochtitlan', 'coatepec-cycle'], sourcePeriods: ['Colonial Nahua witness', 'Late Mexica period'], sourceRefs: [sourceRef('florentineBook3', 'Book 3, Coatepec identity'), sourceRef('monolithCoyolxauhqui', 'Monolith and lunar interpretation')], identityAnchors: ['铃饰面颊', '月盘', '星群'], symbols: ['月亮', '铃饰'], canonicalDesignOverrides: { avoid: ['graphic dismemberment as default portrait'] }, promptFragment: 'Use the lunar reading only as a source-scoped interpretation and keep the adult deity identifiable.', confidence: 'contested' },
  { id: 'interpretation-aztec-tlaltecuhtli-iconographic', characterId: 'character-tlaltecuhtli', slug: 'monolith-iconography', name: '特拉尔特库特利纪念碑图像层', role: '考古对象与大地形象的解释层', summary: 'Tlaltecuhtli 的性别、姿态和大地含义按纪念碑对象与学术解释呈现，不被写成所有创世神话中的唯一角色。', traditionTags: ['mexica-tenochtitlan'], sourcePeriods: ['Late Mexica period'], sourceRefs: [sourceRef('monolithTlaltecuhtli', 'Monolith object record and gender interpretation')], identityAnchors: ['爪足', '张口姿态', '大地'], symbols: ['大地', '纪念碑'], canonicalDesignOverrides: { silhouette: 'monumental earth iconography, not a generic mother goddess' }, promptFragment: 'Keep object evidence and scholarly interpretation explicit; do not invent a universal Tlaltecuhtli biography.', confidence: 'contested' },
];

export const aztecClaims: readonly ContentClaim[] = [
  { id: 'claim-aztec-quetzalcoatl-topiltzin-boundary', subjectType: 'character', subjectId: 'character-quetzalcoatl', claimType: 'identity', summary: 'Quetzalcoatl deity 与 Ce Acatl Topiltzin Quetzalcoatl 保持两个来源解释层，不创建第二个重复 Character，也不强行合并。', status: 'contested', traditionScope: 'Nahua Cuauhtitlan tradition', sourceRefs: [sourceRef('florentineBook1', 'Quetzalcoatl deity identity'), sourceRef('annalsCuauhtitlan', 'Topiltzin Quetzalcoatl narrative')] },
  { id: 'claim-aztec-ometéotl-boundary', subjectType: 'world', subjectId: 'world-cosmic-cycle', claimType: 'interpretation', summary: 'Ometeotl / Omecihuatl / Tonacatecuhtli 等相关身份不在本 P0 包中被写成无争议唯一至高神；后续需要独立 identity review。', status: 'contested', traditionScope: 'Central Mexican Nahua tradition', sourceRefs: [sourceRef('florentineBook1', 'deity and creator-name comparison')] },
  { id: 'claim-aztec-nanahuatzin-tonatiuh', subjectType: 'character', subjectId: 'character-nanahuatzin', claimType: 'identity', summary: '纳纳瓦钦化作太阳是特定创世来源中的转化关系；托纳提乌作为太阳身份层不自动覆盖纳纳瓦钦全部意义。', status: 'contested', traditionScope: 'Colonial Nahua witness', sourceRefs: [sourceRef('florentineBook3', 'Book 3, Nanahuatzin becomes the Sun')] },
  { id: 'claim-aztec-coyolxauhqui-lunar', subjectType: 'character', subjectId: 'character-coyolxauhqui', claimType: 'interpretation', summary: '科约尔沙乌基的月亮 / 星群对应需同时标记文本来源、纪念碑对象与现代解释层。', status: 'contested', traditionScope: 'Mexica-Tenochtitlan tradition', sourceRefs: [sourceRef('florentineBook3', 'Book 3, Coatepec narrative'), sourceRef('monolithCoyolxauhqui', 'Monolith object record')] },
  { id: 'claim-aztec-tlaltecuhtli-gender', subjectType: 'character', subjectId: 'character-tlaltecuhtli', claimType: 'interpretation', summary: 'Tlaltecuhtli 的性别化称谓与图像解释存在学术讨论；页面不将一种现代概括写成唯一古代事实。', status: 'contested', traditionScope: 'Mexica-Tenochtitlan archaeological context', sourceRefs: [sourceRef('monolithTlaltecuhtli', 'Monolith object record and gender interpretation')] },
  { id: 'claim-aztec-borgia-scope', subjectType: 'world', subjectId: 'world-cosmic-cycle', claimType: 'interpretation', summary: 'Borgia Group 属于中央墨西哥仪式 Codex 传统，不默认标成 Mexica-Tenochtitlan 专属。', status: 'supported', traditionScope: 'Central Mexican ritual codex tradition', sourceRefs: [sourceRef('codexBorgia', 'group provenance and ritual imagery scope')] },
];
