import type { ContentClaim, MythStory, MythStorySource, SourceRef } from '../../lib/content/types';
import { sourceRef, storySource } from './sources';

const mythologyId = 'myth-aztec';
const date = '2026-09-02';
const c = (slug: string) => `character-${slug}`;
const w = (slug: string) => `world-${slug}`;
const s = (slug: string) => `scene-${slug}`;

type StorySeed = {
  slug: string; title: string; titleEn: string; subtitle: string; summary: string;
  volumeId: string; volumeTitle: string; volumeOrder: number; displayOrder: number;
  tradition: string; sourceKey: Parameters<typeof storySource>[0]; locator: string;
  characters: string[]; worlds: string[]; scenes: string[]; body: string[]; note: string;
  kind?: MythStory['kind']; extraClaims?: ContentClaim[];
};

const story = (seed: StorySeed): MythStory => {
  const source = storySource(seed.sourceKey, seed.locator);
  const ref: SourceRef = sourceRef(seed.sourceKey, seed.locator);
  const claim: ContentClaim = { id: `claim-${seed.slug}`, subjectType: 'story', subjectId: `story-${seed.slug}`, claimType: seed.kind === 'religious-tradition' ? 'interpretation' : 'narrative', summary: seed.summary, status: 'supported', traditionScope: seed.tradition, sourceRefs: [ref] };
  return {
    id: `story-${seed.slug}`, slug: seed.slug, mythologyId, title: seed.title, titleEn: seed.titleEn,
    subtitle: seed.subtitle, summary: seed.summary, volumeId: seed.volumeId, volumeTitle: seed.volumeTitle,
    volumeOrder: seed.volumeOrder, displayOrder: seed.displayOrder, kind: seed.kind ?? 'myth', tradition: seed.tradition,
    readingMinutes: 5, sources: [source], sourceNotes: [seed.note, '正文按已列出的来源与传统范围组织；不同文本、图像证据与殖民见证不被拼成一部无争议的统一正典。'],
    requiredCharacterIds: seed.characters, requiredWorldIds: seed.worlds, requiredSceneIds: seed.scenes,
    requiredSourceIds: [source.sourceId!], claims: [claim, ...(seed.extraClaims ?? [])], characterIds: seed.characters,
    worldIds: seed.worlds, sceneIds: seed.scenes, heroAssetId: 'story-illustration-aztec-cosmic', publishStatus: 'published', publishedAt: date, updatedAt: date,
    blocks: [{ type: 'paragraph', text: seed.body[0] }, { type: 'image', assetId: 'story-illustration-aztec-cosmic', caption: `${seed.title}的视觉重点是来源范围、身份关系与空间秩序，而不是符号堆叠。`, layout: 'wide' }, ...seed.body.slice(1).map((text) => ({ type: 'paragraph' as const, text }))],
  };
};

export const aztecStories: readonly MythStory[] = [
  story({ slug: 'five-suns-source-guide', title: '太阳时代与世界毁灭：版本导读', titleEn: 'The Five Suns: A Source-Aware Guide', subtitle: '不把多个版本熔成一部唯一正典', summary: '以来源层并置中央墨西哥关于世界时代、太阳与毁灭方式的不同叙述，建立用户可理解但不虚构统一性的入口。', volumeId: 'aztec-cosmic-cycle', volumeTitle: '太阳循环与人类创造', volumeOrder: 1, displayOrder: 1, tradition: 'Central Mexican Nahua textual traditions', sourceKey: 'leyendaSoles', locator: 'world-age sequence and destruction episodes', characters: [c('tezcatlipoca'), c('tonatiuh'), c('chalchiuhtlicue')], worlds: [w('cosmic-cycle')], scenes: [s('teotihuacan-gathering')], body: ['“五太阳”是现代读者熟悉的入口，却不是一条所有来源都完全一致的流水线。不同材料会改变太阳顺序、角色身份和毁灭方式，因此本篇先把它们作为有来源范围的世界时代框架。', '阅读时应把主线叙述与 alternate claim 分开：这能保留太阳循环的宏大结构，也避免把后来的整理误说成一部从未存在的统一圣典。'], note: '主线使用《Leyenda de los Soles》的来源范围，并以殖民 Nahua 见证作为对照。', extraClaims: [{ id: 'claim-aztec-five-suns-alternate', subjectType: 'story', subjectId: 'story-five-suns-source-guide', claimType: 'interpretation', summary: 'Five Suns 的顺序与毁灭方式存在来源差异，不能作为无范围的单一事实呈现。', status: 'contested', traditionScope: 'Central Mexican Nahua textual traditions', sourceRefs: [sourceRef('florentineBook3', 'creation and sun sequence'), sourceRef('leyendaSoles', 'world-age sequence and destruction episodes')] }] }),
  story({ slug: 'teotihuacan-sun-creation', title: '黑暗中的诸神：谁将成为太阳', titleEn: 'The Gods at Teotihuacan', subtitle: '火堆、谦卑与太阳的诞生', summary: '诸神在特奥蒂瓦坎集会，纳纳瓦钦与特库西斯特卡特尔通过投入火堆进入太阳与月亮的诞生叙事。', volumeId: 'aztec-cosmic-cycle', volumeTitle: '太阳循环与人类创造', volumeOrder: 1, displayOrder: 2, tradition: 'Colonial Nahua witness', sourceKey: 'florentineBook3', locator: 'Book 3, gathering at Teotihuacan and Nanahuatzin / Tecuciztecatl', characters: [c('nanahuatzin'), c('tecuciztecatl'), c('tonatiuh'), c('tezcatlipoca')], worlds: [w('cosmic-cycle')], scenes: [s('teotihuacan-gathering'), s('sacrificial-fire-sun')], body: ['在黑暗尚未被太阳分开的时刻，诸神聚集讨论谁承担成为太阳的责任。纳纳瓦钦贫弱而谦卑，特库西斯特卡特尔拥有财富与自信；两种姿态共同把火堆变成选择的门槛。', '投身火焰不是现代意义上的英雄竞赛，而是一场关于奉献、转化与宇宙运行的来源限定叙事。太阳与月亮的身份关系也必须保留在这一段材料中，而不是自动扩展成所有太阳神谱。'], note: '本篇依据《Florentine Codex》Book 3 的来源范围；太阳身份关系在 identities 与 claims 中另行标记。' }),
  story({ slug: 'sun-motion-and-sacrifice', title: '新太阳为何开始运行', titleEn: 'Why the New Sun Moves', subtitle: '太阳显现之后，秩序仍未完成', summary: '太阳与月亮显现后，神圣秩序需要通过牺牲与行动让世界真正进入运动。', volumeId: 'aztec-cosmic-cycle', volumeTitle: '太阳循环与人类创造', volumeOrder: 1, displayOrder: 3, tradition: 'Central Mexican Nahua textual traditions', sourceKey: 'florentineBook3', locator: 'Book 3, solar motion and divine sacrifice', characters: [c('nanahuatzin'), c('tecuciztecatl'), c('tonatiuh'), c('xolotl')], worlds: [w('cosmic-cycle')], scenes: [s('sacrificial-fire-sun')], body: ['太阳出现并不等于世界已经稳定。来源叙事把“开始运行”写成需要承担代价的宇宙事件，神祇的行动使光不只是悬在天上的物体，而成为可以维持时间的秩序。', '不同见证对参与者和细节的重点并不完全相同。本页保留选定来源的范围，不制作一张把所有神都列入牺牲名单的关系图。'], note: '只呈现选定来源支持的太阳运动与牺牲框架，不将现代百科式“众神献祭”当成无范围事实。' }),
  story({ slug: 'quetzalcoatl-mictlan-bones', title: '魁札尔科亚特尔下入米克特兰', titleEn: 'Quetzalcoatl in Mictlan', subtitle: '从亡者之地取回人类骨骸', summary: '魁札尔科亚特尔进入米克特兰，在与亡者领域统治者的挑战中取得前代人类骨骸。', volumeId: 'aztec-cosmic-cycle', volumeTitle: '太阳循环与人类创造', volumeOrder: 1, displayOrder: 4, tradition: 'Colonial Nahua witness', sourceKey: 'florentineBook3', locator: 'Book 3, Quetzalcoatl in Mictlan and the bones of humanity', characters: [c('quetzalcoatl'), c('mictlantecuhtli'), c('xolotl')], worlds: [w('mictlan')], scenes: [s('mictlan-descent-route'), s('bones-of-humanity-chamber')], body: ['当新世界需要人类时，魁札尔科亚特尔必须越过生者与亡者的边界。米克特兰不是一个可随意套用的“地狱”，而是这条来源叙事中拥有统治者、门槛和试炼的神圣空间。', '骨骸的取得不是一场单纯的战斗胜利；它把过去的人类、死亡的权力与未来的生命连接起来，也让魁札尔科亚特尔的文明角色进入具体行动。'], note: '“米克特兰路径”只按本来源中的叙事需要表达，不硬编码现代流行的九层地图。' }),
  story({ slug: 'present-humanity-from-bones', title: '第五世界中的人类如何诞生', titleEn: 'Humanity from the Bones', subtitle: '骨骸、磨碎与新的身体', summary: '魁札尔科亚特尔带回前代人类骨骸，人类在来源限定的造人仪式中获得新的身体。', volumeId: 'aztec-cosmic-cycle', volumeTitle: '太阳循环与人类创造', volumeOrder: 1, displayOrder: 5, tradition: 'Colonial Nahua witness', sourceKey: 'florentineBook3', locator: 'Book 3, grinding the bones and making present humanity', characters: [c('quetzalcoatl'), c('mictlantecuhtli'), c('xolotl')], worlds: [w('mictlan'), w('tamoanchan')], scenes: [s('bones-of-humanity-chamber')], body: ['人类并非在一个没有前史的空白中被制造。骨骸带着旧世界的记忆，经过磨碎、混合与神圣行动，才成为当前世界可以承载的身体。', '本篇把造人写成对死亡、材料与共同体的重新组织，而不是把“第五太阳”当作永恒不变的通用宇宙地图。'], note: '本篇与上一故事形成叙事闭包，但保留不同来源对造人细节与太阳框架的差异。' }),
  story({ slug: 'coatlicue-feather-bundle', title: '科亚特利库埃在科阿特佩克', titleEn: 'Coatlicue and the Feather Bundle', subtitle: '一个羽束开启诞生冲突', summary: '科亚特利库埃扫地时羽束落入衣襟，Coatepec 的诞生叙事由此进入冲突前夜。', volumeId: 'aztec-coatepec', volumeTitle: 'Coatepec 与守护神诞生', volumeOrder: 2, displayOrder: 1, tradition: 'Mexica-Tenochtitlan tradition as recorded in colonial Nahua sources', sourceKey: 'florentineBook3', locator: 'Book 3, Coatlicue and the feather bundle', characters: [c('coatlicue'), c('coyolxauhqui'), c('centzon-huitznahua'), c('huitzilopochtli')], worlds: [w('coatepec')], scenes: [s('coatepec-mountain'), s('coatlicue-sweeping')], body: ['科亚特利库埃在神圣山地扫地时，一束羽毛落入衣襟。这个动作不是家庭谱系的机械起点，而是让山、母体、羽饰与即将到来的神祇诞生共同进入叙事。', '女儿科约尔沙乌基与南方星群的反应把“诞生”转化为共同体冲突。页面把这些角色保留在 Mexica-Tenochtitlan 来源范围中，不扩写成所有 Nahua 社会都一致的母神故事。'], note: 'Coatepec 主线采用殖民时期 Nahua 见证；相关 Monument 是另一层考古解释。' }),
  story({ slug: 'huitzilopochtli-coatepec-birth', title: '维齐洛波奇特利的武装诞生', titleEn: 'Huitzilopochtli’s Armed Birth', subtitle: 'Xiuhcoatl、星群与神圣山地', summary: '维齐洛波奇特利在 Coatepec 武装诞生，以 Xiuhcoatl 介入母亲与星群的冲突。', volumeId: 'aztec-coatepec', volumeTitle: 'Coatepec 与守护神诞生', volumeOrder: 2, displayOrder: 2, tradition: 'Mexica-Tenochtitlan tradition as recorded in colonial Nahua sources', sourceKey: 'florentineBook3', locator: 'Book 3, armed emergence, Xiuhcoatl and the Coatepec conflict', characters: [c('huitzilopochtli'), c('coatlicue'), c('coyolxauhqui'), c('centzon-huitznahua')], worlds: [w('coatepec')], scenes: [s('huitzilopochtli-emergence'), s('coatepec-mountain')], body: ['维齐洛波奇特利不是在战斗结束后才被赋予武器；来源叙事让他的武装诞生本身成为转折。蜂鸟、太阳与 Xiuhcoatl 共同建立一个属于 Mexica 传统的守护神轮廓。', '科约尔沙乌基与 Centzon Huitznahua 的失败在页面上以关系与来源呈现，视觉上则保留纪念碑与仪式解释层，避免把血腥肢解变成角色肖像的默认主题。'], note: '故事把战斗关系限定在具体 Coatepec 叙事，不将其转化成泛中美洲战争神模板。' }),
  story({ slug: 'coyolxauhqui-monument-and-sacred-landscape', title: '科约尔沙乌基纪念碑与神圣景观', titleEn: 'Coyolxauhqui and the Sacred Landscape', subtitle: '考古对象不是神话的字面复制品', summary: '以 Coyolxauhqui Monolith 与 Templo Mayor 考古语境，解释 Coatepec 叙事如何被连接到 Mexica 神圣城市景观。', volumeId: 'aztec-coatepec', volumeTitle: 'Coatepec 与守护神诞生', volumeOrder: 2, displayOrder: 3, tradition: 'Mexica-Tenochtitlan archaeological context', sourceKey: 'monolithCoyolxauhqui', locator: 'Monolith object record and Templo Mayor placement interpretation', characters: [c('coyolxauhqui'), c('huitzilopochtli'), c('coatlicue')], worlds: [w('tenochtitlan')], scenes: [s('coyolxauhqui-monument'), s('sacred-precinct')], kind: 'religious-tradition', body: ['Coyolxauhqui Monolith 是一件考古对象，它可以帮助用户理解 Mexica 神圣区、阶梯与身体姿态如何被组织进城市仪式空间，但它不是一页把神话逐格“复刻”的建筑说明书。', '因此，本页把文本传统、纪念碑对象和现代考古解释并排显示。默认视觉使用石材、月盘与仪式尺度，不用肢解血腥作为人物的唯一识别。'], note: '考古对象属于 evidence；博物馆图像属于资产；现代解释属于学术 claim，三者不共享同一个 provenance。' }),
  story({ slug: 'aztlan-to-tenochtitlan', title: '从阿兹特兰出发：墨西加迁徙记忆', titleEn: 'From Aztlan: Mexica Migration Memory', subtitle: '神谕、移动与未必可定位的路线', summary: '以 Boturini 与 Azcatitlan 等图像史料为范围，介绍 Aztlan、迁徙记忆与墨西加群体移动。', volumeId: 'aztec-migration-foundation', volumeTitle: '迁徙、湖城与神圣中心', volumeOrder: 3, displayOrder: 1, tradition: 'Mexica migration pictorial tradition', sourceKey: 'codexBoturini', locator: 'opening migration scenes and patron deity guidance', characters: [c('huitzilopochtli')], worlds: [w('tenochtitlan')], scenes: [s('aztlan-memory'), s('migration-camp')], kind: 'myth', body: ['阿兹特兰在迁徙记忆中既是出发地，也是一个被不断回望的起源符号。图像记录把群体、神谕、停驻与继续移动组织在一起，但并不提供一条可以用现代地图精确复原的 GPS 路线。', 'Huitzilopochtli 在这里首先是 Mexica 的守护与引导身份。不同图像见证的顺序和地点标记保持分开，避免将 myth-history bridge 写成纯幻想冒险或确定无疑的现代历史年表。'], note: 'Boturini 与 Azcatitlan 是不同的图像史料见证；页面不把它们拼成一份无差异路线。' }),
  story({ slug: 'tenochtitlan-foundation', title: '湖中建城：特诺奇蒂特兰建城传统', titleEn: 'The Foundation of Tenochtitlan', subtitle: '湖泊、征兆与城市中心', summary: '湖泊与建城征兆把迁徙传统连接到特诺奇蒂特兰的神圣城市记忆。', volumeId: 'aztec-migration-foundation', volumeTitle: '迁徙、湖城与神圣中心', volumeOrder: 3, displayOrder: 2, tradition: 'Central Mexican pictorial historical tradition', sourceKey: 'codexAzcatitlan', locator: 'foundation tradition and lake-city sequence', characters: [c('huitzilopochtli'), c('tlaltecuhtli')], worlds: [w('tenochtitlan')], scenes: [s('lake-foundation')], body: ['建城传统把水面、土地、征兆与群体定居压缩到同一幅城市记忆中。它既有神圣叙事的结构，也有图像史料所保存的历史层，因此不应被还原成一只图标或一个现代国家符号。', 'Tlaltecuhtli 的页面以考古与图像解释层出现，不把她/它未经说明地并入所有创世版本。湖城的视觉重点是堤道、火山石与水面秩序。'], note: '本篇属于 myth-history bridge；地名、路线与对象证据均按各自 source scope 表达。' }),
  story({ slug: 'templo-mayor-sacred-precinct', title: 'Templo Mayor：城市中心如何成为神圣轴', titleEn: 'Templo Mayor and the Sacred Precinct', subtitle: '建筑、祭仪与双重神圣中心', summary: '以 Sacred Precinct 考古证据与 Mexica 宗教解释，说明 Templo Mayor 如何成为城市仪式中心。', volumeId: 'aztec-migration-foundation', volumeTitle: '迁徙、湖城与神圣中心', volumeOrder: 3, displayOrder: 3, tradition: 'Mexica-Tenochtitlan archaeological context', sourceKey: 'temploMayor', locator: 'Sacred Precinct, dual temple and urban ritual context', characters: [c('huitzilopochtli'), c('tlaloc'), c('coatlicue')], worlds: [w('tenochtitlan')], scenes: [s('sacred-precinct'), s('coyolxauhqui-monument')], kind: 'religious-tradition', body: ['Templo Mayor 的双神庙与 Sacred Precinct 让城市中心获得高度可见的仪式秩序。考古证据可以说明建筑、供奉、扩建和城市关系，却不能让我们把某一段神话直接当成建筑的字面施工图。', 'Huitzilopochtli 与 Tlaloc 的并置尤其适合说明战争守护、雨水农业和湖城生活如何在同一城市中心相遇。页面将现代考古解释与殖民见证分层呈现。'], note: '这是考古 / 宗教传统单元，不把 Tenochtitlan 误建模成抽象天界。' }),
  story({ slug: 'mictlan-and-the-dead', title: '米克特兰与亡者之路', titleEn: 'Mictlan and the Road of the Dead', subtitle: '死亡不是一张统一的地狱地图', summary: '以 Mictlantecuhtli、Mictecacihuatl 与亡者空间材料为范围，介绍米克特兰的边界与统治秩序。', volumeId: 'aztec-sacred-realms', volumeTitle: '死亡、雨与神圣领域', volumeOrder: 4, displayOrder: 1, tradition: 'Colonial Nahua witness', sourceKey: 'florentineBook1', locator: 'Book 1, Mictlan rulers and death-realm identity', characters: [c('mictlantecuhtli'), c('mictecacihuatl'), c('quetzalcoatl')], worlds: [w('mictlan')], scenes: [s('mictlan-descent-route')], kind: 'religious-tradition', body: ['米克特兰在来源材料中是亡者与统治秩序相连的神圣领域。Mictlantecuhtli 与 Mictecacihuatl 的视觉身份应保持仪式性、骨骸与夜色，而不是被现代欧洲 Grim Reaper 或僵尸类型替代。', '“九层冥界”在不同现代整理中常被画成固定地图。本篇不把未经充分来源化的层级写入 World schema，而只展示被具体材料支持的道路、门槛与角色关系。'], note: '本篇承担死亡领域入口；Quetzalcoatl 的骨骸故事另有独立叙事单元，避免重复拼接。' }),
  story({ slug: 'tlaloc-rain-and-tlalocan', title: '特拉洛克、雨与特拉洛坎', titleEn: 'Tlaloc, Rain, and Tlalocan', subtitle: '水既是天气，也是农业时间', summary: '以 Tlaloc、雨、水与 Tlalocan 的来源范围，说明雨神身份如何连接土地、山地与特定死后空间。', volumeId: 'aztec-sacred-realms', volumeTitle: '死亡、雨与神圣领域', volumeOrder: 4, displayOrder: 2, tradition: 'Colonial Nahua witness', sourceKey: 'florentineBook1', locator: 'Book 1, Tlaloc identity and rain-realm material', characters: [c('tlaloc'), c('chalchiuhtlicue')], worlds: [w('tlalocan')], scenes: [s('tlalocan-rain-mountain')], kind: 'religious-tradition', body: ['雨在中央墨西哥语境中不是纯粹的天气特效：它决定农业时间、山地泉水与共同体能否进入下一轮生长。Tlaloc 的图像锚点需要留在来源限定的眼纹、水与山地材料。', 'Tlalocan 不是泛热带天堂，而是与特定材料相连的神圣领域。页面会显示其来源范围与置信度，不把所有死者命运压成善恶二分。'], note: '视觉避免 Maya Chaac、generic tropical paradise 与泛部落装饰的混合。' }),
  story({ slug: 'new-fire-renewal', title: '新火与五十二年更新', titleEn: 'The New Fire and Renewal', subtitle: '让周期再次点燃', summary: '以 Xiuhtecuhtli 与 New Fire 仪式材料，介绍年周期更新、圣火与共同体秩序。', volumeId: 'aztec-ritual-order', volumeTitle: '火、更新与仪式秩序', volumeOrder: 5, displayOrder: 1, tradition: 'Colonial Nahua witness', sourceKey: 'florentineBook2', locator: 'Book 2, New Fire ceremony and year renewal', characters: [c('xiuhtecuhtli'), c('tezcatlipoca')], worlds: [w('tenochtitlan')], scenes: [s('new-fire-hill')], kind: 'religious-tradition', body: ['新火不是一个脱离共同体的魔法烟火，而是周期能否继续、家火如何重新点燃以及仪式秩序如何恢复的综合事件。Xiuhtecuhtli 的火盆、绿松石与成熟神性构成稳定的视觉锚点。', '本篇只按仪式来源讲述更新，不把五十二年周期渲染成现代倒计时，也不以灾难猎奇作为阅读入口。'], note: 'New Fire 的文字见证带有殖民记录语境；仪式描述与视觉生产保持史料化。' }),
  story({ slug: 'xipe-totec-renewal', title: '西佩·托特克与植物更新', titleEn: 'Xipe Totec and Renewal', subtitle: '更新的仪式层，不是血腥奇观', summary: '以西佩·托特克、农业更新与春季仪式材料说明植物更新的象征结构。', volumeId: 'aztec-ritual-order', volumeTitle: '火、更新与仪式秩序', volumeOrder: 5, displayOrder: 2, tradition: 'Colonial Nahua witness', sourceKey: 'florentineBook2', locator: 'Book 2, Tlacaxipehualiztli and renewal ceremony', characters: [c('xipe-totec'), c('tlaloc')], worlds: [w('tenochtitlan')], scenes: [s('xipe-renewal-rite')], kind: 'religious-tradition', body: ['西佩·托特克的更新身份把植物、季节与仪式层连接起来。页面使用“旧层脱落—新生长出现”的象征结构解释传统，避免将剥皮材料剪裁成 body horror 或视觉噱头。', '这并不意味着回避史料中的艰难内容，而是让用户先理解其宗教与农业语境，再由来源卡片提供必要的历史信息。'], note: 'Default character art 禁止 graphic gore；需要直接历史教育时也必须保留上下文与来源。' }),
  story({ slug: 'tezcatlipoca-ritual-identity', title: '特斯卡特利波卡、镜与仪式身份', titleEn: 'Tezcatlipoca, Mirror, and Ritual Identity', subtitle: '夜、命运与权力的来源层', summary: '以烟雾之镜、夜与王权材料为范围，介绍特斯卡特利波卡的仪式身份而不制作整齐的兄弟宇宙循环。', volumeId: 'aztec-ritual-order', volumeTitle: '火、更新与仪式秩序', volumeOrder: 5, displayOrder: 3, tradition: 'Colonial Nahua witness and Central Mexican ritual codex tradition', sourceKey: 'florentineBook1', locator: 'Book 1, Tezcatlipoca identity and smoking mirror', characters: [c('tezcatlipoca'), c('xiuhtecuhtli')], worlds: [w('tenochtitlan'), w('cosmic-cycle')], scenes: [s('new-fire-hill')], kind: 'religious-tradition', body: ['烟雾之镜不是一个现代黑暗法师道具，它把夜、命运、权力与观看联系到一起。特斯卡特利波卡的身份在不同叙事里具有多重关系，页面保留这些 source scope，不把所有关系整理成一套过度整齐的“轮流毁灭世界”图表。', '镜面、黑曜石与夜色的视觉表现应服务于身份阅读：它既能反射，也能遮蔽；既是权力象征，也是对不确定性的提醒。'], note: '中央墨西哥仪式 Codex 的归属不默认等于 Mexica；相关差异在来源 registry 中保留。' }),
];
