-- 0019_popular_mythology_characters.sql
-- Complete every non-Chinese mythology to 12 representative characters.
-- Selection prioritizes broad public recognition plus coverage of each tradition's core gods, heroes and antagonists.
-- New characters intentionally ship without portrait assets; CharacterCard already has a symbol-based fallback.

INSERT OR IGNORE INTO characters (
  id, mythology_id, slug, name, name_en, role, summary,
  symbols_json, canonical_design_json, publish_status
) VALUES
('character-zeus','myth-greek','zeus','宙斯','Zeus','众神之王与天空之神','执掌天空与雷霆的奥林匹斯之王。','["雷霆","鹰","权杖"]','{"anchors":["雷霆","鹰","权杖"]}','published'),
('character-poseidon','myth-greek','poseidon','波塞冬','Poseidon','海洋与地震之神','以三叉戟统御海洋、风暴与地震。','["三叉戟","海浪","马"]','{"anchors":["三叉戟","海浪","马"]}','published'),
('character-hades','myth-greek','hades','哈迪斯','Hades','冥界之王','统治亡者国度与地下财富的冥界之王。','["双叉杖","冥界王冠","刻耳柏洛斯"]','{"anchors":["双叉杖","冥界王冠","刻耳柏洛斯"]}','published'),
('character-hera','myth-greek','hera','赫拉','Hera','婚姻与王权女神','奥林匹斯王后，象征婚姻、王权与庄严秩序。','["孔雀","王冠","权杖"]','{"anchors":["孔雀","王冠","权杖"]}','published'),
('character-aphrodite','myth-greek','aphrodite','阿佛洛狄忒','Aphrodite','爱与美之女神','由海沫与爱欲意象环绕的爱与美之女神。','["海贝","玫瑰","鸽子"]','{"anchors":["海贝","玫瑰","鸽子"]}','published'),
('character-apollo','myth-greek','apollo','阿波罗','Apollo','太阳、音乐与预言之神','兼具光明、音乐、诗歌与预言权能的神祇。','["里拉琴","月桂","金弓"]','{"anchors":["里拉琴","月桂","金弓"]}','published'),
('character-artemis','myth-greek','artemis','阿耳忒弥斯','Artemis','狩猎与月亮女神','守护荒野与狩猎，并与月亮意象紧密相连。','["银弓","鹿","新月"]','{"anchors":["银弓","鹿","新月"]}','published'),
('character-ares','myth-greek','ares','阿瑞斯','Ares','战争之神','象征战争冲突与战场力量的奥林匹斯战神。','["长矛","头盔","战盾"]','{"anchors":["长矛","头盔","战盾"]}','published'),
('character-hermes','myth-greek','hermes','赫尔墨斯','Hermes','神使与旅行者守护神','穿行诸界的神使，守护旅行、贸易与讯息传递。','["翼盔","双蛇杖","翼鞋"]','{"anchors":["翼盔","双蛇杖","翼鞋"]}','published'),
('character-heracles','myth-greek','heracles','赫拉克勒斯','Heracles','大力英雄','完成十二项伟业、最具代表性的希腊英雄之一。','["狮皮","木棒","弓"]','{"anchors":["狮皮","木棒","弓"]}','published'),
('character-persephone','myth-greek','persephone','珀耳塞福涅','Persephone','冥界王后与春日女神','连接春日复苏与冥界循环的女神。','["石榴","麦穗","花冠"]','{"anchors":["石榴","麦穗","花冠"]}','published'),
('character-odin','myth-norse','odin','奥丁','Odin','众神之王、智慧与战争之神','以独眼、双鸦与长枪象征智慧、战争与王权。','["冈格尼尔","乌鸦","独眼"]','{"anchors":["冈格尼尔","乌鸦","独眼"]}','published'),
('character-thor','myth-norse','thor','索尔','Thor','雷神','挥舞雷神之锤守护诸神与人类世界。','["妙尔尼尔","雷霆","力量腰带"]','{"anchors":["妙尔尼尔","雷霆","力量腰带"]}','published'),
('character-loki','myth-norse','loki','洛基','Loki','诡计与变形者','聪敏多变的诡计者，是诸多北欧神话冲突的核心人物。','["火焰","锁链","变形"]','{"anchors":["火焰","锁链","变形"]}','published'),
('character-frigg','myth-norse','frigg','弗丽嘉','Frigg','婚姻、母性与预知女神','阿斯加德王后，与婚姻、母性和预知相关。','["纺轮","云","钥匙"]','{"anchors":["纺轮","云","钥匙"]}','published'),
('character-baldr','myth-norse','baldr','巴德尔','Baldr','光明与纯洁之神','以光明、美善与悲剧性死亡闻名的神祇。','["白光","槲寄生","船"]','{"anchors":["白光","槲寄生","船"]}','published'),
('character-heimdall','myth-norse','heimdall','海姆达尔','Heimdall','彩虹桥守护神','拥有敏锐感官，守望连接诸界的彩虹桥。','["加拉尔号角","彩虹桥","金甲"]','{"anchors":["加拉尔号角","彩虹桥","金甲"]}','published'),
('character-tyr','myth-norse','tyr','提尔','Tyr','战争与誓约之神','以牺牲一只手束缚芬里尔而象征勇气与誓约。','["单手","剑","誓约"]','{"anchors":["单手","剑","誓约"]}','published'),
('character-freyr','myth-norse','freyr','弗雷','Freyr','丰饶与和平之神','与丰收、繁荣、和平和阳光相关的华纳神族神祇。','["金色野猪","丰饶","太阳"]','{"anchors":["金色野猪","丰饶","太阳"]}','published'),
('character-hel','myth-norse','hel','海拉','Hel','亡者国度统治者','统治赫尔海姆的亡者之主，形象兼具生与死的对照。','["半明半暗面容","冥界","王座"]','{"anchors":["半明半暗面容","冥界","王座"]}','published'),
('character-fenrir','myth-norse','fenrir','芬里尔','Fenrir','巨狼','洛基之子，挣脱束缚并在诸神黄昏中成为关键力量。','["巨狼","锁链","诸神黄昏"]','{"anchors":["巨狼","锁链","诸神黄昏"]}','published'),
('character-jormungandr','myth-norse','jormungandr','耶梦加得','Jörmungandr','尘世巨蛇','环绕米德加尔特的巨蛇，与索尔宿命对决。','["环世巨蛇","海洋","雷神宿敌"]','{"anchors":["环世巨蛇","海洋","雷神宿敌"]}','published'),
('character-ra','myth-egyptian','ra','拉','Ra','太阳神','每日乘太阳神舟穿越天空与冥界的太阳神。','["太阳圆盘","鹰隼","太阳神舟"]','{"anchors":["太阳圆盘","鹰隼","太阳神舟"]}','published'),
('character-osiris','myth-egyptian','osiris','奥西里斯','Osiris','冥界与复生之神','统御亡者审判并象征死亡、复生与秩序。','["白冠","权杖与连枷","绿色肌肤"]','{"anchors":["白冠","权杖与连枷","绿色肌肤"]}','published'),
('character-isis','myth-egyptian','isis','伊西斯','Isis','魔法、母性与王权女神','以魔法与守护闻名，是奥西里斯与荷鲁斯神话的核心。','["王座冠","羽翼","安卡"]','{"anchors":["王座冠","羽翼","安卡"]}','published'),
('character-horus','myth-egyptian','horus','荷鲁斯','Horus','天空与王权之神','鹰首天空神，象征法老王权与神圣秩序。','["鹰隼","荷鲁斯之眼","双冠"]','{"anchors":["鹰隼","荷鲁斯之眼","双冠"]}','published'),
('character-set','myth-egyptian','set','赛特','Set','沙漠、风暴与混沌之神','掌管荒漠与风暴，是奥西里斯神话中的强大对手。','["赛特兽","权杖","沙暴"]','{"anchors":["赛特兽","权杖","沙暴"]}','published'),
('character-bastet','myth-egyptian','bastet','巴斯特','Bastet','猫、家庭与守护女神','以猫科形象守护家庭、欢乐与日常生活。','["猫","香膏瓶","叉铃"]','{"anchors":["猫","香膏瓶","叉铃"]}','published'),
('character-thoth','myth-egyptian','thoth','托特','Thoth','智慧、文字与月亮之神','记录神圣秩序与审判，关联文字、知识和月亮。','["朱鹭","书写板","月轮"]','{"anchors":["朱鹭","书写板","月轮"]}','published'),
('character-hathor','myth-egyptian','hathor','哈索尔','Hathor','爱、音乐与天空女神','以母性、音乐、爱与欢迎亡者的形象著称。','["牛角日盘","叉铃","镜子"]','{"anchors":["牛角日盘","叉铃","镜子"]}','published'),
('character-sekhmet','myth-egyptian','sekhmet','塞赫麦特','Sekhmet','战争与疗愈女神','兼具毁灭性烈焰与疗愈力量的狮首女神。','["狮首","太阳圆盘","火焰"]','{"anchors":["狮首","太阳圆盘","火焰"]}','published'),
('character-sobek','myth-egyptian','sobek','索贝克','Sobek','鳄鱼与尼罗河神','与尼罗河水势、力量、丰饶和王权相关。','["鳄鱼首","尼罗河","安卡"]','{"anchors":["鳄鱼首","尼罗河","安卡"]}','published'),
('character-maat','myth-egyptian','maat','玛阿特','Ma''at','真理、正义与宇宙秩序女神','象征真理与宇宙秩序，羽毛用于亡者心脏称量。','["鸵鸟羽毛","天平","安卡"]','{"anchors":["鸵鸟羽毛","天平","安卡"]}','published'),
('character-amaterasu','myth-japanese','amaterasu','天照大神','Amaterasu','太阳女神','高天原核心神祇，以太阳与光明象征天界秩序。','["日轮","八咫镜","光芒"]','{"anchors":["日轮","八咫镜","光芒"]}','published'),
('character-susanoo','myth-japanese','susanoo','须佐之男','Susanoo','海原与风暴之神','豪迈而冲动的风暴神，以斩杀八岐大蛇闻名。','["十拳剑","八岐大蛇","风暴"]','{"anchors":["十拳剑","八岐大蛇","风暴"]}','published'),
('character-tsukuyomi','myth-japanese','tsukuyomi','月读命','Tsukuyomi','月神','掌管月夜与幽静天光的神祇。','["月轮","夜色","银光"]','{"anchors":["月轮","夜色","银光"]}','published'),
('character-izanagi','myth-japanese','izanagi','伊邪那岐','Izanagi','创世男神','与伊邪那美共同创造日本诸岛，并以黄泉归来后的禊闻名。','["天沼矛","海潮","禊"]','{"anchors":["天沼矛","海潮","禊"]}','published'),
('character-izanami','myth-japanese','izanami','伊邪那美','Izanami','创世女神与黄泉之神','参与国土与诸神诞生，后成为黄泉世界的重要存在。','["天沼矛","黄泉","火"]','{"anchors":["天沼矛","黄泉","火"]}','published'),
('character-inari','myth-japanese','inari','稻荷神','Inari','稻作、丰饶与商业之神','以白狐、稻穗与伏见鸟居意象最具辨识度。','["白狐","稻穗","朱红鸟居"]','{"anchors":["白狐","稻穗","朱红鸟居"]}','published'),
('character-hachiman','myth-japanese','hachiman','八幡神','Hachiman','武运与弓箭守护神','广受武家尊崇的战争与守护神。','["弓箭","鸽子","武家旗"]','{"anchors":["弓箭","鸽子","武家旗"]}','published'),
('character-ame-no-uzume','myth-japanese','ame-no-uzume','天宇受卖命','Ame-no-Uzume','黎明、舞蹈与欢笑女神','以天岩户前的舞蹈引出天照大神而闻名。','["神乐","扇","黎明"]','{"anchors":["神乐","扇","黎明"]}','published'),
('character-okuninushi','myth-japanese','okuninushi','大国主神','Ōkuninushi','国土经营与缘结之神','与因幡白兔、国土经营和缘结传说密切相关。','["大国袋","白兔","结缘"]','{"anchors":["大国袋","白兔","结缘"]}','published'),
('character-raijin','myth-japanese','raijin','雷神','Raijin','雷电之神','环绕雷鼓、驾驭雷电与暴风的强烈神祇形象。','["雷鼓","闪电","云"]','{"anchors":["雷鼓","闪电","云"]}','published'),
('character-fujin','myth-japanese','fujin','风神','Fūjin','风之神','肩负巨大风袋、释放四方风势的神祇。','["风袋","云","疾风"]','{"anchors":["风袋","云","疾风"]}','published'),
('character-shiva','myth-indian','shiva','湿婆','Shiva','毁灭与再生之神','以瑜伽、舞蹈与毁灭后再生的宇宙力量闻名。','["三叉戟","第三眼","新月"]','{"anchors":["三叉戟","第三眼","新月"]}','published'),
('character-vishnu','myth-indian','vishnu','毗湿奴','Vishnu','维护宇宙秩序之神','以多种化身维系宇宙秩序与正法。','["法轮","海螺","莲花"]','{"anchors":["法轮","海螺","莲花"]}','published'),
('character-brahma','myth-indian','brahma','梵天','Brahma','创造之神','传统三相神之一，以四面与创造意象最具辨识度。','["四面","吠陀","莲花"]','{"anchors":["四面","吠陀","莲花"]}','published'),
('character-krishna','myth-indian','krishna','克里希纳','Krishna','毗湿奴化身、牧牛与智慧之神','以长笛、牧牛与《薄伽梵歌》中的智慧形象广为人知。','["长笛","孔雀羽","牛群"]','{"anchors":["长笛","孔雀羽","牛群"]}','published'),
('character-rama','myth-indian','rama','罗摩','Rama','毗湿奴化身、史诗英雄','《罗摩衍那》的核心英雄，象征理想君王与正法。','["长弓","箭","王冠"]','{"anchors":["长弓","箭","王冠"]}','published'),
('character-ganesha','myth-indian','ganesha','象头神伽内什','Ganesha','智慧、吉祥与障碍移除之神','象首形象极具辨识度，常与智慧、吉祥和新起点相关。','["象首","甜食","鼠"]','{"anchors":["象首","甜食","鼠"]}','published'),
('character-hanuman','myth-indian','hanuman','哈奴曼','Hanuman','神猴英雄','《罗摩衍那》中忠勇强大的神猴英雄。','["神杵","山峰","猴面"]','{"anchors":["神杵","山峰","猴面"]}','published'),
('character-lakshmi','myth-indian','lakshmi','吉祥天女','Lakshmi','财富、吉祥与繁荣女神','以莲花与丰盛意象象征财富、幸运和繁荣。','["莲花","金币","大象"]','{"anchors":["莲花","金币","大象"]}','published'),
('character-saraswati','myth-indian','saraswati','辩才天女','Saraswati','知识、音乐与艺术女神','守护学习、语言、音乐与艺术创造。','["维纳琴","白天鹅","书卷"]','{"anchors":["维纳琴","白天鹅","书卷"]}','published'),
('character-durga','myth-indian','durga','杜尔迦','Durga','战胜邪恶的女神','多臂持诸神武器，象征保护与战胜混乱的力量。','["狮虎坐骑","多臂","神兵"]','{"anchors":["狮虎坐骑","多臂","神兵"]}','published'),
('character-kali','myth-indian','kali','迦梨','Kali','时间、毁灭与力量女神','以强烈形象体现时间、毁灭与超越恐惧的力量。','["黑色形象","剑","项链"]','{"anchors":["黑色形象","剑","项链"]}','published'),
('character-indra','myth-indian','indra','因陀罗','Indra','雷电、战争与天界之王','执金刚杵、乘白象的雷雨与战争神。','["金刚杵","白象","雷云"]','{"anchors":["金刚杵","白象","雷云"]}','published'),
('character-morrigan','myth-celtic','morrigan','莫莉甘','The Mórrigan','战争、命运与王权女神','爱尔兰神话中的战争与命运女神，常化作乌鸦出现。','["乌鸦","战场","变形"]','{"anchors":["乌鸦","战场","变形"]}','published'),
('character-cu-chulainn','myth-celtic','cu-chulainn','库丘林','Cú Chulainn','阿尔斯特英雄','《夺牛长征记》中最著名的英雄，以超凡战技与悲剧命运闻名。','["长矛 Gáe Bolg","战车","猎犬"]','{"anchors":["长矛 Gáe Bolg","战车","猎犬"]}','published'),
('character-lugh','myth-celtic','lugh','鲁格','Lugh','多艺、王权与技艺之神','图阿哈·德·达南的重要领袖，以多才多艺与神枪闻名。','["长矛","日光","技艺"]','{"anchors":["长矛","日光","技艺"]}','published'),
('character-brigid','myth-celtic','brigid','布里吉德','Brigid','诗歌、疗愈与锻造女神','与诗歌、疗愈、火焰和工艺相关的重要女神。','["火焰","泉水","诗琴"]','{"anchors":["火焰","泉水","诗琴"]}','published'),
('character-dagda','myth-celtic','dagda','达格达','The Dagda','丰饶、魔法与领袖之神','持有巨棒、魔法竖琴与永不枯竭之锅的强大神祇。','["巨棒","无尽锅","竖琴"]','{"anchors":["巨棒","无尽锅","竖琴"]}','published'),
('character-nuada','myth-celtic','nuada','努阿达','Nuada','银臂王与战士之神','图阿哈·德·达南之王，以失去手臂后获银臂而闻名。','["银臂","长剑","王冠"]','{"anchors":["银臂","长剑","王冠"]}','published'),
('character-fionn-mac-cumhaill','myth-celtic','fionn-mac-cumhaill','芬恩·麦克库尔','Fionn mac Cumhaill','芬尼亚英雄领袖','芬尼亚传说的核心英雄，与智慧鲑鱼和猎团故事相连。','["智慧鲑鱼","长矛","猎犬"]','{"anchors":["智慧鲑鱼","长矛","猎犬"]}','published'),
('character-medb','myth-celtic','medb','梅芙女王','Medb','康诺特女王','《夺牛长征记》的关键人物，代表野心、王权与战争动员。','["王冠","公牛","战车"]','{"anchors":["王冠","公牛","战车"]}','published'),
('character-manannan','myth-celtic','manannan','马纳南·麦克·利尔','Manannán mac Lir','海洋与彼世之神','掌管海洋、迷雾与彼世通道的重要神祇。','["海浪","魔法船","雾"]','{"anchors":["海浪","魔法船","雾"]}','published'),
('character-aengus','myth-celtic','aengus','安格斯','Aengus','青春、爱情与诗意之神','与青春、爱情、梦境和诗意相关的图阿哈神祇。','["天鹅","金色竖琴","梦境"]','{"anchors":["天鹅","金色竖琴","梦境"]}','published'),
('character-cernunnos','myth-celtic','cernunnos','塞尔努诺斯','Cernunnos','自然、动物与丰饶之神','以鹿角与动物环绕形象代表野性自然、丰饶与繁盛。','["鹿角","黄金颈环","蛇"]','{"anchors":["鹿角","黄金颈环","蛇"]}','published'),
('character-epona','myth-celtic','epona','埃波娜','Epona','马匹与守护女神','广布凯尔特欧洲的马匹守护与丰饶女神。','["马","丰饶角","王座"]','{"anchors":["马","丰饶角","王座"]}','published'),
('character-kukulkan','myth-maya','kukulkan','库库尔坎','Kukulkan','羽蛇神','尤卡坦玛雅著名羽蛇神，与风、秩序和奇琴伊察意象相连。','["羽蛇","风","阶梯神庙"]','{"anchors":["羽蛇","风","阶梯神庙"]}','published'),
('character-itzamna','myth-maya','itzamna','伊察姆纳','Itzamna','创造、知识与文化之神','重要创造神与文化英雄，关联文字、历法、医术与祭司。','["书写","天穹","祭司"]','{"anchors":["书写","天穹","祭司"]}','published'),
('character-ix-chel','myth-maya','ix-chel','伊什切尔','Ix Chel','月亮、生育与医药女神','与月亮、生育、医药和纺织相关的重要女神。','["月亮","织布","水"]','{"anchors":["月亮","织布","水"]}','published'),
('character-chaac','myth-maya','chaac','恰克','Chaac','雨与风暴之神','广受崇拜的雨神，控制风暴、农业与水源。','["雨斧","闪电","长鼻面具"]','{"anchors":["雨斧","闪电","长鼻面具"]}','published'),
('character-hunahpu','myth-maya','hunahpu','胡纳普','Hunahpu','英雄双子之一','《波波尔·乌》的英雄双子之一，与兄弟共同战胜西巴尔巴诸神。','["吹箭","球赛","太阳"]','{"anchors":["吹箭","球赛","太阳"]}','published'),
('character-xbalanque','myth-maya','xbalanque','斯巴兰克','Xbalanque','英雄双子之一','英雄双子中的战士，与胡纳普共同完成地下世界试炼。','["美洲豹","球赛","月亮"]','{"anchors":["美洲豹","球赛","月亮"]}','published'),
('character-hun-hunahpu','myth-maya','hun-hunahpu','胡恩·胡纳普','Hun Hunahpu','玉米神与英雄双子之父','被西巴尔巴领主杀害后以玉米再生意象延续的关键人物。','["玉米","葫芦树","球赛"]','{"anchors":["玉米","葫芦树","球赛"]}','published'),
('character-camazotz','myth-maya','camazotz','卡玛佐兹','Camazotz','蝙蝠神','西巴尔巴中的蝙蝠神，在英雄双子试炼中极具辨识度。','["蝙蝠","黑暗","利刃"]','{"anchors":["蝙蝠","黑暗","利刃"]}','published'),
('character-kisin','myth-maya','kisin','基辛','Kisin','死亡与冥界之神','与死亡、腐朽和地下世界相关的玛雅冥界神祇。','["骷髅","腐朽","冥火"]','{"anchors":["骷髅","腐朽","冥火"]}','published'),
('character-huracan','myth-maya','huracan','胡拉坎','Huracan','风暴与创造之神','《波波尔·乌》中的“天之心”，参与创世并引发洪水。','["旋风","闪电","火"]','{"anchors":["旋风","闪电","火"]}','published'),
('character-vucub-caquix','myth-maya','vucub-caquix','乌库布·卡基什','Vucub Caquix','七金刚鹦鹉、伪日神','自称太阳与月亮的骄傲鸟魔，最终被英雄双子击败。','["金刚鹦鹉","宝石牙","日月"]','{"anchors":["金刚鹦鹉","宝石牙","日月"]}','published'),
('character-zipacna','myth-maya','zipacna','西帕克纳','Zipacna','山岳巨灵','七金刚鹦鹉之子，以搬山巨力著称并与英雄双子对抗。','["山岳","大地","巨力"]','{"anchors":["山岳","大地","巨力"]}','published'),
('character-quetzalcoatl','myth-aztec','quetzalcoatl','魁札尔科亚特尔','Quetzalcoatl','羽蛇神、风与文明之神','中美洲最知名神祇之一，与风、知识、文明和人类创造相关。','["羽蛇","风","贝壳"]','{"anchors":["羽蛇","风","贝壳"]}','published'),
('character-huitzilopochtli','myth-aztec','huitzilopochtli','维齐洛波奇特利','Huitzilopochtli','太阳与战争之神','墨西加人的核心守护神，关联太阳、战争与特诺奇蒂特兰。','["蜂鸟","太阳","蛇形武器"]','{"anchors":["蜂鸟","太阳","蛇形武器"]}','published'),
('character-tezcatlipoca','myth-aztec','tezcatlipoca','特斯卡特利波卡','Tezcatlipoca','夜空、命运与王权之神','以“烟雾之镜”象征命运、夜空、权力与冲突。','["黑曜石镜","美洲豹","烟雾"]','{"anchors":["黑曜石镜","美洲豹","烟雾"]}','published'),
('character-tlaloc','myth-aztec','tlaloc','特拉洛克','Tlaloc','雨、水与雷电之神','农业社会中最重要的雨神之一，掌管水、雷雨与丰收。','["护目镜式眼纹","獠牙","雨"]','{"anchors":["护目镜式眼纹","獠牙","雨"]}','published'),
('character-coatlicue','myth-aztec','coatlicue','科亚特利库埃','Coatlicue','大地母神','以蛇裙和强烈母神形象代表大地、生命与死亡循环。','["蛇裙","骷髅项链","大地"]','{"anchors":["蛇裙","骷髅项链","大地"]}','published'),
('character-xipe-totec','myth-aztec','xipe-totec','西佩·托特克','Xipe Totec','春季、农业与更新之神','象征植物更新、播种与春季循环的重要神祇。','["金色皮衣","玉米","春季"]','{"anchors":["金色皮衣","玉米","春季"]}','published'),
('character-mictlantecuhtli','myth-aztec','mictlantecuhtli','米克特兰特库特利','Mictlantecuhtli','冥界之王','统治米克特兰亡者世界的冥界之王。','["骷髅","猫头鹰","黑暗"]','{"anchors":["骷髅","猫头鹰","黑暗"]}','published'),
('character-mictecacihuatl','myth-aztec','mictecacihuatl','米克特卡西瓦特尔','Mictecacihuatl','冥界王后','与米克特兰特库特利共同统治亡者世界的女神。','["骷髅面容","亡者祭礼","夜"]','{"anchors":["骷髅面容","亡者祭礼","夜"]}','published'),
('character-tonatiuh','myth-aztec','tonatiuh','托纳蒂乌','Tonatiuh','第五太阳之神','代表当前第五太阳时代的太阳神。','["太阳盘","鹰","火焰"]','{"anchors":["太阳盘","鹰","火焰"]}','published'),
('character-coyolxauhqui','myth-aztec','coyolxauhqui','科约尔沙乌基','Coyolxauhqui','月亮女神','维齐洛波奇特利诞生神话中的月亮女神与关键对手。','["月铃","月盘","星辰"]','{"anchors":["月铃","月盘","星辰"]}','published'),
('character-xiuhtecuhtli','myth-aztec','xiuhtecuhtli','修特库特利','Xiuhtecuhtli','火与时间之神','掌管火焰、炉火、时间与年岁循环的重要神祇。','["火焰","绿松石","火盆"]','{"anchors":["火焰","绿松石","火盆"]}','published'),
('character-xochipilli','myth-aztec','xochipilli','索奇皮利','Xochipilli','花、艺术与欢愉之神','以花朵、艺术、音乐、舞蹈与夏季欢愉闻名。','["花朵","蝴蝶","乐舞"]','{"anchors":["花朵","蝴蝶","乐舞"]}','published'),
('character-gilgamesh','myth-mesopotamian','gilgamesh','吉尔伽美什','Gilgamesh','乌鲁克英雄王','《吉尔伽美什史诗》的核心英雄，追寻荣耀与永生意义。','["王冠","狮子","城墙"]','{"anchors":["王冠","狮子","城墙"]}','published'),
('character-enkidu','myth-mesopotamian','enkidu','恩奇都','Enkidu','荒野英雄','由荒野走入文明的英雄，与吉尔伽美什结为挚友。','["野兽","长发","力量"]','{"anchors":["野兽","长发","力量"]}','published'),
('character-ishtar','myth-mesopotamian','ishtar','伊什塔尔','Ishtar / Inanna','爱、战争与金星女神','两河流域最具代表性的女神之一，兼具爱欲、战争与王权力量。','["八芒星","狮子","金星"]','{"anchors":["八芒星","狮子","金星"]}','published'),
('character-enki','myth-mesopotamian','enki','恩基','Enki / Ea','智慧、魔法与淡水之神','以智慧和魔法帮助人类，在洪水与创世叙事中地位重要。','["流水","山羊鱼","智慧"]','{"anchors":["流水","山羊鱼","智慧"]}','published'),
('character-enlil','myth-mesopotamian','enlil','恩利尔','Enlil','风、大气与王权之神','早期苏美尔神系中的至高神之一，掌管风、大气与神圣权柄。','["风暴","命运泥板","王冠"]','{"anchors":["风暴","命运泥板","王冠"]}','published'),
('character-marduk','myth-mesopotamian','marduk','马尔杜克','Marduk','巴比伦主神','《埃努玛·埃利什》中击败提亚马特并建立宇宙秩序的巴比伦主神。','["龙蛇 Mušḫuššu","权杖","星辰"]','{"anchors":["龙蛇 Mušḫuššu","权杖","星辰"]}','published'),
('character-ereshkigal','myth-mesopotamian','ereshkigal','埃列什基伽勒','Ereshkigal','冥界女王','统治地下亡者世界，是伊南娜下降冥界故事的核心角色。','["冥界王座","黑暗","门"]','{"anchors":["冥界王座","黑暗","门"]}','published'),
('character-nergal','myth-mesopotamian','nergal','涅伽尔','Nergal','战争、瘟疫与冥界之神','与战争、疫病及冥界力量相关，并成为埃列什基伽勒的配偶。','["狮首权杖","烈日","冥界"]','{"anchors":["狮首权杖","烈日","冥界"]}','published'),
('character-shamash','myth-mesopotamian','shamash','沙玛什','Shamash / Utu','太阳与正义之神','以太阳之光洞察万物，象征司法、公正与秩序。','["太阳盘","锯齿刃","光线"]','{"anchors":["太阳盘","锯齿刃","光线"]}','published'),
('character-sin','myth-mesopotamian','sin','辛','Sin / Nanna','月神','苏美尔与阿卡德传统中的重要月神，关联时间与历法。','["新月","公牛","星夜"]','{"anchors":["新月","公牛","星夜"]}','published'),
('character-tiamat','myth-mesopotamian','tiamat','提亚马特','Tiamat','原初海洋与混沌之母','巴比伦创世史诗中的原初海洋力量，与马尔杜克展开宇宙决战。','["海龙","咸水","混沌"]','{"anchors":["海龙","咸水","混沌"]}','published'),
('character-anu','myth-mesopotamian','anu','安努','Anu','天空之神','苏美尔-阿卡德传统中的高天之神与神圣权威源头。','["角冠","星空","王座"]','{"anchors":["角冠","星空","王座"]}','published');

-- Roster invariant after this migration: each non-Chinese mythology has exactly 12 seeded characters.
-- Existing canonical seeds retained: Athena, Freyja, Anubis and Kaguya-hime.
