-- 0038_english_core_content.sql
-- Publish the first production English content set.
-- Scope: all ten mythology landing entities, five core worlds, and a curated
-- set of high-recognition characters. Other locale rows remain draft/noindex.

INSERT INTO mythology_translations (
  mythology_id, locale, name, tagline, summary, seo_title, seo_description, hero_alt,
  translation_status, source_locale, updated_at
) VALUES
('myth-chinese','en','Chinese Mythology','Celestial Courts · Kunlun · Mountains and Seas','Cloud seas, celestial palaces, Kunlun, moon legends, and strange beings from the mountains and seas form a vast Chinese mythic cosmos.','Chinese Mythology — Gods, Realms and Visual Stories','Explore Chinese mythology through gods, sacred realms, legendary figures, and MythCanvas visual interpretations.','A Chinese celestial realm rising above a sea of clouds','published','zh-Hans',CURRENT_TIMESTAMP),
('myth-greek','en','Greek Mythology','Olympus · Heroes · The Aegean','Marble temples, Aegean light, Olympian gods, and heroic cycles shape a bright, dramatic mythology of power, fate, and transformation.','Greek Mythology — Olympian Gods, Heroes and Realms','Explore Greek mythology, from Olympus and the Olympian gods to heroes, monsters, and the underworld.','Mount Olympus above the clouds in morning light','published','zh-Hans',CURRENT_TIMESTAMP),
('myth-norse','en','Norse Mythology','Yggdrasil · Nine Worlds · Ragnarök','Yggdrasil binds gods, giants, humans, and the dead across a northern cosmos of stone, ice, runes, aurora, and looming fate.','Norse Mythology — Gods, Nine Worlds and Ragnarök','Explore Norse mythology through the gods of Asgard, Yggdrasil, legendary beings, and the coming of Ragnarök.','Asgard beneath the aurora with Yggdrasil on the horizon','published','zh-Hans',CURRENT_TIMESTAMP),
('myth-egyptian','en','Egyptian Mythology','Sun · Nile · Duat','Solar journeys, divine kingship, the Nile, and the Duat create an ancient sacred order centered on death, renewal, balance, and eternity.','Egyptian Mythology — Gods, Duat and Sacred Order','Explore Egyptian mythology through solar gods, the Duat, divine kingship, death, rebirth, and cosmic order.','The Duat beneath a star-filled sky with a solar barque','published','zh-Hans',CURRENT_TIMESTAMP),
('myth-indian','en','Indian Mythology','Creation · Dharma · Cosmic Cycles','Sacred mountains, rivers, lotus imagery, epic heroes, and powerful deities unfold across traditions concerned with creation, dharma, devotion, and cosmic cycles.','Indian Mythology — Deities, Epics and Cosmic Cycles','Explore Indian mythology through major deities, epic heroes, sacred symbols, and stories of creation, preservation, and transformation.','A sacred Indian mythic landscape of temples, mountains, and rivers','published','zh-Hans',CURRENT_TIMESTAMP),
('myth-japanese','en','Japanese Mythology','Takamagahara · Yomi · Izumo','The age of the gods stretches from the creation of the islands to Takamagahara, Yomi, Izumo, and sea realms, shaped by sacred boundaries and natural forces.','Japanese Mythology — Kami, Takamagahara and Yomi','Explore Japanese mythology through the kami, creation myths, Takamagahara, Yomi, Izumo, and later legendary traditions.','Takamagahara with shrine architecture, mist, and moonlight','published','zh-Hans',CURRENT_TIMESTAMP),
('myth-celtic','en','Celtic Mythology','Sacred Groves · Heroic Cycles · Otherworld','Sacred groves, royal halls, standing stones, warrior legends, and journeys into the Otherworld shape a mythology where nature, sovereignty, and magic constantly meet.','Celtic Mythology — Gods, Heroes and the Otherworld','Explore Celtic mythology through Irish and wider Celtic gods, heroic cycles, sacred landscapes, and Otherworld traditions.','An ancient Celtic sacred landscape of forest, stone, and mist','published','zh-Hans',CURRENT_TIMESTAMP),
('myth-maya','en','Maya Mythology','World Tree · Xibalba · Hero Twins','The world tree connects sky, earth, and the underworld while creation stories, rain gods, maize, celestial cycles, and the Hero Twins animate the Maya cosmos.','Maya Mythology — Gods, Xibalba and the Hero Twins','Explore Maya mythology through creation stories, the Hero Twins, rain and maize deities, the world tree, and Xibalba.','A Maya sacred landscape with a stepped temple and world-tree imagery','published','zh-Hans',CURRENT_TIMESTAMP),
('myth-aztec','en','Aztec Mythology','Five Suns · Sacred War · Feathered Serpent','Cycles of suns, rain, maize, sacred warfare, and the Feathered Serpent define the Mexica sacred cosmos and its powerful network of divine forces.','Aztec Mythology — Gods, Five Suns and Sacred Cosmos','Explore Aztec mythology through Quetzalcoatl, Huitzilopochtli, Tlaloc, the Five Suns, and the sacred world of the Mexica.','An Aztec sacred cityscape with stepped temples and solar imagery','published','zh-Hans',CURRENT_TIMESTAMP),
('myth-mesopotamian','en','Mesopotamian Mythology','Cities · Stars · Two Rivers','Temple cities, cuneiform traditions, celestial signs, and the great rivers frame some of humanity''s earliest surviving myths of gods, kings, creation, and mortality.','Mesopotamian Mythology — Gods, Epics and Ancient Cities','Explore Mesopotamian mythology through Sumerian, Akkadian, and Babylonian gods, epics, creation traditions, and sacred cities.','An ancient Mesopotamian city with a ziggurat beneath the stars','published','zh-Hans',CURRENT_TIMESTAMP)
ON CONFLICT(mythology_id, locale) DO UPDATE SET
  name=excluded.name, tagline=excluded.tagline, summary=excluded.summary,
  seo_title=excluded.seo_title, seo_description=excluded.seo_description,
  hero_alt=excluded.hero_alt, translation_status='published', source_locale=excluded.source_locale,
  updated_at=CURRENT_TIMESTAMP;

INSERT INTO world_translations (
  world_id, locale, name, summary, seo_title, seo_description, hero_alt,
  translation_status, source_locale, updated_at
) VALUES
('world-heavenly-palace','en','Celestial Palace','Layered halls rise above a sea of clouds, where jade stairs, golden gates, and celestial thresholds connect the heavenly realms.','Celestial Palace — Chinese Mythology Realm','Explore the Celestial Palace as a MythCanvas realm of cloud seas, heavenly gates, jade architecture, and divine figures.','Celestial palaces and golden gates above a sea of clouds','published','zh-Hans',CURRENT_TIMESTAMP),
('world-olympus','en','Mount Olympus','The dwelling of the Olympian gods rises above high peaks and cloud banks, defined by white marble, open sky, and restrained golden light.','Mount Olympus — Greek Mythology Realm','Explore Mount Olympus, home of the Olympian gods, through its marble halls, divine characters, and visual identity.','White marble halls of Olympus above the clouds','published','zh-Hans',CURRENT_TIMESTAMP),
('world-asgard','en','Asgard','A northern divine realm of stone, metal, and luminous bridges, with Yggdrasil and the aurora shaping its distant horizon.','Asgard — Norse Mythology Realm','Explore Asgard, realm of the Aesir, through its gods, legendary structures, and northern visual language.','Asgard beneath the aurora with monumental stone halls','published','zh-Hans',CURRENT_TIMESTAMP),
('world-takamagahara','en','Takamagahara','The High Plain of Heaven is presented as a sacred celestial expanse of restrained shrine forms, mist, sky, and luminous natural thresholds.','Takamagahara — Japanese Mythology Realm','Explore Takamagahara, the heavenly realm of the kami, through its sacred boundaries, characters, and visual atmosphere.','Takamagahara with shrine forms between mist and moonlit clouds','published','zh-Hans',CURRENT_TIMESTAMP),
('world-duat','en','Duat','The Egyptian netherworld is crossed by the solar barque through gates, darkness, stars, and cycles of danger, judgment, and renewal.','Duat — Egyptian Mythology Realm','Explore the Duat, the Egyptian netherworld of the solar journey, sacred gates, judgment, and rebirth.','The solar barque crossing the star-filled Duat','published','zh-Hans',CURRENT_TIMESTAMP)
ON CONFLICT(world_id, locale) DO UPDATE SET
  name=excluded.name, summary=excluded.summary, seo_title=excluded.seo_title,
  seo_description=excluded.seo_description, hero_alt=excluded.hero_alt,
  translation_status='published', source_locale=excluded.source_locale, updated_at=CURRENT_TIMESTAMP;

INSERT INTO character_translations (
  character_id, locale, name, role, summary, seo_title, seo_description,
  translation_status, source_locale, updated_at
) VALUES
('character-change','en','Chang''e','Moon goddess and immortal','Chang''e is the central figure of Chinese moon legends, closely associated with the moon palace, the Jade Rabbit, and the Mid-Autumn tradition.','Chang''e — Chinese Moon Goddess','Explore Chang''e, the Chinese moon goddess, her mythic identity, visual symbols, and MythCanvas interpretations.','published','zh-Hans',CURRENT_TIMESTAMP),
('character-erlang-shen','en','Erlang Shen','Guardian deity with layered local and literary traditions','Erlang Shen brings together regional water-guardian traditions, religious worship, and later literary portrayals; MythCanvas keeps these source layers distinct rather than forcing them into one origin story.','Erlang Shen — Guardian Deity of Chinese Tradition','Explore Erlang Shen through source-aware local, religious, and literary interpretations.','published','zh-Hans',CURRENT_TIMESTAMP),

('character-athena','en','Athena','Goddess of wisdom, civic order, and strategic warfare','Athena is an Olympian goddess associated with wisdom, civic life, strategic warfare, the aegis, the spear, and the owl.','Athena — Greek Goddess of Wisdom','Explore Athena, Greek goddess of wisdom and strategic warfare, through mythic identity and original visual interpretations.','published','zh-Hans',CURRENT_TIMESTAMP),
('character-zeus','en','Zeus','King of the gods and god of sky and thunder','Zeus rules the Olympian order and is closely associated with the sky, thunder, the eagle, kingship, and the thunderbolt.','Zeus — King of the Greek Gods','Explore Zeus, ruler of Olympus and god of sky and thunder, through mythic identity and MythCanvas visual interpretations.','published','zh-Hans',CURRENT_TIMESTAMP),
('character-poseidon','en','Poseidon','God of the sea and earthquakes','Poseidon is the powerful god of the sea, earthquakes, and horses, most recognizably represented by the trident.','Poseidon — Greek God of the Sea','Explore Poseidon, Greek god of the sea and earthquakes, through his symbols, stories, and visual identity.','published','zh-Hans',CURRENT_TIMESTAMP),
('character-hades','en','Hades','King of the underworld','Hades rules the realm of the dead and is also associated with the hidden wealth beneath the earth.','Hades — King of the Greek Underworld','Explore Hades, ruler of the Greek underworld, through mythic identity, symbols, and visual interpretations.','published','zh-Hans',CURRENT_TIMESTAMP),
('character-hera','en','Hera','Goddess of marriage and royal authority','Hera is queen of Olympus, a goddess of marriage and sovereignty whose imagery often emphasizes dignity, kingship, and the peacock.','Hera — Queen of Olympus','Explore Hera, queen of Olympus and goddess of marriage and royal authority.','published','zh-Hans',CURRENT_TIMESTAMP),

('character-freyja','en','Freyja','Goddess of love, desire, magic, and battle','Freyja is one of the most prominent Norse goddesses, associated with love, desire, seiðr, precious adornment, and the slain.','Freyja — Norse Goddess of Love and Magic','Explore Freyja through Norse myth, her symbols, and original MythCanvas visual interpretations.','published','zh-Hans',CURRENT_TIMESTAMP),
('character-odin','en','Odin','God of wisdom, kingship, poetry, and war','Odin is the one-eyed ruler associated with wisdom, sacrifice, poetry, war, ravens, and the spear Gungnir.','Odin — Norse God of Wisdom','Explore Odin, the one-eyed Norse god of wisdom, kingship, poetry, and war.','published','zh-Hans',CURRENT_TIMESTAMP),
('character-thor','en','Thor','God of thunder','Thor protects gods and humans with Mjölnir, the hammer bound to thunder, strength, storms, and battles against giants.','Thor — Norse God of Thunder','Explore Thor, Norse god of thunder, through Mjölnir, mythic identity, and visual interpretations.','published','zh-Hans',CURRENT_TIMESTAMP),
('character-loki','en','Loki','Trickster and shape-shifter','Loki is a brilliant and unstable boundary-crossing figure whose schemes drive many of the conflicts and transformations of Norse myth.','Loki — Norse Trickster','Explore Loki, the shape-shifting trickster of Norse mythology, through stories, symbols, and visual interpretations.','published','zh-Hans',CURRENT_TIMESTAMP),
('character-frigg','en','Frigg','Goddess of marriage, motherhood, and foresight','Frigg is the queenly goddess of Asgard, closely associated with marriage, motherhood, household authority, and foreknowledge.','Frigg — Norse Queen of Asgard','Explore Frigg, Norse goddess of marriage, motherhood, and foresight.','published','zh-Hans',CURRENT_TIMESTAMP),

('character-anubis','en','Anubis','God of embalming and guardian of the dead','Anubis is the jackal-headed Egyptian deity associated with embalming, funerary protection, and the passage of the dead toward judgment.','Anubis — Egyptian Guardian of the Dead','Explore Anubis, Egyptian god of embalming and guardian of the dead, through mythic symbols and visual interpretations.','published','zh-Hans',CURRENT_TIMESTAMP),
('character-ra','en','Ra','Sun god','Ra is the solar deity whose daily journey across the sky and through the night world expresses renewal, kingship, and cosmic continuity.','Ra — Egyptian Sun God','Explore Ra, the Egyptian sun god, his solar journey, symbols, and visual identity.','published','zh-Hans',CURRENT_TIMESTAMP),
('character-osiris','en','Osiris','God of the dead and renewal','Osiris rules the realm of the dead and embodies themes of death, restoration, legitimate kingship, and renewed life.','Osiris — Egyptian God of the Dead and Rebirth','Explore Osiris through Egyptian myths of kingship, death, judgment, and renewal.','published','zh-Hans',CURRENT_TIMESTAMP),
('character-isis','en','Isis','Goddess of magic, motherhood, and royal protection','Isis is a major Egyptian goddess whose magical skill, protection, and devotion stand at the center of the Osiris and Horus cycle.','Isis — Egyptian Goddess of Magic','Explore Isis, Egyptian goddess of magic, motherhood, and royal protection.','published','zh-Hans',CURRENT_TIMESTAMP),
('character-horus','en','Horus','God of the sky and kingship','Horus is the falcon-associated sky god whose mythology became deeply connected with legitimate kingship and the living pharaoh.','Horus — Egyptian God of Sky and Kingship','Explore Horus through Egyptian myths of kingship, the falcon, and the Eye of Horus.','published','zh-Hans',CURRENT_TIMESTAMP),

('character-kaguya','en','Kaguya-hime','Moon princess of the Tale of the Bamboo Cutter','Kaguya-hime is the mysterious moon-born heroine of The Tale of the Bamboo Cutter, a literary legend kept distinct from the Takamagahara kami tradition.','Kaguya-hime — The Moon Princess','Explore Kaguya-hime, the moon princess of Japan''s Tale of the Bamboo Cutter.','published','zh-Hans',CURRENT_TIMESTAMP),
('character-amaterasu','en','Amaterasu','Sun goddess','Amaterasu is the central solar kami of Takamagahara, associated with light, heavenly order, and the sacred mirror.','Amaterasu — Japanese Sun Goddess','Explore Amaterasu, the solar kami of Japanese mythology, through her symbols and major myths.','published','zh-Hans',CURRENT_TIMESTAMP),
('character-susanoo','en','Susanoo','God of storms and the sea','Susanoo is a turbulent storm deity whose myths include conflict in heaven, exile, and the defeat of the eight-headed serpent Yamata no Orochi.','Susanoo — Japanese Storm God','Explore Susanoo, Japanese god of storms and the sea, through his myths and visual symbols.','published','zh-Hans',CURRENT_TIMESTAMP),
('character-tsukuyomi','en','Tsukuyomi','Moon god','Tsukuyomi is a lunar kami associated with the night, the moon, and the celestial order surrounding Amaterasu.','Tsukuyomi — Japanese Moon God','Explore Tsukuyomi, the lunar kami of Japanese mythology.','published','zh-Hans',CURRENT_TIMESTAMP),
('character-izanagi','en','Izanagi','Creator god','Izanagi is a creator deity who, together with Izanami, generates the islands and many kami before his famous return from Yomi and purification rite.','Izanagi — Japanese Creator God','Explore Izanagi through Japanese creation mythology, Yomi, and the purification that gives rise to major kami.','published','zh-Hans',CURRENT_TIMESTAMP),

('character-shiva','en','Shiva','God of destruction, transformation, and renewal','Shiva is a major Hindu deity associated with asceticism, cosmic dance, destruction, transformation, and the renewal that follows dissolution.','Shiva — Hindu God of Transformation','Explore Shiva through major mythic symbols including the trident, third eye, crescent moon, and cosmic dance.','published','zh-Hans',CURRENT_TIMESTAMP),
('character-vishnu','en','Vishnu','Preserver of cosmic order','Vishnu preserves cosmic order and dharma, appearing through major avatar traditions including Rama and Krishna.','Vishnu — Preserver of Cosmic Order','Explore Vishnu, his symbols, avatars, and role in preserving dharma and cosmic order.','published','zh-Hans',CURRENT_TIMESTAMP),
('character-brahma','en','Brahma','Creator god','Brahma is the creator deity of the Trimurti, commonly represented with four faces and associated with creation and sacred knowledge.','Brahma — Hindu Creator God','Explore Brahma, the four-faced creator deity associated with sacred knowledge and cosmic creation.','published','zh-Hans',CURRENT_TIMESTAMP),
('character-krishna','en','Krishna','Avatar of Vishnu, divine teacher, and pastoral hero','Krishna is one of the most influential figures of Indian sacred tradition, known as a divine child, pastoral hero, lover, king, and teacher of the Bhagavad Gita.','Krishna — Avatar, Hero and Divine Teacher','Explore Krishna through epic, devotional, and philosophical traditions and his major visual symbols.','published','zh-Hans',CURRENT_TIMESTAMP),
('character-rama','en','Rama','Avatar of Vishnu and epic hero','Rama is the central hero of the Ramayana and an influential model of kingship, duty, and dharma.','Rama — Hero of the Ramayana','Explore Rama, the epic hero and avatar of Vishnu, through the Ramayana and his symbols of kingship and dharma.','published','zh-Hans',CURRENT_TIMESTAMP),

('character-morrigan','en','The Mórrigan','Goddess of war, fate, and sovereignty','The Mórrigan is a powerful figure of Irish mythology associated with battle, fate, sovereignty, prophecy, and transformations that often involve the raven or crow.','The Mórrigan — Irish Goddess of War and Fate','Explore the Mórrigan through Irish myth, battle symbolism, sovereignty, and transformation.','published','zh-Hans',CURRENT_TIMESTAMP),
('character-cu-chulainn','en','Cú Chulainn','Hero of the Ulster Cycle','Cú Chulainn is the great warrior hero of the Ulster Cycle, famous for extraordinary combat, the spear Gáe Bolg, and a tragic heroic destiny.','Cú Chulainn — Hero of the Ulster Cycle','Explore Cú Chulainn, the legendary warrior of the Ulster Cycle, through his myths and symbols.','published','zh-Hans',CURRENT_TIMESTAMP),
('character-lugh','en','Lugh','God of skill, leadership, and sovereignty','Lugh is a leading figure of the Tuatha Dé Danann, renowned for mastery of many arts, royal authority, and his formidable spear.','Lugh — Celtic God of Many Skills','Explore Lugh through Irish mythology, kingship, craftsmanship, and the Tuatha Dé Danann.','published','zh-Hans',CURRENT_TIMESTAMP),
('character-brigid','en','Brigid','Goddess of poetry, healing, and smithcraft','Brigid is an important Irish goddess associated with poetry, healing, craft, sacred fire, and creative inspiration.','Brigid — Celtic Goddess of Poetry and Healing','Explore Brigid through traditions of poetry, healing, sacred fire, and craftsmanship.','published','zh-Hans',CURRENT_TIMESTAMP),
('character-dagda','en','The Dagda','God of abundance, magic, and leadership','The Dagda is a powerful leader of the Tuatha Dé Danann, associated with abundance, a great club, a magical harp, and an inexhaustible cauldron.','The Dagda — Celtic God of Abundance','Explore the Dagda through Irish mythology, magical objects, abundance, and divine leadership.','published','zh-Hans',CURRENT_TIMESTAMP),

('character-kukulkan','en','Kukulkan','Feathered Serpent deity','Kukulkan is the famous Feathered Serpent deity of Yucatec Maya tradition, associated with wind, rulership, order, and the monumental setting of Chichen Itza.','Kukulkan — Maya Feathered Serpent','Explore Kukulkan, the Maya Feathered Serpent deity, through sacred symbols and visual interpretations.','published','zh-Hans',CURRENT_TIMESTAMP),
('character-itzamna','en','Itzamna','Creator and knowledge deity','Itzamna is an important Maya creator and culture deity associated with knowledge, writing, calendrical learning, medicine, and priestly authority.','Itzamna — Maya Creator and Knowledge Deity','Explore Itzamna through Maya traditions of creation, writing, knowledge, and sacred authority.','published','zh-Hans',CURRENT_TIMESTAMP),
('character-ix-chel','en','Ix Chel','Goddess associated with the moon, childbirth, medicine, and weaving','Ix Chel is an important Maya goddess associated in later and regional traditions with the moon, childbirth, healing, water, and weaving.','Ix Chel — Maya Goddess of Moon and Healing Traditions','Explore Ix Chel through Maya traditions of the moon, medicine, childbirth, water, and weaving.','published','zh-Hans',CURRENT_TIMESTAMP),
('character-chaac','en','Chaac','Rain and storm deity','Chaac is a widely venerated Maya rain deity associated with storms, lightning, agriculture, and life-giving water.','Chaac — Maya Rain God','Explore Chaac, Maya deity of rain and storms, through his symbols and agricultural significance.','published','zh-Hans',CURRENT_TIMESTAMP),
('character-hunahpu','en','Hunahpu','One of the Hero Twins','Hunahpu is one of the Hero Twins of the Popol Vuh, whose trials, deaths, transformations, and victory over the lords of Xibalba form a central K''iche'' Maya narrative.','Hunahpu — Maya Hero Twin','Explore Hunahpu, one of the Hero Twins of the Popol Vuh, through the trials of Xibalba.','published','zh-Hans',CURRENT_TIMESTAMP),

('character-quetzalcoatl','en','Quetzalcoatl','Feathered Serpent, god of wind and civilization','Quetzalcoatl is one of the best-known deities of central Mexico, associated with the Feathered Serpent, wind, knowledge, priestly authority, and traditions of human creation.','Quetzalcoatl — Aztec Feathered Serpent','Explore Quetzalcoatl through Aztec and central Mexican traditions of wind, knowledge, and the Feathered Serpent.','published','zh-Hans',CURRENT_TIMESTAMP),
('character-huitzilopochtli','en','Huitzilopochtli','God of sun and war, patron of the Mexica','Huitzilopochtli is the central patron deity of the Mexica, closely tied to solar warfare, migration tradition, and the sacred center of Tenochtitlan.','Huitzilopochtli — Mexica God of Sun and War','Explore Huitzilopochtli, patron of the Mexica, through solar, martial, and Tenochtitlan traditions.','published','zh-Hans',CURRENT_TIMESTAMP),
('character-tezcatlipoca','en','Tezcatlipoca','God of night, fate, conflict, and rulership','Tezcatlipoca, the Smoking Mirror, is a major deity associated with night, fate, power, rulership, conflict, and jaguar imagery.','Tezcatlipoca — The Smoking Mirror','Explore Tezcatlipoca through Aztec traditions of fate, night, kingship, conflict, and the obsidian mirror.','published','zh-Hans',CURRENT_TIMESTAMP),
('character-tlaloc','en','Tlaloc','God of rain, water, and storms','Tlaloc is one of the most important rain deities of central Mexico, governing water, storms, agricultural fertility, and dangerous weather.','Tlaloc — Aztec Rain God','Explore Tlaloc, deity of rain and water, through his distinctive symbols and agricultural role.','published','zh-Hans',CURRENT_TIMESTAMP),
('character-coatlicue','en','Coatlicue','Earth mother goddess','Coatlicue is a formidable earth mother whose serpent-skirt imagery expresses the intertwined forces of fertility, life, death, and cosmic regeneration.','Coatlicue — Aztec Earth Mother','Explore Coatlicue through Aztec earth, fertility, life-and-death symbolism, and monumental visual identity.','published','zh-Hans',CURRENT_TIMESTAMP),

('character-gilgamesh','en','Gilgamesh','Hero-king of Uruk','Gilgamesh is the hero-king at the center of the Epic of Gilgamesh, whose journey moves from power and friendship to grief and the search for the meaning of mortality.','Gilgamesh — Hero-King of Uruk','Explore Gilgamesh through the ancient epic of friendship, kingship, mortality, and the search for enduring meaning.','published','zh-Hans',CURRENT_TIMESTAMP),
('character-enkidu','en','Enkidu','Wild-born hero and companion of Gilgamesh','Enkidu begins as a figure of the wilderness before entering human society and becoming Gilgamesh''s closest companion and equal.','Enkidu — Companion of Gilgamesh','Explore Enkidu through the Epic of Gilgamesh, from wilderness to friendship, civilization, and loss.','published','zh-Hans',CURRENT_TIMESTAMP),
('character-ishtar','en','Ishtar / Inanna','Goddess of love, war, and Venus','Inanna and Ishtar stand among the most important goddesses of Mesopotamia, associated with desire, warfare, royal power, and the planet Venus across related but historically distinct traditions.','Ishtar / Inanna — Mesopotamian Goddess of Love and War','Explore Inanna and Ishtar through Mesopotamian traditions of love, war, kingship, and Venus.','published','zh-Hans',CURRENT_TIMESTAMP),
('character-enki','en','Enki / Ea','God of wisdom, magic, and fresh water','Enki, known as Ea in Akkadian tradition, is a god of wisdom, craft, magic, and fresh water who repeatedly acts through clever counsel in creation and flood traditions.','Enki / Ea — Mesopotamian God of Wisdom','Explore Enki through Sumerian and Akkadian traditions of wisdom, magic, fresh water, creation, and human survival.','published','zh-Hans',CURRENT_TIMESTAMP),
('character-enlil','en','Enlil','God of wind, atmosphere, and divine authority','Enlil is one of the most powerful gods of early Mesopotamian religion, associated with wind, atmosphere, kingship, and the authority that structures the divine order.','Enlil — Mesopotamian God of Wind and Authority','Explore Enlil through Sumerian traditions of wind, kingship, divine authority, and cosmic order.','published','zh-Hans',CURRENT_TIMESTAMP)
ON CONFLICT(character_id, locale) DO UPDATE SET
  name=excluded.name, role=excluded.role, summary=excluded.summary,
  seo_title=excluded.seo_title, seo_description=excluded.seo_description,
  translation_status='published', source_locale=excluded.source_locale, updated_at=CURRENT_TIMESTAMP;
