import type { MythStory, MythStorySource } from '../../lib/content/types';

const date = '2026-08-30';
const mythologyId = 'myth-greek';

const sources = {
  theogony: { sourceId: 'source-greek-hesiod-theogony', title: 'Hesiod, Theogony', sourceType: 'primary-text', tradition: '赫西俄德神谱传统', period: '约公元前7—前6世纪', language: 'grc', locator: '按故事主题参见相应诗行' },
  works: { sourceId: 'source-greek-hesiod-works-days', title: 'Hesiod, Works and Days', sourceType: 'primary-text', tradition: '赫西俄德传统', period: '约公元前7—前6世纪', language: 'grc', locator: '42–105' },
  hymnDemeter: { sourceId: 'source-greek-homeric-hymn-demeter', title: 'Homeric Hymn to Demeter', sourceType: 'primary-text', tradition: '荷马颂歌传统', period: '古风时期至古典时期', language: 'grc', locator: '1–495' },
  hymnApollo: { sourceId: 'source-greek-homeric-hymn-apollo', title: 'Homeric Hymn to Apollo', sourceType: 'primary-text', tradition: '荷马颂歌传统', period: '古风时期至古典时期', language: 'grc', locator: '1–546' },
  hymnHermes: { sourceId: 'source-greek-homeric-hymn-hermes', title: 'Homeric Hymn to Hermes', sourceType: 'primary-text', tradition: '荷马颂歌传统', period: '古风时期至古典时期', language: 'grc', locator: '1–580' },
  hymnAphrodite: { sourceId: 'source-greek-homeric-hymn-aphrodite', title: 'Homeric Hymn to Aphrodite', sourceType: 'primary-text', tradition: '荷马颂歌传统', period: '古风时期至古典时期', language: 'grc', locator: '1–293' },
  hymnDionysus: { sourceId: 'source-greek-homeric-hymn-dionysus', title: 'Homeric Hymn to Dionysus', sourceType: 'primary-text', tradition: '荷马颂歌传统', period: '古风时期至古典时期', language: 'grc', locator: '1–59' },
  iliad: { sourceId: 'source-greek-homer-iliad', title: 'Homer, Iliad', sourceType: 'primary-text', tradition: '荷马史诗传统', period: '约公元前8—前7世纪', language: 'grc', locator: '按故事主题参见相应卷' },
  odyssey: { sourceId: 'source-greek-homer-odyssey', title: 'Homer, Odyssey', sourceType: 'primary-text', tradition: '荷马史诗传统', period: '约公元前8—前7世纪', language: 'grc', locator: '按故事主题参见相应卷' },
  apollonius: { sourceId: 'source-greek-apollonius-argonautica', title: 'Apollonius Rhodius, Argonautica', sourceType: 'primary-text', tradition: '阿尔戈英雄传统', period: '希腊化时期', language: 'grc', locator: 'Books 1–4' },
  sophocles: { sourceId: 'source-greek-sophocles-oedipus', title: 'Sophocles, Oedipus Tyrannus', sourceType: 'primary-text', tradition: '底比斯悲剧传统', period: '古典时期', language: 'grc', locator: '全剧' },
  euripides: { sourceId: 'source-greek-euripides-bacchae', title: 'Euripides, Bacchae', sourceType: 'primary-text', tradition: '狄俄尼索斯悲剧传统', period: '古典时期', language: 'grc', locator: '全剧' },
  apollodorus: { sourceId: 'source-greek-pseudo-apollodorus-bibliotheca', title: 'Pseudo-Apollodorus, Bibliotheca', sourceType: 'scholarly-reference', tradition: '古代神话整理传统', period: '罗马帝国时期', language: 'grc', locator: '按故事主题参见相应卷章' },
  ovid: { sourceId: 'source-roman-ovid-metamorphoses', title: 'Ovid, Metamorphoses', sourceType: 'primary-text', tradition: '罗马接受传统', period: '罗马帝国早期', language: 'la', locator: '按故事主题参见相应卷', note: '罗马接受传统；不作为希腊唯一原典。' },
} as const satisfies Record<string, MythStorySource>;

type StoryInput = {
  slug: string;
  title: string;
  titleEn: string;
  subtitle: string;
  summary: string;
  volumeId: string;
  volumeTitle: string;
  volumeOrder: number;
  displayOrder: number;
  tradition: string;
  source: MythStorySource;
  requiredCharacterIds: readonly string[];
  requiredWorldIds?: readonly string[];
  requiredSceneIds?: readonly string[];
  narrative: readonly [string, string];
};

const story = (input: StoryInput): MythStory => ({
  id: `story-${input.slug}`,
  slug: input.slug,
  mythologyId,
  title: input.title,
  titleEn: input.titleEn,
  subtitle: input.subtitle,
  summary: input.summary,
  volumeId: input.volumeId,
  volumeTitle: input.volumeTitle,
  volumeOrder: input.volumeOrder,
  displayOrder: input.displayOrder,
  kind: 'myth',
  tradition: input.tradition,
  readingMinutes: 4,
  sources: [input.source],
  sourceNotes: [`本篇以 ${input.source.title} 为主要叙事依据；不同文本及后世接受传统可能保留不同细节。`, '页面采用可阅读的策展顺序，不将其呈现为所有古希腊传统唯一的绝对时间线。'],
  requiredCharacterIds: input.requiredCharacterIds,
  requiredWorldIds: input.requiredWorldIds ?? [],
  requiredSceneIds: input.requiredSceneIds ?? [],
  requiredSourceIds: [input.source.sourceId ?? input.source.title],
  characterIds: input.requiredCharacterIds,
  worldIds: input.requiredWorldIds ?? [],
  sceneIds: input.requiredSceneIds ?? [],
  claims: [{
    id: `claim-${input.slug}-narrative`, subjectType: 'story', subjectId: `story-${input.slug}`,
    claimType: 'narrative', summary: input.summary, status: 'supported',
    traditionScope: input.tradition,
    sourceRefs: [{ type: 'primary-text', title: input.source.title, locator: input.source.locator ?? '全文', language: input.source.language }],
  }],
  blocks: [
    { type: 'paragraph', text: input.narrative[0] },
    { type: 'paragraph', text: input.narrative[1] },
    { type: 'quote', text: '这一页呈现的是有来源的 MythCanvas 编辑性讲述；版本差异请以来源说明为准。', source: '版本说明' },
  ],
  heroAssetId: 'story-illustration-olympus',
  publishStatus: 'published',
  publishedAt: date,
  updatedAt: date,
});

export const greekStories: readonly MythStory[] = [
  story({ slug: 'creation-from-chaos', title: '混沌与世界诞生', titleEn: 'Creation from Chaos', subtitle: '最初的并非一座神殿，而是开端本身', summary: '卡俄斯、盖亚、塔耳塔罗斯与爱欲构成希腊宇宙最早出现的力量。', volumeId: 'creation', volumeTitle: '创世与神族更替', volumeOrder: 1, displayOrder: 1, tradition: '赫西俄德神谱传统', source: sources.theogony, requiredCharacterIds: ['character-chaos', 'character-gaia', 'character-tartarus', 'character-eros'], requiredWorldIds: ['world-tartarus'], narrative: ['《神谱》的开端不是从一个已经完整的神界讲起，而是从卡俄斯这一无法被普通空间概念完全容纳的开端开始。盖亚提供可承载万物的大地，塔耳塔罗斯标出深不可测的边界，厄洛斯则使生成与连接成为可能。', '这些原初力量不是后来奥林匹斯式的“角色阵容”。它们首先解释世界何以有层次、有繁衍，也为之后天空、大地、泰坦与诸神的秩序铺开舞台。'] }),
  story({ slug: 'gaia-and-uranus', title: '盖亚与乌拉诺斯', titleEn: 'Gaia and Uranus', subtitle: '大地与天空形成第一代神族', summary: '盖亚生出天空乌拉诺斯，二者的结合孕育泰坦和更早的神族冲突。', volumeId: 'creation', volumeTitle: '创世与神族更替', volumeOrder: 1, displayOrder: 2, tradition: '赫西俄德神谱传统', source: sources.theogony, requiredCharacterIds: ['character-gaia', 'character-uranus', 'character-cronus'], narrative: ['盖亚与乌拉诺斯的关系把大地与天空置于同一宇宙图景中。由他们而来的泰坦、独眼巨人与百臂巨人，使神谱从原初力量转化为具有代际关系的家族。', '但第一代秩序并不稳定。乌拉诺斯对后代的压制引出盖亚的不满，也使“子代推翻父代”的模式成为希腊神话最重要的结构之一。'] }),
  story({ slug: 'cronus-overthrows-uranus', title: '克洛诺斯推翻乌拉诺斯', titleEn: 'Cronus Overthrows Uranus', subtitle: '第一次神王更替', summary: '在盖亚协助下，克洛诺斯以镰刀推翻父亲乌拉诺斯，开启泰坦统治。', volumeId: 'creation', volumeTitle: '创世与神族更替', volumeOrder: 1, displayOrder: 3, tradition: '赫西俄德神谱传统', source: sources.theogony, requiredCharacterIds: ['character-gaia', 'character-uranus', 'character-cronus'], narrative: ['盖亚把武器交给最愿意行动的儿子克洛诺斯。克洛诺斯伏击乌拉诺斯的情节极其激烈，但它的核心不是单纯暴力，而是宇宙权力第一次从父代转向子代。', '克洛诺斯由此成为泰坦之王，却也继承了一个可怕的预言：他将像父亲一样被自己的子女推翻。'] }),
  story({ slug: 'cronus-swallows-children', title: '克洛诺斯吞噬子女', titleEn: 'Cronus Swallows His Children', subtitle: '预言使新王重复旧王的恐惧', summary: '克洛诺斯吞下与瑞亚所生的子女，试图阻止新的神王更替。', volumeId: 'creation', volumeTitle: '创世与神族更替', volumeOrder: 1, displayOrder: 4, tradition: '赫西俄德神谱传统', source: sources.theogony, requiredCharacterIds: ['character-cronus', 'character-rhea', 'character-hestia', 'character-demeter', 'character-hera', 'character-hades', 'character-poseidon', 'character-zeus'], narrative: ['克洛诺斯把每一个新生子女吞入腹中，试图让预言失效。瑞亚失去孩子，却没有接受这套循环成为唯一结局。', '这个故事把泰坦统治写成一种被恐惧冻结的秩序：为了不失去权力，神王反而拒绝让新的生命进入世界。'] }),
  story({ slug: 'birth-and-return-of-zeus', title: '宙斯的诞生与成长', titleEn: 'The Birth and Return of Zeus', subtitle: '被藏起的幼神回到权力中心', summary: '瑞亚以石头代替婴儿，宙斯在隐秘处成长并迫使克洛诺斯吐出兄弟姐妹。', volumeId: 'creation', volumeTitle: '创世与神族更替', volumeOrder: 1, displayOrder: 5, tradition: '赫西俄德神谱传统', source: sources.theogony, requiredCharacterIds: ['character-rhea', 'character-cronus', 'character-zeus', 'character-hestia', 'character-demeter', 'character-hera', 'character-hades', 'character-poseidon'], narrative: ['瑞亚把宙斯藏起，再以裹着襁褓的石头欺骗克洛诺斯。被延后的出生因此成为一次有策略的反击，而不是偶然逃脱。', '成年后的宙斯使父亲吐出被吞没的兄弟姐妹。新一代重新聚集，泰坦战争随之成为不可避免的下一步。'] }),
  story({ slug: 'titanomachy', title: '泰坦战争', titleEn: 'Titanomachy', subtitle: '新一代诸神争夺宇宙秩序', summary: '宙斯与同盟者战胜泰坦，结束克洛诺斯的统治。', volumeId: 'creation', volumeTitle: '创世与神族更替', volumeOrder: 1, displayOrder: 6, tradition: '赫西俄德神谱传统', source: sources.theogony, requiredCharacterIds: ['character-zeus', 'character-poseidon', 'character-hades', 'character-cronus', 'character-atlas'], requiredWorldIds: ['world-tartarus'], narrative: ['泰坦战争不是一场单一英雄决斗，而是不同代际神族对宇宙结构的争夺。宙斯的联盟得到被囚力量的帮助，终于击败克洛诺斯一方。', '战败的泰坦被置于塔耳塔罗斯，阿特拉斯承担天穹。战争的结果不是消灭旧神，而是把旧力量安置在新的宇宙秩序中。'] }),
  story({ slug: 'division-of-the-world', title: '三兄弟划分世界', titleEn: 'The Division of the World', subtitle: '天空、海洋与冥界的分工', summary: '宙斯、波塞冬与哈迪斯分掌天空、海洋和冥界，形成奥林匹斯时代的基本空间秩序。', volumeId: 'creation', volumeTitle: '创世与神族更替', volumeOrder: 1, displayOrder: 7, tradition: '荷马史诗传统', source: sources.iliad, requiredCharacterIds: ['character-zeus', 'character-poseidon', 'character-hades'], requiredWorldIds: ['world-olympus', 'world-sea-realm', 'world-underworld'], narrative: ['新秩序并不意味着所有权力都集中在宙斯一人手中。三兄弟以抽签方式分得天空、海洋与冥界，而大地与奥林匹斯仍是共同关涉的空间。', '这种分工解释了为何波塞冬与哈迪斯并非宙斯的臣属替身：他们各自拥有不可轻易取代的神域与权能。'] }),
  story({ slug: 'zeus-and-typhon', title: '宙斯大战堤丰', titleEn: 'Zeus and Typhon', subtitle: '秩序面对最后的风暴', summary: '堤丰以风暴般的怪物力量挑战宙斯，神王以雷霆巩固新秩序。', volumeId: 'creation', volumeTitle: '创世与神族更替', volumeOrder: 1, displayOrder: 8, tradition: '赫西俄德神谱传统', source: sources.theogony, requiredCharacterIds: ['character-zeus', 'character-typhon'], requiredWorldIds: ['world-tartarus'], narrative: ['在泰坦战争之后，堤丰仍以超越常规神祇的怪物力量出现。它让新秩序意识到：取代旧王并不等于混沌已经彻底退场。', '宙斯以雷霆击败堤丰，故事把天空神的武器与维持宇宙边界的能力紧密连接起来。'] }),
  story({ slug: 'prometheus-brings-fire', title: '普罗米修斯盗火', titleEn: 'Prometheus Brings Fire', subtitle: '火种、技艺与神人的边界', summary: '普罗米修斯把火带给人类，也因此触碰宙斯划定的神人边界。', volumeId: 'olympian-order', volumeTitle: '奥林匹斯秩序', volumeOrder: 2, displayOrder: 1, tradition: '赫西俄德传统及后世希腊文学', source: sources.works, requiredCharacterIds: ['character-prometheus', 'character-zeus'], requiredSceneIds: ['scene-prometheus-rock'], narrative: ['火在这里不仅意味着温暖，也意味着技术、祭祀和改变生活的能力。普罗米修斯把这一力量带给人类，使神与人的边界发生转移。', '宙斯的惩罚把普罗米修斯固定在高山与鹰的循环中。故事的张力来自文明的礼物与越界代价同时成立。'] }),
  story({ slug: 'pandora', title: '潘多拉与匣', titleEn: 'Pandora and the Jar', subtitle: '苦难如何进入人间', summary: '潘多拉打开容器后，疾病、劳作与忧患散入人间，而希望仍以复杂的方式留在其中。', volumeId: 'olympian-order', volumeTitle: '奥林匹斯秩序', volumeOrder: 2, displayOrder: 2, tradition: '赫西俄德传统', source: sources.works, requiredCharacterIds: ['character-pandora', 'character-zeus', 'character-prometheus'], narrative: ['潘多拉故事与火种故事相互照应：在人类获得技术之后，人间也获得了无法回避的劳作、疾病与忧患。', '容器中留下的“希望”究竟意味着保留、延迟还是另一种限制，历来存在解释差异。页面保留这一开放性，而不把它简化为单一寓言。'] }),
  story({ slug: 'birth-of-athena', title: '雅典娜诞生', titleEn: 'The Birth of Athena', subtitle: '从神王自身生出的智慧与武装', summary: '雅典娜从宙斯头颅中全副武装而生，成为智慧、城邦与战略战争的女神。', volumeId: 'olympian-order', volumeTitle: '奥林匹斯秩序', volumeOrder: 2, displayOrder: 3, tradition: '赫西俄德神谱传统', source: sources.theogony, requiredCharacterIds: ['character-zeus', 'character-metis', 'character-athena'], requiredWorldIds: ['world-olympus'], requiredSceneIds: ['scene-court-of-gods'], narrative: ['宙斯吞下墨提斯之后，雅典娜以完整、成熟、武装的形态出现。她的诞生方式把智慧、神王权力与城邦秩序连接起来。', '不同艺术和文学传统会强调不同细节，但雅典娜并非单纯“女战神”：她的长矛、盾与猫头鹰共同指向策略、守护和技艺。'] }),
  story({ slug: 'demeter-and-persephone', title: '得墨忒耳与珀耳塞福涅', titleEn: 'Demeter and Persephone', subtitle: '离开、归来与大地的循环', summary: '珀耳塞福涅进入冥界后，得墨忒耳使大地停止生长；往返秩序最终形成。', volumeId: 'olympian-order', volumeTitle: '奥林匹斯秩序', volumeOrder: 2, displayOrder: 4, tradition: '致得墨忒耳颂歌传统', source: sources.hymnDemeter, requiredCharacterIds: ['character-demeter', 'character-persephone', 'character-hades', 'character-zeus'], requiredWorldIds: ['world-underworld'], requiredSceneIds: ['scene-eleusis', 'scene-palace-of-hades'], narrative: ['珀耳塞福涅离开后，得墨忒耳停止让庄稼生长。神与人的祭祀交换也因此濒临中断，母女关系成为宇宙秩序问题。', '最终形成的不是永久团聚，而是往返。它与厄琉息斯传统、生死边界和农业循环相连，不能只缩减为“四季起源”的图解。'] }),
  story({ slug: 'apollo-and-delphi', title: '阿波罗与德尔斐', titleEn: 'Apollo and Delphi', subtitle: '神谕如何被建立', summary: '阿波罗取得德尔斐圣地，将音乐、弓术与预言置入一个可被城邦咨询的神圣中心。', volumeId: 'olympian-order', volumeTitle: '奥林匹斯秩序', volumeOrder: 2, displayOrder: 5, tradition: '荷马颂歌传统', source: sources.hymnApollo, requiredCharacterIds: ['character-apollo', 'character-python'], requiredSceneIds: ['scene-delphi'], narrative: ['德尔斐不是一个只属于单一神祇的空白舞台。阿波罗在此建立神谕权威的叙事，保留了与蛇形守护力量相遇和取代的痕迹。', '因此，阿波罗的稳定身份应以预言、音乐、弓术与疗愈为中心；后期的太阳认同需要作为另一层接受传统被清楚标示。'] }),
  story({ slug: 'hermes-and-the-cattle', title: '赫尔墨斯出生与偷牛', titleEn: 'Hermes and the Cattle', subtitle: '神使从第一天起就越过边界', summary: '新生的赫尔墨斯偷走阿波罗的牛群，并以里拉琴完成和解。', volumeId: 'olympian-order', volumeTitle: '奥林匹斯秩序', volumeOrder: 2, displayOrder: 6, tradition: '荷马颂歌传统', source: sources.hymnHermes, requiredCharacterIds: ['character-hermes', 'character-apollo', 'character-maia', 'character-zeus'], narrative: ['赫尔墨斯一出生就离开洞穴、偷走牛群、发明里拉琴。这个故事用夸张的速度表现他作为旅行、交易、机智和边界之神的特征。', '冲突最终以礼物和交换解决：阿波罗得到乐器，赫尔墨斯获得被承认的神圣位置。'] }),
  story({ slug: 'birth-of-aphrodite', title: '阿佛洛狄忒的诞生', titleEn: 'The Birth of Aphrodite', subtitle: '海沫与爱欲的形象', summary: '赫西俄德传统中，阿佛洛狄忒从海沫而生；其他传统则给出不同谱系。', volumeId: 'olympian-order', volumeTitle: '奥林匹斯秩序', volumeOrder: 2, displayOrder: 7, tradition: '赫西俄德与荷马传统', source: sources.theogony, requiredCharacterIds: ['character-aphrodite', 'character-uranus'], requiredWorldIds: ['world-sea-realm'], narrative: ['海沫诞生让阿佛洛狄忒的视觉语言天然带有海岸、贝壳与风的轻盈感，但这不等于所有传统都使用同一谱系。', '页面把赫西俄德的诞生叙事作为明确来源范围内的讲述，同时在资料层保留其他传统，不用一个版本覆盖全部。'] }),
  story({ slug: 'birth-of-dionysus', title: '狄俄尼索斯的诞生', titleEn: 'The Birth of Dionysus', subtitle: '火焰、酒藤与双重出生', summary: '塞墨勒与宙斯之子的诞生传统，使狄俄尼索斯带有死亡、重生和仪式越界的力量。', volumeId: 'olympian-order', volumeTitle: '奥林匹斯秩序', volumeOrder: 2, displayOrder: 8, tradition: '悲剧与后世神话传统', source: sources.euripides, requiredCharacterIds: ['character-dionysus', 'character-semele', 'character-zeus', 'character-hera'], narrative: ['狄俄尼索斯的诞生常被讲述为一段经过火焰、失去与再生的故事。他既与王室血缘相连，也与酒、戏剧和集体仪式中的越界感相连。', '不同文本对细节有差异，因此“二次出生”等表达需要始终带着传统范围，而不被做成无来源的固定设定。'] }),
  story({ slug: 'hephaestus-and-the-forge', title: '赫淮斯托斯与神之锻炉', titleEn: 'Hephaestus and the Divine Forge', subtitle: '技艺在神界的位置', summary: '赫淮斯托斯以火与锻造制造神圣器物，也让技艺成为奥林匹斯秩序不可缺少的一部分。', volumeId: 'olympian-order', volumeTitle: '奥林匹斯秩序', volumeOrder: 2, displayOrder: 9, tradition: '荷马与后世神话传统', source: sources.iliad, requiredCharacterIds: ['character-hephaestus', 'character-hera', 'character-zeus'], requiredSceneIds: ['scene-forge-of-hephaestus'], narrative: ['赫淮斯托斯的锻炉不是普通的“奇幻武器工坊”。火、材料和反复劳动使神圣器物能够被制造，也让技艺拥有独立的尊严。', '他的出生与离开奥林匹斯的细节在不同传统中并不一致；页面不以一个版本消除这种复杂性。'] }),
  story({ slug: 'perseus-and-medusa', title: '珀尔修斯与美杜莎', titleEn: 'Perseus and Medusa', subtitle: '镜盾、目光与英雄的危险任务', summary: '珀尔修斯借助神赐器物斩下美杜莎首级，避免直视会使人石化的目光。', volumeId: 'hero-cycles', volumeTitle: '英雄周期', volumeOrder: 3, displayOrder: 1, tradition: '古代神话整理与后世诗歌传统', source: sources.apollodorus, requiredCharacterIds: ['character-perseus', 'character-medusa', 'character-athena', 'character-hermes'], narrative: ['美杜莎的凝视使直接对抗变得不可能。珀尔修斯依靠反射、飞行与神赐器物完成任务，胜利始终带有策略和协助的成分。', '关于美杜莎如何成为戈耳工以及雅典娜在其中的位置，存在不同叙事层；页面将人物身份与具体故事版本分开处理。'] }),
  story({ slug: 'heracles-twelve-labours', title: '赫拉克勒斯十二伟业', titleEn: 'The Twelve Labours of Heracles', subtitle: '以劳役建立英雄声名', summary: '赫拉克勒斯通过一系列危险劳役面对怪物、边界与不可能完成的任务。', volumeId: 'hero-cycles', volumeTitle: '英雄周期', volumeOrder: 3, displayOrder: 2, tradition: '英雄传说与古代整理传统', source: sources.apollodorus, requiredCharacterIds: ['character-heracles', 'character-hydra', 'character-cerberus'], requiredWorldIds: ['world-underworld'], requiredSceneIds: ['scene-nemea', 'scene-gate-of-hades'], narrative: ['十二伟业把赫拉克勒斯的力量放进连续的劳役结构中：每次任务都迫使他进入怪物、荒野或冥界边界。', '“十二”与具体任务列表在流传中逐渐稳定，页面以策展主线阅读而非宣称每一细节都来自同一部早期文本。'] }),
  story({ slug: 'theseus-and-minotaur', title: '忒修斯与米诺陶洛斯', titleEn: 'Theseus and the Minotaur', subtitle: '线团穿过迷宫', summary: '忒修斯进入克里特迷宫，以阿里阿德涅的线团找到归路并击败米诺陶洛斯。', volumeId: 'hero-cycles', volumeTitle: '英雄周期', volumeOrder: 3, displayOrder: 3, tradition: '雅典与克里特英雄传统', source: sources.apollodorus, requiredCharacterIds: ['character-theseus', 'character-minotaur', 'character-ariadne'], requiredSceneIds: ['scene-cretan-labyrinth'], narrative: ['迷宫让力量本身失去方向。阿里阿德涅提供的线团因此不是装饰道具，而是使忒修斯能够进入、完成任务并返回的关键。', '故事将城邦、海上贡赋和怪物恐惧集中在同一座建筑里，也让迷宫成为极具复用价值的 MythCanvas 场景。'] }),
  story({ slug: 'jason-and-golden-fleece', title: '伊阿宋与金羊毛', titleEn: 'Jason and the Golden Fleece', subtitle: '跨海远征与危险的合作', summary: '伊阿宋率阿尔戈英雄抵达科尔喀斯，在美狄亚帮助下取得金羊毛。', volumeId: 'hero-cycles', volumeTitle: '英雄周期', volumeOrder: 3, displayOrder: 4, tradition: '阿尔戈英雄传统', source: sources.apollonius, requiredCharacterIds: ['character-jason', 'character-medea'], requiredSceneIds: ['scene-colchis'], narrative: ['金羊毛并非只是一件宝物，它把远航、异地王权和一系列超常试炼连接起来。伊阿宋的成功离不开同行者，也离不开美狄亚的选择。', '把美狄亚处理成单纯的“魔女工具人”会掩盖她在叙事中主动、复杂且随版本变化的位置。'] }),
  story({ slug: 'orpheus-and-eurydice', title: '俄耳甫斯与欧律狄刻', titleEn: 'Orpheus and Eurydice', subtitle: '回望之前的承诺', summary: '俄耳甫斯以音乐进入冥界，获准带回欧律狄刻，却因回望而失去她。', volumeId: 'hero-cycles', volumeTitle: '英雄周期', volumeOrder: 3, displayOrder: 5, tradition: '希腊与罗马诗歌接受传统', source: sources.ovid, requiredCharacterIds: ['character-orpheus', 'character-eurydice', 'character-hades', 'character-persephone'], requiredWorldIds: ['world-underworld'], requiredSceneIds: ['scene-river-styx'], narrative: ['俄耳甫斯以音乐让冥界的秩序短暂松动，获准在不回头的条件下带欧律狄刻离开。这个条件把爱、信任和死亡的边界压缩进一个动作。', '广为人知的“回望”细节来自后世诗歌的显著塑形；应明确标为希腊—罗马接受传统的一部分。'] }),
  story({ slug: 'bellerophon-and-chimera', title: '柏勒洛丰与奇美拉', titleEn: 'Bellerophon and Chimera', subtitle: '飞马与喷火怪物', summary: '柏勒洛丰驾驭珀伽索斯，从空中击败盘踞山地的奇美拉。', volumeId: 'hero-cycles', volumeTitle: '英雄周期', volumeOrder: 3, displayOrder: 6, tradition: '英雄传说与古代整理传统', source: sources.apollodorus, requiredCharacterIds: ['character-bellerophon', 'character-chimera', 'character-pegasus'], narrative: ['奇美拉的混合形象让正面冲锋变得危险。柏勒洛丰和珀伽索斯的组合以高度、速度和视角改变战斗条件。', '故事也提醒英雄成功并不自动等于永远安全：关于柏勒洛丰后来命运的叙事，常将傲慢与坠落写入他的轨迹。'] }),
  story({ slug: 'daedalus-and-icarus', title: '代达罗斯与伊卡洛斯', titleEn: 'Daedalus and Icarus', subtitle: '技艺能造出出口，也能带来风险', summary: '代达罗斯以蜡翼逃离克里特，伊卡洛斯因飞得过高坠入大海。', volumeId: 'hero-cycles', volumeTitle: '英雄周期', volumeOrder: 3, displayOrder: 7, tradition: '希腊与罗马接受传统', source: sources.ovid, requiredCharacterIds: ['character-daedalus', 'character-icarus'], requiredSceneIds: ['scene-cretan-labyrinth'], narrative: ['代达罗斯既是迷宫的建造者，也是被迷宫困住的人。蜡翼因此代表技艺提供的出口，而不是随意的魔法飞行。', '伊卡洛斯飞得过高的版本在罗马诗歌中格外著名。页面将它说明为传播极广的接受传统，而不是抹去其他古代叙事。'] }),
  story({ slug: 'atalanta', title: '阿塔兰忒', titleEn: 'Atalanta', subtitle: '奔跑、狩猎与不能被轻易归类的英雄', summary: '阿塔兰忒以狩猎和奔跑闻名，她的故事挑战了英雄叙事中对女性位置的简单预设。', volumeId: 'hero-cycles', volumeTitle: '英雄周期', volumeOrder: 3, displayOrder: 8, tradition: '英雄传说与罗马接受传统', source: sources.ovid, requiredCharacterIds: ['character-atalanta'], narrative: ['阿塔兰忒常以狩猎和速度被记住。她不以王室婚姻或受救援的位置进入英雄群像，而是作为能行动、能竞赛的主体出现。', '金苹果竞赛的具体文学呈现与后世接受有关；页面把它作为版本化叙事，而不把所有阿塔兰忒材料压缩为一个结局。'] }),
  story({ slug: 'oedipus-and-sphinx', title: '俄狄浦斯与斯芬克斯', titleEn: 'Oedipus and the Sphinx', subtitle: '解开谜语并不意味着逃离命运', summary: '俄狄浦斯解开斯芬克斯谜语进入底比斯王权，却仍走向自己试图躲避的命运。', volumeId: 'thebes-and-troy', volumeTitle: '底比斯与特洛伊', volumeOrder: 4, displayOrder: 1, tradition: '底比斯悲剧传统', source: sources.sophocles, requiredCharacterIds: ['character-oedipus', 'character-sphinx'], requiredSceneIds: ['scene-thebes'], narrative: ['斯芬克斯的谜语让俄狄浦斯以智慧而非力量成为底比斯的救援者。然而解开一题并不等于看清自己。', '悲剧的核心并非“命运战胜聪明人”的简单寓言，而是知识、身份和责任在不断追问中变得更困难。'] }),
  story({ slug: 'judgement-of-paris', title: '帕里斯的裁决', titleEn: 'The Judgement of Paris', subtitle: '一枚金苹果如何进入战争前史', summary: '帕里斯在赫拉、雅典娜和阿佛洛狄忒之间作出裁决，开启特洛伊战争的神人纠葛。', volumeId: 'thebes-and-troy', volumeTitle: '底比斯与特洛伊', volumeOrder: 4, displayOrder: 2, tradition: '特洛伊循环与后世叙事传统', source: sources.apollodorus, requiredCharacterIds: ['character-paris', 'character-hera', 'character-athena', 'character-aphrodite', 'character-helen'], requiredSceneIds: ['scene-mount-ida'], narrative: ['金苹果不是战争的唯一原因，却把神祇的竞争、人的欲望与政治后果压缩成一个选择。帕里斯接受阿佛洛狄忒的承诺，也让海伦成为冲突中心。', '不同特洛伊材料对事件先后与责任分配各有侧重；页面以“战争前史”的方式组织，而不取消多重归责。'] }),
  story({ slug: 'wrath-of-achilles', title: '阿喀琉斯之怒', titleEn: 'The Wrath of Achilles', subtitle: '《伊利亚特》从愤怒开始', summary: '阿喀琉斯与阿伽门农的冲突使他退出战场，希腊军势因此受挫。', volumeId: 'thebes-and-troy', volumeTitle: '底比斯与特洛伊', volumeOrder: 4, displayOrder: 3, tradition: '荷马史诗传统', source: sources.iliad, requiredCharacterIds: ['character-achilles', 'character-agamemnon'], requiredSceneIds: ['scene-troy'], narrative: ['《伊利亚特》不从特洛伊木马开始，而从阿喀琉斯的愤怒开始。英雄与统帅之间的荣誉冲突迅速成为军队能否生存的问题。', '这不是一篇“无敌英雄战记”。它反复追问荣誉如何伤害共同体、权力如何处理失去与羞辱。'] }),
  story({ slug: 'achilles-and-hector', title: '阿喀琉斯与赫克托耳', titleEn: 'Achilles and Hector', subtitle: '城墙之前的决斗', summary: '帕特罗克洛斯之死使阿喀琉斯重返战场，他与赫克托耳的决斗成为《伊利亚特》的情感核心。', volumeId: 'thebes-and-troy', volumeTitle: '底比斯与特洛伊', volumeOrder: 4, displayOrder: 4, tradition: '荷马史诗传统', source: sources.iliad, requiredCharacterIds: ['character-achilles', 'character-hector', 'character-patroclus', 'character-priam'], requiredSceneIds: ['scene-troy'], narrative: ['帕特罗克洛斯之死让阿喀琉斯的愤怒转化为报复。赫克托耳则不是单纯的敌方障碍，他是守城者、父亲与王子的多重身份。', '普里阿摩斯向阿喀琉斯请求儿子遗体的场景，使战争叙事重新回到哀悼、尊严和人与人之间暂时恢复的理解。'] }),
  story({ slug: 'fall-of-troy', title: '特洛伊陷落', titleEn: 'The Fall of Troy', subtitle: '战争并不在木马出现时才开始', summary: '特洛伊木马与城市陷落是漫长战争的终局意象，主要完整叙事多见于后世材料。', volumeId: 'thebes-and-troy', volumeTitle: '底比斯与特洛伊', volumeOrder: 4, displayOrder: 5, tradition: '特洛伊循环与罗马接受传统', source: sources.ovid, requiredCharacterIds: ['character-odysseus', 'character-priam', 'character-helen', 'character-menelaus'], requiredSceneIds: ['scene-troy'], narrative: ['木马的故事极其著名，却不在《伊利亚特》的叙事范围内。把它置于“陷落”而非整场战争的全部，才能看清不同文本各自讲述的部分。', '奥德修斯的谋略、特洛伊城的信任与战争长期积累的创伤一起构成终局，而不是一件奇计脱离历史地突然奏效。'] }),
  story({ slug: 'polyphemus', title: '独眼巨人波吕斐摩斯', titleEn: 'Polyphemus', subtitle: '名字、洞穴与海神的怒意', summary: '奥德修斯以“无人”的名字逃离独眼巨人洞穴，却因暴露身份招来波塞冬的追击。', volumeId: 'odyssey', volumeTitle: '奥德修斯归乡', volumeOrder: 5, displayOrder: 1, tradition: '荷马史诗传统', source: sources.odyssey, requiredCharacterIds: ['character-odysseus', 'character-polyphemus', 'character-poseidon'], requiredWorldIds: ['world-sea-realm'], requiredSceneIds: ['scene-cave-of-polyphemus'], narrative: ['奥德修斯用“无人”欺骗波吕斐摩斯，显示了谋略如何在力量远逊的处境中创造出口。洞穴、巨石和羊群使逃离变成一场空间上的精确计算。', '但他随后喊出真实姓名，令波吕斐摩斯能够请求波塞冬报复。聪明并不总能克制自我展示的冲动。'] }),
  story({ slug: 'circe', title: '喀耳刻', titleEn: 'Circe', subtitle: '变形、停留与继续航行', summary: '喀耳刻使奥德修斯的同伴变形，随后又成为他获得航海指引的主人。', volumeId: 'odyssey', volumeTitle: '奥德修斯归乡', volumeOrder: 5, displayOrder: 2, tradition: '荷马史诗传统', source: sources.odyssey, requiredCharacterIds: ['character-odysseus', 'character-circe'], requiredWorldIds: ['world-sea-realm'], narrative: ['喀耳刻的岛屿首先呈现为危险的陌生空间：药物、变形和失去人类形态使旅行者无法继续前行。', '但故事并未把她停留在单一敌手位置。经过对抗和协商，喀耳刻也提供了继续航行所需要的知识。'] }),
  story({ slug: 'sirens', title: '塞壬之歌', titleEn: 'The Sirens', subtitle: '听见一切的诱惑', summary: '奥德修斯让同伴封住耳朵，并把自己系在桅杆上，以听见塞壬之歌而不被其毁灭。', volumeId: 'odyssey', volumeTitle: '奥德修斯归乡', volumeOrder: 5, displayOrder: 3, tradition: '荷马史诗传统', source: sources.odyssey, requiredCharacterIds: ['character-odysseus', 'character-sirens'], requiredWorldIds: ['world-sea-realm'], narrative: ['塞壬诱惑的不是一般意义上的美妙声音，而是“你将知道一切”的承诺。奥德修斯既想听见，又知道自己不能自由行动。', '蜡封住同伴的耳朵、绳索把他固定在桅杆上，构成了一个把好奇心和自我约束同时保留下来的航海方案。'] }),
  story({ slug: 'calypso', title: '卡吕普索', titleEn: 'Calypso', subtitle: '永生并不等于归乡', summary: '卡吕普索留住奥德修斯并提供不死的可能，但他仍选择回到伊萨卡。', volumeId: 'odyssey', volumeTitle: '奥德修斯归乡', volumeOrder: 5, displayOrder: 4, tradition: '荷马史诗传统', source: sources.odyssey, requiredCharacterIds: ['character-odysseus', 'character-calypso', 'character-hermes'], requiredWorldIds: ['world-sea-realm'], narrative: ['卡吕普索的海岛提供安全、爱情和不死的承诺，却也使奥德修斯停留在一个没有终点的当下。', '归乡的选择因此不是对冒险的否定，而是对有限生命中的关系、土地和责任的确认。赫尔墨斯的到来使神意重新推动旅程。'] }),
  story({ slug: 'return-to-ithaca', title: '重返伊萨卡', titleEn: 'The Return to Ithaca', subtitle: '家宅、弓与身份的恢复', summary: '奥德修斯回到伊萨卡后，以伪装、试探和弓的考验重新确认自己的身份与家宅秩序。', volumeId: 'odyssey', volumeTitle: '奥德修斯归乡', volumeOrder: 5, displayOrder: 5, tradition: '荷马史诗传统', source: sources.odyssey, requiredCharacterIds: ['character-odysseus', 'character-penelope', 'character-telemachus', 'character-athena'], requiredWorldIds: ['world-sea-realm'], requiredSceneIds: ['scene-ithaca'], narrative: ['回到伊萨卡并不是旅行的简单终点。奥德修斯必须先确认谁仍然忠诚、家宅被怎样占据，也必须让自己的身份在风险中重新显现。', '佩涅洛佩、忒勒马科斯和雅典娜都不是背景角色。归乡最终恢复的是一组关系和责任，而不仅是一个人的王位。'] }),
];
