import type { Character, CharacterRelation, ContentConcept, Scene, TaxonomyTerm, World } from '../../lib/content/types';
import { sourceRef } from './sources';

const mythologyId = 'myth-celtic';
const celticImage = { src: '/art/celtic-mist-and-torc.svg', alt: '雾岭、河流、青铜颈环与远方圣丘构成的凯尔特神话入口', width: 1600, height: 900 };

type CharacterSeed = {
  slug: string; name: string; nameEn: string; role: string; symbols: string[]; characterType: NonNullable<Character['characterType']>;
  worldIds: string[]; traditionTags: string[]; sourceKey: string; locator: string; sourcePeriods: string[]; canonicality?: Character['canonicality'];
};

const makeCharacter = (seed: CharacterSeed): Character => ({
  id: `character-${seed.slug}`, mythologyId, worldIds: seed.worldIds, slug: seed.slug, name: seed.name, nameEn: seed.nameEn, role: seed.role,
  summary: `${seed.name}是${seed.role}。本页将其放在${seed.sourcePeriods[0]}的来源范围中，不把不同凯尔特地区和时代的材料拼成单一正典。`, symbols: seed.symbols,
  characterType: seed.characterType, traditionTags: seed.traditionTags, sourcePeriods: seed.sourcePeriods,
  sourceRefs: [sourceRef(seed.sourceKey, seed.locator)], editorialCollections: ['celtic-p0'], canonicality: seed.canonicality ?? 'primary',
  canonicalDesign: {
    anchors: [...seed.symbols.slice(0, 3), `${seed.name}的来源范围`],
    silhouette: `以${seed.symbols.slice(0, 2).join('与')}形成可识别的 MythCanvas 轮廓`,
    appearance: { body: ['成人或来源明确的神话形态', '身份锚点优先，避免现代角色模板'] },
    costumeLanguage: ['青铜、木、石、皮革或来源范围内的织物', '不复制现代商业改编'],
    paletteCues: ['雾白', '河谷青绿', '青铜棕', '克制古金'], signatureMaterials: ['青铜', '木', '石', '湿土'],
    temperament: ['神圣', '叙事功能清晰', '保持来源边界'], mythologicalFacts: [`${seed.name}按${seed.sourcePeriods[0]}呈现。`],
    originalDesignChoices: ['使用 MythCanvas 原创轮廓与材质；不把旅游刻板符号当作古代通用服饰。'],
    avoid: ['generic green-robed druid', 'Norse runes or Viking armor', 'tartan as universal ancient clothing', 'Stonehenge as universal backdrop', 'modern franchise likeness'],
    canonicalPrompt: `Depict ${seed.nameEn} as an original MythCanvas Celtic interpretation. Preserve ${seed.symbols.slice(0, 3).join(', ')} and the source scope ${seed.sourcePeriods[0]}. Use grounded bronze, wood, stone, mist and river materials; avoid generic druid fantasy and modern franchise designs.`,
  },
});

const irish = ['celtic-irish-mythological'];
const ulster = ['celtic-irish-ulster'];
const fenian = ['celtic-irish-fenian'];
const welsh = ['celtic-welsh-four-branches'];
const otherworld = ['celtic-irish-otherworld'];
const continental = ['celtic-continental-gaulish', 'celtic-gallo-roman'];
const periodIrish = ['Medieval Irish literary record'];
const periodWelsh = ['Medieval Welsh literary record'];

const seeds: readonly CharacterSeed[] = [
  { slug: 'morrigan', name: 'The Mórrígan', nameEn: 'The Mórrígan', role: '与战争、主权和预兆相连的爱尔兰叙事人物', symbols: ['乌鸦', '战场预兆', '主权意象'], characterType: 'deity', worldIds: ['world-emain-macha', 'world-cruachan'], traditionTags: [...irish, ...ulster, 'warfare', 'sovereignty'], sourceKey: 'cathMaigeTuired', locator: 'Mórrígan episodes; Táin-related material', sourcePeriods: periodIrish },
  { slug: 'cu-chulainn', name: '库丘林', nameEn: 'Cú Chulainn', role: 'Ulster Cycle 中守卫边境的英雄', symbols: ['战车', '长矛', '狂暴变形'], characterType: 'hero', worldIds: ['world-emain-macha', 'world-cooley'], traditionTags: [...ulster, 'warfare'], sourceKey: 'tainR1', locator: 'Cú Chulainn’s single combat sequence', sourcePeriods: periodIrish },
  { slug: 'lugh', name: '鲁格', nameEn: 'Lugh', role: 'Tuatha Dé Danann 中的多艺者与领袖', symbols: ['长矛', '多种技艺', '塔拉集会'], characterType: 'deity', worldIds: ['world-tara', 'world-mag-tuired'], traditionTags: [...irish, 'warfare', 'poetry'], sourceKey: 'cathMaigeTuired', locator: 'Lugh’s arrival and Second Battle', sourcePeriods: periodIrish },
  { slug: 'brigid', name: '布里吉德', nameEn: 'Brigid', role: '与诗歌、疗愈和锻造关联的神话人物', symbols: ['诗歌', '火', '锻造'], characterType: 'deity', worldIds: ['world-tara'], traditionTags: [...irish, 'poetry', 'healing', 'smithcraft'], sourceKey: 'leborGabala', locator: 'Brigit genealogical and poetic notices', sourcePeriods: periodIrish, canonicality: 'layered' },
  { slug: 'dagda', name: '达格达', nameEn: 'The Dagda', role: 'Tuatha Dé Danann 中具有王者与丰饶力量的神祇', symbols: ['棍棒', '大锅', '竖琴'], characterType: 'deity', worldIds: ['world-tara', 'world-mag-tuired'], traditionTags: [...irish, 'warfare', 'sovereignty'], sourceKey: 'cathMaigeTuired', locator: 'Dagda and Second Battle episodes', sourcePeriods: periodIrish },
  { slug: 'nuada', name: '努阿达', nameEn: 'Nuada', role: 'Tuatha Dé Danann 的王与失去手臂后的王权人物', symbols: ['银臂', '王权', '剑'], characterType: 'deity', worldIds: ['world-tara', 'world-mag-tuired'], traditionTags: [...irish, 'sovereignty', 'smithcraft'], sourceKey: 'cathMaigeTuired', locator: 'Nuada’s lost arm and restoration', sourcePeriods: periodIrish },
  { slug: 'fionn-mac-cumhaill', name: '芬恩·麦克库尔', nameEn: 'Fionn mac Cumhaill', role: 'Fenian Cycle 中的猎人、领袖与知识人物', symbols: ['猎犬', '长矛', '智慧鲑鱼'], characterType: 'hero', worldIds: ['world-fenian-landscape'], traditionTags: [...fenian, 'warfare'], sourceKey: 'macgnimarthaFind', locator: 'Salmon of Knowledge episode', sourcePeriods: ['Medieval Irish Fenian literary record'], canonicality: 'literary' },
  { slug: 'medb', name: '梅芙', nameEn: 'Medb', role: '以主权与战争动员推动 Táin 的康诺特女王', symbols: ['战车', '王冠', '公牛'], characterType: 'mortal', worldIds: ['world-cruachan', 'world-cooley'], traditionTags: [...ulster, 'sovereignty', 'warfare'], sourceKey: 'tainR1', locator: 'Medb and Ailill’s cattle expedition', sourcePeriods: periodIrish },
  { slug: 'manannan', name: '马纳南·麦克利尔', nameEn: 'Manannán mac Lir', role: '爱尔兰彼世与海域边界的人物', symbols: ['雾', '海', '马'], characterType: 'deity', worldIds: ['world-irish-otherworld'], traditionTags: [...irish, ...otherworld], sourceKey: 'leborGabala', locator: 'Manannán notices and otherworld material', sourcePeriods: periodIrish, canonicality: 'layered' },
  { slug: 'aengus', name: '安格斯', nameEn: 'Aengus / Óengus mac ind Óc', role: '以梦、诗歌与寻找 Caer 为核心的神话人物', symbols: ['梦', '天鹅', '金色光线'], characterType: 'deity', worldIds: ['world-tara', 'world-irish-otherworld'], traditionTags: [...irish, ...otherworld, 'poetry'], sourceKey: 'aislingeOenguso', locator: 'Dream and Caer Ibormeith episodes', sourcePeriods: periodIrish },
  { slug: 'cernunnos', name: '塞尔努诺斯', nameEn: 'Cernunnos', role: '以铭文与盘角图像为主要证据的大陆凯尔特人物', symbols: ['鹿角', '颈环', '动物'], characterType: 'deity', worldIds: ['world-gallo-roman-evidence'], traditionTags: continental, sourceKey: 'pillarNautes', locator: 'Inscription and antlered relief panels', sourcePeriods: ['Iron Age and Gallo-Roman evidence'], canonicality: 'contested' },
  { slug: 'epona', name: '埃波娜', nameEn: 'Epona', role: '以马匹关联、铭文与奉献图像为主要证据的大陆凯尔特人物', symbols: ['马', '马鞍', '奉献碑'], characterType: 'deity', worldIds: ['world-gallo-roman-evidence'], traditionTags: continental, sourceKey: 'eponaInscriptions', locator: 'Inscriptions and horse-associated votive monuments', sourcePeriods: ['Roman-period Gallo-Roman evidence'], canonicality: 'layered' },
  { slug: 'balor', name: '巴罗尔', nameEn: 'Balor', role: '拥有致命之眼的福莫尔人物', symbols: ['闭合之眼', '塔楼', '战争'], characterType: 'monster', worldIds: ['world-mag-tuired'], traditionTags: [...irish, 'warfare'], sourceKey: 'cathMaigeTuired', locator: 'Balor and Lugh in the Second Battle', sourcePeriods: periodIrish },
  { slug: 'bres', name: '布雷斯', nameEn: 'Bres', role: '短暂统治 Tuatha Dé Danann 的政治人物', symbols: ['王座', '贡赋', '政治裂痕'], characterType: 'mortal', worldIds: ['world-tara', 'world-mag-tuired'], traditionTags: [...irish, 'sovereignty'], sourceKey: 'cathMaigeTuired', locator: 'Bres’s kingship and fall', sourcePeriods: periodIrish },
  { slug: 'ogma', name: '奥格玛', nameEn: 'Ogma', role: '与力量、诗才和 Tuatha 集会相连的人物', symbols: ['棍棒', '诗才', '战场'], characterType: 'deity', worldIds: ['world-mag-tuired'], traditionTags: [...irish, 'warfare', 'poetry'], sourceKey: 'cathMaigeTuired', locator: 'Ogma notices and battle material', sourcePeriods: periodIrish },
  { slug: 'dian-cecht', name: '迪安·凯赫特', nameEn: 'Dian Cécht', role: 'Tuatha Dé Danann 的疗愈与身体修复人物', symbols: ['疗愈', '银臂', '药草'], characterType: 'deity', worldIds: ['world-mag-tuired'], traditionTags: [...irish, 'healing'], sourceKey: 'cathMaigeTuired', locator: 'Nuada’s silver arm and Dian Cécht material', sourcePeriods: periodIrish },
  { slug: 'miach', name: '米亚赫', nameEn: 'Miach', role: '试图以疗愈技艺恢复 Nuada 身体的神话人物', symbols: ['草药', '疗愈', '银臂'], characterType: 'deity', worldIds: ['world-mag-tuired'], traditionTags: [...irish, 'healing'], sourceKey: 'cathMaigeTuired', locator: 'Miach and the healing of Nuada', sourcePeriods: periodIrish },
  { slug: 'goibniu', name: '戈布纽', nameEn: 'Goibniu', role: 'Tuatha Dé Danann 的铁匠与战争工匠', symbols: ['铁砧', '长矛', '火'], characterType: 'deity', worldIds: ['world-mag-tuired'], traditionTags: [...irish, 'smithcraft'], sourceKey: 'cathMaigeTuired', locator: 'Goibniu’s forge and battle preparations', sourcePeriods: periodIrish },
  { slug: 'cian', name: '基安', nameEn: 'Cian', role: '鲁格家系中连接 Tuatha 叙事的父亲人物', symbols: ['家系', '伪装', '边界'], characterType: 'deity', worldIds: ['world-tara', 'world-mag-tuired'], traditionTags: [...irish], sourceKey: 'cathMaigeTuired', locator: 'Cian, Ethniu and Lugh genealogy', sourcePeriods: periodIrish },
  { slug: 'ethniu', name: '埃特纽', nameEn: 'Ethniu / Eithne', role: '连接巴罗尔家系与鲁格身世的母亲人物', symbols: ['塔楼', '家系', '边界'], characterType: 'mortal', worldIds: ['world-mag-tuired'], traditionTags: [...irish], sourceKey: 'cathMaigeTuired', locator: 'Ethniu and Lugh birth material', sourcePeriods: periodIrish },
  { slug: 'caer-ibormeith', name: '凯尔·伊博尔梅斯', nameEn: 'Caer Ibormeith', role: '在安格斯梦中以天鹅形态出现的彼世人物', symbols: ['天鹅', '梦', '湖水'], characterType: 'mortal', worldIds: ['world-irish-otherworld'], traditionTags: [...irish, ...otherworld, 'poetry'], sourceKey: 'aislingeOenguso', locator: 'Caer Ibormeith and swan transformation', sourcePeriods: periodIrish },
  { slug: 'ailill-mac-mata', name: '阿伊利尔·麦克·马塔', nameEn: 'Ailill mac Máta', role: '康诺特国王与梅芙的政治配偶', symbols: ['王权', '战车', '公牛'], characterType: 'mortal', worldIds: ['world-cruachan'], traditionTags: [...ulster, 'sovereignty'], sourceKey: 'tainR1', locator: 'Ailill and Medb’s cattle comparison', sourcePeriods: periodIrish },
  { slug: 'conchobar-mac-nessa', name: '孔科巴尔·麦克·内萨', nameEn: 'Conchobar mac Nessa', role: '乌尔斯特的国王与战争秩序人物', symbols: ['王座', '战车', '乌尔斯特'], characterType: 'mortal', worldIds: ['world-emain-macha'], traditionTags: [...ulster, 'sovereignty'], sourceKey: 'tainR1', locator: 'Conchobar and the Ulstermen', sourcePeriods: periodIrish },
  { slug: 'fergus-mac-roich', name: '弗格斯·麦克·罗伊赫', nameEn: 'Fergus mac Róich', role: '在乌尔斯特与康诺特之间移动的英雄与盟友', symbols: ['长剑', '流亡', '盟约'], characterType: 'hero', worldIds: ['world-emain-macha', 'world-cruachan'], traditionTags: [...ulster, 'warfare'], sourceKey: 'tainR1', locator: 'Fergus and the Ulster exile material', sourcePeriods: periodIrish },
  { slug: 'fer-diad', name: '费尔·迪亚德', nameEn: 'Fer Diad', role: '在 Táin 中与库丘林决斗的英雄', symbols: ['盾牌', '河滩', '友谊与决斗'], characterType: 'hero', worldIds: ['world-cooley'], traditionTags: [...ulster, 'warfare'], sourceKey: 'tainR1', locator: 'Cú Chulainn and Fer Diad single combat', sourcePeriods: periodIrish },
  { slug: 'loeg', name: '洛伊格', nameEn: 'Lóeg', role: '库丘林的御者与战车同伴', symbols: ['战车', '马匹', '观察'], characterType: 'mortal', worldIds: ['world-cooley', 'world-emain-macha'], traditionTags: [...ulster], sourceKey: 'tainR2', locator: 'Lóeg and Cú Chulainn’s chariot', sourcePeriods: periodIrish },
  { slug: 'macha', name: '马查', nameEn: 'Macha', role: 'Noínden Ulad 中与乌尔斯特失能相连的人物', symbols: ['赛马', '诅咒', '怀孕'], characterType: 'deity', worldIds: ['world-emain-macha'], traditionTags: [...ulster, 'sovereignty'], sourceKey: 'noindenUlad', locator: 'Macha and the debility of the Ulstermen', sourcePeriods: periodIrish, canonicality: 'contested' },
  { slug: 'donn-cuailnge', name: '敦·库阿林', nameEn: 'Donn Cúailnge', role: 'Táin 争夺的库利棕牛', symbols: ['棕牛', '牧场', '战争目标'], characterType: 'creature', worldIds: ['world-cooley'], traditionTags: [...ulster, 'warfare'], sourceKey: 'tainR1', locator: 'The Brown Bull of Cooley', sourcePeriods: periodIrish },
  { slug: 'findbennach', name: '芬德本纳赫', nameEn: 'Findbennach', role: '与库利棕牛相争的白角公牛', symbols: ['白角', '白牛', '决斗'], characterType: 'creature', worldIds: ['world-cruachan'], traditionTags: [...ulster, 'warfare'], sourceKey: 'tainR2', locator: 'The White Bull and final combat', sourcePeriods: periodIrish },
  { slug: 'pwyll', name: '普伊尔', nameEn: 'Pwyll', role: '第一 Branch 中与安温交换身份的迪费德国王', symbols: ['王冠', '猎犬', '土丘'], characterType: 'mortal', worldIds: ['world-dyfed', 'world-annwn'], traditionTags: welsh, sourceKey: 'pwyll', locator: 'First Branch: Pwyll and Arawn', sourcePeriods: periodWelsh },
  { slug: 'rhiannon', name: '里安农', nameEn: 'Rhiannon', role: '与婚姻、马匹、失踪与归来相连的威尔士人物', symbols: ['马', '鸟', '土丘'], characterType: 'mortal', worldIds: ['world-dyfed'], traditionTags: welsh, sourceKey: 'pwyll', locator: 'First Branch: Rhiannon and Pryderi', sourcePeriods: periodWelsh },
  { slug: 'pryderi', name: '普利德里', nameEn: 'Pryderi', role: '贯穿 Four Branches 的迪费德王子', symbols: ['王子', '猪群', '魔法束缚'], characterType: 'mortal', worldIds: ['world-dyfed', 'world-annwn'], traditionTags: welsh, sourceKey: 'pwyll', locator: 'First Branch: Pryderi’s birth and return', sourcePeriods: periodWelsh },
  { slug: 'arawn', name: '阿冉', nameEn: 'Arawn', role: '安温的王与交换身份叙事中的彼世统治者', symbols: ['猎犬', '王冠', '彼世边界'], characterType: 'deity', worldIds: ['world-annwn'], traditionTags: [...welsh, 'otherworld'], sourceKey: 'pwyll', locator: 'First Branch: Arawn and Annwn', sourcePeriods: periodWelsh },
  { slug: 'branwen', name: '布兰温', nameEn: 'Branwen ferch Llŷr', role: '第二 Branch 中引发政治裂痕的王室人物', symbols: ['海峡', '鸟', '王室婚姻'], characterType: 'mortal', worldIds: ['world-welsh-court'], traditionTags: welsh, sourceKey: 'branwen', locator: 'Second Branch: Branwen’s marriage and insult', sourcePeriods: periodWelsh },
  { slug: 'brân', name: '布兰·本迪盖德弗兰', nameEn: 'Bendigeidfran / Brân', role: '渡海远征与断首遗物叙事中的巨人王', symbols: ['巨人', '渡海', '首颅'], characterType: 'deity', worldIds: ['world-welsh-court'], traditionTags: welsh, sourceKey: 'branwen', locator: 'Second Branch: Brân crosses the sea', sourcePeriods: periodWelsh },
  { slug: 'manawydan', name: '马纳韦丹', nameEn: 'Manawydan fab Llŷr', role: '第三 Branch 中面对荒废与魔法的幸存者', symbols: ['手艺', '道路', '耐心'], characterType: 'mortal', worldIds: ['world-dyfed'], traditionTags: welsh, sourceKey: 'manawydan', locator: 'Third Branch: Manawydan and Dyfed', sourcePeriods: periodWelsh },
  { slug: 'efnisien', name: '埃夫尼斯延', nameEn: 'Efnisien', role: '第二 Branch 中以破坏性行动加剧战争的人物', symbols: ['冲突', '马匹', '牺牲'], characterType: 'mortal', worldIds: ['world-welsh-court'], traditionTags: welsh, sourceKey: 'branwen', locator: 'Second Branch: Efnisien and the cauldron', sourcePeriods: periodWelsh },
  { slug: 'math', name: '马思·马松维', nameEn: 'Math fab Mathonwy', role: '第四 Branch 中以王权与魔法维持秩序的统治者', symbols: ['魔法', '王座', '足下禁忌'], characterType: 'deity', worldIds: ['world-math-court'], traditionTags: welsh, sourceKey: 'math', locator: 'Fourth Branch: Math and Goewin', sourcePeriods: periodWelsh },
  { slug: 'goewin', name: '戈温', nameEn: 'Goewin', role: '第四 Branch 中承受王权禁忌后果的人物', symbols: ['脚下禁忌', '宫廷', '转折'], characterType: 'mortal', worldIds: ['world-math-court'], traditionTags: welsh, sourceKey: 'math', locator: 'Fourth Branch: Goewin and Math', sourcePeriods: periodWelsh },
  { slug: 'gwydion', name: '圭迪翁', nameEn: 'Gwydion', role: '以魔法、策略与创造介入第四 Branch 的人物', symbols: ['魔法', '诗歌', '树形战士'], characterType: 'deity', worldIds: ['world-math-court'], traditionTags: welsh, sourceKey: 'math', locator: 'Fourth Branch: Gwydion and Lleu', sourcePeriods: periodWelsh },
  { slug: 'arianrhod', name: '阿丽安罗德', nameEn: 'Arianrhod', role: '在 Lleu 的命名与身份问题中占核心位置的威尔士人物', symbols: ['银轮', '命名', '纺线'], characterType: 'deity', worldIds: ['world-math-court'], traditionTags: welsh, sourceKey: 'math', locator: 'Fourth Branch: Arianrhod and Lleu', sourcePeriods: periodWelsh },
  { slug: 'lleu-law-gyffes', name: '卢厄·劳·盖弗斯', nameEn: 'Lleu Llaw Gyffes', role: '经历命名、武装与变形命运的威尔士人物', symbols: ['矛', '鹰', '身份'], characterType: 'deity', worldIds: ['world-math-court'], traditionTags: welsh, sourceKey: 'math', locator: 'Fourth Branch: Lleu’s names and transformations', sourcePeriods: periodWelsh },
  { slug: 'blodeuwedd', name: '布洛德韦德', nameEn: 'Blodeuwedd', role: '由花朵创造并在背叛与变形中结束故事的威尔士人物', symbols: ['花朵', '猫头鹰', '变形'], characterType: 'mortal', worldIds: ['world-math-court'], traditionTags: welsh, sourceKey: 'math', locator: 'Fourth Branch: Blodeuwedd’s creation and fate', sourcePeriods: periodWelsh },
];

export const celticCharacters: readonly Character[] = seeds.map(makeCharacter);

const world = (slug: string, name: string, nameEn: string, summary: string, anchors: string[]): World => ({ id: `world-${slug}`, mythologyId, slug, name, nameEn, summary, canonicalDesign: { anchors, signatureMaterials: ['青铜', '木', '石', '雾'], atmosphere: ['河谷', '圣丘', '边界感'] }, heroImage: { ...celticImage, alt: `${name}的来源限定视觉场景` } });
export const celticWorlds: readonly World[] = [
  world('tara', '塔拉集会', 'Tara Assembly', '爱尔兰 Mythological Cycle 中王权、集会与身份试炼相连的叙事空间。', ['山丘集会', '王座', '宴会厅']),
  world('mag-tuired', '马格·图伊雷德战场', 'Mag Tuired', 'Cath Maige Tuired 的战争地景；不是所有凯尔特战争的通用战场。', ['雾中平原', '青铜武器', '远山']),
  world('irish-otherworld', '爱尔兰彼世叙事空间', 'Irish Otherworld Narrative Space', '用于 Manannán 与 Aengus 相关材料的来源范围空间，不合并成泛凯尔特彼世地图。', ['海雾', '湖水', '土丘边界']),
  world('emain-macha', '艾明·马查', 'Emain Macha', 'Ulster Cycle 的王庭与乌尔斯特人物关系空间。', ['王庭', '战车场', '丘陵']),
  world('cruachan', '克鲁阿亨', 'Cruachan', '梅芙与阿伊利尔统治下的康诺特王庭。', ['王庭', '牧地', '战车']),
  world('cooley', '库利半岛', 'Cooley', 'Táin Bó Cúailnge 中牛群、海岸与英雄决斗交汇的地景。', ['山谷', '牛群', '河滩']),
  world('fenian-landscape', '芬恩的猎行地景', 'Fenian Hunting Landscape', 'Fenian Cycle 中森林、猎行与知识获得相连的叙事地景。', ['森林', '河流', '猎犬']),
  world('annwn', '安温', 'Annwn', 'Four Branches 中 Arawn 统治的威尔士彼世；不与 Manannán 的爱尔兰空间合并。', ['彼世宫廷', '白色猎犬', '土丘门槛']),
  world('dyfed', '迪费德', 'Dyfed', 'Four Branches 中 Pwyll、Rhiannon、Pryderi 活动的威尔士王国。', ['海岸', '农田', '木制王庭']),
  world('welsh-court', '威尔士王室与海峡', 'Welsh Court and Strait', 'Branwen Branch 中王室婚姻、渡海和战争的空间集合。', ['海峡', '长屋', '渡海船队']),
  world('math-court', '马思的宫廷', 'Math’s Court', 'Fourth Branch 中魔法、命名、身份和王权禁忌交汇的宫廷。', ['宫廷', '织物', '魔法边界']),
  world('gallo-roman-evidence', '高卢—罗马证据场域', 'Gallo-Roman Evidence Context', '以铭文、浮雕、奉献碑与博物馆考古语境呈现 Cernunnos 与 Epona。', ['石碑', '奉献碑', '颈环与马匹图像']),
];

const scene = (slug: string, name: string, nameEn: string, summary: string, worldId?: string): Scene => ({ id: `scene-${slug}`, mythologyId, worldId, slug, name, nameEn, summary, canonicalDesign: { anchors: [name, '来源范围清晰的凯尔特空间', '可复用叙事地标'] }, heroImage: { ...celticImage, alt: `${name}的凯尔特神话场景` } });
export const celticScenes: readonly Scene[] = [
  scene('tara-hall', '塔拉王庭', 'Tara Hall', '鲁格接受多艺者试炼、王权与集会关系展开的空间。', 'world-tara'), scene('mag-tuired-battlefield', '马格·图伊雷德战场', 'Mag Tuired Battlefield', 'Tuatha Dé Danann 与敌对力量交锋的战争地景。', 'world-mag-tuired'), scene('nuada-silver-arm', '银臂锻造场', 'Nuada’s Silver Arm Workshop', '努阿达身体修复与工匠技艺相连的场景。', 'world-mag-tuired'), scene('dagda-morrigan-river-meeting', '河畔相遇', 'River Meeting', '达格达与 Mórrígan 战前相遇的来源限定河岸。', 'world-mag-tuired'), scene('aengus-dream', '安格斯的梦', 'Aengus’s Dream', '梦、天鹅与湖水交叠的彼世门槛。', 'world-irish-otherworld'),
  scene('emain-macha', '艾明·马查王庭', 'Emain Macha Court', '乌尔斯特王庭与失能前的集会空间。', 'world-emain-macha'), scene('cruachan-court', '克鲁阿亨王庭', 'Cruachan Court', '梅芙与阿伊利尔讨论财富、权力和牛群的场所。', 'world-cruachan'), scene('cooley-cattle-raid', '库利牛群之地', 'Cooley Cattle Country', '牛群、山谷与出征路线组成的 Táin 地景。', 'world-cooley'), scene('cu-chulainn-ford', '库丘林河滩', 'Cú Chulainn at the Ford', '库丘林独守道路、与来者决斗的边界场景。', 'world-cooley'), scene('fer-diad-duel', '库丘林与费尔·迪亚德决斗', 'Cú Chulainn and Fer Diad', '友谊与战争在河滩上发生不可逆转的决裂。', 'world-cooley'), scene('bulls-final-duel', '两头公牛的最终冲突', 'Final Bull Combat', 'Donn Cúailnge 与 Findbennach 的结局性冲突。', 'world-cooley'),
  scene('fenian-salmon-river', '智慧鲑鱼河岸', 'Salmon of Knowledge River', '芬恩在河岸和劳动中获得智慧的芬尼亚起源场景。', 'world-fenian-landscape'), scene('pwyll-annwn-exchange', '安温交换身份', 'Pwyll and Arawn Exchange', 'Pwyll 与 Arawn 在安温边界交换身份的场景。', 'world-annwn'), scene('arberth-mound', '阿伯里斯土丘', 'Arberth Mound', 'Rhiannon 与神秘道路、土丘观看相连的威尔士场景。', 'world-dyfed'), scene('branwen-harlech-court', '哈莱赫王庭', 'Harlech Court', 'Branwen Branch 中婚姻与政治裂痕积累的王庭。', 'world-welsh-court'), scene('bran-crosses-sea', '布兰渡海', 'Brân Crosses the Sea', '威尔士军队跨越海峡走向战争的场景。', 'world-welsh-court'), scene('empty-dyfed', '荒废的迪费德', 'Empty Dyfed', 'Manawydan Branch 中人群消失、土地仍在的寂静地景。', 'world-dyfed'), scene('math-court', '马思宫廷', 'Math’s Court', '命名、足下禁忌与魔法秩序交汇的宫廷。', 'world-math-court'), scene('blodeuwedd-creation', '花朵创造场', 'Blodeuwedd’s Creation', '圭迪翁与马思以花朵创造 Blodeuwedd 的场景。', 'world-math-court'),
  scene('cernunnos-pillar', '舟夫柱浮雕', 'Pillar of the Boatmen Relief', '铭文、浮雕与盘角形象共存的高卢—罗马证据场景。', 'world-gallo-roman-evidence'), scene('epona-votive-stone', '埃波娜奉献碑', 'Epona Votive Stone', '马匹、骑乘与地方崇拜证据相连的奉献语境。', 'world-gallo-roman-evidence'),
];

const taxonomy = (slug: string, name: string, nameEn: string, kind: TaxonomyTerm['kind'], displayOrder: number): TaxonomyTerm => ({ id: `taxonomy-celtic-${slug}`, mythologyId, slug, kind, name, nameEn, summary: `${name}相关的凯尔特来源范围内容分组。`, displayOrder });
export const celticTaxonomy: readonly TaxonomyTerm[] = [
  taxonomy('celtic-irish-mythological', '爱尔兰神话循环', 'Irish Mythological Cycle', 'story-cycle', 10), taxonomy('celtic-irish-ulster', '乌尔斯特循环', 'Ulster Cycle', 'story-cycle', 20), taxonomy('celtic-irish-fenian', '芬尼亚循环', 'Fenian Cycle', 'story-cycle', 30), taxonomy('celtic-welsh-four-branches', '威尔士 Four Branches', 'Welsh Four Branches', 'story-cycle', 40), taxonomy('celtic-irish-otherworld', '爱尔兰彼世叙事', 'Irish Otherworld', 'editorial-collection', 50), taxonomy('celtic-continental-gaulish', '大陆高卢证据', 'Continental Gaulish Evidence', 'editorial-collection', 60), taxonomy('celtic-gallo-roman', '高卢—罗马语境', 'Gallo-Roman Context', 'editorial-collection', 70), taxonomy('sovereignty', '主权与王权', 'Sovereignty', 'domain', 80), taxonomy('warfare', '战争与英雄', 'Warfare and Heroism', 'domain', 90), taxonomy('poetry', '诗歌与技艺', 'Poetry and Skill', 'domain', 100), taxonomy('healing', '疗愈', 'Healing', 'domain', 110), taxonomy('smithcraft', '锻造技艺', 'Smithcraft', 'domain', 120), taxonomy('otherworld', '彼世与边界', 'Otherworld and Thresholds', 'domain', 130),
];

export const celticConcepts: readonly ContentConcept[] = [
  { id: 'concept-celtic-multi-tradition', mythologyId, slug: 'multi-tradition-umbrella', name: '多传统聚合入口', summary: 'Celtic 是产品聚合入口，涵盖爱尔兰、威尔士与大陆／高卢—罗马证据，不能被读作单一统一正典。', sourceRefs: [sourceRef('leborGabala', 'mythographic framework'), sourceRef('whiteBook', 'Four Branches witness context')] },
  { id: 'concept-ulster-debility', mythologyId, slug: 'ulster-debility', name: '乌尔斯特失能前置', summary: 'Noínden Ulad 解释 Táin 中乌尔斯特主力为何无法及时参战；Macha 身份关系保持来源限定。', sourceRefs: [sourceRef('noindenUlad', 'Macha and the debility of the Ulstermen')] },
  { id: 'concept-cernunnos-iconography', mythologyId, slug: 'cernunnos-iconography', name: '塞尔努诺斯盘角图像', summary: '以颈环、盘角和动物关联组织证据，不把所有盘角图像自动命名为 Cernunnos。', sourceRefs: [sourceRef('pillarNautes', 'Inscription and antlered relief panels'), sourceRef('cernunnosEvidence', 'antlered imagery comparison')] },
  { id: 'concept-epona-horse-cult', mythologyId, slug: 'epona-horse-cult', name: '埃波娜马匹崇拜证据', summary: '通过铭文、马匹图像与奉献碑呈现 Epona 的证据范围，不制造爱尔兰家谱。', sourceRefs: [sourceRef('eponaInscriptions', 'Inscriptions and horse-associated votive monuments')] },
];

const relation = (id: string, fromCharacterId: string, toCharacterId: string | undefined, relationType: string, ref: ReturnType<typeof sourceRef>, traditionScope: string, isDefault = true, toConceptId?: string): CharacterRelation => ({ id, fromCharacterId, toCharacterId, toConceptId, relationType, assertionKey: `${fromCharacterId}|${toCharacterId ?? toConceptId}|${relationType}`, traditionScope, isDefault, sourceRefs: [ref], confidence: isDefault ? 'high' : 'contested' });
export const celticRelations: readonly CharacterRelation[] = [
  relation('celtic-ally-lugh-nuada', 'character-lugh', 'character-nuada', 'ally', sourceRef('cathMaigeTuired', 'Lugh joins Nuada and the Tuatha'), 'celtic-irish-mythological'), relation('celtic-ally-lugh-dagda', 'character-lugh', 'character-dagda', 'ally', sourceRef('cathMaigeTuired', 'Second Battle preparations'), 'celtic-irish-mythological'), relation('celtic-enemy-nuada-bres', 'character-nuada', 'character-bres', 'enemy', sourceRef('cathMaigeTuired', 'Nuada, Bres and kingship'), 'celtic-irish-mythological'), relation('celtic-defeats-lugh-balor', 'character-lugh', 'character-balor', 'defeats', sourceRef('cathMaigeTuired', 'Lugh and Balor in the Second Battle'), 'celtic-irish-mythological'), relation('celtic-enemy-morrigan-cu', 'character-morrigan', 'character-cu-chulainn', 'enemy', sourceRef('tainR1', 'Mórrígan and Cú Chulainn episodes'), 'celtic-irish-ulster', false), relation('celtic-encounters-aengus-caer', 'character-aengus', 'character-caer-ibormeith', 'encounters', sourceRef('aislingeOenguso', 'Dream and Caer Ibormeith episodes'), 'celtic-irish-otherworld'),
  relation('celtic-consort-medb-ailill', 'character-medb', 'character-ailill-mac-mata', 'consort', sourceRef('tainR1', 'Medb and Ailill’s cattle comparison'), 'celtic-irish-ulster'), relation('celtic-enemy-medb-cu', 'character-medb', 'character-cu-chulainn', 'enemy', sourceRef('tainR2', 'Medb’s expedition and Cú Chulainn'), 'celtic-irish-ulster'), relation('celtic-ally-fergus-cu', 'character-fergus-mac-roich', 'character-cu-chulainn', 'ally', sourceRef('tainR1', 'Fergus and the Ulster exile material'), 'celtic-irish-ulster'), relation('celtic-enemy-cu-fer-diad', 'character-cu-chulainn', 'character-fer-diad', 'enemy', sourceRef('tainR1', 'Cú Chulainn and Fer Diad single combat'), 'celtic-irish-ulster'), relation('celtic-enemy-donn-findbennach', 'character-donn-cuailnge', 'character-findbennach', 'enemy', sourceRef('tainR2', 'The White Bull and final combat'), 'celtic-irish-ulster'), relation('celtic-associated-macha-debility', 'character-macha', undefined, 'associated-with', sourceRef('noindenUlad', 'Macha and the debility of the Ulstermen'), 'celtic-irish-ulster', false, 'concept-ulster-debility'),
  relation('celtic-exchanges-pwyll-arawn', 'character-pwyll', 'character-arawn', 'exchanges-with', sourceRef('pwyll', 'First Branch: Pwyll and Arawn'), 'celtic-welsh-four-branches'), relation('celtic-consort-pwyll-rhiannon', 'character-pwyll', 'character-rhiannon', 'consort', sourceRef('pwyll', 'First Branch: Pwyll and Rhiannon'), 'celtic-welsh-four-branches'), relation('celtic-parent-rhiannon-pryderi', 'character-rhiannon', 'character-pryderi', 'parent', sourceRef('pwyll', 'First Branch: Pryderi’s birth and return'), 'celtic-welsh-four-branches'), relation('celtic-sibling-bran-branwen', 'character-brân', 'character-branwen', 'sibling', sourceRef('branwen', 'Second Branch: Branwen and Brân'), 'celtic-welsh-four-branches'), relation('celtic-enemy-bran-efnisien', 'character-brân', 'character-efnisien', 'enemy', sourceRef('branwen', 'Second Branch: Efnisien and the cauldron'), 'celtic-welsh-four-branches'), relation('celtic-ally-manawydan-pryderi', 'character-manawydan', 'character-pryderi', 'ally', sourceRef('manawydan', 'Third Branch: Manawydan and Pryderi'), 'celtic-welsh-four-branches'), relation('celtic-master-math-gwydion', 'character-math', 'character-gwydion', 'master', sourceRef('math', 'Fourth Branch: Math and Gwydion'), 'celtic-welsh-four-branches'), relation('celtic-parent-arianrhod-lleu', 'character-arianrhod', 'character-lleu-law-gyffes', 'parent', sourceRef('math', 'Fourth Branch: Arianrhod and Lleu'), 'celtic-welsh-four-branches'), relation('celtic-created-gwydion-blodeuwedd', 'character-gwydion', 'character-blodeuwedd', 'created', sourceRef('math', 'Fourth Branch: Blodeuwedd’s creation and fate'), 'celtic-welsh-four-branches'),
  relation('celtic-associated-cernunnos-iconography', 'character-cernunnos', undefined, 'associated-with', sourceRef('cernunnosEvidence', 'antlered imagery comparison'), 'celtic-continental-gaulish', false, 'concept-cernunnos-iconography'), relation('celtic-associated-epona-horse-cult', 'character-epona', undefined, 'associated-with', sourceRef('eponaInscriptions', 'Inscriptions and horse-associated votive monuments'), 'celtic-gallo-roman', false, 'concept-epona-horse-cult'),
];
