import type { CharacterInterpretation, CharacterName, ContentClaim } from '../../lib/content/types';
import { sourceRef } from './sources';

export const celticNames: readonly CharacterName[] = [
  { id: 'name-celtic-morrigan-morrigan', characterId: 'character-morrigan', name: 'Morrigan', nameEn: 'Morrigan', nameKind: 'alias', isPrimaryForScope: false, sourceRefs: [sourceRef('cathMaigeTuired', 'Mórrígan episodes')], confidence: 'high' },
  { id: 'name-celtic-cu-cuchulainn', characterId: 'character-cu-chulainn', name: 'Cuchulainn', nameEn: 'Cuchulainn', nameKind: 'alias', isPrimaryForScope: false, sourceRefs: [sourceRef('tainR1', 'Cú Chulainn’s single combat sequence')], confidence: 'high' },
  { id: 'name-celtic-cu-cuchulain', characterId: 'character-cu-chulainn', name: 'Cuchulain', nameEn: 'Cuchulain', nameKind: 'alias', isPrimaryForScope: false, sourceRefs: [sourceRef('tainR2', 'Cú Chulainn’s single combat sequence')], confidence: 'high' },
  { id: 'name-celtic-fionn-finn', characterId: 'character-fionn-mac-cumhaill', name: 'Finn mac Cumhaill', nameEn: 'Finn mac Cumhaill', nameKind: 'alias', isPrimaryForScope: false, sourceRefs: [sourceRef('macgnimarthaFind', 'Salmon of Knowledge episode')], confidence: 'high' },
  { id: 'name-celtic-fionn-finn-maccool', characterId: 'character-fionn-mac-cumhaill', name: 'Finn MacCool', nameEn: 'Finn MacCool', nameKind: 'alias', isPrimaryForScope: false, sourceRefs: [sourceRef('macgnimarthaFind', 'Fionn name and boyhood deeds')], confidence: 'medium' },
  { id: 'name-celtic-aengus-oengus', characterId: 'character-aengus', name: 'Óengus', nameEn: 'Óengus', nameKind: 'alias', isPrimaryForScope: true, sourceRefs: [sourceRef('aislingeOenguso', 'Dream and Caer Ibormeith episodes')], confidence: 'high' },
  { id: 'name-celtic-manannan-manannan', characterId: 'character-manannan', name: 'Manannan mac Lir', nameEn: 'Manannan mac Lir', nameKind: 'alias', isPrimaryForScope: false, sourceRefs: [sourceRef('leborGabala', 'Manannán notices and otherworld material')], confidence: 'high' },
  { id: 'name-celtic-medb-maeve', characterId: 'character-medb', name: 'Maeve', nameEn: 'Maeve', nameKind: 'alias', isPrimaryForScope: false, sourceRefs: [sourceRef('tainR1', 'Medb and Ailill’s cattle comparison')], confidence: 'medium' },
  { id: 'name-celtic-bran-bran', characterId: 'character-brân', name: 'Brân', nameEn: 'Brân', nameKind: 'alias', isPrimaryForScope: true, sourceRefs: [sourceRef('branwen', 'Second Branch: Brân crosses the sea')], confidence: 'high' },
  { id: 'name-celtic-bran-bendigeidfran', characterId: 'character-brân', name: 'Bendigeidfran', nameEn: 'Bendigeidfran', nameKind: 'alias', isPrimaryForScope: false, sourceRefs: [sourceRef('branwen', 'Second Branch: Brân and Branwen')], confidence: 'high' },
  { id: 'name-celtic-lleu-full', characterId: 'character-lleu-law-gyffes', name: 'Lleu Llaw Gyffes', nameEn: 'Lleu Llaw Gyffes', nameKind: 'primary', isPrimaryForScope: true, sourceRefs: [sourceRef('math', 'Fourth Branch: Lleu’s names and transformations')], confidence: 'high' },
];
export const celticInterpretations: readonly CharacterInterpretation[] = [
  { id: 'interpretation-celtic-morrigan-ulster', characterId: 'character-morrigan', slug: 'ulster-source-layer', name: '乌尔斯特叙事层', role: 'Táin 中与冲突、援助和预兆相关的身份层', summary: '只覆盖 Ulster Cycle 的来源范围；不把 Badb、Macha、Nemain 自动压成固定三相家谱。', traditionTags: ['celtic-irish-ulster', 'warfare'], sourcePeriods: ['Medieval Irish literary record'], sourceRefs: [sourceRef('tainR1', 'Mórrígan and Cú Chulainn episodes'), sourceRef('tainR2', 'Mórrígan and Cú Chulainn episodes')], identityAnchors: ['乌鸦与预兆', '战场边界', '来源差异'], symbols: ['乌鸦', '河滩', '预兆'], canonicalDesignOverrides: { avoid: ['fixed triple-goddess diagram'] }, promptFragment: 'Keep the Ulster Cycle source scope explicit; do not turn Mórrígan into a generic gothic witch.', confidence: 'contested' },
  { id: 'interpretation-celtic-macha-noinden', characterId: 'character-macha', slug: 'noinden-ulad', name: 'Noínden Ulad 身份层', role: '与乌尔斯特失能前置相关的 Macha', summary: '只覆盖 Noínden Ulad 的 Macha 叙事，不把她自动并入 Mórrígan 的固定三位一体。', traditionTags: ['celtic-irish-ulster', 'sovereignty'], sourcePeriods: ['Medieval Irish literary record'], sourceRefs: [sourceRef('noindenUlad', 'Macha and the debility of the Ulstermen')], identityAnchors: ['赛马', '临产', '诅咒与共同体'], symbols: ['马匹', '诅咒', '王庭'], canonicalDesignOverrides: {}, promptFragment: 'Preserve Macha as a source-scoped Ulster figure and avoid forced identification with Mórrígan.', confidence: 'contested' },
  { id: 'interpretation-celtic-brigid-mythic', characterId: 'character-brigid', slug: 'mythic-brigid', name: '神话 Brigid', role: '诗歌、疗愈与锻造关联的神话身份', summary: '本解释层只呈现神话 Brigid，不注入 Saint Brigid 的圣徒传、修女服或教堂图像。', traditionTags: ['celtic-irish-mythological', 'poetry', 'healing', 'smithcraft'], sourcePeriods: ['Medieval Irish literary record'], sourceRefs: [sourceRef('leborGabala', 'Brigit genealogical and poetic notices')], identityAnchors: ['诗歌', '疗愈', '锻造'], symbols: ['火', '铁砧', '诗歌'], canonicalDesignOverrides: { avoid: ['nun habit', 'Christian cross as canonical identity'] }, promptFragment: 'Depict mythic Brigid through poetry, healing and smithcraft; keep later saintly material outside the canonical design.', confidence: 'high' },
  { id: 'interpretation-celtic-cernunnos-evidence', characterId: 'character-cernunnos', slug: 'gallo-roman-evidence', name: '高卢—罗马证据层', role: '铭文、浮雕与盘角图像中的 Cernunnos', summary: '以 Pillar of the Boatmen 与相关图像证据组织身份，不补写连续史诗。', traditionTags: ['celtic-continental-gaulish', 'celtic-gallo-roman'], sourcePeriods: ['Iron Age and Gallo-Roman evidence'], sourceRefs: [sourceRef('pillarNautes', 'Inscription and antlered relief panels'), sourceRef('cernunnosEvidence', 'antlered imagery comparison')], identityAnchors: ['盘角', '颈环', '动物关联', '铭文语境'], symbols: ['鹿角', '颈环', '蛇'], canonicalDesignOverrides: { costumeLanguage: ['Gallo-Roman stone relief and metalwork context'] }, promptFragment: 'Lead with inscription and relief evidence; do not depict Cernunnos as a satanic demon or fantasy forest king.', confidence: 'medium' },
  { id: 'interpretation-celtic-epona-evidence', characterId: 'character-epona', slug: 'horse-cult-evidence', name: '马匹崇拜证据层', role: '铭文、奉献碑与马匹图像中的 Epona', summary: '以跨地区奉献和马匹关联证据呈现 Epona，不制造爱尔兰家谱或连续史诗。', traditionTags: ['celtic-continental-gaulish', 'celtic-gallo-roman'], sourcePeriods: ['Roman-period Gallo-Roman evidence'], sourceRefs: [sourceRef('eponaInscriptions', 'Inscriptions and horse-associated votive monuments')], identityAnchors: ['马匹', '奉献碑', '保护与陪伴'], symbols: ['马', '马鞍', '石碑'], canonicalDesignOverrides: { avoid: ['Valkyrie armor', 'Irish genealogy'] }, promptFragment: 'Use horse companionship and votive monument evidence; avoid Valkyrie or generic warrior-goddess imagery.', confidence: 'high' },
];

export const celticClaims: readonly ContentClaim[] = [
  { id: 'claim-celtic-multi-tradition', subjectType: 'world', subjectId: 'world-gallo-roman-evidence', claimType: 'interpretation', summary: 'Celtic 是产品聚合入口，必须把爱尔兰、威尔士与大陆／高卢—罗马来源范围分开呈现。', status: 'supported', traditionScope: 'MythCanvas editorial aggregation', sourceRefs: [sourceRef('leborGabala', 'mythographic framework'), sourceRef('whiteBook', 'Four Branches witness context'), sourceRef('cernunnosEvidence', 'evidence scope')] },
  { id: 'claim-celtic-lugh-lugus', subjectType: 'character', subjectId: 'character-lugh', claimType: 'identity', summary: '爱尔兰叙事中的 Lugh 与大陆铭文中的 Lugus 可作比较对象，但本包不将二者静默合并。', status: 'contested', traditionScope: 'Irish Mythological Cycle versus Continental evidence', sourceRefs: [sourceRef('cathMaigeTuired', 'Lugh’s arrival and the Samildánach challenge'), sourceRef('caesarGaul', 'Book 6 external account scope')] },
  { id: 'claim-celtic-brigid-saint', subjectType: 'character', subjectId: 'character-brigid', claimType: 'identity', summary: '神话 Brigid 与后来的 Saint Brigid 是不同来源层；圣徒服饰、十字架和教堂不进入神话 Brigid 的 Canonical Design。', status: 'contested', traditionScope: 'Irish mythic layer versus Christian hagiographic reception', sourceRefs: [sourceRef('leborGabala', 'Brigit genealogical and poetic notices')] },
  { id: 'claim-celtic-nuada-nodens', subjectType: 'character', subjectId: 'character-nuada', claimType: 'identity', summary: 'Nuada 与 Nodens 不在 P0 中自动视为同一人物；任何对应都需要独立的铭文与身份论证。', status: 'contested', traditionScope: 'Irish literary record versus Continental / Romano-British evidence', sourceRefs: [sourceRef('cathMaigeTuired', 'Nuada’s lost arm and restoration'), sourceRef('cernunnosEvidence', 'evidence comparison boundary')] },
  { id: 'claim-celtic-manannan-manawydan', subjectType: 'character', subjectId: 'character-manannan', claimType: 'identity', summary: 'Manannán mac Lir 与 Manawydan fab Llŷr 各自拥有独立 P0 叙事，不因名称相似而合并。', status: 'supported', traditionScope: 'Irish Otherworld versus Welsh Four Branches', sourceRefs: [sourceRef('leborGabala', 'Manannán notices and otherworld material'), sourceRef('manawydan', 'Third Branch: Manawydan and Dyfed')] },
  { id: 'claim-celtic-aengus-maponos', subjectType: 'character', subjectId: 'character-aengus', claimType: 'identity', summary: 'Aengus / Óengus 与 Maponos / Mabon 保持比较边界，不作为同一 Character 的别名。', status: 'contested', traditionScope: 'Irish Mythological Cycle versus Continental / Welsh comparison', sourceRefs: [sourceRef('aislingeOenguso', 'Dream and Caer Ibormeith episodes'), sourceRef('whiteBook', 'Four Branches witness context')] },
  { id: 'claim-celtic-macha-morrigan', subjectType: 'character', subjectId: 'character-macha', claimType: 'identity', summary: 'Macha 与 Mórrígan、Badb、Nemain 的关系必须 source-scoped；P0 不强制一个固定三位一体模型。', status: 'contested', traditionScope: 'Ulster Cycle', sourceRefs: [sourceRef('noindenUlad', 'Macha and the debility of the Ulstermen'), sourceRef('tainR1', 'Mórrígan and Cú Chulainn episodes')] },
  { id: 'claim-celtic-cernunnos-gundestrup', subjectType: 'character', subjectId: 'character-cernunnos', claimType: 'identity', summary: 'Gundestrup Cauldron 的盘角人物可作为比较证据，但不能仅凭相似图像直接命名为 Cernunnos。', status: 'contested', traditionScope: 'Continental / Gallo-Roman evidence', sourceRefs: [sourceRef('cernunnosEvidence', 'Gundestrup comparison and naming boundary')] },
];
