import type { ContentClaim, MythStory } from '../../lib/content/types';
import { sourceRef, storySource } from './sources';

const mythologyId = 'myth-celtic';
const date = '2026-09-02';
type StoryInput = {
  slug: string; title: string; titleEn: string; subtitle: string; summary: string; volumeId: string; volumeTitle: string; volumeOrder: number; displayOrder: number; kind: MythStory['kind']; tradition: string; readingMinutes: number;
  sources: readonly [string, string, string?][]; sourceNotes: readonly string[]; characters: readonly string[]; worlds: readonly string[]; scenes: readonly string[]; paragraphs: readonly [string, string]; claims?: readonly ContentClaim[];
};

const story = (input: StoryInput): MythStory => {
  const attachedSources = input.sources.map(([key, locator, note]) => storySource(key, locator, note));
  return {
    id: `story-celtic-${input.slug}`, slug: `celtic-${input.slug}`, mythologyId, title: input.title, titleEn: input.titleEn, subtitle: input.subtitle, summary: input.summary,
    volumeId: input.volumeId, volumeTitle: input.volumeTitle, volumeOrder: input.volumeOrder, displayOrder: input.displayOrder, kind: input.kind, tradition: input.tradition, readingMinutes: input.readingMinutes,
    sources: attachedSources, sourceNotes: input.sourceNotes, requiredCharacterIds: input.characters, requiredWorldIds: input.worlds, requiredSceneIds: input.scenes, requiredSourceIds: attachedSources.map((item) => item.sourceId!).filter((id, index, all) => all.indexOf(id) === index),
    claims: input.claims, characterIds: input.characters, worldIds: input.worlds, sceneIds: input.scenes, blocks: input.paragraphs.map((text) => ({ type: 'paragraph' as const, text })), publishStatus: 'published', publishedAt: date, updatedAt: date,
  };
};

const claim = (slug: string, summary: string, status: ContentClaim['status'], traditionScope: string, refs: readonly [string, string][]): ContentClaim => ({ id: `claim-story-celtic-${slug}`, subjectType: 'story', subjectId: `story-celtic-${slug}`, claimType: 'narrative', summary, status, traditionScope, sourceRefs: refs.map(([key, locator]) => sourceRef(key, locator)) });

const irishMyth = 'Irish Mythological Cycle / Tuatha Dé Danann';
const ulsterTradition = 'Ulster Cycle';
const welshTradition = 'Welsh Four Branches of the Mabinogi';

export const celticStories: readonly MythStory[] = [
  story({ slug: 'nuada-silver-arm', title: '努阿达、银臂与王权危机', titleEn: 'Nuada, the Silver Arm and Kingship', subtitle: '身体的损伤改变了王座的资格', summary: '从努阿达在战斗中失去手臂开始，介绍银臂、疗愈技艺与 Tuatha Dé Danann 王权危机。', volumeId: 'celtic-tuatha', volumeTitle: '爱尔兰 Mythological Cycle：Tuatha Dé Danann', volumeOrder: 1, displayOrder: 1, kind: 'myth', tradition: irishMyth, readingMinutes: 5, sources: [['cathMaigeTuired', 'Nuada’s lost arm and restoration']], sourceNotes: ['正文依据中世纪爱尔兰文学记录进行原创转述，不把银臂写成现代机械义肢，也不把文学层直接等同于铁器时代宗教事实。'], characters: ['character-nuada', 'character-dian-cecht', 'character-miach'], worlds: ['world-tara', 'world-mag-tuired'], scenes: ['scene-nuada-silver-arm'], paragraphs: ['努阿达在战争中失去手臂，伤口立刻变成王权问题：Tuatha Dé Danann 的王是否必须保持完整身体，才能继续代表共同体？', '银臂和疗愈技艺把身体修复与政治秩序连接起来。这里的“银”是来源中的神话工艺，不应被视觉化为赛博义肢或现代科幻升级。'] }),
  story({ slug: 'bres-kingship', title: '布雷斯的统治与 Tuatha 的困境', titleEn: 'Bres and the Strain of Kingship', subtitle: '礼仪、贡赋与失去民心', summary: '布雷斯的统治把王权的外来关系、贡赋压力与 Tuatha Dé Danann 的不满推向冲突。', volumeId: 'celtic-tuatha', volumeTitle: '爱尔兰 Mythological Cycle：Tuatha Dé Danann', volumeOrder: 1, displayOrder: 2, kind: 'myth', tradition: irishMyth, readingMinutes: 4, sources: [['cathMaigeTuired', 'Bres’s kingship and fall']], sourceNotes: ['本篇只处理 Cath Maige Tuired 的王权冲突，不把布雷斯概括成整个凯尔特传统的统一反派。'], characters: ['character-bres', 'character-nuada', 'character-dagda'], worlds: ['world-tara', 'world-mag-tuired'], scenes: ['scene-tara-hall'], paragraphs: ['布雷斯的王座并不只靠血缘维持。宴会、贡赋和对待诗人的方式，都让共同体判断一个统治者是否仍然配得上王名。', '当礼仪关系变成单向索取，王权就失去回声。这个冲突为努阿达的回归和 Tuatha 的战争准备留下政治原因。'] }),
  story({ slug: 'lugh-at-tara', title: '鲁格来到塔拉：多艺者的试炼', titleEn: 'Lugh at Tara: The Many-Skilled One', subtitle: '一个人能否以技艺进入王庭', summary: '鲁格以多种技艺进入塔拉集会，展示他为何不是只凭“太阳神”标签识别的人物。', volumeId: 'celtic-tuatha', volumeTitle: '爱尔兰 Mythological Cycle：Tuatha Dé Danann', volumeOrder: 1, displayOrder: 3, kind: 'myth', tradition: irishMyth, readingMinutes: 5, sources: [['cathMaigeTuired', 'Lugh’s arrival and the Samildánach challenge']], sourceNotes: ['鲁格的多艺者身份按爱尔兰叙事呈现；不把 Lugus 的大陆证据静默合并为同一人物。'], characters: ['character-lugh', 'character-nuada'], worlds: ['world-tara'], scenes: ['scene-tara-hall'], paragraphs: ['鲁格来到塔拉时，守门者逐项询问他的技艺：铁匠、战士、诗人、医者或棋手是否足以打开王庭之门？他以“多艺者”回应这种分类。', '这场试炼的重点不是给人物堆叠超能力，而是说明一个共同体如何识别能在多种制度之间行动的人。鲁格的长矛和技艺因此服务于领袖身份，而不是单一太阳化视觉。'] }),
  story({ slug: 'tuatha-preparations', title: '诸神备战：工匠、战士与集会', titleEn: 'The Tuatha Prepare for War', subtitle: '战争先从工坊和议庭开始', summary: '达格达、奥格玛、戈布纽与疗愈者共同组织战争准备，展示 Tuatha 的协作结构。', volumeId: 'celtic-tuatha', volumeTitle: '爱尔兰 Mythological Cycle：Tuatha Dé Danann', volumeOrder: 1, displayOrder: 4, kind: 'myth', tradition: irishMyth, readingMinutes: 4, sources: [['cathMaigeTuired', 'Goibniu, Ogma and battle preparations']], sourceNotes: ['正文以工艺、后勤和集会组织为叙事核心，不把 Tuatha 改写成有统一军制的现代阵营。'], characters: ['character-dagda', 'character-ogma', 'character-goibniu', 'character-lugh'], worlds: ['world-mag-tuired'], scenes: ['scene-mag-tuired-battlefield'], paragraphs: ['在真正的交锋发生前，武器、技艺、诗歌和食物已经把共同体组织起来。戈布纽的锻造、奥格玛的力量与达格达的王者姿态并不是同一种“战斗力”。', '鲁格加入集会后，备战变成跨角色的协作：工匠、诗人、战士和统治者各自承担不能互换的工作。'] }),
  story({ slug: 'morrigan-dagda-river', title: '河畔相遇：Mórrígan、达格达与战争预兆', titleEn: 'Mórrígan and the Dagda at the River', subtitle: '预兆不是一份统一神谱', summary: '以来源限定的河畔相遇为入口，呈现 Mórrígan 的预兆角色与达格达的战争处境。', volumeId: 'celtic-tuatha', volumeTitle: '爱尔兰 Mythological Cycle：Tuatha Dé Danann', volumeOrder: 1, displayOrder: 5, kind: 'myth', tradition: irishMyth, readingMinutes: 4, sources: [['cathMaigeTuired', 'Mórrígan and the Dagda before battle']], sourceNotes: ['Mórrígan 的不同名字、职能和后世“三相女神”说法不在本篇压成固定家谱；正文只保留所引叙事范围。'], characters: ['character-morrigan', 'character-dagda'], worlds: ['world-mag-tuired'], scenes: ['scene-dagda-morrigan-river-meeting'], paragraphs: ['河流边的相遇把战争写成一种需要预兆、身体和谈判共同参与的事件。Mórrígan 不是泛化的哥特女巫，达格达也不是喜剧化的肥胖神。', '本篇不试图回答所有名字是否构成固定三位一体，而是让用户看到一段具体的爱尔兰叙事及其来源边界。'] }),
  story({ slug: 'second-battle-mag-tuired', title: '第二次马格·图伊雷德战役', titleEn: 'The Second Battle of Mag Tuired', subtitle: '王权、工艺与致命之眼的决战', summary: '鲁格、努阿达、巴罗尔与 Tuatha Dé Danann 在第二次马格·图伊雷德战役中完成主线冲突。', volumeId: 'celtic-tuatha', volumeTitle: '爱尔兰 Mythological Cycle：Tuatha Dé Danann', volumeOrder: 1, displayOrder: 6, kind: 'myth', tradition: irishMyth, readingMinutes: 7, sources: [['cathMaigeTuired', 'Second Battle: Nuada, Lugh and Balor']], sourceNotes: ['战役细节按 Cath Maige Tuired 的中世纪文学记录转述；不补写一个覆盖全部凯尔特地区的统一创世或末日。'], characters: ['character-lugh', 'character-nuada', 'character-dagda', 'character-morrigan', 'character-balor', 'character-bres', 'character-dian-cecht', 'character-goibniu', 'character-ogma', 'character-cian', 'character-ethniu'], worlds: ['world-mag-tuired'], scenes: ['scene-mag-tuired-battlefield', 'scene-nuada-silver-arm'], paragraphs: ['第二次战役将此前分散的王权、工艺和家系冲突推到同一片战场：努阿达的合法性、鲁格的多艺和巴罗尔的致命之眼各自代表一种力量。', '战役的结果不是“凯尔特诸神统一登场”，而是 Cath Maige Tuired 这条爱尔兰叙事线的收束。巴罗尔与鲁格的关系也应沿来源叙述呈现，不被现代太阳神分类取代。'] }),
  story({ slug: 'aengus-caer', title: '安格斯的梦与寻找 Caer', titleEn: 'Aengus and the Dream of Caer Ibormeith', subtitle: '梦把彼世带到湖岸', summary: '安格斯反复梦见 Caer，并沿着梦的线索寻找她，故事在成年爱情、天鹅与彼世边界之间展开。', volumeId: 'celtic-otherworld', volumeTitle: '爱尔兰彼世叙事：安格斯与梦', volumeOrder: 2, displayOrder: 1, kind: 'folk-legend', tradition: 'Irish Mythological Cycle / Otherworld tale', readingMinutes: 5, sources: [['aislingeOenguso', 'Dream and Caer Ibormeith episodes']], sourceNotes: ['Caer 的天鹅形态属于本篇来源范围；不把她解释成一个跨凯尔特地区通用的白鸟女神。'], characters: ['character-aengus', 'character-caer-ibormeith'], worlds: ['world-irish-otherworld'], scenes: ['scene-aengus-dream'], paragraphs: ['安格斯的梦不是一次随即消散的幻觉，而是反复出现、迫使他改变行动的相遇。梦中的少女与天鹅形态让湖岸成为人间与彼世之间的薄处。', '寻找 Caer 的过程最终要求安格斯理解变形和选择，而不是以神力占有对方。故事因此保留梦、诗歌和成年关系的复杂度。'] }),
  story({ slug: 'noinden-ulad', title: '马查与乌尔斯特的失能', titleEn: 'Macha and the Debility of the Ulstermen', subtitle: 'Táin 的战争逻辑从一场诅咒开始', summary: 'Noínden Ulad 解释乌尔斯特战士在关键时刻无法参战的前置逻辑，并单独处理马查身份。', volumeId: 'celtic-ulster', volumeTitle: '乌尔斯特循环：Táin 的前置故事', volumeOrder: 3, displayOrder: 0, kind: 'folk-legend', tradition: ulsterTradition, readingMinutes: 5, sources: [['noindenUlad', 'Macha and the debility of the Ulstermen']], sourceNotes: ['马查在本篇保持为独立、来源限定的人物；不据此宣布她就是 Mórrígan、Badb、Nemain 的固定三位一体。'], characters: ['character-macha', 'character-conchobar-mac-nessa'], worlds: ['world-emain-macha'], scenes: ['scene-emain-macha'], paragraphs: ['当乌尔斯特的王庭要求马查在临产前参加赛马时，王权对身体和誓言的利用最终反转为诅咒。马查的痛苦成为整个战士共同体必须承担的后果。', '这段前置故事解释了 Táin 中一个关键问题：为什么乌尔斯特主力无法及时出战。它还提醒我们，马查与 Mórrígan 的关系属于身份审查问题，而不是可以自动填入的整齐家谱。'] }),
  story({ slug: 'medb-expedition', title: '梅芙与阿伊利尔的出征动机', titleEn: 'Medb, Ailill and the Expedition', subtitle: '财富比较如何变成战争', summary: '梅芙与阿伊利尔的财富比较和主权竞争推动康诺特对库利棕牛的出征。', volumeId: 'celtic-ulster', volumeTitle: '乌尔斯特循环：Táin Bó Cúailnge', volumeOrder: 3, displayOrder: 1, kind: 'myth', tradition: ulsterTradition, readingMinutes: 5, sources: [['tainR1', 'Medb and Ailill’s cattle comparison'], ['tainR2', 'Medb’s expedition opening']], sourceNotes: ['Recension I 与 II 作为不同来源并列；本篇不把细节差异抹平为一部唯一无版本的 Táin。'], characters: ['character-medb', 'character-ailill-mac-mata'], worlds: ['world-cruachan'], scenes: ['scene-cruachan-court'], paragraphs: ['梅芙与阿伊利尔在王庭中比较财富，牛群不只是牲畜数量，也成为主权、婚姻和政治声望的可见尺度。一个缺少的公牛因此被放大成必须解决的公共问题。', '出征动机不是一个单纯的“女王想要牛”，而是两种王权评价方式相互竞争的结果。不同 Táin 版本对叙述节奏和细节有所差异，本篇保持这种来源层。'], claims: [claim('medb-expedition', 'Táin 的出征动机与财富比较必须在 Recension I / II 的来源范围内阅读。', 'contested', ulsterTradition, [['tainR1', 'Medb and Ailill’s cattle comparison'], ['tainR2', 'Medb’s expedition opening']])] }),
  story({ slug: 'donn-cuailnge', title: '敦·库阿林与库利牛群之争', titleEn: 'Donn Cúailnge and the Cattle Raid', subtitle: '一头公牛成为跨越边界的目标', summary: '康诺特军队为获得敦·库阿林而进入库利半岛，战争目标由动物、土地和声望共同构成。', volumeId: 'celtic-ulster', volumeTitle: '乌尔斯特循环：Táin Bó Cúailnge', volumeOrder: 3, displayOrder: 2, kind: 'myth', tradition: ulsterTradition, readingMinutes: 5, sources: [['tainR1', 'Donn Cúailnge and the raid route'], ['tainR2', 'The Brown Bull of Cooley']], sourceNotes: ['两种 recension 的牛群路线与叙述细节不作无标记合并；正文使用原创概述。'], characters: ['character-medb', 'character-donn-cuailnge', 'character-findbennach'], worlds: ['world-cruachan', 'world-cooley'], scenes: ['scene-cooley-cattle-raid'], paragraphs: ['敦·库阿林是一个具体的动物目标，却承载了康诺特和乌尔斯特之间关于财富、土地与声望的争夺。牛群的移动让政治冲突沿着道路和牧地展开。', '当故事从王庭进入半岛，库丘林尚未成为唯一的防线。此处的视觉中心应是牛群、山谷、车队和海岸，而不是一张泛化的中世纪战争海报。'], claims: [claim('donn-cuailnge', '敦·库阿林的战争意义来自 Táin 叙事内部的财富与主权冲突，不是泛凯尔特圣牛母题的自动汇总。', 'supported', ulsterTradition, [['tainR1', 'Donn Cúailnge and the raid route']])] }),
  story({ slug: 'cu-chulainn-alone', title: '库丘林为何独守乌尔斯特', titleEn: 'Why Cú Chulainn Stands Alone', subtitle: '失能前置让英雄成为最后的边界', summary: '把 Noínden Ulad 与 Táin 主线连接起来，解释库丘林如何在主力失能时独自守住道路。', volumeId: 'celtic-ulster', volumeTitle: '乌尔斯特循环：Táin Bó Cúailnge', volumeOrder: 3, displayOrder: 3, kind: 'myth', tradition: ulsterTradition, readingMinutes: 6, sources: [['noindenUlad', 'Macha and the debility of the Ulstermen'], ['tainR1', 'Cú Chulainn’s single combat sequence'], ['tainR2', 'Cú Chulainn’s single combat sequence']], sourceNotes: ['Noínden Ulad 是独立前置来源；Táin Recension I / II 的单独决斗段落并列标出，避免把“独守”写成无版本差异的单一史实。'], characters: ['character-macha', 'character-cu-chulainn', 'character-loeg', 'character-conchobar-mac-nessa'], worlds: ['world-emain-macha', 'world-cooley'], scenes: ['scene-emain-macha', 'scene-cooley-cattle-raid', 'scene-cu-chulainn-ford'], paragraphs: ['乌尔斯特战士因为马查的诅咒陷入周期性的失能，康诺特军队因此获得了推进的窗口。库丘林不只是“最强英雄”，而是被放到一道必须有人守住的边界上。', '战车、河滩、御者洛伊格和连续单挑让英雄性变成时间管理与身体代价。不同 recension 的叙述仍需在读者侧保持可见，不能把所有细节揉成一版。'], claims: [claim('cu-chulainn-alone', '库丘林独守的叙事逻辑依赖 Noínden Ulad 前置与 Táin 的版本化段落。', 'supported', ulsterTradition, [['noindenUlad', 'Macha and the debility of the Ulstermen'], ['tainR1', 'Cú Chulainn’s single combat sequence'], ['tainR2', 'Cú Chulainn’s single combat sequence']])] }),
  story({ slug: 'morrigan-cu-chulainn', title: 'Mórrígan与库丘林：冲突、援助与预兆', titleEn: 'Mórrígan and Cú Chulainn', subtitle: '同一人物在不同段落中并不只有一种姿态', summary: '以 Táin 中的冲突、援助和预兆段落为范围，呈现 Mórrígan 与库丘林的复杂关系。', volumeId: 'celtic-ulster', volumeTitle: '乌尔斯特循环：Táin Bó Cúailnge', volumeOrder: 3, displayOrder: 4, kind: 'myth', tradition: ulsterTradition, readingMinutes: 5, sources: [['tainR1', 'Mórrígan and Cú Chulainn episodes'], ['tainR2', 'Mórrígan and Cú Chulainn episodes']], sourceNotes: ['Mórrígan 的不同段落和身份称谓属于来源范围内的叙事差异；不把现代“三相女神”模型注入正文。'], characters: ['character-morrigan', 'character-cu-chulainn'], worlds: ['world-cooley'], scenes: ['scene-cu-chulainn-ford'], paragraphs: ['Mórrígan 与库丘林的相遇可能表现为冲突、试探、援助或预兆。把她固定成单一阵营，会丢失 Táin 叙事中反复转向的张力。', '本篇的乌鸦、河滩和战车构图服务于具体文本，而不是把 Mórrígan 变成抽象的黑翼女王。身份与关系均随来源 locator 读取。'], claims: [claim('morrigan-cu-chulainn', 'Mórrígan 与库丘林的关系在 Táin 不同段落中具有来源差异，不能被一条固定的敌友标签完全覆盖。', 'contested', ulsterTradition, [['tainR1', 'Mórrígan and Cú Chulainn episodes'], ['tainR2', 'Mórrígan and Cú Chulainn episodes']])] }),
  story({ slug: 'fer-diad-duel', title: '库丘林与费尔·迪亚德', titleEn: 'Cú Chulainn and Fer Diad', subtitle: '友谊被战争推到河滩', summary: '费尔·迪亚德与库丘林的连续决斗把英雄友谊、义务和身体代价推向不可逆的结局。', volumeId: 'celtic-ulster', volumeTitle: '乌尔斯特循环：Táin Bó Cúailnge', volumeOrder: 3, displayOrder: 5, kind: 'myth', tradition: ulsterTradition, readingMinutes: 6, sources: [['tainR1', 'Cú Chulainn and Fer Diad single combat'], ['tainR2', 'Cú Chulainn and Fer Diad single combat']], sourceNotes: ['正文是原创中文转述；决斗细节依 Recension I / II 的共同主题与各自段落呈现，不复制现代译本。'], characters: ['character-cu-chulainn', 'character-fer-diad'], worlds: ['world-cooley'], scenes: ['scene-fer-diad-duel'], paragraphs: ['费尔·迪亚德不是一个只为衬托库丘林而存在的反派。他们共享训练、技巧与记忆，因此每一次在河滩上交手，都让“完成任务”与“保留友谊”变得互相冲突。', '当决斗走到终点，胜利并不能抵消失去朋友的代价。Táin 的英雄性在这里不是无伤凯旋，而是必须承担自己被迫做出的选择。'] }),
  story({ slug: 'ulster-turning-point', title: '乌尔斯特军势恢复与战争转折', titleEn: 'The Ulster Army Returns', subtitle: '等待结束，战线重新移动', summary: '随着乌尔斯特战士恢复，库丘林独守的时间窗口结束，战争从个人决斗转向军队冲突。', volumeId: 'celtic-ulster', volumeTitle: '乌尔斯特循环：Táin Bó Cúailnge', volumeOrder: 3, displayOrder: 6, kind: 'myth', tradition: ulsterTradition, readingMinutes: 5, sources: [['tainR1', 'Ulster army and the battle turn'], ['tainR2', 'Ulster army and the battle turn']], sourceNotes: ['本篇用来连接独守与结局战场；不同 recension 的军势和战斗顺序必须回到各自 source locator。'], characters: ['character-cu-chulainn', 'character-conchobar-mac-nessa', 'character-fergus-mac-roich', 'character-medb'], worlds: ['world-emain-macha', 'world-cruachan'], scenes: ['scene-emain-macha', 'scene-cruachan-court'], paragraphs: ['库丘林独守的时间终究会结束。乌尔斯特军势恢复后，原本被压缩到河滩和单挑中的冲突重新扩展成军队、王庭和退路的选择。', '转折并不抹去库丘林此前付出的代价，而是改变了故事的尺度：个人守门成为共同体重新进入战争的条件。'] }),
  story({ slug: 'bulls-final-combat', title: '两头公牛的最终冲突', titleEn: 'The Final Combat of the Bulls', subtitle: '战争目标在动物身上完成结局', summary: 'Donn Cúailnge 与 Findbennach 的最终冲突结束了 Táin 的牛群争夺，也留下毁灭性的余波。', volumeId: 'celtic-ulster', volumeTitle: '乌尔斯特循环：Táin Bó Cúailnge', volumeOrder: 3, displayOrder: 7, kind: 'myth', tradition: ulsterTradition, readingMinutes: 5, sources: [['tainR1', 'The two bulls and final combat'], ['tainR2', 'The White Bull and final combat']], sourceNotes: ['两头公牛的结局保留 Táin 版本化来源范围；不把动物冲突扩写成所有凯尔特牛神话的统一原型。'], characters: ['character-donn-cuailnge', 'character-findbennach', 'character-medb', 'character-ailill-mac-mata'], worlds: ['world-cooley', 'world-cruachan'], scenes: ['scene-bulls-final-duel'], paragraphs: ['当两头公牛终于相遇，王庭里关于财富和声望的争论变成动物身体的冲撞。Donn Cúailnge 与 Findbennach 的力量把战争的代价从人群扩展到土地和牲畜。', '结局不是一场干净的胜利：争夺的对象被重新夺回，却带着毁灭性的后果离开。Táin 因此以余波结束，而不是以统一王权庆典结束。'] }),
  story({ slug: 'fionn-salmon', title: '芬恩与智慧鲑鱼', titleEn: 'Fionn and the Salmon of Knowledge', subtitle: '知识先经过手，再改变名字', summary: '芬恩在芬尼亚传统的起源桥接中因智慧鲑鱼获得知识，建立他作为猎人、领袖与智慧人物的身份。', volumeId: 'celtic-fenian', volumeTitle: '芬尼亚循环：芬恩的起源桥接', volumeOrder: 4, displayOrder: 1, kind: 'folk-legend', tradition: 'Fenian Cycle', readingMinutes: 5, sources: [['macgnimarthaFind', 'Salmon of Knowledge episode']], sourceNotes: ['本篇只承担 Fionn 的起源桥接，不宣称已经完整覆盖 Fenian Cycle，也不把 Fionn 直接改写为中世纪骑士。'], characters: ['character-fionn-mac-cumhaill'], worlds: ['world-fenian-landscape'], scenes: ['scene-fenian-salmon-river'], paragraphs: ['年轻的芬恩替导师照看智慧鲑鱼，却在烹煮时触碰到鱼皮上的一滴油脂。知识不是通过一场宏大加冕进入他身体，而是由劳动、意外和一瞬间的反应传递。', '当他吸吮手指后，芬恩获得了能够辨认危险与道路的智慧。这段起源让他首先成为猎行者和领袖，而不是被套进骑士传奇的现成轮廓。'] }),
  story({ slug: 'pwyll-arawn', title: '普伊尔与阿冉交换身份', titleEn: 'Pwyll and Arawn Exchange Places', subtitle: '王权从一次守信开始', summary: 'Pwyll 在安温边界与 Arawn 交换身份，以守约和克制获得彼世王的信任。', volumeId: 'celtic-welsh-four-branches', volumeTitle: 'Welsh Four Branches：Pwyll', volumeOrder: 5, displayOrder: 1, kind: 'myth', tradition: welshTradition, readingMinutes: 5, sources: [['whiteBook', 'First Branch witness: Pwyll and Arawn'], ['redBook', 'First Branch witness: Pwyll and Arawn'], ['pwyll', 'First Branch: Pwyll and Arawn']], sourceNotes: ['Four Branches 按威尔士中世纪文学记录组织；White Book / Red Book 是见证层，正文不假装恢复一个未保存的唯一古代原文。'], characters: ['character-pwyll', 'character-arawn'], worlds: ['world-dyfed', 'world-annwn'], scenes: ['scene-pwyll-annwn-exchange'], paragraphs: ['Pwyll 在安温边界遇到 Arawn 后，接受一项危险的交换：以彼世王的身份生活，并在决斗中守住对方的承诺。身份在这里不是服装变换，而是对行为后果的承担。', 'Pwyll 没有趁交换之机占有王权或王后，他的克制使两位统治者建立起跨世界的信任。安温因此是一个具体的威尔士叙事空间，不是泛凯尔特“九界”。'] }),
  story({ slug: 'rhiannon-pryderi', title: '里安农、婚姻与普利德里的失踪', titleEn: 'Rhiannon, Marriage and Pryderi', subtitle: '土丘边的等待与归来', summary: '里安农与 Pwyll 的婚姻、普利德里的失踪和归来组成第一 Branch 的家庭与王权转折。', volumeId: 'celtic-welsh-four-branches', volumeTitle: 'Welsh Four Branches：Pwyll', volumeOrder: 5, displayOrder: 2, kind: 'myth', tradition: welshTradition, readingMinutes: 5, sources: [['whiteBook', 'First Branch: Rhiannon and Pryderi'], ['redBook', 'First Branch: Rhiannon and Pryderi'], ['pwyll', 'First Branch: Pryderi’s birth and return']], sourceNotes: ['里安农的马匹和土丘意象属于本 Branch 的来源场景；不套用爱尔兰 Mórrígan 或 Epona 的身份。'], characters: ['character-pwyll', 'character-rhiannon', 'character-pryderi'], worlds: ['world-dyfed'], scenes: ['scene-arberth-mound'], paragraphs: ['里安农在土丘边的出现把婚姻写成一次需要选择的相遇，而不是王室安排的背景。普利德里的出生和失踪随后让家庭关系承担王国秩序的压力。', '失踪后的归来不是简单的“被找回”，而是多个见证者重新确认身份。里安农的马匹、土丘和道路应保持威尔士故事的具体质地。'] }),
  story({ slug: 'branwen-insult', title: '布兰温的婚姻与政治裂痕', titleEn: 'Branwen, Marriage and Political Rupture', subtitle: '一次侮辱越过海峡', summary: 'Branwen 的婚姻和受辱引发威尔士与爱尔兰之间的政治裂痕，成为第二 Branch 的起点。', volumeId: 'celtic-welsh-four-branches', volumeTitle: 'Welsh Four Branches：Branwen', volumeOrder: 5, displayOrder: 3, kind: 'myth', tradition: welshTradition, readingMinutes: 5, sources: [['whiteBook', 'Second Branch: Branwen’s marriage and insult'], ['redBook', 'Second Branch: Branwen’s marriage and insult'], ['branwen', 'Second Branch: Branwen’s marriage and insult']], sourceNotes: ['“爱尔兰”在本篇是威尔士叙事中的对岸政治空间，不代表现代民族或所有凯尔特传统的历史地图。'], characters: ['character-branwen', 'character-brân', 'character-efnisien'], worlds: ['world-welsh-court'], scenes: ['scene-branwen-harlech-court'], paragraphs: ['布兰温的婚姻本可以连接两个王室，却因为羞辱和惩罚变成一条不断收紧的政治裂痕。她的处境让王室关系的代价落在一个具体的人身上。', '埃夫尼斯延的破坏性行动进一步加剧了冲突。第二 Branch 的战争因此不是单一英雄发起的征服，而是侮辱、复仇和亲属关系层层推进的结果。'] }),
  story({ slug: 'bran-crosses-sea', title: '布兰渡海与断首遗物', titleEn: 'Brân Crosses the Sea', subtitle: '巨人王的身体成为边界', summary: '布兰率军渡海、战争结束与断首遗物构成 Branwen Branch 的战争收束。', volumeId: 'celtic-welsh-four-branches', volumeTitle: 'Welsh Four Branches：Branwen', volumeOrder: 5, displayOrder: 4, kind: 'myth', tradition: welshTradition, readingMinutes: 6, sources: [['whiteBook', 'Second Branch: Brân crosses the sea and the war'], ['redBook', 'Second Branch: Brân crosses the sea and the war'], ['branwen', 'Second Branch: Brân crosses the sea']], sourceNotes: ['布兰之首是 Four Branches 的叙事遗物，不把它解释为统一凯尔特圣物或不死王传说。'], characters: ['character-brân', 'character-branwen', 'character-efnisien'], worlds: ['world-welsh-court'], scenes: ['scene-bran-crosses-sea'], paragraphs: ['布兰的身躯足以成为渡海和战争的视觉中心，但战争的重量并不等于荣耀。随着亲属关系和军队不断损耗，巨人王的身体也从统治者变成必须被安置的遗物。', '断首继续面向威尔士土地的意象，让结束和守护同时存在。它是 Welsh Branch 内部的叙事结果，不应被包装成所有凯尔特传统共享的末日机制。'] }),
  story({ slug: 'manawydan-empty-dyfed', title: '荒废的迪费德与幸存者的生活', titleEn: 'The Empty Land of Dyfed', subtitle: '魔法之后仍要耕作和谋生', summary: 'Manawydan 与 Pryderi 面对人口消失后的 Dyfed，故事把彼世魔法转化为具体的生活困境。', volumeId: 'celtic-welsh-four-branches', volumeTitle: 'Welsh Four Branches：Manawydan', volumeOrder: 5, displayOrder: 5, kind: 'myth', tradition: welshTradition, readingMinutes: 5, sources: [['whiteBook', 'Third Branch: empty Dyfed'], ['redBook', 'Third Branch: empty Dyfed'], ['manawydan', 'Third Branch: Manawydan and Dyfed']], sourceNotes: ['第三 Branch 的荒废地景属于 Dyfed 叙事；不将其扩写为统一凯尔特世界末日。'], characters: ['character-manawydan', 'character-pryderi', 'character-rhiannon'], worlds: ['world-dyfed'], scenes: ['scene-empty-dyfed'], paragraphs: ['迪费德突然空无一人，留下的不是宏大废墟，而是需要被继续使用的土地、工具和道路。Manawydan 以手艺和耐心面对荒废，把“英雄行动”拉回生活尺度。', '当 Pryderi 和 Rhiannon 进一步消失，幸存者必须追问魔法如何进入土地与家庭。第三 Branch 的紧张感来自空旷和等待，而不是一套通用的彼世地图。'] }),
  story({ slug: 'manawydan-breaks-magic', title: '普利德里与里安农的消失', titleEn: 'Manawydan Breaks the Enchantment', subtitle: '耐心拆解一场魔法陷阱', summary: 'Manawydan 通过观察、谈判和坚持，逐步解除使 Pryderi 与 Rhiannon 消失的魔法。', volumeId: 'celtic-welsh-four-branches', volumeTitle: 'Welsh Four Branches：Manawydan', volumeOrder: 5, displayOrder: 6, kind: 'myth', tradition: welshTradition, readingMinutes: 5, sources: [['whiteBook', 'Third Branch: Pryderi and Rhiannon disappear'], ['redBook', 'Third Branch: Pryderi and Rhiannon disappear'], ['manawydan', 'Third Branch: breaking the enchantment']], sourceNotes: ['正文按第三 Branch 的魔法和谈判结构原创转述；Manawydan 与爱尔兰 Manannán mac Lir 保持独立人物。'], characters: ['character-manawydan', 'character-pryderi', 'character-rhiannon'], worlds: ['world-dyfed'], scenes: ['scene-empty-dyfed'], paragraphs: ['魔法把 Pryderi 和 Rhiannon 从日常土地中抽离，却没有让 Manawydan 失去判断力。他从异常的物件、行为和交换条件中辨认出这不是自然灾害。', '解除魔法需要谈判和对后果的承担，而不是一击击败一个怪物。Manawydan 的力量因此来自耐心、技艺与关系责任。'] }),
  story({ slug: 'math-goewin-gwydion', title: '马思、戈温与圭迪翁', titleEn: 'Math, Goewin and Gwydion', subtitle: '王权禁忌被打破之后', summary: '第四 Branch 从 Goewin 承受的王权禁忌开始，转向 Math 与 Gwydion 的秩序修复和冲突。', volumeId: 'celtic-welsh-four-branches', volumeTitle: 'Welsh Four Branches：Math', volumeOrder: 5, displayOrder: 7, kind: 'myth', tradition: welshTradition, readingMinutes: 5, sources: [['whiteBook', 'Fourth Branch: Math and Goewin'], ['redBook', 'Fourth Branch: Math and Goewin'], ['math', 'Fourth Branch: Math and Gwydion']], sourceNotes: ['第四 Branch 的“足下禁忌”与魔法秩序按 Welsh 文本范围处理，不用现代道德标签替代叙事关系。'], characters: ['character-math', 'character-goewin', 'character-gwydion', 'character-pryderi'], worlds: ['world-math-court'], scenes: ['scene-math-court'], paragraphs: ['马思必须以脚放在 Goewin 膝上的禁忌维持王权秩序，这一安排在战争和欲望介入后被打破。戈温不是宫廷装饰，她的处境迫使权力重新安排责任。', '圭迪翁以魔法和策略介入后，冲突从宫廷礼仪延伸到 Pryderi 的死亡与新的继承安排。第四 Branch 让“魔法”始终与政治后果相连。'] }),
  story({ slug: 'arianrhod-lleu', title: '阿丽安罗德、命名与卢厄', titleEn: 'Arianrhod and Lleu’s Names', subtitle: '身份先被拒绝，再被创造', summary: '阿丽安罗德拒绝为 Lleu 命名和武装，圭迪翁通过策略重新打开身份与成长的路径。', volumeId: 'celtic-welsh-four-branches', volumeTitle: 'Welsh Four Branches：Math', volumeOrder: 5, displayOrder: 8, kind: 'myth', tradition: welshTradition, readingMinutes: 5, sources: [['whiteBook', 'Fourth Branch: Arianrhod and Lleu'], ['redBook', 'Fourth Branch: Arianrhod and Lleu'], ['math', 'Fourth Branch: Lleu’s names and weapons']], sourceNotes: ['Lleu 的身份、命名和武装是本 Branch 的叙事问题；不与爱尔兰 Lugh 静默合并。'], characters: ['character-arianrhod', 'character-lleu-law-gyffes', 'character-gwydion'], worlds: ['world-math-court'], scenes: ['scene-math-court'], paragraphs: ['Lleu 的身份并没有因为出生就自动获得确认。命名、武装和母亲的承认依次成为门槛，圭迪翁必须用策略为他创造可以被世界看见的条件。', '这条故事线让“名字”成为一种社会关系，而不是简单的异体拼写。Lleu 与爱尔兰的 Lugh 可以并置比较，但本篇保持 Welsh 文本内部的身份。'] }),
  story({ slug: 'blodeuwedd', title: '花朵创造、背叛与猫头鹰', titleEn: 'Blodeuwedd: Flowers, Betrayal and Owl', subtitle: '被创造的身份寻找自己的出口', summary: '圭迪翁与马思从花朵创造 Blodeuwedd，她的背叛和变形完成第四 Branch 的结局。', volumeId: 'celtic-welsh-four-branches', volumeTitle: 'Welsh Four Branches：Math', volumeOrder: 5, displayOrder: 9, kind: 'myth', tradition: welshTradition, readingMinutes: 6, sources: [['whiteBook', 'Fourth Branch: Blodeuwedd’s creation and fate'], ['redBook', 'Fourth Branch: Blodeuwedd’s creation and fate'], ['math', 'Fourth Branch: Blodeuwedd’s creation and fate']], sourceNotes: ['花朵、鹰和猫头鹰意象按第四 Branch 的具体叙事处理；不把 Blodeuwedd 变成泛化的森林精灵。'], characters: ['character-gwydion', 'character-math', 'character-lleu-law-gyffes', 'character-blodeuwedd'], worlds: ['world-math-court'], scenes: ['scene-blodeuwedd-creation'], paragraphs: ['Blodeuwedd 由花朵创造，却被放入一段已经安排好的婚姻和身份中。她的行动不能被简单压扁成“背叛的花精”，因为故事同时展示了创造者、丈夫和她自己之间的权力关系。', '当 Lleu 变成鹰、Blodeuwedd 变成猫头鹰，变形成为惩罚也成为一种新的叙事位置。Four Branches 以不稳定的身份结束，而不是以整齐的道德结论结束。'] }),
];
