/**
 * Explicit World/Scene closure for existing Norse Story units.
 *
 * This is kept separate from the source manifest because it describes the
 * current content-model mapping, not a new mythological claim. Human review
 * must still confirm that each mapping is appropriate for the cited source.
 */
export type NorseStoryDependencyPlan = {
  world: readonly string[];
  scene: readonly string[];
};

export const norseStoryDependencyPlan: Readonly<Record<string, NorseStoryDependencyPlan>> = {
  'ymir-creation': { world: ['world-jotunheim', 'world-niflheim'], scene: ['scene-ginnungagap'] },
  'audhumla-and-buri': { world: ['world-niflheim'], scene: ['scene-ginnungagap'] },
  'ymir-world-making': { world: ['world-midgard', 'world-asgard'], scene: ['scene-ginnungagap'] },
  'ask-and-embla': { world: ['world-midgard'], scene: ['scene-midgard-coast'] },
  'yggdrasil-and-wells': { world: ['world-asgard', 'world-niflheim'], scene: ['scene-world-tree-roots', 'scene-well-of-mimir'] },
  'norns-at-urdarbrunnr': { world: ['world-asgard'], scene: ['scene-world-tree-roots'] },
  'sun-moon-pursuers': { world: ['world-midgard'], scene: ['scene-world-tree-roots'] },
  'nidhoggr-and-world-tree': { world: ['world-niflheim'], scene: ['scene-world-tree-roots'] },
  'gullveig-and-aesir-vanir-war': { world: ['world-asgard', 'world-vanaheim'], scene: ['scene-asgard-court'] },
  'aesir-vanir-truce': { world: ['world-asgard', 'world-vanaheim'], scene: ['scene-asgard-court'] },
  'kvasir-and-mead': { world: ['world-asgard'], scene: ['scene-asgard-court'] },
  'odin-steals-mead': { world: ['world-asgard', 'world-jotunheim'], scene: ['scene-jotunheim-border'] },
  'idunn-and-thjazi': { world: ['world-asgard', 'world-jotunheim'], scene: ['scene-asgard-court', 'scene-jotunheim-border'] },
  'skadi-compensation': { world: ['world-asgard', 'world-jotunheim'], scene: ['scene-asgard-court'] },
  'njordr-and-skadi': { world: ['world-asgard', 'world-jotunheim'], scene: ['scene-jotunheim-border'] },
  'asgard-wall-and-sleipnir': { world: ['world-asgard', 'world-jotunheim'], scene: ['scene-asgard-court'] },
  'sifs-hair-and-treasures': { world: ['world-asgard'], scene: ['scene-asgard-court'] },
  'freyr-and-gerdr': { world: ['world-vanaheim', 'world-jotunheim'], scene: ['scene-jotunheim-border'] },
  'odin-and-mimir': { world: ['world-asgard'], scene: ['scene-well-of-mimir'] },
  'odin-on-world-tree': { world: ['world-asgard'], scene: ['scene-world-tree-roots'] },
  'odin-and-vafthrudnir': { world: ['world-asgard', 'world-jotunheim'], scene: ['scene-jotunheim-border'] },
  'grimnir-revealed': { world: ['world-asgard'], scene: ['scene-asgard-court'] },
  'odin-ravens': { world: ['world-asgard'], scene: ['scene-asgard-court'] },
  'valholl-and-valkyries': { world: ['world-asgard'], scene: ['scene-asgard-court'] },
  'odin-seidr': { world: ['world-asgard'], scene: ['scene-asgard-court'] },
  'thor-and-hrungnir': { world: ['world-jotunheim', 'world-asgard'], scene: ['scene-jotunheim-border'] },
  'thor-and-hymir': { world: ['world-jotunheim'], scene: ['scene-jotunheim-border'] },
  'thor-fishes-for-serpent': { world: ['world-midgard', 'world-jotunheim'], scene: ['scene-midgard-coast'] },
  'thryms-stolen-hammer': { world: ['world-jotunheim', 'world-asgard'], scene: ['scene-thryms-hall'] },
  'thor-and-thjalfi-roskva': { world: ['world-midgard'], scene: ['scene-midgard-coast'] },
  'thor-and-skrymir': { world: ['world-jotunheim'], scene: ['scene-jotunheim-border'] },
  'thor-in-utgard': { world: ['world-jotunheim'], scene: ['scene-jotunheim-border'] },
  'thor-and-geirrod': { world: ['world-jotunheim'], scene: ['scene-jotunheim-border'] },
  'thor-and-alviss': { world: ['world-asgard'], scene: ['scene-asgard-court'] },
  'thor-and-harbard': { world: ['world-midgard'], scene: ['scene-midgard-coast'] },
  'loki-and-angrboda': { world: ['world-asgard', 'world-jotunheim', 'world-midgard', 'world-hel'], scene: ['scene-asgard-court'] },
  'fenrir-and-gleipnir': { world: ['world-asgard', 'world-jotunheim'], scene: ['scene-asgard-court'] },
  'lokis-feast': { world: ['world-asgard'], scene: ['scene-asgard-court'] },
  'loki-and-baldr': { world: ['world-asgard'], scene: ['scene-asgard-court'] },
  'loki-bound': { world: ['world-asgard'], scene: ['scene-world-tree-roots'] },
  'loki-at-ragnarok': { world: ['world-asgard', 'world-midgard'], scene: ['scene-bifrost'] },
  'baldrs-dreams': { world: ['world-asgard'], scene: ['scene-asgard-court'] },
  'baldrs-death': { world: ['world-asgard'], scene: ['scene-asgard-court'] },
  'baldrs-funeral': { world: ['world-asgard', 'world-hel'], scene: ['scene-baldr-funeral-shore'] },
  'hermod-rides-to-hel': { world: ['world-asgard', 'world-hel'], scene: ['scene-hall-of-hel'] },
  'vali-avenges-baldr': { world: ['world-asgard'], scene: ['scene-asgard-court'] },
  fimbulwinter: { world: ['world-midgard', 'world-jotunheim'], scene: ['scene-fimbulwinter-field'] },
  'odin-and-fenrir': { world: ['world-midgard', 'world-asgard'], scene: ['scene-fimbulwinter-field'] },
  'thor-and-jormungandr-final-battle': { world: ['world-midgard'], scene: ['scene-midgard-coast'] },
  'freyr-and-surtr': { world: ['world-muspell', 'world-asgard'], scene: ['scene-muspell-flame-border'] },
  'tyr-and-garmr': { world: ['world-hel'], scene: ['scene-fimbulwinter-field'] },
  'heimdall-and-loki': { world: ['world-asgard'], scene: ['scene-bifrost'] },
  'ragnarok-renewal': { world: ['world-midgard', 'world-asgard'], scene: ['scene-renewed-earth'] },
  'volsung-and-sword-tree': { world: ['world-midgard'], scene: ['scene-volsung-hall'] },
  'signy-and-siggeir': { world: ['world-midgard'], scene: ['scene-volsung-hall'] },
  'sigmund-and-sinfjotli': { world: ['world-midgard'], scene: ['scene-volsung-hall'] },
  'sigmunds-death-and-hjordis': { world: ['world-midgard'], scene: ['scene-volsung-hall'] },
  'andvari-gold': { world: ['world-midgard'], scene: ['scene-volsung-hall'] },
  'sigurd-and-regin': { world: ['world-midgard'], scene: ['scene-volsung-hall'] },
  'sigurd-kills-fafnir': { world: ['world-midgard'], scene: ['scene-volsung-hall'] },
  'sigurd-and-sigrdrifa': { world: ['world-midgard'], scene: ['scene-volsung-hall'] },
  'sigurd-and-brynhildr': { world: ['world-midgard'], scene: ['scene-volsung-hall'] },
  'sigurds-death': { world: ['world-midgard'], scene: ['scene-volsung-hall'] },
  'gudrun-and-atli': { world: ['world-midgard'], scene: ['scene-volsung-hall'] },
  'gudrun-svanhild-hamdir-sorli': { world: ['world-midgard'], scene: ['scene-volsung-hall'] },
  'helgi-hjorvardsson-and-svava': { world: ['world-midgard'], scene: ['scene-midgard-coast'] },
  'helgi-hundingsbani': { world: ['world-midgard'], scene: ['scene-midgard-coast'] },
  'helgi-and-sigrun': { world: ['world-midgard'], scene: ['scene-midgard-coast'] },
  'helgi-burial-mound': { world: ['world-midgard'], scene: ['scene-midgard-coast'] },
  'volundr-captive-smith': { world: ['world-midgard'], scene: ['scene-volsung-hall'] },
  'volundr-escape': { world: ['world-midgard'], scene: ['scene-volsung-hall'] },
  'svipdagr-and-mengloth': { world: ['world-midgard'], scene: ['scene-volsung-hall'] },
  'rig-and-social-orders': { world: ['world-midgard'], scene: ['scene-volsung-hall'] },
  grottasongr: { world: ['world-midgard'], scene: ['scene-volsung-hall'] },
};
