import type { MythStory, MythStorySource } from '../../lib/content/types';
import { storySource } from './sources';

const mythologyId = 'myth-norse';
const date = '2026-09-01';

const sources = {
  prose: storySource('proseEddaGylfaginning', '按相关章节；Phase 3 逐篇精确化'),
  poetic: storySource('voluspa', '按相关诗篇与诗节；Phase 3 逐篇精确化'),
  skaldic: storySource('haustlong', '按相关 stanza；Phase 3 逐篇精确化'),
  volsung: storySource('volsungaSaga', '按相关章节；Phase 3 逐篇精确化'),
} as const satisfies Record<string, MythStorySource>;

/** Precise source replacements for legacy entries that originally shared a broad placeholder source. */
const preciseLegacySources: Readonly<Record<string, MythStorySource>> = {
  'aesir-vanir-war': storySource('voluspa', 'st. 21–24'),
  'thor-in-utgard': storySource('proseEddaGylfaginning', 'ch. 46–47'),
  'thor-and-geirrod': storySource('thorsdrapa', 'selected stanzas'),
  'fenrir-and-gleipnir': storySource('proseEddaGylfaginning', 'ch. 34'),
  'lokis-feast': storySource('lokasenna', 'st. 1–65'),
  'loki-bound': storySource('proseEddaGylfaginning', 'ch. 50'),
  'baldrs-dreams': storySource('baldrsDraumar', 'st. 1–14'),
  'baldrs-death': storySource('proseEddaGylfaginning', 'ch. 49'),
  'hermod-rides-to-hel': storySource('proseEddaGylfaginning', 'ch. 49'),
  fimbulwinter: storySource('voluspa', 'st. 41–45'),
  'odin-and-fenrir': storySource('voluspa', 'st. 53–54'),
  'thor-and-jormungandr-final-battle': storySource('voluspa', 'st. 56'),
  'freyr-and-surtr': storySource('proseEddaGylfaginning', 'ch. 51'),
  'heimdall-and-loki': storySource('voluspa', 'st. 46, 51'),
  'sigurd-and-regin': storySource('reginsmal', 'st. 1–40'),
  'sigurd-kills-fafnir': storySource('fafnismal', 'st. 1–44'),
  'sigurd-and-brynhildr': storySource('volsungaSaga', 'chs. 20–27'),
  'sigurds-death': storySource('sigurdarkvida', 'fragmentary poems; scoped comparison with saga'),
};

type StoryInput = {
  slug: string;
  title: string;
  titleEn: string;
  subtitle: string;
  summary: string;
  kind?: MythStory['kind'];
  volumeId: string;
  volumeTitle: string;
  volumeOrder: number;
  displayOrder: number;
  source: MythStorySource;
  tradition: string;
  characters: readonly string[];
  worlds?: readonly string[];
  scenes?: readonly string[];
  objects?: readonly string[];
  legacySlugs?: readonly string[];
  narrative: string;
  /** A structured draft is deliberately distinct from the legacy prototype body. */
  sections?: readonly {
    id: string;
    heading: string;
    paragraphs: readonly string[];
  }[];
  editorialStatus?: MythStory['editorialStatus'];
};

const sourceForStory = (input: StoryInput): MythStorySource => preciseLegacySources[input.slug] ?? input.source;

const storyBlocks = (input: StoryInput): MythStory['blocks'] => input.sections
  ? input.sections.flatMap((section) => [
      { type: 'heading' as const, id: section.id, text: section.heading, level: 2 as const },
      ...section.paragraphs.map((text) => ({ type: 'paragraph' as const, text })),
    ])
  : [
      { type: 'heading' as const, id: 'narrative-scope', text: '叙事线索', level: 2 as const },
      { type: 'paragraph' as const, text: input.narrative },
      { type: 'heading' as const, id: 'source-scope', text: '来源范围', level: 2 as const },
      { type: 'paragraph' as const, text: `本研究稿以 ${sourceForStory(input).title}（${sourceForStory(input).locator ?? '待补精确 locator'}）为依据；正文仍须逐项核对其人物、行动与版本差异，不能把后世改编补作来源事实。` },
      { type: 'heading' as const, id: 'reading-path', text: '继续探索', level: 2 as const },
      { type: 'paragraph' as const, text: `本篇已关联 ${input.characters.length} 位人物、${input.worlds?.length ?? 0} 个世界、${input.scenes?.length ?? 0} 个场景与 ${input.objects?.length ?? 0} 件物件；这些链接是下一轮实体和 Claim 审校的工作范围，而非已完成的编辑认证。` },
    ];

const story = (input: StoryInput): MythStory => ({
  id: `story-${input.slug}`,
  slug: input.slug,
  mythologyId,
  title: input.title,
  titleEn: input.titleEn,
  subtitle: input.subtitle,
  summary: input.summary,
  volumeId: input.volumeId,
  volumeTitle: input.volumeTitle,
  volumeOrder: input.volumeOrder,
  displayOrder: input.displayOrder,
  kind: input.kind ?? 'myth',
  legacySlugs: input.legacySlugs,
  tradition: input.tradition,
  readingMinutes: input.sections ? Math.max(3, Math.round(input.sections.flatMap((section) => section.paragraphs).join('').replace(/\s/g, '').length / 250)) : 4,
  sources: [sourceForStory(input)],
  sourceNotes: [
    `本篇以 ${sourceForStory(input).title} 为主要叙事依据；现存北欧材料多为中世纪记录，版本范围不被压缩为唯一正史。`,
    '故事、关系和视觉设计分别保留其来源范围；来源未统一的空间与身份不自动合并。',
  ],
  requiredCharacterIds: input.characters,
  requiredWorldIds: input.worlds ?? [],
  requiredSceneIds: input.scenes ?? [],
  requiredObjectIds: input.objects ?? [],
  requiredSourceIds: [sourceForStory(input).sourceId ?? sourceForStory(input).title],
  characterIds: input.characters,
  worldIds: input.worlds ?? [],
  sceneIds: input.scenes ?? [],
  objectIds: input.objects ?? [],
  claims: [{
    id: `claim-${input.slug}-narrative`,
    subjectType: 'story',
    subjectId: `story-${input.slug}`,
    claimType: 'narrative',
    summary: input.summary,
    status: 'supported',
    traditionScope: input.tradition,
    sourceRefs: [{ sourceId: sourceForStory(input).sourceId, type: 'primary-text', title: sourceForStory(input).title, locator: sourceForStory(input).locator ?? '按章节', language: sourceForStory(input).language }],
  }],
  blocks: storyBlocks(input),
  publishStatus: 'published',
  editorialStatus: input.editorialStatus ?? 'researching',
  publishedAt: date,
  updatedAt: date,
});

const c = (...ids: string[]) => ids.map((id) => `character-${id}`);
const w = (...ids: string[]) => ids.map((id) => `world-${id}`);
const s = (...ids: string[]) => ids.map((id) => `scene-${id}`);

type ResearchStoryInput = Omit<StoryInput, 'narrative' | 'sections' | 'editorialStatus'> & { focus: string };

/** A source-scoped editorial draft; it intentionally remains below source-reviewed. */
const researchStory = ({ focus, ...input }: ResearchStoryInput): MythStory => story({
  ...input,
  narrative: focus,
  editorialStatus: 'structured',
  sections: [
    { id: 'source-event', heading: '文本中的事件与人物', paragraphs: [focus] },
    { id: 'reading-scope', heading: '来源范围与后续阅读', paragraphs: [`本篇目前只依据 ${input.source.title}（${input.source.locator ?? '待补 locator'}）建立阅读入口。平行版本、解释争议和未被该来源支持的视觉细节不能作为既定事实呈现。`, '正文已具备可审阅的结构和来源链接，但仍需具名人工编辑核对人物、关系与叙事细节后，才能进入 source-reviewed。'] },
  ],
});

export const norseStories: readonly MythStory[] = [
  story({ slug: 'ymir-creation', title: '尤弥尔与世界的诞生', titleEn: 'Ymir and the Making of the World', subtitle: '冰与火之间诞生的巨人', summary: '寒冷与火焰在金伦加鸿沟相遇，尤弥尔出现，北欧宇宙的材料由此展开。', volumeId: 'norse-origins', volumeTitle: '创世与宇宙结构', volumeOrder: 1, displayOrder: 1, source: storySource('proseEddaGylfaginning', 'chs. 4–8'), tradition: '《欺骗古鲁菲》创世叙事范围', characters: c('ymir'), worlds: w('jotunheim', 'niflheim'), scenes: s('ginnungagap'), narrative: '金伦加鸿沟不是一座已经画好边界的地图，而是寒冷与热力相遇的原初间隙。尤弥尔的出现把巨人、冰霜和生成放进同一条宇宙叙事。', editorialStatus: 'structured', sections: [{ id: 'ginnungagap', heading: '鸿沟并非空无', paragraphs: ['《欺骗古鲁菲》把创世开端放在金伦加鸿沟：北方的尼福尔海姆与南方的穆斯贝尔海姆并列，冰霜与热力在中间相遇。它不是后世地图上已被划定的一国，而是世界尚未稳定时的原初间隙。', '当霜气受热融化，叙事让生命从物质变化中显现。这里的“诞生”不等于由一位全能造物者凭空制造；文本更强调冰、热、流动与凝结如何先构成可被讲述的宇宙材料。'] }, { id: 'ymir-appears', heading: '尤弥尔与原初生命', paragraphs: ['尤弥尔在这一叙事中首先是原初巨人，而不是后来故事里某一族群的普通成员。其出现使巨人谱系与宇宙的起始材料相连，也解释了为何后续故事会把巨人放进诸神秩序之外、却又无法与它切断的历史。', '同一章节还让奥德胡姆拉为尤弥尔提供乳汁。两者并置，不应被现代读者简化成“怪物与牲畜”：牛、冰、盐与巨人共同构成世界生成之初的生命图景。'] }, { id: 'reader-note', heading: '阅读这一创世片段', paragraphs: ['本篇只说明《欺骗古鲁菲》组织创世材料的方式，并不把中世纪冰岛散文当作唯一或不变的“北欧圣典”。诗歌与散文中关于起源、神族与世界结构的重点并不总是相同。', '接下来的奥德胡姆拉与布里、以及尤弥尔之躯化为世界，会分别展开祖先谱系和宇宙材料的两个问题。人物、地点与来源链接保留为独立入口，方便读者回到具体证据范围。'] }] }),
  story({ slug: 'audhumla-and-buri', title: '奥德胡姆拉与布里的出现', titleEn: 'Auðumbla and the Emergence of Búri', subtitle: '冰霜中显现的祖先', summary: '原初的牛奥德胡姆拉舔开咸冰，使布里从冰中显现。', volumeId: 'norse-origins', volumeTitle: '创世与宇宙结构', volumeOrder: 1, displayOrder: 2, source: storySource('proseEddaGylfaginning', 'ch. 6'), tradition: '《欺骗古鲁菲》创世叙事范围', characters: c('buri', 'ymir'), worlds: w('niflheim'), scenes: s('ginnungagap'), narrative: '奥德胡姆拉以冰与盐为食，舔开冰层后显现出布里。这个片段将神族祖先放在寒冷物质与原初生命的交界上。', editorialStatus: 'structured', sections: [{ id: 'nourishing-ymir', heading: '原初之牛的乳汁', paragraphs: ['在《欺骗古鲁菲》第六章，奥德胡姆拉从冰块中取食，同时以四条乳流哺养尤弥尔。文本用这种极具体的身体意象，让原初生命并非抽象概念：巨人的存续依赖可被描述的滋养。', '这段材料没有把牛写成后世牧场中的动物，也没有赋予她独立的人格化冒险。她的作用是把冰霜环境、盐分与生命来源连在一起，因此适合作为创世结构中的关键对象，而非普通背景。'] }, { id: 'buri-emerges', heading: '从咸冰中显现的布里', paragraphs: ['奥德胡姆拉舔食带盐的冰块，第一日显出头发，第二日显出头，第三日显出完整男子；这名男子就是布里。叙事的节奏刻意缓慢，祖先不是从无到有地突然出现，而是逐日从冰中显形。', '布里后来成为博尔之父，进而连到奥丁、威利与维的谱系。这里仅记录该散文叙事中的谱系位置；它不要求读者把所有神祇的来源压缩成一张没有版本差异的家谱。'] }, { id: 'source-scope', heading: '来源与后续关系', paragraphs: ['本篇的主要依据限定为《欺骗古鲁菲》第六章。它与尤弥尔的出现同在创世段落中，却服务于不同的叙事问题：前者解释原初巨人的生存，后者引出后来神族祖先。', '布里的视觉或人物设计若进入后续资产制作，应以“冰中显现的祖先”这一来源可支持的锚点为基础，不能据此虚构一套固定盔甲、年龄或现代奇幻阵营设定。'] }] }),
  story({ slug: 'odin-creates-world', title: '奥丁兄弟以尤弥尔之躯创造世界', titleEn: 'Odin and His Brothers Shape the World', subtitle: '巨人的身体成为宇宙材料', summary: '奥丁、威利与维以尤弥尔之躯塑造大地、海洋与天空。', volumeId: 'norse-origins', volumeTitle: '创世与宇宙结构', volumeOrder: 1, displayOrder: 3, source: storySource('proseEddaGylfaginning', 'ch. 8'), tradition: '《欺骗古鲁菲》创世叙事范围', characters: c('odin', 'vili', 've', 'ymir'), worlds: w('midgard', 'asgard'), scenes: s('ginnungagap'), narrative: '尤弥尔的身体被重新组织为山、海、天空与边界。创世在这里不是凭空制造，而是把原初巨人的材料转化为可以居住和穿行的世界。', editorialStatus: 'structured', sections: [{ id: 'slaying-ymir', heading: '杀死原初巨人', paragraphs: ['第八章叙述博尔之子奥丁、威利与维杀死尤弥尔。巨人死后流出的血造成洪水，除贝尔格尔密尔及其妻乘船逃出外，霜巨人几近覆灭；这是一则与巨人谱系有关的散文解释，而不是可任意套用的地质史。', '叙事将暴力置于宇宙秩序形成之前：新世界并不是在无代价的宁静中建立，诸神的可居住空间以原初存在的死亡为条件。读者可在人物关系中继续查看这一冲突的来源范围。'] }, { id: 'body-as-material', heading: '身体成为大地、海与天', paragraphs: ['在这一版本中，尤弥尔的肉成为大地，血成为海与湖，骨头和牙齿成为山石，头盖骨被安置为天空。文本逐项列举材料转化，强调世界由既有身体重新组织，而非一句概括性的“创造”。', '神祇又把火焰的火星安置在天空中，形成日、月与星辰的框架。该段与日月追逐者的诗歌传统有关联，但本篇不把不同文本中的天象细节混作同一直接引文。'] }, { id: 'midgard-boundary', heading: '米德加尔特是一道边界', paragraphs: ['散文还说诸神以尤弥尔的睫毛造出围绕人类居所的防护。米德加尔特因此不仅是“人间”的名称，也包含被围起、可居住、与外部相区隔的空间逻辑。', '阿斯加德、米德加尔特和巨人世界在不同材料中并非总能化成固定坐标。本篇保留《欺骗古鲁菲》第八章的叙事范围；页面中的世界关联是阅读路径，不将它伪装成无争议的古代地图。'] }] }),
  story({ slug: 'ask-and-embla', title: '阿斯克与恩布拉', titleEn: 'Ask and Embla', subtitle: '人类获得呼吸与意识', summary: '奥丁、威利与维赋予树木形体以生命，使人类进入世界。', volumeId: 'norse-origins', volumeTitle: '创世与宇宙结构', volumeOrder: 1, displayOrder: 4, source: storySource('voluspa', 'sts. 17–18'), tradition: '《女预言家之歌》人类起源段落', characters: c('odin', 'vili', 've'), worlds: w('midgard'), scenes: s('midgard-coast'), narrative: '阿斯克与恩布拉的故事把人类放在木材、呼吸和意识的交界。人类不是宇宙之外的旁观者，而是被置于米德加尔特的有限空间中。', editorialStatus: 'structured', sections: [{ id: 'found-without-fate', heading: '发现尚无命运的人', paragraphs: ['《女预言家之歌》第十七节说，三位“强大而仁慈的阿萨神”在陆地上发现阿斯克与恩布拉时，他们仍无命运。这一诗句的重点首先是人类尚未具备完整生命条件，而不是提供一套可以精确复原的现代生物学过程。', '诗中没有在这两节中点明三位神的姓名。后世解释常把他们联系到奥丁、海尼尔与洛德尔，或以散文传统中的奥丁、威利与维来叙述；本页沿用现有角色导航，但不把其中一种识别当作诗句唯一明说的事实。'] }, { id: 'gifts-of-life', heading: '气息、心智与外貌', paragraphs: ['第十八节依次写到三位神所给予的恩赐：气息与生命、心智与行动力、外貌、言语、听觉和色彩。其结构说明“成为人”不是单一瞬间，而是多种能力与感官被赋予。', '中文叙述以“生命、心智与感知”概括这些层次，不替换具体诗节。读者若需追踪翻译差异，可通过来源卡片返回诗节，而不是把页面摘要当作古诺尔斯语文本本身。'] }, { id: 'human-place', heading: '人类在宇宙中的位置', paragraphs: ['阿斯克与恩布拉被赋予生命后，故事把人类纳入已经出现的天地与天体秩序。米德加尔特在本项目中作为他们的阅读关联世界，表示人类居所的叙事位置，而非声明该诗节逐字命名这一地点。', '因此，人物关系、地理图与视觉设计各自有不同证据边界。创作人类起源场景时，应避免把诗歌的简洁叙述强行填成特定的王宫、服装或族群设定。'] }] }),
  story({ slug: 'yggdrasil-wells-norns', title: '世界树、三口井与诺恩', titleEn: 'Yggdrasil, the Wells and the Norns', subtitle: '命运在树根之间流动', summary: '世界树连接不同空间，井泉与诺恩使宇宙获得时间与命运的纵深。', volumeId: 'norse-origins', volumeTitle: '创世与宇宙结构', volumeOrder: 1, displayOrder: 5, source: storySource('grimnismal', 'sts. 29–35'), tradition: '《格里姆尼尔之歌》宇宙树段落', characters: c('odin', 'mimir'), worlds: w('asgard', 'niflheim'), scenes: s('world-tree-roots', 'well-of-mimir'), narrative: '世界树不是一张固定九界地图，而是一条把井泉、根系、道路与命运连接起来的宇宙轴。它允许同一世界被不同故事从不同方向进入。', editorialStatus: 'structured', sections: [{ id: 'tree-under-pressure', heading: '树并非静止的宇宙装饰', paragraphs: ['《格里姆尼尔之歌》第二十九至三十五节描述白蜡树伊格德拉西尔及其根部所承受的压力：鹿啃食枝叶、山羊取食树梢、尼德霍格啃噬根部，树上与树下的生命持续侵蚀它。', '因此，世界树不宜被制作成一棵永远完美无损、只为装点九界地图的巨树。诗歌强调的是负担、损耗与维系，正好为后续场景和关系提供更有张力的阅读入口。'] }, { id: 'wells-and-roots', heading: '井、根与知识', paragraphs: ['诗中一根通向霜巨人处，一根通向人类世界，另一根在海尔之下；密米尔泉与相关根系使世界树、知识与亡者空间相互靠近。不同文本对井与根的说明并不总以同一方式排列。', '本篇把“世界树与井”限定在《格里姆尼尔之歌》的诗歌范围。密米尔与奥丁之眼的故事应由单独页面说明，不能因为共享井名就把所有细节合并为同一次事件。'] }, { id: 'norns-split', heading: '诺恩需要独立阅读', paragraphs: ['诺恩在乌尔德之井旁塑造命运的著名说法主要见于《女预言家之歌》第二十节与散文转述，而非这一组《格里姆尼尔之歌》诗节。原有页面将世界树、井与诺恩合为一篇，适合导航却掩盖了来源边界。', '本阶段将该旧页保留为世界树与井的结构化故事；“诺恩与命运之井”列为独立 Story 待发布。这样既不删除读者已有入口，也不让单一标题承诺超出所列来源的内容。'] }] }),
  story({ slug: 'norns-at-urdarbrunnr', title: '诺恩与命运之井', titleEn: 'The Norns at Urðarbrunnr', subtitle: '三位命运塑造者在井旁出现', summary: '乌尔德、薇尔丹蒂与斯库尔德在世界树旁决定人的命运，使时间与命运成为宇宙秩序的一部分。', volumeId: 'norse-origins', volumeTitle: '创世与宇宙结构', volumeOrder: 1, displayOrder: 6, source: storySource('voluspa', 'st. 20'), tradition: '《女预言家之歌》命运之井段落', characters: c('urd', 'verdandi', 'skuld'), worlds: w('asgard'), scenes: s('world-tree-roots'), narrative: '三位诺恩在世界树旁决定人类的命运。', editorialStatus: 'structured', sections: [{ id: 'three-norns', heading: '三位从水下而来者', paragraphs: ['《女预言家之歌》第二十节说，三位少女从树下的湖泊而来；她们被称为乌尔德、薇尔丹蒂和斯库尔德。诗句把她们放在世界树附近，但没有要求读者将其理解为一套可以机械化计算的命运机关。', '三个名字常被现代读者对应为过去、正在发生与应当发生等时间词。这样的解释有助于入门，却不应遮蔽诗句本身的简洁性；本页以名字和文本中的行动为优先，保留解释的边界。'] }, { id: 'they-shaped-lives', heading: '她们为人塑造生命', paragraphs: ['诗歌接着说，三位诺恩“为人立法、选择生命、宣告命运”。这里的行动同时关乎秩序与个体生命，说明命运不是遥远的抽象背景，而是人类存在被安排进宇宙结构的方式。', '页面将这一点写为叙事概述，不添加诗节没有明确说明的织布工具、服装颜色或预言仪式。未来视觉设计可以使用井、水面与刻痕等原创锚点，但应标明其为 MythCanvas 解释。'] }, { id: 'scope-and-links', heading: '与世界树故事的分界', paragraphs: ['世界树与诺恩经常在现代百科或改编中同框，然而本项目将二者拆成独立 Story：前者主要阅读《格里姆尼尔之歌》的根、井和树；本篇只处理《女预言家之歌》第二十节的三位诺恩。', '这种拆分让来源卡、角色页与未来系列都能保持精确。读者仍可从世界树场景抵达这篇故事，但不会因此误以为所有相关细节都出自同一段古代文本。'] }] }),
  story({ slug: 'sun-and-moon-chase', title: '日月运行与追逐者', titleEn: 'The Sun, the Moon and Their Pursuers', subtitle: '天体在追逐中运行', summary: '日月的运行被写成持续的追逐，预示秩序终将面临断裂。', volumeId: 'norse-origins', volumeTitle: '创世与宇宙结构', volumeOrder: 1, displayOrder: 7, source: storySource('voluspa', 'sts. 5, 40–41'), tradition: '《女预言家之歌》天体与末日预兆段落', characters: c('sol', 'mani', 'skoll', 'hati'), worlds: w('midgard'), scenes: s('world-tree-roots'), narrative: '日月并非静止悬挂在天空，而在追逐与被追逐的节奏中运行。天象因此成为命运压力的可见形式。', editorialStatus: 'structured', sections: [{ id: 'ordered-sky', heading: '天体获得运行秩序', paragraphs: ['《女预言家之歌》第五节将太阳放在南方厅堂，众星知晓自己的位置，新月也知道其力量。诗歌用“知道”来描述天体秩序，使日月星辰不仅是物体，也构成可被预言打破的宇宙节律。', '这并不等于诗歌给出了完整的天文学系统。页面把它作为创世循环中的天象段落，帮助读者理解为何后面“狼吞日月”的意象会被视为秩序的瓦解。'] }, { id: 'pursuers', heading: '追逐者与狼后代', paragraphs: ['第四十至四十一节写到一位女巨人在铁森林中养育狼后代，其中一只将吞食月亮；另有“月之掠夺者”以死者之血染红诸天。翻译与注释中对具体狼名的对应并不总完全一致。', '斯库尔与哈提的具体命名依《欺骗古鲁菲》第十二章另作来源链接；它补充追逐日月的狼名，但不将散文补充伪装成《女预言家之歌》原句。'] }, { id: 'ragnarok-connection', heading: '从日常运行到末日征兆', paragraphs: ['日月的追逐使末日并非只在战场开始。它先在每天可见的天空中持续发生：秩序运行得越稳定，追逐者的存在越像一项被延后的威胁。', '本篇仅处理《女预言家之歌》所给出的预兆与图像。芬布尔之冬、束缚崩解和诸神黄昏的战斗另有独立故事；把它们放在同一时间线中阅读，不等于把所有诗句说成一次连续的散文记录。'] }] }),
  story({ slug: 'aesir-vanir-war', title: '阿萨神族与华纳神族的冲突与和解', titleEn: 'The War and Truce of Aesir and Vanir', subtitle: '两个神族重新安排秩序', summary: '阿萨与华纳之间的冲突最终通过交换与共同居住得到缓和。', volumeId: 'norse-order', volumeTitle: '神族秩序与知识', volumeOrder: 2, displayOrder: 1, source: sources.poetic, tradition: '阿萨—华纳传统', characters: c('odin', 'freyja', 'freyr', 'njordr'), worlds: w('asgard', 'vanaheim'), scenes: s('asgard-court'), narrative: '阿萨与华纳的冲突并不只是阵营战斗，它也关乎不同神圣能力如何进入同一秩序。交换人质与共同生活让两个传统彼此改写。' }),
  story({ slug: 'kvasir-and-mead', title: '克瓦希尔与诗歌蜜酒', titleEn: 'Kvasir and the Mead of Poetry', subtitle: '知识被酿成可以争夺的液体', summary: '克瓦希尔的智慧与诗歌蜜酒把知识、语言和盗取联系在一起。', volumeId: 'norse-order', volumeTitle: '神族秩序与知识', volumeOrder: 2, displayOrder: 2, source: storySource('proseEddaSkaldskaparmal', 'ch. 1'), tradition: '《诗语法》诗歌蜜酒叙事范围', characters: c('kvasir', 'odin'), worlds: w('asgard'), scenes: s('asgard-court'), objects: ['object-norse-mead-of-poetry'], narrative: '诗歌蜜酒把智慧变成需要寻找、守护和夺取的资源。', editorialStatus: 'structured', sections: [{ id: 'truce-and-kvasir', heading: '和约之后的克瓦希尔', paragraphs: ['《诗语法》第一章把克瓦希尔放在阿萨与华纳和解之后：双方把唾液吐入同一器皿，由此形成一位极具智慧的人物。它是斯诺里散文中对和约与知识来源的组织方式，不能替代所有诗歌对两族关系的表述。', '克瓦希尔周游各地回答问题，叙事先建立他的智慧，再让读者看见这种智慧如何被暴力和利益转化。页面以人物和来源卡保留这一顺序，而不是把“蜜酒”直接当作无来由的魔法饮品。'] }, { id: 'blood-and-brew', heading: '血被酿成诗歌蜜酒', paragraphs: ['两名侏儒杀死克瓦希尔，将他的血与蜂蜜混合，酿成使饮者成为诗人或学者的蜜酒。故事并未把知识写成纯洁、无代价的礼物：它能被保存、索取、争夺，也带着死亡与欺骗的痕迹。', '本项目把蜜酒单独建模为物件，使克瓦希尔、奥丁和后续的夺取故事可以各自引用同一来源，而不需要把复杂链条压扁为一张人物关系图。'] }, { id: 'later-odin', heading: '奥丁的盗取属于后续一篇', paragraphs: ['第一章后半段还通向蜜酒被巨人保存、奥丁以伪装取得的故事。但“克瓦希尔被杀、蜜酒被酿成”与“奥丁夺取蜜酒”是不同的叙事阶段，适合分成相邻 Story 阅读。', '本篇不把奥丁表现为克瓦希尔死亡的直接施动者。这样可以让读者先理解蜜酒的来源，再进入伪装、交换和飞行等后续情节。'] }] }),
  story({ slug: 'odin-and-mimir', title: '奥丁以一只眼换取智慧', titleEn: 'Odin and Mímir’s Well', subtitle: '知识总有可见的代价', summary: '奥丁在密米尔之井前付出一只眼，以换取洞察力。', volumeId: 'norse-order', volumeTitle: '神族秩序与知识', volumeOrder: 2, displayOrder: 3, source: storySource('voluspa', 'st. 28'), tradition: '《女预言家之歌》密米尔之井段落', characters: c('odin', 'mimir'), worlds: w('asgard'), scenes: s('well-of-mimir'), narrative: '奥丁的智慧不是无条件赠礼。他在井边留下身体的一部分，显示知识、牺牲与王权之间的紧张关系。', editorialStatus: 'structured', sections: [{ id: 'well-and-hostage', heading: '井边的抵押物', paragraphs: ['《女预言家之歌》第二十八节让预言者看见奥丁的眼睛被藏在密米尔的井中，密米尔每天清晨从那里饮蜜酒。诗句给出的是一幅井、眼睛和饮用的图像，而不是一段完整的交易对白。', '读者常把它概括成“奥丁用一眼换智慧”。这一概括适合作为导航标题，但正文应保留诗歌的表达边界：我们知道眼睛在井中、密米尔从中饮用，却不把未明说的谈判细节写成古代原文。'] }, { id: 'knowledge-with-cost', heading: '知识带有可见的代价', paragraphs: ['眼睛并未简单消失，而是留在知识之井旁。这个意象使奥丁的求知不只是抽象属性，也表现为身体上的缺失、记忆与持续的关联。MythCanvas 的人物设计可用独眼和井水作为来源锚点，但不能由此推断一套固定的现代奇幻装备。', '密米尔在此处是井与知识图像中的关键人物。其他文本中的密米尔头颅、奥丁咨询等材料具有不同来源范围，不应在这篇页面中自动叠加。'] }, { id: 'poetic-scope', heading: '一节诗歌的阅读尺度', paragraphs: ['本篇主要依据一节诗歌，因此不以长篇小说式细节填补沉默。它提供的是理解奥丁知识主题的明确窗口，也提醒读者北欧材料常由简洁诗句和后来的散文解释共同构成。', '世界树、诺恩和奥丁的悬挂自我牺牲各有单独故事与来源。将它们并置探索可以形成“知识与代价”的线索，但不等于它们发生在同一地点或同一次仪式。'] }] }),
  story({ slug: 'odin-world-tree', title: '奥丁悬于世界树九夜', titleEn: 'Odin on the World Tree', subtitle: '以牺牲换取符文知识', summary: '《高者之歌》中的说话者讲述自己被长矛刺伤、悬在树上九夜，终于取到符文。', volumeId: 'norse-order', volumeTitle: '神族秩序与知识', volumeOrder: 2, displayOrder: 4, source: storySource('havamal', 'sts. 138–141'), tradition: '《高者之歌》九夜与符文段落', characters: c('odin'), worlds: w('asgard'), scenes: s('world-tree-roots'), narrative: '奥丁把自己悬在世界树上，既是求知者，也是知识仪式的参与者。符文在这里不是装饰性的发光字样，而是经过代价获得的能力。', editorialStatus: 'structured', sections: [{ id: 'nine-nights', heading: '九夜的自我献祭', paragraphs: ['《高者之歌》138 节以第一人称叙述：说话者被风吹拂的树吊着九个长夜，被长矛刺伤，并且“献给奥丁、我自己献给我自己”。诗句没有在此处替树命名，也没有展开一段完整的树木地理；把它直接等同于《欺骗古鲁菲》中带有根、井与居民的宇宙树，是后续读法而非这几节诗本身的明示。', '这段话把获得知识写成一种自我施加、无人供食饮的极限状态。它并不是关于“奥丁发现了魔法道具”的轻快传说；身体受创、孤悬与等待共同构成知识出现的条件。'] }, { id: 'runes', heading: '符文从何处被取到', paragraphs: ['第 139 节说说话者向下凝望、呼喊，随后“取起符文”，并倒下。诗在这里强调获得的动作和结果，却没有给出一套可据以复原历史字母表或固定仪式流程的说明。页面中的符文只应作为文本中的知识与能力意象，不应被包装成无来源的神秘科技。', '后续诗节把歌咒、知识与人与人之间的交换并列。因而本篇关注的是诗歌中“代价—领悟—言说”的结构；米米尔之井、失去一只眼等另一来源范围内的奥丁知识叙事会保持独立链接。'] }, { id: 'reading-scope', heading: '来源范围与视觉边界', paragraphs: ['本篇依据《高者之歌》138–141 节，采用“传统上与奥丁相连的第一人称说话者”这一谨慎表述。关于说话者是否、以及如何完全等同奥丁，现代释读会讨论；读者页不把解释争议消去，也不将每一条相关叙事拼成单一传记。', '若制作关键场景，稳定锚点是悬挂、长矛、九夜、无食无饮与向下凝望；树的具体形制、服饰和光线属于 MythCanvas 原创设计，必须与来源事实分层记录。'] }] }),
  story({ slug: 'freyr-and-gerdr', legacySlugs: ['freyja-and-gerdr'], title: '弗雷与葛德', titleEn: 'Freyr and Gerðr', subtitle: '丰饶神对巨人庭院的凝望', summary: '弗雷爱上葛德，并派遣斯基尔尼尔穿过边界向她求婚。', volumeId: 'norse-order', volumeTitle: '神族秩序与知识', volumeOrder: 2, displayOrder: 5, source: storySource('skirnismal', 'sts. 1–42'), tradition: '《斯基尔尼尔之歌》传统', characters: c('freyr', 'gerdr', 'skirnir'), worlds: w('vanaheim', 'jotunheim'), scenes: s('jotunheim-border'), objects: ['object-norse-freyrs-sword'], narrative: '弗雷与葛德的故事把爱慕、交换、威胁和跨越边界放在同一个谈判过程中。', editorialStatus: 'structured', sections: [{ id: 'freyrs-silence', heading: '弗雷的沉默与斯基尔尼尔的出发', paragraphs: ['《斯基尔尼尔之歌》开头并不立刻描写求婚，而是让弗雷坐在奥丁的高座上望向约顿海姆，随后因看见葛德而陷入沉默。斯基尔尼尔察觉主人的痛苦，被要求前去询问原因。', '这一设置使故事的行动者不止弗雷与葛德。斯基尔尼尔承担谈判、穿越边界和传递言语的职责；将他删成无名使者，会遮蔽诗歌中的实际叙事结构。'] }, { id: 'gifts-and-threats', heading: '赠礼、拒绝与威胁', paragraphs: ['斯基尔尼尔先提出黄金与其他赠礼，葛德拒绝。随后诗歌转向威胁、诅咒与孤立的言辞，葛德最终答应在巴里林地相会。文本并未把这一过程写成无条件的浪漫互许。', '本页不以“爱情征服”美化强迫性的语言，也不把葛德化作弗雷丰饶属性的附属物。她拥有庭院、家族和拒绝的声音；读者应能看到求婚叙事中权力差异与跨越边界的压力。'] }, { id: 'sword-and-later-cost', heading: '弗雷之剑与后续代价', paragraphs: ['斯基尔尼尔为完成旅程取得弗雷之剑，剑在后来的诸神黄昏叙事中成为弗雷失去的关键物件。这里应将它理解为诗歌中的交换条件与故事连接点，而不应把它演成现代奇幻武器任务。', '《斯基尔尼尔之歌》主要给出求婚与承诺；弗雷在末日与苏尔特的结局来自其他来源范围。页面通过物件链接提示后续阅读，但不把两种材料混写成同一首诗所述的连续结局。'] }] }),
  story({ slug: 'idunn-and-thjazi', title: '伊登被夏基掳走', titleEn: 'Iðunn and Þjazi', subtitle: '青春苹果离开神域', summary: '伊登与青春苹果被带离阿斯加德，诸神的衰老暴露了宝物的秩序作用。', volumeId: 'norse-order', volumeTitle: '神族秩序与知识', volumeOrder: 2, displayOrder: 6, source: storySource('haustlong', 'sts. 1–13'), tradition: '《秋长诗》伊登与夏基叙事范围', characters: c('idunn', 'loki', 'thjazi'), worlds: w('asgard', 'jotunheim'), scenes: s('asgard-court', 'jotunheim-border'), objects: ['object-norse-idunn-apples'], narrative: '青春苹果不是普通道具。伊登离开后，诸神的身体和秩序开始衰老。', editorialStatus: 'structured', sections: [{ id: 'journey-and-eagle', heading: '旅程、饥饿与鹰形巨人', paragraphs: ['《秋长诗》以奥丁、海尼尔与洛基旅行时无法煮熟牛肉开场。巨大的鹰要求分享食物，洛基试图用棍子攻击它，棍子却黏在鹰身上，洛基被拖入空中。', '诗歌随后将鹰表明为夏基。这个开端让伊登被带走并不是孤立绑架事件，而是洛基在旅程中的冲突、承诺和被迫让步所引出的后果。'] }, { id: 'idunn-leaves', heading: '伊登与苹果离开神域', paragraphs: ['为脱身，洛基答应把伊登及其苹果带出阿斯加德。伊登离开后，诸神开始衰老；苹果的叙事作用因此不是“回血道具”，而是维系神族青春与共同体稳定的关键条件。', '本页将苹果作为独立物件链接，避免把伊登的身份缩减为一篮可被转移的物品。她的离开改变的是整个神域的身体状态与秩序，而非只提供一场追逐的理由。'] }, { id: 'return-and-boundary', heading: '归还并不抹去责任', paragraphs: ['诸神迫使洛基前去带回伊登，夏基追至阿斯加德边缘后被杀。不同材料对于变形与追逐的描写层次不同；本篇以《秋长诗》第一至十三节为主，不把后世所有补充当作同一首诗的细节。', '洛基在这里既不是单一的恶人标签，也不能免除他先前承诺的责任。故事通过旅程、胁迫与归还展示神族秩序如何依赖关系网络，而不是由固定阵营自动维持。'] }] }),
  story({ slug: 'odin-steals-mead', title: '奥丁夺取诗歌蜜酒', titleEn: 'Odin Steals the Mead of Poetry', subtitle: '知识通过伪装、交换与飞行易手', summary: '奥丁以伪名进入苏通的山中，饮尽诗歌蜜酒，化作鹰飞回阿斯加德。', volumeId: 'norse-order', volumeTitle: '神族秩序与知识', volumeOrder: 2, displayOrder: 6, source: storySource('proseEddaSkaldskaparmal', 'ch. 1'), tradition: '《诗语法》诗歌蜜酒夺取段落', characters: c('odin'), worlds: w('asgard', 'jotunheim'), scenes: s('jotunheim-border'), objects: ['object-norse-mead-of-poetry'], narrative: '奥丁通过劳动、伪名与变形进入守护蜜酒的山中，将诗歌能力带回诸神之地。', editorialStatus: 'structured', sections: [{ id: 'baugi', heading: '以博尔维尔克之名进入山中', paragraphs: ['《诗语法》第一章把蜜酒的去向接在克瓦希尔死亡之后：侏儒将它交给巨人苏通，苏通把蜜酒藏在山中，由女儿贡勒德看守。奥丁以“博尔维尔克”之名来到苏通之弟鲍吉处，提出替他完成劳作以换取一口蜜酒。', '这不是一条只靠力量夺宝的直线叙事。奥丁先介入农事与兄弟间的利益，又在鲍吉无法兑现承诺时要求进入岩山；伪名、交易和劳动构成进入守卫空间的不同层次。'] }, { id: 'gunnlod', heading: '三夜与三口饮尽', paragraphs: ['奥丁用钻子开出通道，变作蛇进入山中，并与贡勒德相处三夜。作为回报，他每夜获准饮一口蜜酒；叙事说他每口都喝尽一个容器，因而饮完全部蜜酒。此处涉及承诺、诱骗与不对等权力，页面不将其改写为无摩擦的浪漫相遇。', '诗歌蜜酒在这段散文中是可被储藏、分配和盗取的知识性物件。它与克瓦希尔的血有关，但奥丁并非该蜜酒最初被酿造时的直接参与者；两篇 Story 以物件连接，而不混成同一事件。'] }, { id: 'eagle', heading: '飞回阿斯加德的诗', paragraphs: ['奥丁化作鹰飞回阿斯加德，苏通也化作鹰追赶。诸神备好容器，奥丁吐出蜜酒；散文还解释，有一部分在追逐中落到人间，成为“劣诗人的份额”。这是斯诺里关于诗歌来源的叙事性解释，不是对现实文学才能的分类。', '本篇限定在《诗语法》第一章。视觉锚点可采用山中容器、钻孔、鹰形与追逐，但贡勒德、苏通和具体山景的设计须注明来源未规定的原创部分。'] }] }),
  story({ slug: 'skadi-compensation', title: '斯卡蒂的赔偿', titleEn: 'Skaði’s Compensation', subtitle: '巨人的女儿走进诸神的议庭', summary: '夏基被杀后，女儿斯卡蒂来到阿斯加德索取赔偿；诸神以选夫、逗笑和星辰回应。', volumeId: 'norse-order', volumeTitle: '神族秩序与知识', volumeOrder: 2, displayOrder: 9, source: storySource('proseEddaGylfaginning', 'ch. 23'), tradition: '《欺骗古鲁菲》斯卡蒂赔偿段落', characters: c('skadi', 'njordr'), worlds: w('asgard', 'jotunheim'), scenes: s('asgard-court'), narrative: '斯卡蒂为父亲夏基之死而来，诸神的赔偿将复仇、婚姻与难以消除的身份差异并置。', editorialStatus: 'structured', sections: [{ id: 'claim', heading: '带着武器来到阿斯加德', paragraphs: ['《欺骗古鲁菲》第二十三章中，夏基的女儿斯卡蒂披甲持武来到阿斯加德，要求为父亲被杀得到赔偿。她不是偶然进入神域的旁观者，而是以明确的亲属损失和诉求进入谈判。', '诸神提出三项补偿：她可从诸神中选择夫婿，但只能看脚；诸神必须让她发笑；奥丁把夏基的眼睛抛上天成为星辰。文本把这三件事并列，既未抹去杀父的暴力，也没有给出一种完全对等的和解。'] }, { id: 'choice', heading: '只看脚的选择', paragraphs: ['斯卡蒂以为最洁净的一双脚会属于巴德尔，于是选择了尼约德。这个选择由被限制的信息导致，叙事随后才让读者看见她的山地生活与尼约德的海边居所并不相合。', '“只能看脚”是该散文故事的关键条件，不宜把它删成一次自由、全面的爱情选择。它也不能说明斯卡蒂的意志不存在：她先提出赔偿，之后仍会对生活地点表达明确偏好。'] }, { id: 'scope', heading: '赔偿并不等于关系终结', paragraphs: ['洛基把一只山羊系在自己身上，二者的拉扯使斯卡蒂发笑；奥丁将夏基之眼置于天上。此处的滑稽与星辰并不把父亲之死变成轻松插曲，而显示补偿由仪式、戏剧与权力共同完成。', '本篇聚焦第二十三章的赔偿顺序；尼约德与斯卡蒂后来居住安排的冲突分为下一篇。夏基与伊登的故事则应回到《秋长诗》与相应散文材料。'] }] }),
  story({ slug: 'njordr-and-skadi', title: '尼约德与斯卡蒂的婚姻', titleEn: 'Njörðr and Skaði', subtitle: '海岸与山地之间无法折中的居所', summary: '斯卡蒂选择尼约德为夫，但二人对山地与海岸的不同偏好使婚姻未能稳定。', volumeId: 'norse-order', volumeTitle: '神族秩序与知识', volumeOrder: 2, displayOrder: 10, source: storySource('proseEddaGylfaginning', 'ch. 23'), tradition: '《欺骗古鲁菲》尼约德与斯卡蒂段落', characters: c('njordr', 'skadi'), worlds: w('asgard', 'jotunheim'), scenes: s('jotunheim-border'), narrative: '尼约德与斯卡蒂尝试轮流住在海岸与山地，却发现每个人的声音、景观和生活节律都难以互换。', editorialStatus: 'structured', sections: [{ id: 'two-homes', heading: '诺阿通与斯里姆海姆', paragraphs: ['同一章节把尼约德与斯卡蒂的婚后冲突写成居所之争：尼约德来自海岸的诺阿通，斯卡蒂习惯父亲的山中斯里姆海姆。双方约定在对方居所各住九夜，希望用轮换解决差异。', '这里的“海”与“山”首先是叙事中人物生活经验的差异，而不是给两个世界贴上永久阵营标签。页面将诺阿通与斯里姆海姆作为来源中的地名/居所说明，不把它们自动扩写为可精确量化的九界行政区。'] }, { id: 'unhappy-nights', heading: '谁也无法习惯对方的夜晚', paragraphs: ['尼约德住山里后抱怨狼嚎、怀念海鸟；斯卡蒂住海边后抱怨海鸟鸣叫、想念山中。两段诗式引语对照地展示了他们不同的感官与依恋，冲突不靠某次大战爆发，而在日常夜晚逐渐显形。', '轮换没有达成共同生活的方案，散文说二人随后分开。将这段故事写成“异地恋失败”会过度现代化；它的重点是身份、居所与婚姻安排在神话叙事中的不相容。'] }, { id: 'after-marriage', heading: '将婚姻与赔偿分开阅读', paragraphs: ['斯卡蒂最初因索赔而进入阿斯加德，选择尼约德是赔偿的一部分；但婚后的居住试验具有自己的叙事节奏。拆为两篇 Story 后，读者能同时看到公共谈判与私人生活，而不把女性角色压缩为被安排的结局。', '本篇依据《欺骗古鲁菲》第二十三章。后来的谱系、配偶或崇拜信息若来自其他文本，须以独立来源处理；视觉设计也不应把“雪山猎手”或“海神”固化成现代版权作品的服装模板。'] }] }),
  story({ slug: 'asgard-wall-and-sleipnir', title: '阿斯加德城墙与斯莱普尼尔', titleEn: 'The Wall of Asgard and Sleipnir', subtitle: '一座城墙换来一匹跨界坐骑', summary: '一名建造者以太阳、月亮和芙蕾雅为报酬修筑城墙；洛基使其骏马偏离工程，斯莱普尼尔随后出生。', volumeId: 'norse-order', volumeTitle: '神族秩序与知识', volumeOrder: 2, displayOrder: 7, source: storySource('proseEddaGylfaginning', 'ch. 42'), tradition: '《欺骗古鲁菲》阿斯加德城墙叙事', characters: c('loki', 'sleipnir'), worlds: w('asgard', 'jotunheim'), scenes: s('asgard-court'), narrative: '阿斯加德城墙的建造暴露了神族对契约、时间和外部力量的依赖。洛基的变形最终带来斯莱普尼尔，也让边界不再只是石头。', editorialStatus: 'structured', sections: [{ id: 'bargain', heading: '报酬高得近乎不可能', paragraphs: ['《欺骗古鲁菲》第四十二章让一名未具名的建造者提出为诸神修筑堡垒，条件是一个冬季内完工，并以芙蕾雅、太阳和月亮为报酬。诸神在洛基的劝说下接受了条件，却限制建造者只能使用一匹马；这个决定把看似不可能的交易变成日后必须兑现的契约。', '建造者的骏马斯瓦迪尔法利搬运石料极快。工程接近完成时，诸神意识到失去太阳、月亮和芙蕾雅的后果，转而把责任推回提出建议的洛基。文本并不把这种处理描写成无代价的聪明，而明确点出洛基若不能阻止工程将遭到严惩。'] }, { id: 'distraction', heading: '变形改变了工程进度', paragraphs: ['洛基变成一匹母马，把斯瓦迪尔法利引离工地；建造者因此不能按时完成城墙。建造者盛怒，诸神这才认出他是山巨人，并由索尔以妙尔尼尔击杀。这一段的冲突来自交易、时间和边界，并不能被概括为所有巨人都天然欺骗或所有神都始终遵守约定。', '散文随后补述洛基生下一匹灰色八足马，即斯莱普尼尔，并称其为诸马之最、为奥丁所有。斯莱普尼尔的出生是这次干预的后果；他并非城墙本身，也不应在页面中被错误归为建造者的坐骑。'] }, { id: 'source-scope', heading: '同一叙事中的边界与责任', paragraphs: ['本篇只采用《欺骗古鲁菲》第四十二章的叙事次序。它记录的是一则中世纪散文中的城墙建造、变形与马匹来历，并不提供可精确绘制阿斯加德防御工事的建筑史。', '视觉设计可以强调未完石墙、冬日工期与奔离的马，但“八足”“奥丁坐骑”等稳定身份锚点必须来自本篇所述结果；建筑材料、镜头和角色服装则属于原创设计层。'] }] }),
  story({ slug: 'sifs-hair-and-treasures', title: '西芙的头发与诸神宝物', titleEn: 'Sif’s Hair and the Gods’ Treasures', subtitle: '失去的金色被重新锻造', summary: '洛基为被剪去头发的西芙寻求赔偿；两组矮人工匠竞作，产出金发、船、长矛、指环、野猪与妙尔尼尔。', volumeId: 'norse-order', volumeTitle: '神族秩序与知识', volumeOrder: 2, displayOrder: 8, source: storySource('proseEddaSkaldskaparmal', 'ch. 35'), tradition: '《诗语法》宝物锻造叙事', characters: c('sif', 'loki', 'odin', 'freyr', 'thor'), worlds: w('asgard'), scenes: s('asgard-court'), objects: ['object-norse-mjolnir', 'object-norse-skidbladnir', 'object-norse-draupnir'], narrative: '西芙的金发与宝物锻造把身体、赔偿、工艺和神权连在一起。宝物不是凭空出现，而是在冲突之后被工匠与契约制造出来。', editorialStatus: 'structured', sections: [{ id: 'repair', heading: '从剪发到赔偿', paragraphs: ['《诗语法》第三十五章开头说洛基剪去了索尔之妻西芙的头发。索尔威胁要折断洛基的每一根骨头，洛基于是前往黑侏儒处，请伊瓦尔第的儿子们制作能像真发一样生长的金发。这个开端把宝物置于一次明确的伤害与赔偿之后，而不是把它们当作无来由的装备清单。', '同一组工匠又制成斯基德布拉德尼尔船和贡格尼尔长矛。文本赋予它们可收纳、顺风与不落空等特性，但不提供现代游戏式的数值体系；页面将把功能、所属与来源章节分开呈现。'] }, { id: 'wager', heading: '两组工匠的赌赛', paragraphs: ['洛基以自己的头作赌注，向布洛克挑战：其兄辛德里能否作出同样珍贵的东西。洛基化作苍蝇干扰风箱，但辛德里仍完成金鬃野猪古林布尔斯蒂、会自行滴出同重金环的德劳普尼尔，以及锤柄较短的妙尔尼尔。短柄是叙事中与干扰相连的工艺结果，不是现代改编可以随意忽略的细节。', '诸神裁判将金发判给西芙、长矛判给奥丁、船与野猪判给弗雷、指环判给奥丁、妙尔尼尔判给索尔。洛基借“头不含颈”躲过斩首，却被缝住嘴唇；这不是单纯的奖励仪式，而是一次工艺、赌约和语言诡辩相互咬合的故事。'] }, { id: 'object-boundaries', heading: '宝物不是一套无差别神装', paragraphs: ['本篇依《诗语法》第三十五章叙述，将多件宝物置于同一竞作框架。它并不处理《欺骗古鲁菲》或诗歌材料中其他关于锤、船和指环的用法；同一物件在不同文本出现时，需要保留各自的来源范围。', '对视觉生产而言，西芙的可生长金发、可折叠的船、金鬃野猪、滴环和短柄雷锤可作为来源支撑的对象锚点；材质细节、场景和工坊美术则须另外标记为 MythCanvas 原创诠释。'] }] }),
  story({ slug: 'thor-and-hrungnir', title: '索尔与赫朗格尼尔', titleEn: 'Thor and Hrungnir', subtitle: '神与巨人的决斗', summary: '赫朗格尼尔与奥丁赛马后受邀入阿斯加德；醉酒的巨人挑战索尔，二者以锤与燧石搏斗。', volumeId: 'norse-thor', volumeTitle: '索尔、洛基与巨人', volumeOrder: 3, displayOrder: 1, source: storySource('proseEddaSkaldskaparmal', 'ch. 17'), tradition: '《诗语法》索尔与赫朗格尼尔叙事', characters: c('thor', 'hrungnir'), worlds: w('jotunheim', 'asgard'), scenes: s('jotunheim-border'), objects: ['object-norse-mjolnir'], narrative: '赫朗格尼尔代表约顿世界中不可被简单归类为冰雪怪物的力量。索尔的胜利依赖锤、身体和边界空间的共同作用。', editorialStatus: 'structured', sections: [{ id: 'horse-race', heading: '赛马后的不受欢迎客人', paragraphs: ['《诗语法》第十七章先讲奥丁骑斯莱普尼尔进入巨人之地，与赫朗格尼尔赛马。赫朗格尼尔追到阿斯加德门前后才停下，并获邀入厅饮酒；他的到来不是一次战场突袭，而是由竞赛、招待和越界共同推动。', '巨人饮下大量酒后夸口要搬走瓦尔哈拉、把阿斯加德沉进海里、杀死诸神，只留下芙蕾雅和西芙。诸神召来索尔；此时文本的冲突已从宾客礼遇转为威胁与挑战，不能简单归因于某个族群的天性。'] }, { id: 'duel', heading: '燧石、铁盾与妙尔尼尔', paragraphs: ['赫朗格尼尔约定在格里奥图纳石界与索尔决斗。巨人们造出泥人莫克尔卡尔菲相助，赫朗格尼尔自己有石心、石头的头和盾，并以燧石为武器；这是散文叙事对非常规身体与武器的描写，不等于可确证的历史宗教形象。', '索尔与夏尔菲抵达后，妙尔尼尔和燧石在空中相撞。锤击碎了赫朗格尼尔的头，燧石碎片却嵌入索尔头中；倒下的巨人一只脚压住索尔颈部。胜利并非无伤的碾压，索尔仍需要旁人解除身体上的危险。'] }, { id: 'aftermath', heading: '被压住的胜者', paragraphs: ['众神试图搬开巨人的脚都没有成功，年幼的马格尼来到后轻易移开，并说可惜没有早些到，否则能一拳杀死巨人。索尔把名为“金鬃”的马赠给马格尼，这一后果把决斗与亲属、赏赐相连。', '故事还说巫女格罗娅试图取出索尔头中的燧石，索尔用贝尔甘米尔相关往事逗她开心，反而使她忘了咒语。此处仅提示后续关联；赫朗格尼尔之死、碎石解释和格罗娅的叙事位置都应保持同一散文章节的限定。'] }] }),
  story({ slug: 'thor-fishes-for-serpent', title: '索尔垂钓世界蛇', titleEn: 'Thor Fishes for the World Serpent', subtitle: '海面下的宿敌', summary: '索尔与海米尔出海，以牛头为饵钓起世界蛇；海米尔割断钓线，巨蛇沉回海中。', volumeId: 'norse-thor', volumeTitle: '索尔、洛基与巨人', volumeOrder: 3, displayOrder: 2, source: storySource('hymiskvida', 'sts. 17–24'), tradition: '《海米尔之歌》垂钓段落', characters: c('thor', 'jormungandr', 'hymir'), worlds: w('midgard', 'jotunheim'), scenes: s('midgard-coast'), narrative: '索尔垂钓世界蛇的场景让海洋成为宿命关系的舞台。巨蛇不是一个普通怪兽，而是包围人类世界、与雷神形成结构性对抗的存在。', editorialStatus: 'structured', sections: [{ id: 'rowing-out', heading: '越过海米尔习惯的渔场', paragraphs: ['《海米尔之歌》中，索尔要求海米尔带他出海。海米尔担心他体力不支，索尔却先取走一头牛的头作鱼饵；两人划得比海米尔平常钓鱼的地方更远。诗将挑战设置在海的边缘，而不是明确的神界战场。', '牛头沉入深水后，环绕大地的巨蛇咬钩。索尔使双脚顶住船底、拉起鱼线，蛇从海中抬头，毒液与威胁在水面上相对。文本用夸张的身体动作呈现冲突，却没有把这次相遇写成诸神黄昏的最终战。'] }, { id: 'cut-line', heading: '钓线被割断', paragraphs: ['海米尔看见世界蛇后害怕，割断钓线，蛇沉回海中。不同叙事与图像传统会强调索尔是否以锤击中蛇，但《海米尔之歌》这一段的叙事结果是蛇逃回深海；读者不应把后来的结局倒灌成此次垂钓已经杀死了它。', '诗中紧接着索尔把船带回岸边，随后故事转入大锅与巨人宅邸的情节。页面将垂钓、取锅和末日对决作为三个可区分的阅读节点，避免把同一首诗和不同散文版本压成一幅连续战斗图。'] }, { id: 'relation-scope', heading: '一次相遇与末日宿敌', paragraphs: ['本篇以《海米尔之歌》17–24 节为主。世界蛇与索尔在《女预言家之歌》的诸神黄昏段落还会再度相遇，但那是另一处来源与另一种叙事位置。', '视觉锚点可以是狭小船只、牛头鱼饵、拉紧的线和海面上升起的蛇首；不得把“被钓起”直接等同“已被杀死”，也不要用现代海怪设计替代其围绕人类世界的宇宙功能。'] }] }),
  story({ slug: 'thryms-stolen-hammer', title: '雷神之锤被盗', titleEn: 'The Theft of Mjölnir', subtitle: '神锤与伪装的新娘', summary: '巨人索列姆夺走索尔的锤子，洛基协助索尔伪装成新娘，在婚宴中取回武器。', volumeId: 'norse-thor', volumeTitle: '索尔、洛基与巨人', volumeOrder: 3, displayOrder: 3, source: storySource('thrymskvida', 'st. 1–32'), tradition: '《索列姆之歌》传统', characters: c('thor', 'loki', 'freyja', 'heimdall', 'thrymr'), worlds: w('jotunheim', 'asgard'), scenes: s('thryms-hall'), objects: ['object-norse-mjolnir'], narrative: '失去妙尔尼尔后，索尔的守护身份暂时失去支点。索列姆以芙蕾雅为交换条件，洛基则协助索尔伪装赴宴。故事以婚宴、服装与策略把武器归还变成一场公开的表演。' }),
  story({ slug: 'thor-in-utgard', title: '索尔在乌特加德', titleEn: 'Thor in Útgarða-Loki’s Hall', subtitle: '力量被幻象重新定义', summary: '索尔在巨人大厅中接受看似简单却被魔法改写的挑战。', volumeId: 'norse-thor', volumeTitle: '索尔、洛基与巨人', volumeOrder: 3, displayOrder: 4, source: sources.prose, tradition: '乌特加德传统', characters: c('thor', 'loki'), worlds: w('jotunheim'), scenes: s('jotunheim-border'), narrative: '乌特加德的挑战不是公平竞技，而是把海洋、老年和世界本身伪装成对手。索尔即使失败，也因此显露出力量的尺度。' }),
  story({ slug: 'thor-and-geirrod', title: '索尔与盖尔罗德', titleEn: 'Thor and Geirröðr', subtitle: '穿越巨人领地的危险旅程', summary: '索尔在洛基协助与意外装备下进入盖尔罗德的领地。', volumeId: 'norse-thor', volumeTitle: '索尔、洛基与巨人', volumeOrder: 3, displayOrder: 5, source: sources.skaldic, tradition: '索尔与巨人传统', characters: c('thor', 'loki'), worlds: w('jotunheim'), scenes: s('jotunheim-border'), narrative: '这段旅程把渡河、伪装、巨人厅堂和武器交给一个连续空间。索尔的力量始终需要通过道路与工具才能抵达冲突现场。' }),
  story({ slug: 'fenrir-and-gleipnir', title: '芬里尔与格莱普尼尔', titleEn: 'Fenrir and Gleipnir', subtitle: '一条看不见的束缚', summary: '诸神用格莱普尼尔束缚芬里尔，并由提尔付出一只手作为代价。', volumeId: 'norse-thor', volumeTitle: '索尔、洛基与巨人', volumeOrder: 3, displayOrder: 6, source: sources.prose, tradition: '芬里尔束缚传统', characters: c('fenrir', 'tyr', 'odin'), worlds: w('asgard', 'jotunheim'), scenes: s('asgard-court'), narrative: '格莱普尼尔由看似不可能的材料制成，芬里尔最终接受试探却不再相信诸神。提尔把手放入狼口，使契约的代价留在身体上。' }),
  story({ slug: 'lokis-feast', title: '洛基的宴席争辩', titleEn: 'Loki’s Flyting', subtitle: '宴席成为秩序的审判场', summary: '洛基在宴席中揭露诸神的秘密，语言冲突使共同体的裂缝公开化。', volumeId: 'norse-thor', volumeTitle: '索尔、洛基与巨人', volumeOrder: 3, displayOrder: 7, source: sources.poetic, tradition: '《洛基的争辩》传统', characters: c('loki', 'odin', 'thor', 'freyja', 'tyr'), worlds: w('asgard'), scenes: s('asgard-court'), narrative: '洛基的攻击不是普通吵架，而是把神族内部的债务、欲望和不体面历史重新带到公共宴席。秩序正是在被说出之后开始崩裂。' }),
  story({ slug: 'baldrs-dreams', title: '巴德尔的梦', titleEn: 'Baldr’s Dreams', subtitle: '死亡先以梦的形式到来', summary: '巴德尔反复梦见危险，诸神开始寻找梦境背后的死亡预兆。', volumeId: 'norse-baldr', volumeTitle: '巴德尔之死与秩序崩裂', volumeOrder: 4, displayOrder: 1, source: sources.poetic, tradition: '巴德尔循环', characters: c('baldr', 'odin', 'frigg'), worlds: w('asgard'), scenes: s('asgard-court'), narrative: '巴德尔的梦把末日提前写进神域日常。奥丁前往亡者道路寻找答案，预言由此成为无法轻易解除的压力。' }),
  story({ slug: 'baldrs-death', title: '巴德尔之死', titleEn: 'The Death of Baldr', subtitle: '一枝槲寄生穿过保护', summary: '弗丽嘉让万物保证不伤害巴德尔，却遗漏了槲寄生；洛基借霍德尔之手完成致命一击。', volumeId: 'norse-baldr', volumeTitle: '巴德尔之死与秩序崩裂', volumeOrder: 4, displayOrder: 2, source: sources.prose, tradition: '巴德尔之死传统', characters: c('baldr', 'frigg', 'loki', 'hodr'), worlds: w('asgard'), scenes: s('asgard-court'), narrative: '保护巴德尔的誓言制造出一种看似绝对的安全，却留下一个微小而致命的例外。洛基、霍德尔与槲寄生让神域的游戏转为真正的哀悼。' }),
  story({ slug: 'baldrs-funeral', title: '巴德尔的葬礼', titleEn: 'Baldr’s Funeral', subtitle: '葬船驶入无法挽回的悲剧', summary: '巴德尔被送上赫林霍尔尼葬船，诸神的秩序在仪式与哀悼中暴露出裂痕。', volumeId: 'norse-baldr', volumeTitle: '巴德尔之死与秩序崩裂', volumeOrder: 4, displayOrder: 3, source: storySource('proseEddaGylfaginning', 'ch. 49'), tradition: '《欺骗古鲁菲》葬礼传统', characters: c('baldr', 'odin', 'frigg', 'thor', 'nanna'), worlds: w('asgard', 'hel'), scenes: s('baldr-funeral-shore'), objects: ['object-norse-hringhorni'], narrative: '葬礼把巴德尔的死亡从个人事件变成整个神族共同体的损失。赫林霍尔尼、火焰与哭泣并没有自动带来复原，反而使之后的追寻更加迫切。纳吉尔法属于诸神黄昏的另一条末日叙事，不在此处出现。' }),
  story({ slug: 'hermod-rides-to-hel', title: '赫尔莫德前往赫尔', titleEn: 'Hermóðr Rides to Hel', subtitle: '穿过亡者道路的请求', summary: '赫尔莫德骑行前往海拉的国度，请求让巴德尔返回神域。', volumeId: 'norse-baldr', volumeTitle: '巴德尔之死与秩序崩裂', volumeOrder: 4, displayOrder: 4, source: sources.prose, tradition: '亡者道路传统', characters: c('hermod', 'baldr', 'hel'), worlds: w('asgard', 'hel'), scenes: s('hall-of-hel'), narrative: '赫尔莫德的旅程把 Hel 作为一个有道路、有统治者、有条件的空间，而不是把人物 Hel 与地点混为同一项。' }),
  story({ slug: 'loki-bound', title: '洛基被捕与束缚', titleEn: 'Loki Bound', subtitle: '毒液滴落在秩序裂缝上', summary: '洛基因巴德尔之死被捕并束缚，西格恩试图接住滴落的毒液。', volumeId: 'norse-baldr', volumeTitle: '巴德尔之死与秩序崩裂', volumeOrder: 4, displayOrder: 5, source: sources.prose, tradition: '洛基受缚传统', characters: c('loki', 'sigyn'), worlds: w('asgard'), scenes: s('world-tree-roots'), narrative: '洛基的束缚是惩罚，也是诸神试图把裂缝固定在一个身体上的行为。西格恩的碗让陪伴、疼痛与持续时间成为场景核心。' }),
  story({ slug: 'fimbulwinter', title: '芬布尔之冬与束缚崩解', titleEn: 'Fimbulwinter and the Breaking of Bonds', subtitle: '漫长冬季先于世界毁灭', summary: '芬布尔之冬、狼吞日月与束缚崩解共同预示诸神黄昏。', volumeId: 'norse-ragnarok', volumeTitle: '诸神黄昏与世界再生', volumeOrder: 5, displayOrder: 1, source: sources.poetic, tradition: '诸神黄昏传统', characters: c('fenrir', 'jormungandr', 'loki', 'odin'), worlds: w('midgard', 'jotunheim'), scenes: s('fimbulwinter-field'), narrative: '末日不是突然降临的一次爆炸，而是冬季、饥荒、冲突和束缚崩解逐步积累的过程。世界的尺度因此先通过天气和道路被感知。' }),
  story({ slug: 'odin-and-fenrir', title: '奥丁与芬里尔', titleEn: 'Odin and Fenrir', subtitle: '预言中的吞噬', summary: '诸神黄昏中芬里尔挣脱束缚并吞噬奥丁，复仇由维达尔完成。', volumeId: 'norse-ragnarok', volumeTitle: '诸神黄昏与世界再生', volumeOrder: 5, displayOrder: 2, source: sources.poetic, tradition: '诸神黄昏传统', characters: c('odin', 'fenrir', 'vidarr'), worlds: w('midgard', 'asgard'), scenes: s('fimbulwinter-field'), narrative: '奥丁与芬里尔的关系把早先的束缚、恐惧和预言推向结局。维达尔的存续并不是简单的胜利，而是旧秩序崩解后仍保留的反击能力。' }),
  story({ slug: 'thor-and-jormungandr-final-battle', title: '索尔与世界蛇的最后一战', titleEn: 'Thor and Jörmungandr at Ragnarök', subtitle: '宿敌在海与雷之间相遇', summary: '索尔击杀世界蛇，却在九步之后倒下，宿命关系以双重胜负结束。', volumeId: 'norse-ragnarok', volumeTitle: '诸神黄昏与世界再生', volumeOrder: 5, displayOrder: 3, source: sources.poetic, tradition: '诸神黄昏传统', characters: c('thor', 'jormungandr'), worlds: w('midgard'), scenes: s('midgard-coast'), narrative: '索尔与世界蛇的结局不适合用单纯胜负概括。雷神完成守护者的动作，却也承受巨蛇毒液，二者的故事在同一瞬间完成。' }),
  story({ slug: 'freyr-and-surtr', title: '弗雷与苏尔特', titleEn: 'Freyr and Surtr', subtitle: '丰饶神面对火焰边界', summary: '弗雷在诸神黄昏中面对苏尔特，失去武器的代价最终显现。', volumeId: 'norse-ragnarok', volumeTitle: '诸神黄昏与世界再生', volumeOrder: 5, displayOrder: 4, source: sources.poetic, tradition: '诸神黄昏传统', characters: c('freyr', 'surtr'), worlds: w('muspell', 'asgard'), scenes: s('muspell-flame-border'), narrative: '弗雷与苏尔特把丰饶、武器和火焰末日放进同一个对照。穆斯贝尔不是普通的红色背景，而是旧世界终结的力量边界。' }),
  story({ slug: 'heimdall-and-loki', title: '海姆达尔、洛基与加拉尔号角', titleEn: 'Heimdall, Loki and Gjallarhorn', subtitle: '号角吹响最后的警报', summary: '海姆达尔吹响号角，最终与洛基相遇并在战斗中同归于尽。', volumeId: 'norse-ragnarok', volumeTitle: '诸神黄昏与世界再生', volumeOrder: 5, displayOrder: 5, source: sources.poetic, tradition: '诸神黄昏传统', characters: c('heimdall', 'loki'), worlds: w('asgard'), scenes: s('bifrost'), narrative: '海姆达尔的号角把末日从隐约预兆转为公共事件。彩虹桥成为守望、通行和最后冲突同时发生的窄地。' }),
  story({ slug: 'ragnarok', title: '世界毁灭、回归与新生', titleEn: 'Destruction, Return and Renewal', subtitle: '火焰之后仍有世界', summary: '世界被火与海重塑，幸存者与归来的神祇重新开始生活。', volumeId: 'norse-ragnarok', volumeTitle: '诸神黄昏与世界再生', volumeOrder: 5, displayOrder: 6, source: storySource('voluspa', 'st. 54–66'), tradition: '《女预言家之歌》诸神黄昏与再生传统', characters: c('vidarr', 'baldr', 'hodr'), worlds: w('midgard', 'asgard'), scenes: s('renewed-earth'), objects: ['object-norse-naglfar'], narrative: '毁灭并不是北欧宇宙的唯一终点。火焰退去、土地重新显现，幸存者和归来的神祇让“再生”保留了损失之后的重量。弗雷在与苏尔特的冲突中倒下，不列入此处的幸存者。' }),
  story({ slug: 'volsung-and-sword-tree', title: '沃尔松格与树中神剑', titleEn: 'Völsung and the Sword-Tree', subtitle: '宴席上的陌生人留下了一把剑', summary: '西格尔德与西格妮的婚宴上，一名独眼陌生人将剑插入树中；只有西格蒙德能拔出它。', kind: 'heroic-legend', volumeId: 'norse-volsung', volumeTitle: '沃尔松格英雄传统', volumeOrder: 6, displayOrder: 1, source: storySource('volsungaSaga', 'chs. 2–3'), tradition: '《沃尔松格萨迦》沃尔松格家族前史', characters: c('volsung', 'sigmund'), worlds: w('midgard'), scenes: s('volsung-hall'), narrative: '树中之剑让沃尔松格家族的婚姻、待客、竞争与后续复仇从一场宴席开始缠绕。', editorialStatus: 'structured', sections: [{ id: 'feast', heading: '婚宴中的陌生人', paragraphs: ['《沃尔松格萨迦》第二至三章叙述国王沃尔松格的女儿西格妮嫁给西格盖尔。宴席上，一个戴斗篷、独眼的陌生人走入大厅，将一把剑插进厅中的大树，并宣称能拔出者便可拥有它。叙事不需要把陌生人所有身份解释都提前说尽，但这幅形象与后续家族命运紧密相连。', '宾客逐一尝试失败，西格蒙德拔出剑。西格盖尔愿以重金购买，西格蒙德拒绝；剑由此不只是武器，而成为婚姻结盟刚刚建立时就显出的竞争与敌意。'] }, { id: 'betrayal', heading: '礼物转为敌对的预兆', paragraphs: ['西格盖尔带西格妮与沃尔松格诸子回到自己的领地，并准备背叛他们。萨迦将剑、宴席和旅行安排为家庭灾难的前奏，而不是一条可独立收集的“英雄装备”任务。', '本篇只覆盖沃尔松格前史和树中之剑的出现。西格妮如何留在西格盖尔家中、西格蒙德如何幸存、以及复仇的伦理代价，将在后续独立 Story 中展开。'] }, { id: 'scope', heading: '英雄传统的起点', paragraphs: ['沃尔松格传统属于英雄传奇，而非诸神黄昏的直接续篇。人物可与奥丁形象发生叙事关联，但家族、婚姻和复仇的因果必须按《沃尔松格萨迦》的范围阅读。', '视觉锚点是大厅中的大树、插入树干的剑和宾客的失败尝试；任何王国徽章、盔甲体系或确定的时代建筑均属 MythCanvas 的原创诠释。'] }] }),
  story({ slug: 'signy-and-siggeir', title: '西格妮与西格盖尔', titleEn: 'Signý and Siggeir', subtitle: '幸存者与复仇被困在同一座王宫', summary: '西格盖尔背叛沃尔松格家族，西格妮留在仇敌身边，协助西格蒙德完成复仇。', kind: 'heroic-legend', volumeId: 'norse-volsung', volumeTitle: '沃尔松格英雄传统', volumeOrder: 6, displayOrder: 2, source: storySource('volsungaSaga', 'chs. 3–8'), tradition: '《沃尔松格萨迦》西格妮复仇段落', characters: c('signy', 'siggeir', 'sigmund'), worlds: w('midgard'), scenes: s('volsung-hall'), narrative: '西格妮的选择并非被动等待：她在无法离开仇敌王宫的处境中，为幸存的兄弟准备复仇。', editorialStatus: 'structured', sections: [{ id: 'ambush', heading: '婚姻后的背叛', paragraphs: ['西格盖尔将沃尔松格及其儿子引至自己的领地后发动袭击。萨迦写西格妮预感到危险，却不能阻止父亲与兄弟赴约；沃尔松格被杀，西格蒙德等人被囚，后又遭狼袭，只有西格蒙德幸存。', '西格妮选择不与西格蒙德一同逃离，而留在西格盖尔的王宫。她的处境与行动使这条复仇线不只是“男性英雄回归”的故事：信息、藏身处与决断同样来自留在敌方空间的人。'] }, { id: 'revenge', heading: '复仇的代价', paragraphs: ['西格妮秘密协助西格蒙德，并以极端且令人不安的方式确保复仇者的血统和忠诚。两人最终焚毁西格盖尔的厅堂；西格妮选择与丈夫同死，而西格蒙德离开。', '这段材料包含亲属、胁迫、暴力与自我毁灭，不能被改写为浪漫或励志桥段。页面会给出内容提示，并将复仇的伦理张力保留为故事本身的问题，而非替读者做无成本的道德洗白。'] }, { id: 'scope', heading: '复仇不是唯一的英雄价值', paragraphs: ['本篇以《沃尔松格萨迦》第三至八章为范围。西格妮与西格盖尔的婚姻、树中剑和西格蒙德的幸存相互关联，却都不应被压缩成一条简单家谱。', '后续“西格蒙德与辛菲奥特利”会处理幸存者共同生活、狼皮与下一代；本篇停在复仇完成后的断裂，避免把西格妮的叙事能动性从主线中抹去。'] }] }),
  story({ slug: 'sigmund-and-sinfjotli', title: '西格蒙德与辛菲奥特利', titleEn: 'Sigmund and Sinfjötli', subtitle: '幸存者、狼皮与下一代复仇者', summary: '西格蒙德与辛菲奥特利共同生活、穿上狼皮并参与复仇，家族暴力在下一代延续。', kind: 'heroic-legend', volumeId: 'norse-volsung', volumeTitle: '沃尔松格英雄传统', volumeOrder: 6, displayOrder: 3, source: storySource('volsungaSaga', 'chs. 7–10'), tradition: '《沃尔松格萨迦》西格蒙德与辛菲奥特利段落', characters: c('sigmund', 'sinfjotli'), worlds: w('midgard'), scenes: s('volsung-hall'), narrative: '西格蒙德与辛菲奥特利的故事把生存、变形、亲属关系与复仇代际并置。', editorialStatus: 'structured', sections: [{ id: 'forest', heading: '森林中的父子', paragraphs: ['萨迦让西格蒙德与辛菲奥特利在林中共同生活，并取得会使穿戴者化为狼的皮。两人在既定期限内不能轻易脱下狼皮，故事因此把人、动物性和暴力置于一种受限制的变形状态。', '辛菲奥特利的出身与西格妮的复仇计划有关，这一信息不能被写成英雄血统的浪漫来源。它说明家族为了复仇跨越了严重的伦理边界，也使人物命运长期被前一篇故事牵引。'] }, { id: 'conflict', heading: '复仇延续而非修复', paragraphs: ['西格蒙德与辛菲奥特利后来回到社会空间，卷入新的婚姻与敌对冲突。辛菲奥特利杀死西格盖尔之子等事件，使复仇不再只是一次已完成的清算，而成为代际间不断扩散的行为方式。', '文本中的死亡、诱骗和暴力不会被产品叙述淡化为升级打怪。故事的重要性在于它让读者看见：幸存并没有使沃尔松格家族脱离旧债，而是产生了新的亲属与政治后果。'] }, { id: 'scope', heading: '通向西格蒙德晚年的一段路', paragraphs: ['本篇以第七至十章为范围，后面将由“西格蒙德之死与希奥尔迪斯”处理辛菲奥特利之死、再婚和西格尔德的出生背景。', '视觉设计可用森林、狼皮和两人共同穿行的状态传达来源锚点，但不把他们塑造成现代狼人类型的固定设定。'] }] }),
  story({ slug: 'sigurd-and-regin', title: '西格尔德与雷金', titleEn: 'Sigurd and Regin', subtitle: '英雄被锻造成命运的刀锋', summary: '西格尔德在雷金的引导下获得格拉墨，走进沃尔松格英雄传统。', kind: 'heroic-legend', volumeId: 'norse-volsung', volumeTitle: '沃尔松格英雄传统', volumeOrder: 6, displayOrder: 4, source: sources.volsung, tradition: '沃尔松格英雄传统', characters: c('sigurd'), worlds: w('midgard'), scenes: s('volsung-hall'), objects: ['object-norse-gram'], narrative: '沃尔松格故事把神话宇宙的英雄传统带入家族、锻造和复仇。西格尔德的身份由武器、师承和家族债务共同塑造。' }),
  story({ slug: 'sigurd-kills-fafnir', title: '西格尔德斩杀法夫纳', titleEn: 'Sigurd Slays Fafnir', subtitle: '龙血与宝藏的危险知识', summary: '西格尔德在洞穴外设伏杀死法夫纳，获得宝藏却也继承诅咒。', kind: 'heroic-legend', volumeId: 'norse-volsung', volumeTitle: '沃尔松格英雄传统', volumeOrder: 6, displayOrder: 2, source: sources.volsung, tradition: '沃尔松格英雄传统', characters: c('sigurd', 'fafnir'), worlds: w('midgard'), scenes: s('volsung-hall'), objects: ['object-norse-gram', 'object-norse-andvaranaut'], narrative: '法夫纳不是天生的抽象恶龙，而是被贪欲转化的角色。西格尔德的胜利因此同时是屠龙、夺宝和进入诅咒网络。' }),
  story({ slug: 'sigurd-and-brynhildr', title: '西格尔德与布伦希尔德', titleEn: 'Sigurd and Brynhildr', subtitle: '誓言穿过火焰边界', summary: '西格尔德与布伦希尔德的相遇和誓言为英雄传统埋下后续冲突。', kind: 'heroic-legend', volumeId: 'norse-volsung', volumeTitle: '沃尔松格英雄传统', volumeOrder: 6, displayOrder: 3, source: sources.volsung, tradition: '沃尔松格英雄传统', characters: c('sigurd', 'brynhildr'), worlds: w('midgard'), scenes: s('volsung-hall'), narrative: '布伦希尔德与西格尔德的关系以火焰、誓言和记忆为核心。它不是一个脱离传统的浪漫支线，而是家族政治与英雄声誉的关键节点。' }),
  story({ slug: 'sigurds-death', title: '西格尔德之死', titleEn: 'The Death of Sigurd', subtitle: '英雄声名无法阻止背叛', summary: '西格尔德的死亡使誓言、婚姻与宝藏的冲突进入不可逆的结局。', kind: 'heroic-legend', volumeId: 'norse-volsung', volumeTitle: '沃尔松格英雄传统', volumeOrder: 6, displayOrder: 4, source: sources.volsung, tradition: '沃尔松格英雄传统', characters: c('sigurd', 'brynhildr'), worlds: w('midgard'), scenes: s('volsung-hall'), narrative: '西格尔德之死让英雄传统脱离单纯的胜利叙事。身份、误认、誓言和宝藏彼此交错，最终把声名转成哀悼。' }),
  story({ slug: 'odin-and-vafthrudnir', title: '奥丁与瓦夫苏鲁德尼尔', titleEn: 'Odin and Vafþrúðnir', subtitle: '以知识作赌注的问答', summary: '奥丁伪名格里姆尼尔前往瓦夫苏鲁德尼尔处，以宇宙和末日知识进行问答，最终提出只有自己知道的问题。', volumeId: 'norse-order', volumeTitle: '神族秩序与知识', volumeOrder: 2, displayOrder: 11, source: storySource('vafthrudnismal', 'sts. 1–55'), tradition: '《瓦夫苏鲁德尼尔之歌》问答传统', characters: c('odin', 'vafthrudnir'), worlds: w('asgard', 'jotunheim'), scenes: s('jotunheim-border'), narrative: '知识竞赛既展示宇宙起源与末日预言，也暴露提问者如何以身份优势结束赌局。', editorialStatus: 'structured', sections: [{ id: 'contest', heading: '格里姆尼尔进入巨人的厅堂', paragraphs: ['《瓦夫苏鲁德尼尔之歌》让奥丁以格里姆尼尔之名拜访以智慧闻名的巨人。弗丽嘉警告他不要轻率赌上性命；奥丁仍接受问答，这使诗中的知识从一开始就带有风险与竞争。', '双方轮流询问世界最初的状态、天体、神祇与诸神黄昏后的幸存者。诗歌的问答形式不是百科目录，而是把宇宙知识放进两个对手的语言关系中。'] }, { id: 'final-question', heading: '无人能答的问题', paragraphs: ['最后奥丁问：巴德尔被送上火葬船时，他在儿子耳中说了什么。瓦夫苏鲁德尼尔意识到提问者身份，只能承认奥丁最有智慧。这里的胜利并不只是“答对更多题”，而是奥丁掌握了对方不可能拥有的私密知识。', '本篇以全诗一至五十五节为范围。关于巴德尔葬礼的细节应回到《欺骗古鲁菲》及独立 Story；本页不把问答诗和散文叙事混作同一直接见证。'] }] }),
  story({ slug: 'thor-and-hymir', title: '索尔与海米尔的大锅', titleEn: 'Thor and Hymir’s Cauldron', subtitle: '一口足以供诸神酿酒的大锅', summary: '诸神需要大锅酿酒，索尔随提尔前往海米尔处，通过试炼取得巨锅。', volumeId: 'norse-thor', volumeTitle: '索尔、洛基与巨人', volumeOrder: 3, displayOrder: 8, source: storySource('hymiskvida', 'sts. 1–39'), tradition: '《海米尔之歌》取锅叙事', characters: c('thor', 'hymir'), worlds: w('jotunheim'), scenes: s('jotunheim-border'), narrative: '取锅故事将宴饮需要、巨人宅邸、垂钓与力量试炼编织在同一首诗中。', editorialStatus: 'structured', sections: [{ id: 'need', heading: '诸神需要一口大锅', paragraphs: ['《海米尔之歌》以诸神想酿酒却缺少足够大的锅开始。提尔知道巨人海米尔拥有一口适合的巨锅，于是索尔与他一同前往；这让故事的目标首先是共同体的宴饮，而非无端挑战巨人。', '在海米尔宅邸，索尔经历食物、酒杯和力量的多重试炼。诗中不同段落的衔接与人物身份存在研究问题，页面不把每一个注释争议伪装成没有分歧的连续电影情节。'] }, { id: 'cauldron', heading: '带走巨锅', paragraphs: ['垂钓世界蛇之后，故事回到大锅：索尔打碎石柱、搬走巨锅，并在追赶中以力量应对海米尔及其他巨人。大锅是一个可追溯物件，而不是“战利品”式的无来源图标。', '本篇涵盖全诗一至三十九节；垂钓段落已有独立 Story，以便读者区分一次海上相遇和取得大锅的整体任务。视觉设计可借助巨大锅、厅堂与归途，但不能把北欧饮酒器具的现代想象当作文本事实。'] }] }),
  story({ slug: 'loki-and-angrboda', title: '洛基与安格尔伯达', titleEn: 'Loki and Angrboða', subtitle: '三名孩子与诸神的恐惧', summary: '《欺骗古鲁菲》将洛基与巨人安格尔伯达所生的芬里尔、世界蛇和赫尔并置，诸神对预言的回应改变三者命运。', volumeId: 'norse-thor', volumeTitle: '索尔、洛基与巨人', volumeOrder: 3, displayOrder: 9, source: storySource('proseEddaGylfaginning', 'ch. 34'), tradition: '《欺骗古鲁菲》洛基子女叙事', characters: c('loki', 'angrboda', 'fenrir', 'jormungandr', 'hel'), worlds: w('asgard', 'jotunheim', 'midgard', 'hel'), scenes: s('asgard-court'), narrative: '三名子女的命运由他们自身的形象与诸神预言中的恐惧共同塑造。', editorialStatus: 'structured', sections: [{ id: 'children', heading: '三个被并置的子女', paragraphs: ['第四十三章前的叙事脉络中，《欺骗古鲁菲》第三十四章说明洛基与安格尔伯达生下芬里尔、世界蛇和赫尔。文本将三者的未来威胁与诸神的预言相连，却不把安格尔伯达展开为一段完整人物传记。', '因此，本页把她作为这则散文叙事的亲属节点，而不凭空填充外貌、阵营或母职性格。三个子女也并非同一种存在：狼、蛇与赫尔的统治空间各有不同的后续故事。'] }, { id: 'separation', heading: '预言引出的分离', paragraphs: ['诸神将世界蛇投入环绕人类世界的海，将赫尔送往亡者之地，又决定抚养芬里尔直到无法继续控制。这些安排是诸神对未来的应对，不能被改写成三者天然“自愿选择”自己的位置。', '芬里尔的束缚、世界蛇与索尔的冲突、赫尔与巴德尔的谈判都另有来源范围和 Story。拆开阅读能让读者看到同一章中预言如何分叉成多条叙事，而不将所有内容压入洛基一人的单线反派故事。'] }] }),
  story({ slug: 'grimnir-revealed', title: '格里姆尼尔的启示', titleEn: 'Grímnir Revealed', subtitle: '受折磨的陌生人说出诸神世界', summary: '奥丁化名格里姆尼尔受困于盖鲁德王，连续八夜遭受火焰折磨后说出诸神居所，最终显露身份。', volumeId: 'norse-order', volumeTitle: '神族秩序与知识', volumeOrder: 2, displayOrder: 12, source: storySource('grimnismal', 'sts. 1–54'), tradition: '《格里姆尼尔之歌》传统', characters: c('odin'), worlds: w('asgard'), scenes: s('asgard-court'), narrative: '诗歌把宇宙知识置于囚禁、待客失败和王权惩罚的情境之中。', editorialStatus: 'structured', sections: [{ id: 'captivity', heading: '两堆火之间的陌生人', paragraphs: ['《格里姆尼尔之歌》散文序言说，奥丁化名格里姆尼尔来到盖鲁德王处，被夹在两堆火之间八夜。王子阿格纳尔给他饮水，成为这段待客失范中的少数善意。', '格里姆尼尔的启示不是安静讲课：住所、河流、世界树和诸神的名字都在受折磨的言说中被列出，因此每一项都必须按诗节范围而非现代百科地图理解。'] }, { id: 'revelation', heading: '身份显露与王的死亡', paragraphs: ['诗末格里姆尼尔说出自己是奥丁，并列举多个名字。盖鲁德王拔剑欲解除折磨，却自己跌倒在剑上死亡；阿格纳尔继位。', '本篇限于全诗及其散文框架。瓦尔哈拉、世界树和奥丁乌鸦分别有可独立追踪的诗节与 Story，不用一次启示替代所有叙事。'] }] }),
  story({ slug: 'valholl-and-valkyries', title: '瓦尔哈拉与女武神', titleEn: 'Valhöll and the Valkyries', subtitle: '战死者的大厅与日常秩序', summary: '《格里姆尼尔之歌》描述奥丁的瓦尔哈拉、其中的战死者与服务宴饮的女武神。', volumeId: 'norse-order', volumeTitle: '神族秩序与知识', volumeOrder: 2, displayOrder: 13, source: storySource('grimnismal', 'sts. 8–13, 36'), tradition: '《格里姆尼尔之歌》瓦尔哈拉段落', characters: c('odin'), worlds: w('asgard'), scenes: s('asgard-court'), narrative: '瓦尔哈拉是诗歌中的奥丁大厅，而非可任意填充的现代军营。', editorialStatus: 'structured', sections: [{ id: 'hall', heading: '奥丁的大厅', paragraphs: ['诗中说瓦尔哈拉有许多门，战死者每日相互战斗、复生，并在晚间回到大厅进食。描述强调的是循环、集体和宴饮，不等于提供一套完整死后世界制度。', '女武神在诗的不同段落中被命名并与选择战死者、端酒等意象关联。页面避免把她们统一成没有名字和行动的装饰性侍者。'] }, { id: 'scope', heading: '不与所有亡者世界混同', paragraphs: ['瓦尔哈拉属于奥丁的大厅，赫尔则是另一人物与亡者空间；两者不能在产品中混成同义词。诸神黄昏中的死者和军队也需回到其各自诗节。', '本篇仅按第八至十三、三十六节设置来源范围。大厅构图、武器与服装可作原创设计，但“所有北欧亡者都去瓦尔哈拉”不是本页或该诗能够支持的结论。'] }] }),
  story({ slug: 'andvari-gold', title: '安德瓦里与被诅咒的黄金', titleEn: 'Andvari’s Gold', subtitle: '赔偿之金进入沃尔松格悲剧', summary: '洛基以安德瓦里的黄金赔偿赫瑞德玛尔，安德瓦里诅咒戒指，财物随后引发家庭杀戮。', kind: 'heroic-legend', volumeId: 'norse-volsung', volumeTitle: '沃尔松格英雄传统', volumeOrder: 6, displayOrder: 5, source: storySource('reginsmal', 'sts. 1–26'), tradition: '《雷金之歌》安德瓦里黄金段落', characters: c('andvari', 'ottr', 'hreidmar', 'fafnir'), worlds: w('midgard'), scenes: s('volsung-hall'), objects: ['object-norse-andvaranaut'], narrative: '黄金既是补偿，也是把暴力与贪欲传递到英雄家族的媒介。', editorialStatus: 'structured', sections: [{ id: 'ransom', heading: '被杀的奥特与人头金', paragraphs: ['《雷金之歌》开篇中，洛基、奥丁和海尼尔杀死水獭形态的奥特；奥特的父亲赫瑞德玛尔要求用黄金填满皮囊作为赔偿。洛基从矮人安德瓦里处取得黄金和戒指。', '安德瓦里试图保留戒指，仍被夺走，并诅咒财物将给持有者带来死亡。叙事不是“黄金天然邪恶”的抽象寓言，而将杀害、赔偿、夺取和诅咒连在具体人物身上。'] }, { id: 'aftermath', heading: '财物没有终止债务', paragraphs: ['赫瑞德玛尔得到黄金后，法夫纳杀父并占有财物，后成为守护黄金的龙。安德瓦里的诅咒因而成为连接奥特、赫瑞德玛尔、法夫纳、雷金与西格尔德的叙事线索。', '本篇依据一至二十六节；萨迦和其他英雄诗对人物动机、宝物和后果有平行版本。页面保留物件与来源连接，不把戒指直接等同于现代奇幻作品的同名母题。'] }] }),
  story({ slug: 'helgi-hundingsbani', title: '赫尔吉·洪丁斯巴尼', titleEn: 'Helgi Hundingsbani', subtitle: '战船、女武神与英雄诗歌的开端', summary: '赫尔吉在与洪丁家族的冲突中获得名字与英雄身份，西格伦作为女武神进入这条诗歌传统。', kind: 'heroic-legend', volumeId: 'norse-helgi', volumeTitle: '赫尔吉英雄传统', volumeOrder: 7, displayOrder: 1, source: storySource('helgakvidaHundingsbana1', 'sts. 1–57'), tradition: '《赫尔吉·洪丁斯巴尼之歌 I》传统', characters: c('helgi-hundingsbani', 'sigrun', 'sinfjotli'), worlds: w('midgard'), scenes: s('midgard-coast'), narrative: '赫尔吉的英雄身份在战争、航行与女武神的出现中形成。', editorialStatus: 'structured', sections: [{ id: 'name-and-conflict', heading: '名字在冲突中获得', paragraphs: ['《赫尔吉·洪丁斯巴尼之歌 I》以家族冲突、隐匿的幼子和得名的过程开启。赫尔吉的名字与杀死洪丁的行动相连，诗歌由此把个人身份、敌对家系和名誉放进同一个叙事起点。', '这不是一份可以无缝接到诸神家谱上的神祇传记。赫尔吉属于英雄诗歌的传统层，人物的行动、亲属关系和女武神意象要按这组诗歌的范围阅读。'] }, { id: 'sigrun-enters', heading: '西格伦作为女武神出现', paragraphs: ['西格伦在诗中以女武神身份进入赫尔吉的战场世界；她既传递战事信息，也拥有自己的亲属与婚姻冲突。把她写成单纯奖赏或装饰，会抹去诗歌对她行动与选择的呈现。', '本页只使用《赫尔吉·洪丁斯巴尼之歌 I》的范围。赫尔吉与西格伦之后的相遇、死亡和葬丘主题，应由第二首诗和独立 Story 继续展开。'] }, { id: 'heroic-lane', heading: '为何单列英雄传统', paragraphs: ['赫尔吉故事的战船、长矛、婚姻冲突与复归母题，形成不同于奥丁、索尔或诸神黄昏的叙事节奏。页面将它单列为“赫尔吉英雄传统”，避免把所有古诺尔斯材料都压进同一神祇宇宙时间线。', '角色卡与来源卡保留为可追溯入口；任何未来视觉设计都应依据诗歌中的战场、航行和女武神关系，而非借用现代影视或游戏的北欧战士模板。'] }] }),
  story({ slug: 'volundr-captive-smith', title: '沃伦德：被囚的铁匠', titleEn: 'Völundr the Captive Smith', subtitle: '技艺、囚禁与逃离之前的静默', summary: '沃伦德被尼杜德囚禁在岛上铁匠铺，其技艺、戒指与失去自由共同构成独立英雄诗歌的张力。', kind: 'heroic-legend', volumeId: 'norse-independent-eddic', volumeTitle: '独立埃达英雄传统', volumeOrder: 8, displayOrder: 1, source: storySource('volundarkvida', 'sts. 1–19'), tradition: '《沃伦德之歌》囚禁段落', characters: c('volundr', 'nidudr'), worlds: w('midgard'), scenes: s('volsung-hall'), narrative: '沃伦德被囚禁后的铁匠工作，使技艺成为失去自由的见证。', editorialStatus: 'structured', sections: [{ id: 'three-brothers', heading: '离去的女伴与留下的戒指', paragraphs: ['《沃伦德之歌》开篇写沃伦德与两位兄弟同居，三位女伴后来离去。沃伦德仍留在原处，锻造金环，并期待她归来；这段等待让戒指既是物件，也成为失去关系后的叙事线索。', '诗歌的地名和身份称谓并不总能被现代改编整理成稳定王国地图。本页保留“北方英雄诗歌”的来源范围，不把它强行纳入沃尔松格家系或阿斯加德的固定地理。'] }, { id: 'captivity', heading: '囚禁并没有抹去技艺', paragraphs: ['尼杜德得知沃伦德的技艺后，将他囚禁在岛上，割断其腿筋并迫使他为王室制作器物。文本的暴力和权力关系是故事的核心，不能用“天才铁匠的奇幻冒险”轻描淡写。', '沃伦德在囚禁中继续工作，戒指被带入王室，人物关系因此从等待扩展为占有、控制与报复的张力。后半段的逃离与伤害另作独立 Story，避免压缩为一段猎奇情节。'] }, { id: 'independent-poem', heading: '独立诗歌不是边角素材', paragraphs: ['《沃伦德之歌》并非为了给诸神宝物补一条背景，而是一首拥有自身人物、地点和伦理冲突的英雄诗。它与赫尔吉、沃尔松格等传统可在产品中并列探索，却不应被混写成一条唯一正史。', '视觉创作应以铁砧、戒指、岛上工坊和受限的行动为锚点，避免把沃伦德设计成现代超级英雄或无来源的蒸汽朋克发明家。'] }] }),
  story({ slug: 'thor-and-skrymir', title: '索尔与斯克里米尔', titleEn: 'Thor and Skrymir', subtitle: '巨大的手套与无法击穿的头颅', summary: '索尔、洛基和随行者与斯克里米尔同行，索尔三次锤击看似失败，实际触及的是远方山体。', volumeId: 'norse-thor', volumeTitle: '索尔、洛基与巨人', volumeOrder: 3, displayOrder: 10, source: storySource('proseEddaGylfaginning', 'ch. 45'), tradition: '《欺骗古鲁菲》乌特加德前段', characters: c('thor', 'loki', 'skrymir'), worlds: w('jotunheim'), scenes: s('jotunheim-border'), narrative: '通往乌特加德的旅程先用尺度错觉削弱索尔对自身力量的判断。', editorialStatus: 'structured', sections: [{ id: 'journey', heading: '一只手套被误认成屋子', paragraphs: ['第四十五章中，索尔一行遇见斯克里米尔，夜里把他的巨大手套当作屋舍。斯克里米尔替他们背行囊，却用绳结令索尔无法打开食物袋；日常物件在巨人尺度下成为力量与无力的试验。', '索尔趁斯克里米尔睡着三次挥锤，次日巨人只说头部似有树叶或橡子落下。故事先让读者和人物共同误判锤击的效果。'] }, { id: 'revelation', heading: '失败并不等于力量不存在', paragraphs: ['到达乌特加德后，巨人之王解释三次锤击实际上击中了山，并留下深谷。这一揭示属于接下来的大厅故事，但也重置了索尔在旅程中经历的“失败”。', '本篇限定在第四十五章；斯克里米尔与乌特加达洛基的关系不应被简化为无来源的同一身份。'] }] }),
  story({ slug: 'loki-and-baldr', title: '洛基与巴德尔之死', titleEn: 'Loki and Baldr’s Death', subtitle: '被遗漏的槲寄生', summary: '洛基发现槲寄生未被弗丽嘉要求起誓，引导霍德尔投掷它，巴德尔因此死亡。', volumeId: 'norse-baldr', volumeTitle: '巴德尔之死与秩序崩裂', volumeOrder: 4, displayOrder: 7, source: storySource('proseEddaGylfaginning', 'ch. 49'), tradition: '《欺骗古鲁菲》巴德尔之死段落', characters: c('loki', 'baldr', 'hodr', 'frigg'), worlds: w('asgard'), scenes: s('asgard-court'), narrative: '一项看似周全的保护因被忽略的植物而失效，洛基将游戏变成了死亡。', editorialStatus: 'structured', sections: [{ id: 'oaths', heading: '誓言留下的例外', paragraphs: ['散文说巴德尔做不祥之梦后，弗丽嘉让万物承诺不伤害他；诸神便把向他投掷物件当作游戏。槲寄生因被认为太小而未被要求起誓，保护因此并非绝对。', '洛基向弗丽嘉探问后取得槲寄生，并将其交给未参与游戏的霍德尔。文本将死亡置于疏漏、试探与引导的链条中。'] }, { id: 'death', heading: '游戏成为哀悼', paragraphs: ['霍德尔投出槲寄生，巴德尔倒下。诸神震惊却无法立刻报复；这使神域的日常游戏转为不可逆的共同损失。', '本篇仅依第四十九章，不把霍德尔的身份与动机超出该散文范围地补写。葬礼、赫尔莫德之旅和洛基受缚另由独立 Story 处理。'] }] }),
  story({ slug: 'sigmunds-death-and-hjordis', title: '西格蒙德之死与希奥尔迪斯', titleEn: 'Sigmund’s Death and Hjördis', subtitle: '断剑与尚未出生的英雄', summary: '西格蒙德在战场上被独眼战士击断神剑而死；希奥尔迪斯保存剑的碎片，孕育西格尔德。', kind: 'heroic-legend', volumeId: 'norse-volsung', volumeTitle: '沃尔松格英雄传统', volumeOrder: 6, displayOrder: 6, source: storySource('volsungaSaga', 'chs. 11–12'), tradition: '《沃尔松格萨迦》西格尔德前史', characters: c('sigmund', 'hjordis', 'sigurd'), worlds: w('midgard'), scenes: s('volsung-hall'), narrative: '西格蒙德之死没有终结家族叙事：断裂的剑和希奥尔迪斯的行动把它交给未出生的西格尔德。', editorialStatus: 'structured', sections: [{ id: 'battle', heading: '剑在战场断裂', paragraphs: ['萨迦中西格蒙德在战争中遇到一名独眼战士，对方以长矛击碎其剑。西格蒙德拒绝让人医治，认为自己的好运已尽；这不是普通战败，而是家族武器与命运共同断裂。', '希奥尔迪斯在战后找到他，西格蒙德要求她保存剑的碎片给腹中的孩子。她的保存与传递使下一代英雄的条件并非只来自父亲的遗名。'] }, { id: 'inheritance', heading: '从碎片到西格尔德', paragraphs: ['希奥尔迪斯后来与阿尔夫王相遇，生下西格尔德；碎片将被重铸为格拉墨。故事将死亡、再婚和抚养置于英雄出现之前。', '本篇限定第十一至十二章，不把雷金的教育或法夫纳的黄金提前混入；它们属于西格尔德自身的后续 Story。'] }] }),
  story({ slug: 'loki-at-ragnarok', title: '洛基在诸神黄昏', titleEn: 'Loki at Ragnarök', subtitle: '从束缚者到末日战者', summary: '《女预言家之歌》在末日段落中让洛基随舰而来，并与海姆达尔同归于尽。', volumeId: 'norse-ragnarok', volumeTitle: '诸神黄昏与世界再生', volumeOrder: 5, displayOrder: 7, source: storySource('voluspa', 'sts. 46–51'), tradition: '《女预言家之歌》诸神黄昏段落', characters: c('loki', 'heimdall'), worlds: w('asgard', 'midgard'), scenes: s('bifrost'), narrative: '洛基在末日的叙事位置连接先前的束缚与最终的共同毁灭。', editorialStatus: 'structured', sections: [{ id: 'arrival', heading: '末日中的到来', paragraphs: ['《女预言家之歌》以巨人、船只、号角和诸神集结的图像推进末日。洛基在这一段与海姆达尔的结局相连，但诗歌并不提供一部可无缝填满的战场编年史。', '因此页面不将所有散文中洛基的前史都当作这几节诗的明说背景；束缚、航船和末日战争分别保留各自来源范围。'] }, { id: 'mutual-death', heading: '与海姆达尔的同归于尽', paragraphs: ['诗歌传统将洛基与海姆达尔置于最终冲突中，并以双方死亡收束这条对立。它不是奥丁、索尔等主战的附属桥段，而是守望者与秩序裂缝共同消失的结局。', '本篇使用四十六至五十一节；海姆达尔的号角和诸神黄昏整体将以交叉链接呈现，不把争议的细节写成唯一正史。'] }] }),
  story({ slug: 'sigurd-and-sigrdrifa', title: '西格尔德与西格德里法', titleEn: 'Sigurd and Sigrdrífa', subtitle: '火焰之后的知识与劝诫', summary: '西格尔德唤醒沉睡在盾墙中的西格德里法，她向他传授胜利符文与处世劝诫。', kind: 'heroic-legend', volumeId: 'norse-volsung', volumeTitle: '沃尔松格英雄传统', volumeOrder: 6, displayOrder: 7, source: storySource('sigrdrifumal', 'sts. 1–37'), tradition: '《西格德里法之歌》传统', characters: c('sigurd', 'brynhildr'), worlds: w('midgard'), scenes: s('volsung-hall'), narrative: '英雄相遇在诗歌中首先通过苏醒、知识与劝诫展开，而非只是一段浪漫关系。', editorialStatus: 'structured', sections: [{ id: 'awakening', heading: '从盾墙中醒来', paragraphs: ['《西格德里法之歌》开篇让西格尔德看见盾墙中的沉睡女子并使她醒来。人物身份与布伦希尔德的对应在不同传统中需要谨慎处理，页面以诗歌标题人物与来源范围为先。', '她以“胜利符文”等知识回应西格尔德，说明相遇不仅是英雄的行动成果，也包含女性人物的言说与传授。'] }, { id: 'counsel', heading: '劝诫并非战利品', paragraphs: ['后续诗节列出饮酒、誓言、分娩、航行与处世等不同情境的劝诫。它们不应被压缩为一页技能表，而是英雄诗歌把行动与言辞伦理并列的方式。', '本篇限于一至三十七节；西格尔德与布伦希尔德的婚姻、误认和死亡使用萨迦及其他诗歌的独立范围。'] }] }),
  story({ slug: 'gudrun-and-atli', title: '古德伦与阿特利', titleEn: 'Guðrún and Atli', subtitle: '宴席中的复仇与哀歌', summary: '阿特利以黄金为饵引诱古德伦的兄弟，古德伦预警失败后以极端方式复仇。', kind: 'heroic-legend', volumeId: 'norse-volsung', volumeTitle: '沃尔松格英雄传统', volumeOrder: 6, displayOrder: 8, source: storySource('atlakvida', 'sts. 1–46'), tradition: '《阿特利之歌》传统', characters: c('gudrun', 'atli', 'gunnar', 'hogni'), worlds: w('midgard'), scenes: s('volsung-hall'), narrative: '古德伦的哀歌与复仇使沃尔松格传统的家庭、财富和暴力走向更深的断裂。', editorialStatus: 'structured', sections: [{ id: 'warning', heading: '无法阻止的赴宴', paragraphs: ['《阿特利之歌》写阿特利邀请古德伦的兄弟贡纳尔与霍格尼，古德伦送出警告，却未能阻止他们前往。黄金与亲属关系在这里是诱饵和威胁，而非稳定联盟。', '两兄弟被杀的叙事存在诗歌与萨迦版本差异；本页以本诗的措辞和范围呈现，不把各版本细节强行统一。'] }, { id: 'revenge', heading: '复仇没有恢复家庭', paragraphs: ['古德伦杀死阿特利的儿子，以宴席和火焰实施复仇。材料含有严重暴力，不应被游戏化或美化为单纯的胜利。', '本篇使用一至四十六节，重点是古德伦的行动、哀悼与伦理断裂。斯万希尔德和哈姆迪尔兄弟属于另一条后续传统。'] }] }),
  story({ slug: 'helgi-hjorvardsson-and-svava', title: '赫尔吉·希奥尔瓦尔松与斯瓦瓦', titleEn: 'Helgi Hjörvarðsson and Sváfa', subtitle: '名字、誓言与女武神', summary: '赫尔吉在斯瓦瓦引导下取得名字与武器，二人的誓言被战争与继承冲突考验。', kind: 'heroic-legend', volumeId: 'norse-helgi', volumeTitle: '赫尔吉英雄传统', volumeOrder: 7, displayOrder: 2, source: storySource('helgakvidaHjorvardssonar', 'sts. 1–51'), tradition: '《赫尔吉·希奥尔瓦尔松之歌》传统', characters: c('helgi-hjorvardsson', 'svava'), worlds: w('midgard'), scenes: s('midgard-coast'), narrative: '赫尔吉与斯瓦瓦的诗歌将命名、女武神协助和婚姻誓言编入英雄成长。', editorialStatus: 'structured', sections: [{ id: 'name', heading: '由斯瓦瓦命名的英雄', paragraphs: ['诗歌让尚未命名的赫尔吉遇见女武神斯瓦瓦；她与武器、名誉和未来行动相连。斯瓦瓦不是英雄获得装备的无名奖赏，而是向他提出行动条件的人物。', '二人的关系在战事和家族安排中发展，不能直接套入另一位赫尔吉或西格伦的故事。'] }, { id: 'scope', heading: '独立的赫尔吉传统', paragraphs: ['本篇以一至五十一节为范围，呈现赫尔吉·希奥尔瓦尔松与斯瓦瓦的独立诗歌线。它与洪丁斯巴尼传统可并列阅读，不能因名字相同而合并为同一传记。', '视觉锚点是女武神、航行和誓言；具体服饰与城邦属于原创设计层。'] }] }),
  story({ slug: 'helgi-and-sigrun', title: '赫尔吉与西格伦', titleEn: 'Helgi and Sigrún', subtitle: '战场、亲属与婚姻选择', summary: '西格伦拒绝既定婚姻并支持赫尔吉，二人的关系被家族战争持续撕裂。', kind: 'heroic-legend', volumeId: 'norse-helgi', volumeTitle: '赫尔吉英雄传统', volumeOrder: 7, displayOrder: 3, source: storySource('helgakvidaHundingsbana2', 'sts. 1–51'), tradition: '《赫尔吉·洪丁斯巴尼之歌 II》传统', characters: c('helgi-hundingsbani', 'sigrun'), worlds: w('midgard'), scenes: s('midgard-coast'), narrative: '西格伦具有明确的选择与行动，婚姻并不能脱离其家族与战场背景理解。', editorialStatus: 'structured', sections: [{ id: 'choice', heading: '西格伦的选择', paragraphs: ['第二首赫尔吉诗把西格伦置于家族安排的婚姻和她自己支持赫尔吉之间。她传递消息、表达意愿，也承担由此带来的亲属冲突。', '将她写成战士的奖赏会抹去诗歌中的主动性与危险。'] }, { id: 'war', heading: '爱情无法隔绝战争', paragraphs: ['赫尔吉与西格伦的结合伴随复仇、战斗和亲属死亡。诗歌并不把他们的相遇收束为无代价的团圆，而将其留在英雄传统的暴力循环中。', '后续死亡和葬丘归来另由独立 Story 说明。'] }] }),
  story({ slug: 'helgi-burial-mound', title: '赫尔吉的葬丘与归来', titleEn: 'Helgi’s Burial Mound', subtitle: '一夜的相会不能逆转死亡', summary: '赫尔吉死后进入葬丘，西格伦在一夜相会中见到他，黎明后仍被留在生者世界。', kind: 'heroic-legend', volumeId: 'norse-helgi', volumeTitle: '赫尔吉英雄传统', volumeOrder: 7, displayOrder: 4, source: storySource('helgakvidaHundingsbana2', 'sts. 39–51'), tradition: '《赫尔吉·洪丁斯巴尼之歌 II》葬丘段落', characters: c('helgi-hundingsbani', 'sigrun'), worlds: w('midgard'), scenes: s('midgard-coast'), narrative: '葬丘场景让爱情与哀悼短暂相接，却不取消死亡。', editorialStatus: 'structured', sections: [{ id: 'mound', heading: '死者回到葬丘', paragraphs: ['诗末说赫尔吉在葬丘中归来，西格伦前往相会。归来被限定在夜晚与特定地点，而非死者真正恢复日常生活。', '这段相会强调哀悼的强度，也强调其时间边界。'] }, { id: 'dawn', heading: '黎明后的等待', paragraphs: ['黎明迫近时赫尔吉离去，西格伦仍留在生者一侧。诗歌没有以重逢治愈战争和死亡，而让等待继续存在。', '本篇仅使用三十九至五十一节，不把其他亡者传统或赫尔的国度自动拼入葬丘。'] }] }),
  story({ slug: 'volundr-escape', title: '沃伦德的逃离', titleEn: 'Völundr’s Escape', subtitle: '复仇、飞行与无法收回的伤害', summary: '沃伦德在囚禁中报复尼杜德家族，制作翅膀飞离岛上工坊。', kind: 'heroic-legend', volumeId: 'norse-independent-eddic', volumeTitle: '独立埃达英雄传统', volumeOrder: 8, displayOrder: 2, source: storySource('volundarkvida', 'sts. 20–41'), tradition: '《沃伦德之歌》逃离段落', characters: c('volundr', 'bodvildr'), worlds: w('midgard'), scenes: s('volsung-hall'), narrative: '逃离是囚禁故事的后半段，但复仇造成的伤害不能被技术奇观掩盖。', editorialStatus: 'structured', sections: [{ id: 'revenge', heading: '囚禁者的报复', paragraphs: ['《沃伦德之歌》后段写沃伦德对尼杜德之子的杀害，以及与博德维尔德相关的强制和后果。内容涉及严重暴力与性伤害，页面必须提供提示，不能将其包装为痛快复仇。', '沃伦德的技艺在此仍是权力不对等中的工具，并未抵消他先前遭受的囚禁。'] }, { id: 'flight', heading: '飞离工坊', paragraphs: ['沃伦德制作翅膀升空，尼杜德只能在地上询问自己的家人。诗以飞行结束行动，却不为任何一方提供道德上的轻易结算。', '本篇以二十至四十一节为范围，和囚禁篇共同构成独立的沃伦德传统。'] }] }),
  researchStory({ slug: 'nidhoggr-and-world-tree', title: '尼德霍格与世界树', titleEn: 'Níðhöggr and the World Tree', subtitle: '树根下的啃噬者', summary: '尼德霍格在世界树根部啃噬，成为宇宙树持续受损的一部分。', volumeId: 'norse-origins', volumeTitle: '创世与宇宙结构', volumeOrder: 1, displayOrder: 8, source: storySource('grimnismal', 'sts. 32–35'), tradition: '《格里姆尼尔之歌》世界树段落', characters: c('nidhoggr'), worlds: w('niflheim'), scenes: s('world-tree-roots'), focus: '《格里姆尼尔之歌》将尼德霍格置于世界树根部，和啃食枝叶的动物一起说明宇宙树并非无损的装饰，而是持续承受侵蚀的存在。' }),
  researchStory({ slug: 'odin-ravens', title: '胡金与穆宁', titleEn: 'Huginn and Muninn', subtitle: '每天飞越世界的两只乌鸦', summary: '奥丁担心胡金和穆宁飞越世界后不能归来。', volumeId: 'norse-order', volumeTitle: '神族秩序与知识', volumeOrder: 2, displayOrder: 14, source: storySource('grimnismal', 'st. 20'), tradition: '《格里姆尼尔之歌》乌鸦段落', characters: c('odin', 'huginn', 'muninn'), worlds: w('asgard'), scenes: s('asgard-court'), focus: '第二十节说胡金与穆宁每日飞越世界，奥丁更担心“思维”胡金不归，却也忧虑“记忆”穆宁；本页不把这一简短诗节扩写为秘密情报系统。' }),
  researchStory({ slug: 'odin-seidr', title: '奥丁与塞德魔法', titleEn: 'Odin and Seiðr', subtitle: '知识、预言与越界的技艺', summary: '《英灵格林伽萨迦》将塞德魔法与奥丁和弗蕾雅相连，也记述其社会污名。', volumeId: 'norse-order', volumeTitle: '神族秩序与知识', volumeOrder: 2, displayOrder: 15, source: storySource('ynglingaSaga', 'ch. 7'), tradition: '《英灵格林伽萨迦》塞德段落', characters: c('odin', 'freyja'), worlds: w('asgard'), scenes: s('asgard-court'), focus: '第七章将塞德描述为可知未来、造成伤害或不幸的技艺，并称弗蕾雅向阿萨神传授它；对奥丁施行此术的评价反映中世纪文本中的性别与社会观念，不能直接当作古代社会事实。' }),
  researchStory({ slug: 'thor-and-thjalfi-roskva', title: '索尔、夏尔菲与罗丝克瓦', titleEn: 'Thor, Þjálfi and Röskva', subtitle: '一根骨头带来的侍从关系', summary: '夏尔菲折断山羊腿骨后，索尔带走他与罗丝克瓦作为侍从。', volumeId: 'norse-thor', volumeTitle: '索尔、洛基与巨人', volumeOrder: 3, displayOrder: 11, source: storySource('proseEddaGylfaginning', 'ch. 44'), tradition: '《欺骗古鲁菲》索尔旅程段落', characters: c('thor', 'thjalfi', 'roskva'), worlds: w('midgard'), scenes: s('midgard-coast'), focus: '第四十四章中，索尔宰食两只山羊又使其复活，夏尔菲因打断一根腿骨导致山羊跛行；作为补偿，他和妹妹罗丝克瓦随索尔离去。' }),
  researchStory({ slug: 'thor-and-alviss', title: '索尔与阿尔维斯', titleEn: 'Thor and Alvíss', subtitle: '问答拖延到日出', summary: '索尔以连续提问拖住想娶女儿的矮人阿尔维斯，直到阳光使其化为石头。', volumeId: 'norse-thor', volumeTitle: '索尔、洛基与巨人', volumeOrder: 3, displayOrder: 12, source: storySource('alvissmal', 'sts. 1–35'), tradition: '《阿尔维斯之歌》传统', characters: c('thor', 'alviss'), worlds: w('asgard'), scenes: s('asgard-court'), focus: '《阿尔维斯之歌》以索尔和矮人的问答展开，不同族类如何称呼天空、地面与事物是其核心；日出终止谈话，阿尔维斯被石化。' }),
  researchStory({ slug: 'thor-and-harbard', title: '索尔与哈巴德', titleEn: 'Thor and Hárbarðr', subtitle: '渡口上的辱骂与争辩', summary: '索尔无法过河，与船夫哈巴德互相嘲讽并争论功绩。', volumeId: 'norse-thor', volumeTitle: '索尔、洛基与巨人', volumeOrder: 3, displayOrder: 13, source: storySource('harbardsljod', 'sts. 1–60'), tradition: '《哈巴德之歌》传统', characters: c('thor', 'odin'), worlds: w('midgard'), scenes: s('midgard-coast'), focus: '《哈巴德之歌》中，索尔与自称哈巴德的船夫隔河互相侮辱；船夫通常被理解为奥丁，但诗歌本身的表演性和身份游戏应保留为解释范围。' }),
  researchStory({ slug: 'vali-avenges-baldr', title: '瓦利为巴德尔复仇', titleEn: 'Váli Avenges Baldr', subtitle: '新生者迅速完成复仇', summary: '《女预言家之歌》说瓦利一夜成长并杀死霍德尔，为巴德尔复仇。', volumeId: 'norse-ragnarok', volumeTitle: '诸神黄昏与世界再生', volumeOrder: 5, displayOrder: 8, source: storySource('voluspa', 'sts. 32–33'), tradition: '《女预言家之歌》巴德尔段落', characters: c('vali', 'hodr'), worlds: w('asgard'), scenes: s('asgard-court'), focus: '第三十二至三十三节将瓦利写为奥丁之子，他一夜成长、从不洗手梳头，直至杀死巴德尔的杀手；本页不将诗歌简略叙述补写为完整司法程序。' }),
  researchStory({ slug: 'tyr-and-garmr', title: '提尔与加姆', titleEn: 'Týr and Garmr', subtitle: '诸神黄昏中的相互毁灭', summary: '《欺骗古鲁菲》让提尔与加姆在末日相战并同归于尽。', volumeId: 'norse-ragnarok', volumeTitle: '诸神黄昏与世界再生', volumeOrder: 5, displayOrder: 9, source: storySource('proseEddaGylfaginning', 'ch. 51'), tradition: '《欺骗古鲁菲》诸神黄昏段落', characters: c('tyr', 'garmr'), worlds: w('hel'), scenes: s('fimbulwinter-field'), focus: '第五十一章在诸神黄昏的战斗配对中让提尔与加姆相互杀死；它不要求将加姆与其他狼形存在自动视为同一角色。' }),
  researchStory({ slug: 'gudrun-svanhild-hamdir-sorli', title: '古德伦、斯万希尔德与哈姆迪尔兄弟', titleEn: 'Guðrún, Svanhildr, Hamðir and Sörli', subtitle: '母亲催促儿子复仇', summary: '古德伦在斯万希尔德死后催促哈姆迪尔与索尔利复仇，诗歌以失败和哀歌收束。', kind: 'heroic-legend', volumeId: 'norse-volsung', volumeTitle: '沃尔松格英雄传统', volumeOrder: 6, displayOrder: 9, source: storySource('hamdismal', 'sts. 1–30'), tradition: '《哈姆迪尔之歌》传统', characters: c('gudrun', 'svanhildr', 'hamdir', 'sorli'), worlds: w('midgard'), scenes: s('volsung-hall'), focus: '《哈姆迪尔之歌》从古德伦的催促、兄弟旅程和对仇人的袭击展开；它以伤痛、石击和家族复仇的失败感结束。' }),
  researchStory({ slug: 'svipdagr-and-mengloth', title: '斯维普达格与孟格洛德', titleEn: 'Svipdagr and Menglöð', subtitle: '母亲的咒语与门前问答', summary: '斯维普达格先求亡母格罗娅帮助，再在孟格洛德所在之地经历问答。', kind: 'heroic-legend', volumeId: 'norse-independent-eddic', volumeTitle: '独立埃达英雄传统', volumeOrder: 8, displayOrder: 3, source: storySource('svipdagsmal', 'Grógaldr and Fjölsvinnsmál; editorial split to be reviewed'), tradition: '《斯维普达格之歌》复合传统', characters: c('svipdagr', 'groa', 'mengloth'), worlds: w('midgard'), scenes: s('volsung-hall'), focus: '《格罗娅咒语》与《菲奥尔斯温之歌》常被并置为斯维普达格传统，但其组合方式本身需要编辑审查；本页保留母亲咒语、旅程与门前问答的最小来源范围。' }),
  researchStory({ slug: 'rig-and-social-orders', title: '里格与社会秩序', titleEn: 'Rígr and Social Orders', subtitle: '走访三户人家的陌生人', summary: '《里格之歌》以里格走访不同家庭并生下后代的方式解释社会等级。', kind: 'heroic-legend', volumeId: 'norse-independent-eddic', volumeTitle: '独立埃达英雄传统', volumeOrder: 8, displayOrder: 4, source: storySource('rigsthula', 'selected stanzas'), tradition: '《里格之歌》传统', characters: c('rigr'), worlds: w('midgard'), scenes: s('volsung-hall'), focus: '《里格之歌》把社会身份安排成陌生人造访不同家庭后的谱系结果；它反映文本中的等级想象，不能被产品叙述认可为合理或自然的社会秩序。' }),
  researchStory({ slug: 'grottasongr', title: '格罗蒂之歌', titleEn: 'Grottasöngr', subtitle: '磨坊、奴役与战争', summary: '两位女巨人被迫推磨，磨出的财富最终转为敌军与毁灭。', kind: 'heroic-legend', volumeId: 'norse-independent-eddic', volumeTitle: '独立埃达英雄传统', volumeOrder: 8, displayOrder: 5, source: storySource('grottasongr', 'selected stanzas'), tradition: '《格罗蒂之歌》传统', characters: [], worlds: w('midgard'), scenes: s('volsung-hall'), focus: '《格罗蒂之歌》以被奴役的女巨人推磨为中心，财富生产在诗中与强迫劳动、战争和统治者的毁灭相连。' }),
];
