import type { MythStorySource, SourceRef, SourceRefType } from '../../lib/content/types';

/**
 * Mesopotamian sources are deliberately keyed by work / corpus rather than by
 * an invented chronology. A source period describes the cited witness or
 * corpus; story notes explain when a tradition is older than that witness.
 */
export type MesopotamianSource = {
  sourceId: string;
  title: string;
  author?: string;
  type: SourceRefType;
  storyType: MythStorySource['sourceType'];
  tradition: string;
  period: string;
  language?: string;
  edition?: string;
  url?: string;
  note: string;
};

export const mesopotamianSources = {
  enkiNinhursaga: {
    sourceId: 'source-meso-enki-ninhursaga-etscl',
    title: 'Enki and Ninhursaga',
    author: 'Electronic Text Corpus of Sumerian Literature',
    type: 'primary-text',
    storyType: 'scholarly-reference',
    tradition: 'Sumerian literary tradition',
    period: 'Old Babylonian witnesses preserving a Sumerian composition',
    language: 'sux',
    edition: 'ETCSL 1.1.1, composite text and translation',
    url: 'https://etcsl.orinst.ox.ac.uk/cgi-bin/etcsl.cgi?text=t.1.1.1',
    note: 'The cited witnesses preserve a Sumerian composition; witness period is not treated as the date of first composition.',
  },
  enkiWorldOrder: {
    sourceId: 'source-meso-enki-world-order-etscl',
    title: 'Enki and the World Order',
    author: 'Electronic Text Corpus of Sumerian Literature',
    type: 'primary-text',
    storyType: 'scholarly-reference',
    tradition: 'Sumerian literary tradition',
    period: 'Old Babylonian witnesses preserving a Sumerian composition',
    language: 'sux',
    edition: 'ETCSL 1.1.3, composite text and translation',
    url: 'https://etcsl.orinst.ox.ac.uk/cgi-bin/etcsl.cgi?text=t.1.1.3',
    note: 'A source lane for the distribution of divine offices, cities and ordered abundance; not a universal pantheon chart.',
  },
  enlilNinlil: {
    sourceId: 'source-meso-enlil-ninlil-etscl',
    title: 'Enlil and Ninlil',
    author: 'Electronic Text Corpus of Sumerian Literature',
    type: 'primary-text',
    storyType: 'scholarly-reference',
    tradition: 'Sumerian literary tradition',
    period: 'Old Babylonian witnesses preserving a Sumerian composition',
    language: 'sux',
    edition: 'ETCSL 1.2.1, composite text and translation',
    url: 'https://etcsl.orinst.ox.ac.uk/cgi-bin/etcsl.cgi?text=t.1.2.1',
    note: 'The narrative is kept source-scoped; later genealogical summaries do not overwrite its own sequence and terminology.',
  },
  inannaEnki: {
    sourceId: 'source-meso-inanna-enki-etscl',
    title: 'Inanna and Enki',
    author: 'Electronic Text Corpus of Sumerian Literature',
    type: 'primary-text',
    storyType: 'scholarly-reference',
    tradition: 'Sumerian literary tradition',
    period: 'Old Babylonian witnesses preserving a Sumerian composition',
    language: 'sux',
    edition: 'ETCSL 1.3.1, composite text and translation',
    url: 'https://etcsl.orinst.ox.ac.uk/cgi-bin/etcsl.cgi?text=t.1.3.1',
    note: 'The me are treated as a source-specific order / culture concept, not as a generic magic inventory.',
  },
  inannaDescent: {
    sourceId: 'source-meso-inanna-descent-etscl',
    title: "Inana's Descent to the Nether World",
    author: 'Electronic Text Corpus of Sumerian Literature',
    type: 'primary-text',
    storyType: 'scholarly-reference',
    tradition: 'Sumerian literary tradition',
    period: 'Old Babylonian witnesses preserving a Sumerian composition',
    language: 'sux',
    edition: 'ETCSL 1.4.1, composite text and translation',
    url: 'https://etcsl.orinst.ox.ac.uk/cgi-bin/etcsl.cgi?text=t.1.4.1',
    note: 'The ETCSL text keeps line references and witness notes visible; the page does not silently merge the Akkadian Descent of Ishtar.',
  },
  dumuziDream: {
    sourceId: 'source-meso-dumuzi-dream-etscl',
    title: "Dumuzi's Dream",
    author: 'Electronic Text Corpus of Sumerian Literature',
    type: 'primary-text',
    storyType: 'scholarly-reference',
    tradition: 'Sumerian literary tradition',
    period: 'Old Babylonian witnesses preserving a Sumerian composition',
    language: 'sux',
    edition: 'ETCSL 1.4.3, composite text and translation',
    url: 'https://etcsl.orinst.ox.ac.uk/cgi-bin/etcsl.cgi?text=t.1.4.3',
    note: 'Dumuzi material is presented as a distinct Sumerian narrative lane, not as a generic resurrection story.',
  },
  sumerianFlood: {
    sourceId: 'source-meso-sumerian-flood-etscl',
    title: 'The Flood Story',
    author: 'Electronic Text Corpus of Sumerian Literature',
    type: 'primary-text',
    storyType: 'scholarly-reference',
    tradition: 'Sumerian literary tradition',
    period: 'Old Babylonian witness with substantial lacunae',
    language: 'sux',
    edition: 'ETCSL 1.7.4, composite text and translation',
    url: 'https://etcsl.orinst.ox.ac.uk/cgi-bin/etcsl.cgi?text=t.1.7.4',
    note: 'The surviving text is fragmentary; Ziusudra is not merged with Atrahasis or Utnapishtim.',
  },
  lugalE: {
    sourceId: 'source-meso-lugal-e-etscl',
    title: 'Lugal-e / The Deeds of Ninurta',
    author: 'Electronic Text Corpus of Sumerian Literature',
    type: 'primary-text',
    storyType: 'scholarly-reference',
    tradition: 'Sumerian Ninurta tradition',
    period: 'Old Babylonian witnesses preserving a Sumerian composition',
    language: 'sux',
    edition: 'ETCSL 1.6.2, composite text and translation',
    url: 'https://etcsl.orinst.ox.ac.uk/cgi-bin/etcsl.cgi?text=t.1.6.2',
    note: 'The heroic order of Ninurta is not used to collapse Ninurta into every local Ningirsu tradition.',
  },
  atrahasis: {
    sourceId: 'source-meso-atrahasis-old-babylonian',
    title: 'The Atraḫasis Epic',
    author: 'A. R. George, source and edition context',
    type: 'primary-text',
    storyType: 'scholarly-reference',
    tradition: 'Akkadian / Old Babylonian literary tradition',
    period: 'Old Babylonian copy tradition with later Assyrian witnesses',
    language: 'akk',
    edition: 'Old Babylonian and first-millennium textual witnesses, source-scoped excerpts',
    url: 'https://www.livius.org/sources/content/anet/104-106-the-epic-of-atrahasis/',
    note: 'The fuller flood account is a textual tradition with multiple witnesses; it is not evidence that all flood heroes are one ancient person.',
  },
  adapa: {
    sourceId: 'source-meso-adapa-akkadian',
    title: 'The Adapa Myth',
    type: 'primary-text',
    storyType: 'scholarly-reference',
    tradition: 'Akkadian literary tradition',
    period: 'Second-millennium and first-millennium witnesses',
    language: 'akk',
    edition: 'Akkadian literary witnesses, source-scoped translation',
    url: 'https://oracc.museum.upenn.edu/amgg/listofdeities/ea/index.html',
    note: 'Adapa remains an Akkadian sage figure; no Adapa = Adam same-as claim is made.',
  },
  etana: {
    sourceId: 'source-meso-etana-akkadian',
    title: 'The Etana Legend',
    type: 'primary-text',
    storyType: 'scholarly-reference',
    tradition: 'Akkadian literary tradition',
    period: 'Old Babylonian and first-millennium witnesses',
    language: 'akk',
    edition: 'Akkadian narrative witnesses, source-scoped translation',
    note: 'The eagle journey is kept as a royal / succession quest and not turned into a general ascent myth.',
  },
  anzu: {
    sourceId: 'source-meso-anzu-first-millennium',
    title: 'The Anzu Epic',
    type: 'primary-text',
    storyType: 'scholarly-reference',
    tradition: 'Akkadian literary tradition',
    period: 'Old Babylonian and first-millennium witnesses',
    language: 'akk',
    edition: 'Akkadian Anzu narrative, source-scoped translation',
    note: 'Anzu and the Tablet of Destinies are kept distinct from the later Babylonian Tiamat conflict.',
  },
  gilgameshSumerian: {
    sourceId: 'source-meso-gilgamesh-sumerian-etscl',
    title: 'Sumerian Gilgamesh poems',
    author: 'Electronic Text Corpus of Sumerian Literature',
    type: 'primary-text',
    storyType: 'scholarly-reference',
    tradition: 'Sumerian Gilgamesh literary tradition',
    period: 'Old Babylonian witnesses preserving separate Sumerian poems',
    language: 'sux',
    edition: 'ETCSL Gilgamesh compositions, source-scoped text units',
    url: 'https://etcsl.orinst.ox.ac.uk/',
    note: 'Separate Sumerian poems are not silently completed with scenes from the Standard Babylonian epic.',
  },
  gilgameshOldBabylonian: {
    sourceId: 'source-meso-gilgamesh-old-babylonian',
    title: 'Old Babylonian Gilgamesh fragments',
    type: 'primary-text',
    storyType: 'scholarly-reference',
    tradition: 'Old Babylonian Gilgamesh literary tradition',
    period: 'Old Babylonian fragments',
    language: 'akk',
    edition: 'Old Babylonian fragments, source-scoped translation',
    note: 'Fragments are used as evidence for a textual lane, not as a complete substitute for the Standard Babylonian edition.',
  },
  gilgameshStandard: {
    sourceId: 'source-meso-gilgamesh-standard-babylonian',
    title: 'The Standard Babylonian Epic of Gilgamesh',
    author: 'Andrew George, critical edition and translation context',
    type: 'primary-text',
    storyType: 'scholarly-reference',
    tradition: 'Standard Babylonian Gilgamesh tradition',
    period: 'First-millennium witnesses preserving an older composite tradition',
    language: 'akk',
    edition: 'Standard Babylonian edition, Tablets I–XII, source-scoped tablet references',
    url: 'https://www.soas.ac.uk/baplar/recordings',
    note: 'The cited witness period does not by itself date the first composition of every episode.',
  },
  enumaElish: {
    sourceId: 'source-meso-enuma-elish-standard-babylonian',
    title: 'Enūma Eliš',
    type: 'primary-text',
    storyType: 'scholarly-reference',
    tradition: 'Babylonian theological composition',
    period: 'First-millennium witnesses preserving a Babylon-centered composition',
    language: 'akk',
    edition: 'Tablets I–VII, source-scoped edition and translation',
    url: 'https://ccp.yale.edu/P365300',
    note: 'A Babylon-centered theological composition; it is not presented as a universal Sumerian creation account.',
  },
  ishtarDescent: {
    sourceId: 'source-meso-ishtar-descent-akkadian',
    title: "Ishtar's Descent to the Netherworld",
    type: 'primary-text',
    storyType: 'scholarly-reference',
    tradition: 'Akkadian Descent of Ishtar tradition',
    period: 'First-millennium Akkadian witness tradition',
    language: 'akk',
    edition: 'Akkadian Descent of Ishtar, source-scoped translation',
    note: 'This is a separate Akkadian textual witness, not a silent continuation of the Sumerian Inanna composition.',
  },
  nergalEreshkigal: {
    sourceId: 'source-meso-nergal-ereshkigal-amarna',
    title: 'Nergal and Ereshkigal',
    type: 'primary-text',
    storyType: 'scholarly-reference',
    tradition: 'Akkadian underworld literary tradition',
    period: 'Middle Babylonian Amarna witness and later first-millennium copies',
    language: 'akk',
    edition: 'Amarna and later copies, source-scoped versions',
    url: 'https://oracc.museum.upenn.edu/amgg/listofdeities/nergal/index.html',
    note: 'Different versions resolve the relationship differently; the page preserves version scope rather than choosing a single timeless plot.',
  },
  anAnum: {
    sourceId: 'source-meso-an-anum-god-list',
    title: 'An = Anum god list',
    type: 'historical-record',
    storyType: 'scholarly-reference',
    tradition: 'Mesopotamian lexical and scholarly list tradition',
    period: 'First-millennium scholarly witnesses',
    language: 'sux-akk',
    edition: 'God-list correspondence, source-scoped entries',
    note: 'Used for name correspondence and learned theology, not as a narrative Story or fixed universal genealogy.',
  },
  assyrianCult: {
    sourceId: 'source-meso-assyrian-cult-local',
    title: 'Assyrian royal, temple and local-cult evidence',
    type: 'local-cult-record',
    storyType: 'scholarly-reference',
    tradition: 'Neo-Assyrian religious tradition',
    period: 'Neo-Assyrian first millennium BCE',
    language: 'akk',
    edition: 'Source-scoped inscriptions, cult and scholarly records',
    url: 'https://oracc.museum.upenn.edu/amgg/listofdeities/ashur/index.html',
    note: 'Assyrian state theology and local Ishtar manifestations are not treated as timeless Mesopotamian consensus.',
  },
  iconography: {
    sourceId: 'source-meso-iconography-object-evidence',
    title: 'Mesopotamian seals, reliefs and divine symbols',
    type: 'academic-secondary',
    storyType: 'scholarly-reference',
    tradition: 'Archaeological and iconographic evidence',
    period: 'Period- and object-specific evidence',
    language: 'sux-akk',
    edition: 'Object-grounded catalogue and identification notes',
    note: 'An object establishes a period / place manifestation, not an eternal appearance for a deity.',
  },
} as const satisfies Record<string, MesopotamianSource>;

export type MesopotamianSourceKey = keyof typeof mesopotamianSources;

export const sourceRef = (key: MesopotamianSourceKey, locator: string, note?: string): SourceRef => {
  const source: MesopotamianSource = mesopotamianSources[key];
  return {
    sourceId: source.sourceId,
    type: source.type,
    title: source.title,
    author: source.author,
    period: source.period,
    edition: source.edition,
    locator,
    language: source.language,
    url: source.url,
    note: note ?? source.note,
  };
};

export const storySource = (key: MesopotamianSourceKey, locator: string, note?: string): MythStorySource => {
  const source: MesopotamianSource = mesopotamianSources[key];
  return {
    sourceId: source.sourceId,
    title: source.title,
    sourceType: source.storyType,
    tradition: source.tradition,
    period: source.period,
    locator,
    language: source.language,
    translation: source.edition,
    url: source.url,
    note: note ?? source.note,
  };
};
