import type { MythStory } from '../../lib/content/types';
import { storySource } from './sources';

const mythologyId = 'myth-mesopotamian';
const date = '2026-09-02';
const c = (slug: string) => `character-${slug}`;
const s = (slug: string) => `scene-${slug}`;
const w = (slug: string) => `world-${slug}`;

type StorySeed = {
  id: string;
  slug: string;
  title: string;
  titleEn: string;
  subtitle: string;
  summary: string;
  volumeId: string;
  volumeTitle: string;
  volumeOrder: number;
  displayOrder: number;
  kind: MythStory['kind'];
  tradition: string;
  sourceKey: Parameters<typeof storySource>[0];
  sourceLocator: string;
  sourceNote: string;
  characters: string[];
  worlds?: string[];
  scenes: string[];
  body: string[];
  extraSourceKeys?: Array<{ key: Parameters<typeof storySource>[0]; locator: string }>;
};

const makeStory = (seed: StorySeed): MythStory => {
  const sources = [storySource(seed.sourceKey, seed.sourceLocator), ...(seed.extraSourceKeys ?? []).map(({ key, locator }) => storySource(key, locator))];
  const characterIds = seed.characters.map(c);
  const worldIds = (seed.worlds ?? []).map(w);
  const sceneIds = seed.scenes.map(s);
  return {
    id: seed.id,
    slug: seed.slug,
    mythologyId,
    title: seed.title,
    titleEn: seed.titleEn,
    subtitle: seed.subtitle,
    summary: seed.summary,
    volumeId: seed.volumeId,
    volumeTitle: seed.volumeTitle,
    volumeOrder: seed.volumeOrder,
    displayOrder: seed.displayOrder,
    kind: seed.kind,
    tradition: seed.tradition,
    readingMinutes: 5,
    sources,
    sourceNotes: [seed.sourceNote],
    requiredCharacterIds: characterIds,
    requiredWorldIds: worldIds,
    requiredSceneIds: sceneIds,
    requiredSourceIds: sources.flatMap((source) => source.sourceId ? [source.sourceId] : []),
    characterIds,
    worldIds,
    sceneIds,
    blocks: seed.body.map((text, index) => ({ type: 'paragraph' as const, text: index === 0 ? text : text })),
    publishStatus: 'published',
    publishedAt: date,
    updatedAt: date,
  };
};

export const mesopotamianStories: readonly MythStory[] = [
  makeStory({ id: 'story-meso-enki-ninhursaga', slug: 'enki-and-ninhursaga', title: '恩基、宁胡尔萨格与迪尔蒙', titleEn: 'Enki, Ninhursaga and Dilmun', subtitle: '生命从清洁的水域与复杂的诞生关系中展开', summary: '《Enki and Ninhursaga》以 Dilmun、淡水、生命与神圣生育组织一条 Sumerian 叙事线。', volumeId: 'meso-sumerian-foundations', volumeTitle: 'Sumerian 神圣秩序', volumeOrder: 1, displayOrder: 1, kind: 'myth', tradition: 'Sumerian literary tradition', sourceKey: 'enkiNinhursaga', sourceLocator: 'ETCSL 1.1.1, Dilmun and birth sequence', sourceNote: '本篇依据 Sumerian 作品的现存见证展开；不会把后期 Akkadian 术语或其他创世叙事补写进空缺。', characters: ['enki-ea', 'ninhursaga', 'nammu'], worlds: ['abzu'], scenes: ['dilmun-sacred-landscape', 'eridu-e-abzu'], body: ['在这条 Sumerian 叙事线中，Dilmun 不是一张泛化的天堂明信片，而是与洁净、淡水和生命秩序相关的来源限定空间。Enki 与 Ninhursaga 的关系通过身体、土地和诞生展开。', '故事中的生育与神格关系不能被压缩成单一“母神”公式。Ninhursaga 保持自己的 source-scoped 身份，Enki 的淡水权能也与 Abzu 这个 World 分开建模。']}),
  makeStory({ id: 'story-meso-enki-world-order', slug: 'enki-and-the-world-order', title: '恩基分配世界的职责', titleEn: 'Enki and the World Order', subtitle: '神圣秩序不是一张脱离文本的职位表', summary: '《Enki and the World Order》描述城市、自然力量与神祇职责如何被安排到有秩序的世界中。', volumeId: 'meso-sumerian-foundations', volumeTitle: 'Sumerian 神圣秩序', volumeOrder: 1, displayOrder: 2, kind: 'myth', tradition: 'Sumerian literary tradition', sourceKey: 'enkiWorldOrder', sourceLocator: 'ETCSL 1.1.3, office and city-distribution passages', sourceNote: '本篇保留作品自身的职责分配语境；城市是 Scene / cult context，不生成城市人物边。', characters: ['enki-ea', 'an-anu', 'enlil', 'utu-shamash', 'ishkur-adad', 'nanna-sin'], worlds: ['abzu'], scenes: ['eridu-e-abzu', 'nippur-ekur', 'ur-nanna-sanctuary'], body: ['Enki 的“秩序”不是一个跨三千年的固定神谱，而是作品把神、城市、河流、风暴与劳作安置到各自位置的叙事行动。Eridu 与 Abzu 因而成为可复用的空间语境，而不是所有神都必须站在同一座神塔前。', 'An、Enlil、Utu、Iškur 与 Nanna 的职责在不同语言和传统中会重新排列。页面把这些内容标为 Sumerian literary lane，避免用后期 Babylonian theology 回填早期材料。']}),
  makeStory({ id: 'story-meso-enlil-ninlil', slug: 'enlil-and-ninlil', title: '恩利尔与宁利尔', titleEn: 'Enlil and Ninlil', subtitle: 'Nippur、河流与南纳的诞生', summary: '《Enlil and Ninlil》将 Nippur 语境、两位神的相遇以及 Nanna / Suen 的诞生连接起来。', volumeId: 'meso-sumerian-foundations', volumeTitle: 'Sumerian 神圣秩序', volumeOrder: 1, displayOrder: 3, kind: 'myth', tradition: 'Sumerian literary tradition', sourceKey: 'enlilNinlil', sourceLocator: 'ETCSL 1.2.1, Ninlil encounter and Nanna birth', sourceNote: '文本见证的时期与作品传统的形成时间分开记录；本页不把一条故事改写成普遍神谱。', characters: ['enlil', 'ninlil', 'nanna-sin'], scenes: ['nippur-ekur', 'ur-nanna-sanctuary'], body: ['Nippur 的空间在这篇作品中承担叙事作用：河流、边界、相遇与神圣关系都围绕具体城市传统展开。宁利尔不是一条只为补全谱系而存在的配偶字段。', 'Nanna / Suen 的诞生让月神进入一条有来源的家庭与城市线，但不意味着所有 Mesopotamian 传统都共享同一份固定家谱。']}),
  makeStory({ id: 'story-meso-inanna-enki-me', slug: 'inanna-and-enki-me', title: '伊南娜与恩基：me 的转移', titleEn: 'Inanna and Enki: The Me', subtitle: '文明秩序如何成为可移动、可争夺的神圣职责', summary: 'Inanna 从 Eridu 带走 me 的故事，以神圣职责与城市秩序为核心，而非现代意义的魔法盗窃。', volumeId: 'meso-inanna-ishtar', volumeTitle: 'Inanna / Ishtar', volumeOrder: 2, displayOrder: 1, kind: 'myth', tradition: 'Sumerian literary tradition', sourceKey: 'inannaEnki', sourceLocator: 'ETCSL 1.3.1, me list and transfer sequence', sourceNote: 'me 被建模为来源限定的 ContentConcept；本篇不把它们改写为游戏技能或通用魔法清单。', characters: ['inanna-ishtar', 'enki-ea'], worlds: ['abzu'], scenes: ['eridu-e-abzu', 'uruk-eanna'], body: ['me 是作品中与职责、礼仪、制度和文明秩序相关的集合。Inanna 与 Enki 的宴饮及转移因此既是神祇关系，也是 Eridu 与 Uruk 两个城市语境之间的叙事运动。', '页面保留“me”这个不可被一行中文完全替代的概念，并将城市作为 Scene。这样用户能看到 Inanna 的 Uruk 关联，却不会把 Uruk 伪装成一个 Character。']}),
  makeStory({ id: 'story-meso-inanna-descent', slug: 'inannas-descent', title: '伊南娜下到冥界', titleEn: "Inanna's Descent to the Nether World", subtitle: '穿过七门，权力被逐层卸下', summary: 'Sumerian《Inana’s Descent》讲述女神进入冥界、在七门失去装饰、死亡并通过替代返回的叙事。', volumeId: 'meso-inanna-ishtar', volumeTitle: 'Inanna / Ishtar', volumeOrder: 2, displayOrder: 2, kind: 'myth', tradition: 'Sumerian literary tradition', sourceKey: 'inannaDescent', sourceLocator: 'ETCSL 1.4.1, lines / sections on seven gates, death and return', sourceNote: '七门、Ereškigal、Ninshubur 与替代规则按 Sumerian 文本范围叙述；Akkadian Descent of Ishtar 另有独立 Story。', characters: ['inanna-ishtar', 'ereshkigal', 'ninshubur', 'namtar', 'dumuzi-tammuz'], worlds: ['mesopotamian-netherworld'], scenes: ['seven-gates', 'ereshkigal-throne', 'dumuzi-seizure'], body: ['Inanna 进入冥界时，七门不是游戏关卡，而是逐层解除地上身份和权力标记的叙事装置。Ereškigal 的王座、Namtar 的执行和 Ninshubur 的求援共同构成一套来源明确的冥界秩序。', '返回并不意味着死亡从未发生。Dumuzi 的替代进入后续哀悼与季节性解释层；本页保持 Inanna、Ereškigal 与 Dumuzi 的关系可追踪，而不拼接所有后期版本。']}),
  makeStory({ id: 'story-meso-dumuzi-dream', slug: 'dumuzis-dream', title: '杜穆兹的梦与追捕', titleEn: "Dumuzi's Dream", subtitle: '梦境先于冥界追捕发出预兆', summary: '《Dumuzi’s Dream》让梦、解释和逃亡成为 Dumuzi 死亡与替代传统的独立入口。', volumeId: 'meso-inanna-ishtar', volumeTitle: 'Inanna / Ishtar', volumeOrder: 2, displayOrder: 3, kind: 'myth', tradition: 'Sumerian literary tradition', sourceKey: 'dumuziDream', sourceLocator: 'ETCSL 1.4.3, dream and Geshtinanna interpretation', sourceNote: 'Dumuzi / Tammuz 作为跨语言延续身份保留，但本篇只讲 Sumerian 梦境与追捕范围。', characters: ['dumuzi-tammuz', 'geshtinanna', 'inanna-ishtar', 'namtar'], worlds: ['mesopotamian-netherworld'], scenes: ['dumuzi-seizure', 'land-of-dust'], body: ['Dumuzi 的梦不是一段被后人随意解释的预言，而是故事中死亡逼近、亲属辨认和逃亡开始的叙事结构。Geshtinanna 的解释把梦境变成行动知识。', '追捕将牧人、羊群、冥界执行者与尘土之地连接起来。Dumuzi / Tammuz 的后期哀歌传统可以继续链接，但不能抹去这一篇的 Sumerian 见证范围。']}),
  makeStory({ id: 'story-meso-ishtar-descent', slug: 'akkadian-ishtars-descent', title: '伊什塔尔下到冥界：Akkadian 见证', titleEn: "Ishtar's Descent: An Akkadian Witness", subtitle: '相近母题不等于同一份文本', summary: 'Akkadian《Ishtar’s Descent》作为独立文本见证呈现，与 Sumerian Inanna 下行保持可比较但不静默合并的关系。', volumeId: 'meso-inanna-ishtar', volumeTitle: 'Inanna / Ishtar', volumeOrder: 2, displayOrder: 4, kind: 'myth', tradition: 'Akkadian Descent of Ishtar tradition', sourceKey: 'ishtarDescent', sourceLocator: 'Akkadian text, opening, gates and return sequence', sourceNote: '本篇与《Inana’s Descent》并列展示；相似的冥界母题进入编辑比较层，不成为人物 Graph 的文学对应边。', characters: ['inanna-ishtar', 'ereshkigal', 'namtar'], worlds: ['mesopotamian-netherworld'], scenes: ['seven-gates', 'ereshkigal-throne', 'land-of-dust'], body: ['Akkadian 文本以 Ishtar 的名称进入冥界叙事。它与 Sumerian Inanna 故事共享一些可比较的结构，但版本、语言和具体细节不能被一把拼接。', '产品把“对应”放在 source-scoped Story 与 ContentClaim 中，而不是让 Graph 暗示两个文本人物曾经互相认识或存在一条古代 genealogy。']}),
  makeStory({ id: 'story-meso-ziusudra-flood', slug: 'ziusudra-flood', title: '齐乌苏德拉与洪水', titleEn: 'Ziusudra and the Flood', subtitle: '一份残缺的 Sumerian 洪水见证', summary: 'Sumerian《Flood Story》保存了 Ziusudra、神意与洪水的来源限定片段，文本本身存在缺损。', volumeId: 'meso-humanity-flood', volumeTitle: '人类、洪水与神的边界', volumeOrder: 3, displayOrder: 1, kind: 'myth', tradition: 'Sumerian literary tradition', sourceKey: 'sumerianFlood', sourceLocator: 'ETCSL 1.7.4, segment A and flood survivor passages', sourceNote: '现存文本有明确缺损；Ziusudra 不与 Atrahasis 或 Utnapishtim 合并，三者只在编辑比较层相邻。', characters: ['ziusudra', 'an-anu', 'enlil', 'enki-ea', 'ninhursaga'], scenes: ['uruk-walls', 'eridu-e-abzu'], body: ['Ziusudra 的故事来自一份有缺损的 Sumerian 洪水见证。页面明确标注缺口，不使用后来的完整洪水情节替它补写失落行文。', 'An、Enlil、Enki 与 Ninhursaga 在此处共同构成文本中的神圣背景，但这不是一张固定成员、固定职能的全 Mesopotamian 神谱。']}),
  makeStory({ id: 'story-meso-atrahasis-creation', slug: 'atrahasis-divine-labour', title: '阿特拉哈西斯：神的劳作与人的出现', titleEn: 'Atrahasis: Divine Labour and Human Creation', subtitle: '人类诞生先被放在神的劳作冲突中', summary: 'Atraḫasis 开篇叙事围绕低等神劳作、反抗与人类被创造来承担秩序展开。', volumeId: 'meso-humanity-flood', volumeTitle: '人类、洪水与神的边界', volumeOrder: 3, displayOrder: 2, kind: 'myth', tradition: 'Akkadian / Old Babylonian literary tradition', sourceKey: 'atrahasis', sourceLocator: 'Tablet I, divine labour, revolt and human creation', sourceNote: '本篇依据 Akkadian / Old Babylonian source lane；不能将其创世叙事回填为所有 Sumerian 传统。', characters: ['atrahasis', 'enki-ea', 'enlil', 'igigi', 'anunnaki'], scenes: ['eridu-e-abzu', 'nippur-ekur'], body: ['Atraḫasis 把人类的出现置于神的劳作冲突中：低等神承担工作、发生反抗，创造人类成为重新分配劳作的方案。这个框架属于作品自身的 Akkadian 叙事。', 'Igigi 与 Anunnaki 在此处作为文本中的集合称谓处理，不固定成员，也不将现代外星人解释带入古代层。']}),
  makeStory({ id: 'story-meso-atrahasis-flood', slug: 'atrahasis-population-and-flood', title: '阿特拉哈西斯：人口、灾难与洪水', titleEn: 'Atrahasis: Population, Disaster and Flood', subtitle: '神与人的边界被洪水重新划出', summary: 'Atraḫasis 的后续泥板连接人口增长、灾难、警告、造船与洪水幸存。', volumeId: 'meso-humanity-flood', volumeTitle: '人类、洪水与神的边界', volumeOrder: 3, displayOrder: 3, kind: 'myth', tradition: 'Akkadian / Old Babylonian literary tradition', sourceKey: 'atrahasis', sourceLocator: 'Tablets II–III, population, disasters, boat and flood', sourceNote: '不同抄本与方言见证共同构成研究对象；本篇不把 Atraḫasis 当作所有洪水人物的唯一原型。', characters: ['atrahasis', 'enki-ea', 'enlil', 'igigi'], scenes: ['eridu-e-abzu', 'utnapishtim-dwelling'], body: ['人口增长与灾难在 Atraḫasis 中不是现代人口学寓言，而是神与人之间秩序边界的叙事机制。Ea / Enki 以来源限定的救助角色介入，幸存者得以准备船只。', '洪水结束后的秩序并非简单回到原点。Atraḫasis 的文本 lane 与 Ziusudra、Utnapishtim 彼此相邻，却不因此成为同一人物或同一版本。']}),
  makeStory({ id: 'story-meso-adapa', slug: 'adapa-and-the-food-of-life', title: '阿达帕与死亡之食', titleEn: 'Adapa and the Food of Life', subtitle: '智慧并不自动等于不死', summary: 'Adapa 在 Ea 的智慧与天界食物之间面对死亡边界，故事不是 Adapa = Adam 的证据。', volumeId: 'meso-akkadian-bridge', volumeTitle: 'Akkadian / Old Babylonian 桥接', volumeOrder: 4, displayOrder: 1, kind: 'myth', tradition: 'Akkadian literary tradition', sourceKey: 'adapa', sourceLocator: 'Adapa opening, wind episode and food / water of life', sourceNote: 'Adapa 保持为 Akkadian 智者；本包明确排除 Adapa / Adam 的 same-as 主张。', characters: ['adapa', 'enki-ea', 'an-anu'], worlds: ['abzu'], scenes: ['eridu-e-abzu', 'ereshkigal-throne'], body: ['Adapa 的智慧来自 Ea / Enki 的教导，但智慧并未自动把他变成不死者。食物与水的选择让故事把知识、服从和死亡边界放在同一场景中。', '后世读者可能寻找跨文化同名关系，但 MythCanvas 将 Adapa 留在 Akkadian 文学传统，任何比较都必须另有来源与明确 reception 层。']}),
  makeStory({ id: 'story-meso-etana', slug: 'etana-and-the-eagle', title: '埃塔纳与鹰之旅', titleEn: 'Etana and the Eagle', subtitle: '王权继承通过一次危险的上升被想象', summary: 'Etana 传说将王权、继承愿望与鹰的高空旅程组织成 Akkadian 叙事单元。', volumeId: 'meso-akkadian-bridge', volumeTitle: 'Akkadian / Old Babylonian 桥接', volumeOrder: 4, displayOrder: 2, kind: 'folk-legend', tradition: 'Akkadian literary tradition', sourceKey: 'etana', sourceLocator: 'Etana and the eagle succession quest', sourceNote: '本篇按 Akkadian 传奇文本范围呈现；高空旅程不被泛化为所有升天叙事的共同模板。', characters: ['etana'], scenes: ['uruk-walls', 'mount-mashu'], body: ['Etana 的愿望与王位继承相关，鹰提供了越过人间尺度的交通方式。高空不是纯粹的奇观，而是王权连续性焦虑的视觉化。', '故事保存为一个独立的 Akkadian 文学单元，不与 Gilgamesh 的远行或现代飞行想象强行合并。']}),
  makeStory({ id: 'story-meso-anzu', slug: 'anzu-and-the-tablet-of-destinies', title: '安祖与命运泥板', titleEn: 'Anzu and the Tablet of Destinies', subtitle: '神权秩序的关键不只是一件宝物', summary: 'Anzu 窃取命运泥板后，神圣权威、追捕与英雄秩序发生冲突。', volumeId: 'meso-ninurta-anzu', volumeTitle: 'Ninurta / Anzu', volumeOrder: 5, displayOrder: 1, kind: 'myth', tradition: 'Akkadian literary tradition', sourceKey: 'anzu', sourceLocator: 'Anzu theft of the Tablet of Destinies and champion sequence', sourceNote: 'Anzu 的命运泥板冲突与 Enūma Eliš 的 Tiamat 战争保持为不同文本 lane。', characters: ['anzu', 'ninurta'], scenes: ['anzu-mountain'], body: ['命运泥板在 Anzu 叙事中不是一张可随意读取的魔法卡，而是与神权秩序和合法性相连的对象。Anzu 的窃取使谁能够命令世界成为直接问题。', 'Ninurta 的英雄角色按此 Akkadian 传统呈现，不自动合并 Ningirsu，也不把 Anzu 作为 Tiamat 阵营的成员。']}),
  makeStory({ id: 'story-meso-lugal-e', slug: 'ninurta-and-asag', title: '宁乌尔塔与阿萨格', titleEn: 'Ninurta and Asag', subtitle: '山岳、石头与英雄秩序', summary: 'Sumerian《Lugal-e》以 Ninurta 对 Asag 及山岳力量的胜利组织英雄秩序叙事。', volumeId: 'meso-ninurta-anzu', volumeTitle: 'Ninurta / Anzu', volumeOrder: 5, displayOrder: 2, kind: 'myth', tradition: 'Sumerian Ninurta tradition', sourceKey: 'lugalE', sourceLocator: 'ETCSL 1.6.2, Asag conflict and Ninurta victory', sourceNote: '只发布 Ninurta 所需的 Lugal-e source lane，不把其英雄功能回填为所有战神身份。', characters: ['ninurta', 'asag'], scenes: ['anzu-mountain', 'nippur-ekur'], body: ['Lugal-e 让山岳成为有重量、有阻力的叙事对象。Ninurta 的胜利不是没有代价的技能动画，而是对混乱地景重新组织的神圣行动。', 'Asag 保持为这条作品中的敌对存在。视觉设计可以使用石、山与尘土，但不应误称为一份可读的楔形文字铭文。']}),
  makeStory({ id: 'story-meso-gilgamesh-meeting', slug: 'gilgamesh-and-enkidu-meet', title: '吉尔伽美什与恩奇都相遇', titleEn: 'Gilgamesh and Enkidu Meet', subtitle: '城市王权与荒野力量先以冲突相遇', summary: 'Standard Babylonian《Epic of Gilgamesh》开篇将 Uruk 王与荒野人物的冲突转成伙伴关系。', volumeId: 'meso-gilgamesh', volumeTitle: 'Gilgamesh', volumeOrder: 6, displayOrder: 1, kind: 'literary-fantasy', tradition: 'Standard Babylonian Gilgamesh tradition', sourceKey: 'gilgameshStandard', sourceLocator: 'Tablets I–II, Uruk, Enkidu and the meeting', sourceNote: '本篇明确属于 Standard Babylonian lane；Sumerian Gilgamesh poems 与 Old Babylonian fragments 不静默补写其中缺口。', characters: ['gilgamesh', 'enkidu', 'ninsun'], scenes: ['uruk-walls', 'uruk-eanna'], body: ['Gilgamesh 与 Enkidu 的相遇先是对抗：一个属于城墙与王权，一个从荒野与动物关系中出现。冲突被转成伙伴关系后，Uruk 的秩序获得了一个来自外部的镜像。', 'Ninsun 的梦境解释把新伙伴关系纳入王权叙事，但不说明所有 Gilgamesh 文本都按同一顺序讲述。']}),
  makeStory({ id: 'story-meso-gilgamesh-humbaba', slug: 'gilgamesh-cedar-forest', title: '吉尔伽美什、恩奇都与洪巴巴', titleEn: 'Gilgamesh, Enkidu and Humbaba', subtitle: '雪松森林是边界，不是普通冒险地图', summary: '两位英雄前往雪松森林，面对其守护者 Humbaba，并在名望与代价之间做出选择。', volumeId: 'meso-gilgamesh', volumeTitle: 'Gilgamesh', volumeOrder: 6, displayOrder: 2, kind: 'literary-fantasy', tradition: 'Standard Babylonian Gilgamesh tradition', sourceKey: 'gilgameshStandard', sourceLocator: 'Tablet V, Cedar Forest and Humbaba encounter', sourceNote: '森林、守护者与战斗按 Standard Babylonian tablet scope；不把所有版本的战斗细节拼成唯一原始场景。', characters: ['gilgamesh', 'enkidu', 'humbaba'], scenes: ['cedar-forest', 'humbaba-encounter'], body: ['雪松森林不是一块供英雄拍照的异域背景，而是城市边界之外的权力与恐惧空间。Humbaba 的守护者身份让远行变成对“谁能进入、谁能砍伐、谁能获得名声”的挑战。', 'Gilgamesh 与 Enkidu 的胜利同时带来伦理与命运压力。作品不把 Humbaba 的面容固定成某种现代怪兽模板，而以文本身份和空间关系作为稳定锚点。']}),
  makeStory({ id: 'story-meso-bull-of-heaven', slug: 'ishtar-and-bull-of-heaven', title: '伊什塔尔与天之公牛', titleEn: 'Ishtar and the Bull of Heaven', subtitle: '神的拒绝、城市灾难与英雄报偿', summary: 'Ishtar 与 Gilgamesh 的冲突引出天之公牛，Uruk 成为灾难与反击的具体城市现场。', volumeId: 'meso-gilgamesh', volumeTitle: 'Gilgamesh', volumeOrder: 6, displayOrder: 3, kind: 'literary-fantasy', tradition: 'Standard Babylonian Gilgamesh tradition', sourceKey: 'gilgameshStandard', sourceLocator: 'Tablet VI, Ishtar, Bull of Heaven and Uruk', sourceNote: '本篇沿 Standard Babylonian Tablet VI 组织；“Inanna / Ishtar”身份维度与地方范围仍通过 Character Interpretation 分开呈现。', characters: ['inanna-ishtar', 'gilgamesh', 'enkidu', 'bull-of-heaven'], scenes: ['bull-of-heaven-uruk', 'uruk-walls'], body: ['Ishtar 的提议被拒绝后，Bull of Heaven 进入 Uruk，灾难不再是抽象天象，而是具体城市、土地与人口的破坏。', 'Gilgamesh 与 Enkidu 的反击提升了英雄名声，也加重了对神圣秩序的冒犯。天之公牛以叙事复合巨物呈现，不被套入现代奇幻坐骑图鉴。']}),
  makeStory({ id: 'story-meso-enkidu-death', slug: 'enkidu-death', title: '恩奇都之死', titleEn: 'The Death of Enkidu', subtitle: '英雄史诗从名望转向失去', summary: 'Enkidu 在神罚与疾病的阴影中死去，Gilgamesh 的远行由此从英雄冒险转为对死亡的追问。', volumeId: 'meso-gilgamesh', volumeTitle: 'Gilgamesh', volumeOrder: 6, displayOrder: 4, kind: 'literary-fantasy', tradition: 'Standard Babylonian Gilgamesh tradition', sourceKey: 'gilgameshStandard', sourceLocator: 'Tablets VII–VIII, judgement, illness and Enkidu death', sourceNote: '死亡段落按 Standard Babylonian 见证呈现；早期 Gilgamesh 材料中的差异不被静默抹平。', characters: ['gilgamesh', 'enkidu', 'inanna-ishtar'], worlds: ['mesopotamian-netherworld'], scenes: ['uruk-walls', 'land-of-dust'], body: ['Enkidu 的死亡改变了史诗的重心。荒野伙伴不再只是 Gilgamesh 的对手或战友，而成为让王直面自身有限性的失去。', '哀悼把 Uruk 的城墙与冥界的尘土联系起来。这里没有简单的“复活任务”，只有一个活人开始学习死亡会怎样改变他的王权与道路。']}),
  makeStory({ id: 'story-meso-gilgamesh-quest', slug: 'gilgamesh-seeks-utnapishtim', title: '吉尔伽美什寻找乌特纳比什提姆', titleEn: 'Gilgamesh Seeks Utnapishtim', subtitle: '穿越玛舒山、海岸与死亡之水', summary: 'Gilgamesh 为逃离死亡踏上远行，依次经过山门、Siduri、Urshanabi 与死亡之水。', volumeId: 'meso-gilgamesh', volumeTitle: 'Gilgamesh', volumeOrder: 6, displayOrder: 5, kind: 'literary-fantasy', tradition: 'Standard Babylonian Gilgamesh tradition', sourceKey: 'gilgameshStandard', sourceLocator: 'Tablets IX–X, Mount Mashu, Siduri, Urshanabi and Waters of Death', sourceNote: '远行路线依 Standard Babylonian tablets 标注；不把它当成所有 Mesopotamian 地理的统一地图。', characters: ['gilgamesh', 'siduri', 'urshanabi'], worlds: ['mesopotamian-netherworld'], scenes: ['mount-mashu', 'siduri-shore', 'waters-of-death'], body: ['Gilgamesh 的远行经过玛舒山的门、Siduri 的海岸和 Urshanabi 的渡船。每个空间都代表一种边界：太阳的通道、日常生活的劝告、以及不能徒手触碰的死亡之水。', '这条路不是通往一个可供人类永久占有的秘密地点，而是逐步拆解“英雄可以逃离死亡”这一愿望。']}),
  makeStory({ id: 'story-meso-utnapishtim-flood', slug: 'utnapishtim-flood-account', title: '乌特纳比什提姆讲述洪水', titleEn: 'Utnapishtim’s Flood Account', subtitle: 'Standard Babylonian 见证中的洪水与远居', summary: 'Utnapishtim 向 Gilgamesh 讲述洪水、造船、幸存与神祇重新划定边界的故事。', volumeId: 'meso-gilgamesh', volumeTitle: 'Gilgamesh', volumeOrder: 6, displayOrder: 6, kind: 'literary-fantasy', tradition: 'Standard Babylonian Gilgamesh tradition', sourceKey: 'gilgameshStandard', sourceLocator: 'Tablet XI, flood account, boat and distant dwelling', sourceNote: 'Utnapishtim 的洪水叙述是 Standard Babylonian Tablet XI 的来源单元；与 Atraḫasis、Ziusudra 的比较只在 ContentClaim 中表达。', characters: ['gilgamesh', 'utnapishtim', 'enki-ea'], worlds: ['mesopotamian-netherworld'], scenes: ['utnapishtim-dwelling', 'waters-of-death'], body: ['Utnapishtim 的故事嵌在 Gilgamesh 的远行中：一位已经越过人类寿命边界的幸存者，向另一位仍在追问死亡的王讲述洪水。', '这个版本的洪水与 Atraḫasis 共享可比较的材料，但产品不把比较关系写成人物之间的古代边。文本 lane、witness period 与人物身份各自保持可见。']}),
  makeStory({ id: 'story-meso-gilgamesh-return', slug: 'gilgamesh-return-to-uruk', title: '不死之草与重返乌鲁克', titleEn: 'The Plant and the Return to Uruk', subtitle: '答案最后落在城墙，而不是永恒身体', summary: 'Gilgamesh 取得不死之草又失去它，最终带着对人的边界的新认识返回 Uruk。', volumeId: 'meso-gilgamesh', volumeTitle: 'Gilgamesh', volumeOrder: 6, displayOrder: 7, kind: 'literary-fantasy', tradition: 'Standard Babylonian Gilgamesh tradition', sourceKey: 'gilgameshStandard', sourceLocator: 'Tablet XI, plant, serpent and return to Uruk', sourceNote: '本篇使用 Standard Babylonian Tablet XI 的结尾范围；不以现代“长生药”概念覆盖作品的城市与王权结尾。', characters: ['gilgamesh', 'urshanabi'], scenes: ['utnapishtim-dwelling', 'uruk-walls'], body: ['不死之草让 Gilgamesh 短暂接近自己想要的答案，但蛇的出现与草的失去再次说明人类不能把永生当作战利品带回家。', '重返 Uruk 把史诗的尺度从远方带回城墙：王可以建造、治理、记忆，也必须接受人的有限性。']}),
  makeStory({ id: 'story-meso-enuma-elish-origins', slug: 'enuma-elish-apsu-tiamat', title: '阿普苏、提阿马特与初始诸神', titleEn: 'Apsu, Tiamat and the First Gods', subtitle: 'Babylon-centered composition 的开端', summary: 'Enūma Eliš 以 Apsû 与 Tiamat 的原初水域开启神祇世代与冲突。', volumeId: 'meso-babylon-marduk', volumeTitle: 'Babylon / Marduk', volumeOrder: 7, displayOrder: 1, kind: 'religious-tradition', tradition: 'Babylonian theological composition', sourceKey: 'enumaElish', sourceLocator: 'Tablet I, Apsû, Tiamat and first divine generations', sourceNote: 'Enūma Eliš 是 Babylon-centered theological composition；Apsu Character 与 Abzu World 分开，不能回填为 universal Sumerian Genesis。', characters: ['apsu-enuma-elish', 'tiamat', 'kingu', 'anunnaki'], worlds: ['abzu'], scenes: ['tiamat-battlefield', 'babylon-sacred-precinct'], extraSourceKeys: [{ key: 'iconography', locator: 'Apsu / Tiamat identification and visual evidence scope' }], body: ['Enūma Eliš 的开端以原初水域与神祇世代建立叙事条件。Apsû 和 Tiamat 是文本中的神格角色，而 Abzu 是另一种宇宙空间语义；二者不能仅凭相近词形共用 ID。', '这条作品线后来通向 Babylon 的神学提升，但其地域与文本范围需要一直写在页面上，不应被包装成所有 Sumerian 传统的唯一创世开端。']}),
  makeStory({ id: 'story-meso-marduk-champion', slug: 'marduk-champion', title: '马尔杜克被推举为 champion', titleEn: 'Marduk Becomes Champion', subtitle: '神权在危机中被重新授权', summary: '当 Tiamat 的阵营威胁既有秩序，Marduk 以条件和能力获得神群的授权。', volumeId: 'meso-babylon-marduk', volumeTitle: 'Babylon / Marduk', volumeOrder: 7, displayOrder: 2, kind: 'religious-tradition', tradition: 'Babylonian theological composition', sourceKey: 'enumaElish', sourceLocator: 'Tablets II–III, Tiamat’s forces and Marduk’s champion appointment', sourceNote: '“被推举”按 Enūma Eliš 的 Babylonian theological lane 处理；不将 Marduk 的权威投射到所有早期神学。', characters: ['marduk', 'tiamat', 'kingu', 'anunnaki'], scenes: ['babylon-sacred-precinct', 'tiamat-battlefield'], body: ['Marduk 的出场不是一开始就拥有整个 Mesopotamia 的最高权力，而是在作品的危机中提出条件并获得神群授权。神权因此是一种在叙事中被谈判、被见证的权力。', 'Kingu 与 Tiamat 的阵营保持文本角色，Anunnaki 作为集合称谓不被固定成一份七人名单。']}),
  makeStory({ id: 'story-meso-marduk-tiamat-battle', slug: 'marduk-and-tiamat-battle', title: '马尔杜克与提阿马特之战', titleEn: 'Marduk and Tiamat', subtitle: '风、海水与宇宙重排', summary: 'Marduk 以风与武器击败 Tiamat，并将战场转化为宇宙秩序的材料。', volumeId: 'meso-babylon-marduk', volumeTitle: 'Babylon / Marduk', volumeOrder: 7, displayOrder: 3, kind: 'religious-tradition', tradition: 'Babylonian theological composition', sourceKey: 'enumaElish', sourceLocator: 'Tablets IV–V, battle and cosmic ordering', sourceNote: 'Tiamat 的水生 / 蛇形视觉属于原创解释选择；文本事实与图像证据分开记录。', characters: ['marduk', 'tiamat', 'kingu'], worlds: ['abzu'], scenes: ['tiamat-battlefield'], body: ['决战把风、网、武器与海水结合起来。Marduk 的胜利在作品内是宇宙重排的前提，但不是可脱离 Babylonian composition 直接套用于所有 Mesopotamian 创世传统的结论。', 'Tiamat 的文字身份明确，具体多头水生轮廓则属于 MythCanvas 的原创设计选项。任何视觉资产都不得把这项选择伪装成唯一古代图像。']}),
  makeStory({ id: 'story-meso-fifty-names-babylon', slug: 'marduk-fifty-names-and-babylon', title: '五十个名字与巴比伦的提升', titleEn: 'Fifty Names and the Elevation of Babylon', subtitle: '神名、城市与神学中心的重排', summary: 'Enūma Eliš 的后段通过 Marduk 名称、Babylon 与 Esagil 将城市神学提升到作品中心。', volumeId: 'meso-babylon-marduk', volumeTitle: 'Babylon / Marduk', volumeOrder: 7, displayOrder: 4, kind: 'religious-tradition', tradition: 'Babylonian theological composition', sourceKey: 'enumaElish', sourceLocator: 'Tablets VI–VII, fifty names, Babylon and Esagil', sourceNote: '本篇显式标注 Babylon-centered scope；Babylon、Esagil 与 Etemenanki 是 Scene，不是全两河唯一视觉皮肤。', characters: ['marduk', 'nabu', 'sarpanitum'], scenes: ['babylon-sacred-precinct', 'esagil', 'etemenanki', 'akitu-procession'], extraSourceKeys: [{ key: 'iconography', locator: 'Neo-Babylonian glazed-brick and mušhuššu object scope' }], body: ['五十个名字把 Marduk 的职责、权能和 Babylon 的神学中心连接起来。城市不是一个抽象背景，而是作品试图解释其中心地位的具体对象。', '因此 Babylon 的釉砖蓝、狮子和 mušhuššu 只能在相应的 Neo-Babylonian 或 Babylonian 场景中使用，不能成为所有 Sumerian、Akkadian 与 Assyrian 内容的统一皮肤。']}),
  makeStory({ id: 'story-meso-nergal-ereshkigal', slug: 'nergal-and-ereshkigal', title: '涅伽尔与埃列什基伽尔', titleEn: 'Nergal and Ereshkigal', subtitle: '冥界关系在不同版本中有不同结局', summary: 'Nergal 进入 Ereshkigal 的领域并形成关系；Amarna 与后期版本不被压成单一永恒情节。', volumeId: 'meso-underworld', volumeTitle: '冥界与死亡秩序', volumeOrder: 8, displayOrder: 1, kind: 'myth', tradition: 'Akkadian underworld literary tradition', sourceKey: 'nergalEreshkigal', sourceLocator: 'Amarna witness and later copy comparison, descent and relationship resolution', sourceNote: '不同版本的关系结局与抄本时期必须并列说明；本篇不把 Nergal 与 Erra 默认合并。', characters: ['nergal', 'ereshkigal', 'enki-ea'], worlds: ['mesopotamian-netherworld'], scenes: ['ereshkigal-throne', 'land-of-dust'], body: ['Nergal 进入 Ereshkigal 的领域后，故事围绕礼仪、危险、权力与关系展开。现存版本并不完全相同，页面因此把 Amarna 见证与后期抄本当作可比较的文本层。', 'Ereshkigal 保持冥界女王的位置，Nergal 也保持自己的死亡与战争身份。后期神学可能出现关联，但这不等于 Nergal、Erra 或所有冥界神格都应被合并。']}),
  makeStory({ id: 'story-meso-netherworld-terms', slug: 'netherworld-terms-and-dust', title: '冥界、七门与尘土', titleEn: 'Netherworld Terms, Gates and Dust', subtitle: '没有一张跨时期唯一的地下世界地图', summary: '以 Inanna / Ishtar 下行材料为入口，解释 Kur、Great Below、Irkalla 与 land of no return 等术语的来源范围。', volumeId: 'meso-underworld', volumeTitle: '冥界与死亡秩序', volumeOrder: 8, displayOrder: 2, kind: 'religious-tradition', tradition: 'Mesopotamian underworld religious tradition', sourceKey: 'inannaDescent', sourceLocator: 'Sumerian gate, dust and no-return imagery', sourceNote: '冥界术语按作品与语言分层；World“两河冥界”是产品聚合空间，不宣称每个术语完全同义。', characters: ['ereshkigal', 'inanna-ishtar', 'namtar', 'dumuzi-tammuz'], worlds: ['mesopotamian-netherworld'], scenes: ['seven-gates', 'ereshkigal-throne', 'land-of-dust', 'dumuzi-seizure'], extraSourceKeys: [{ key: 'ishtarDescent', locator: 'Akkadian descent terminology and gate sequence' }], body: ['“冥界”是产品为了帮助阅读而使用的聚合入口，古代文本却使用多个词语、地理想象和叙事场景。Kur、Great Below、Irkalla 与 land of no return 不能被压成跨时期唯一的正式地名。', '七门、王座、尘土与替代共同构成视觉线索，但每条线索都要回到对应的 Story 和 sourceRef。这样用户看到的是多个传统相互照明的空间，而不是一张伪造的统一地图。']}),
  makeStory({ id: 'story-meso-ashur-bridge', slug: 'ashur-assyrian-state-theology', title: '阿舒尔与 Assyrian 国家神学', titleEn: 'Ashur and Assyrian State Theology', subtitle: '继承、改写与地方神权', summary: 'Ashur 的 Assyrian source-scoped 解释层展示国家神学如何重用 inherited Mesopotamian 语言。', volumeId: 'meso-assyrian-bridge', volumeTitle: 'Assyrian Bridge', volumeOrder: 9, displayOrder: 1, kind: 'religious-tradition', tradition: 'Neo-Assyrian religious tradition', sourceKey: 'assyrianCult', sourceLocator: 'Ashur, royal ideology and local-cult evidence', sourceNote: 'Royal / state theology 不自动等于全 Mesopotamian 共识；Ashur 与 Marduk 保持为不同 Character。', characters: ['ashur', 'marduk', 'nabu', 'utu-shamash', 'nanna-sin', 'ishkur-adad'], scenes: ['assur-sacred-context', 'neo-assyrian-palace'], body: ['Ashur 的身份要从 Assyrian 城市、王权和神圣圆盘等来源范围进入，而不是被当作 Marduk 的换名。Assyrian 神学可以借用、改写或重新排列 inherited Mesopotamian 语言，这正是需要显示的历史层。', '宫殿浮雕与王权材料证明的是某一时期、某一地点的表现。视觉系统因此把 pale stone、relief rhythm 与 bronze 限定在 Neo-Assyrian domain，不回填早期 Sumerian 神祇。']}),
  makeStory({ id: 'story-meso-ishtar-local-cults', slug: 'ishtar-nineveh-and-arbela', title: '尼尼微与阿尔贝拉的伊什塔尔', titleEn: 'Ishtar of Nineveh and Arbela', subtitle: '同一 Character 下的地方 manifestation', summary: 'Nineveh 与 Arbela 的 Ishtar 以两种 local-cult Interpretation 呈现，彼此可比较但不覆盖 Uruk。', volumeId: 'meso-assyrian-bridge', volumeTitle: 'Assyrian Bridge', volumeOrder: 9, displayOrder: 2, kind: 'religious-tradition', tradition: 'Neo-Assyrian local-cult tradition', sourceKey: 'assyrianCult', sourceLocator: 'Nineveh and Arbela Ishtar local-cult evidence', sourceNote: '地方 manifestation 进入 CharacterInterpretation；不为每个城市强造独立 Character，也不把它们当作同一无差别图像。', characters: ['inanna-ishtar', 'ashur', 'nabu'], scenes: ['nineveh-ishtar-cult', 'arbela-ishtar-cult', 'neo-assyrian-palace'], worlds: ['mesopotamian-netherworld'], extraSourceKeys: [{ key: 'iconography', locator: 'period- and object-specific Ishtar identification' }], body: ['Nineveh 与 Arbela 的 Ishtar 都可以进入同一个稳定 Character 的身份图谱，但每个地方 manifestation 都需要自己的解释层。地方神庙、城市政治与仪式材料不会自动覆盖 Uruk 的 Inanna 或 Akkadian 文本中的所有 Ištar。', '页面把地方范围放在 Interpretation 与 Scene 中，并在 Graph / Story 上保留来源说明。这样“同神跨语言延续”和“地方崇拜差异”可以同时被看见。']}),
];
